In [ ]:
# Your name and student id

In [ ]:
%cd "/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/March24LC"

/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/March24LC

In [ ]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/March24LC'

In [ ]:
%ls

City.db  March24_LC_Pre.ipynb

In [ ]:
%pip install jupysql duckdb duckdb-engine --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.3/95.3 kB 3.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.6/49.6 kB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 192.8/192.8 kB 6.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.6/79.6 kB 5.4 MB/s eta 0:00:00

In [ ]:
# Load the SQL extension
%load_ext sql

In [ ]:
# Setting: Show all rows
%config SqlMagic.displaylimit = None

displaylimit: Value None will be treated as 0 (no limit)

In [ ]:
# connect to database file
%sql sqlite:///City.db

Connecting to 'sqlite:///City.db'

In [ ]:
%sqlcmd tables

+------+
| Name |
+------+
| data |
+------+

In [ ]:
%sqlcmd columns -t data

+------------+---------+----------+---------+-------------+
|    name    |   type  | nullable | default | primary_key |
+------------+---------+----------+---------+-------------+
|     ID     | INTEGER |  False   |   None  |      1      |
|    City    |   TEXT  |   True   |   None  |      0      |
|   State    |   TEXT  |   True   |   None  |      0      |
| Population | INTEGER |   True   |   None  |      0      |
|    lat     |   REAL  |   True   |   None  |      0      |
|    lon     |   REAL  |   True   |   None  |      0      |
+------------+---------+----------+---------+-------------+

In [ ]:
%%sql
select *
from data
;

Running query in 'sqlite:///City.db'

+------+----------------------------+----------------------+------------+--------------------+---------------------+
|  ID  |            City            |        State         | Population |        lat         |         lon         |
+------+----------------------------+----------------------+------------+--------------------+---------------------+
|  1   |         Marysville         |      Washington      |   63269    |     48.0517637     |     -122.1770818    |
|  2   |           Perris           |      California      |   72326    |     33.7825194     |     -117.2286478    |
|  3   |         Cleveland          |         Ohio         |   390113   |      41.49932      |     -81.6943605     |
|  4   |         Worcester          |    Massachusetts     |   182544   | 42.262593200000005 |     -71.8022934     |
|  5   |          Columbia          |    South Carolina    |   133358   |     34.0007104     |     -81.0348144     |
|  6   |         Waterbury          |     Connecticut      |   109676   | 41.558152500000006 |     -73.0514965     |
|  7   |           Eagan            |      Minnesota       |   65453    | 44.804132200000005 |     -93.1668858     |
|  8   |         Southfield         |       Michigan       |   73006    |     42.4733688     |     -83.2218731     |
|  9   |         Lafayette          |      Louisiana       |   124276   |     30.2240897     |     -92.0198427     |
|  10  |         Boise City         |        Idaho         |   214237   |     43.6187102     |     -116.2146068    |
|  11  |          Elkhart           |       Indiana        |   51265    |     41.6819935     |     -85.9766671     |
|  12  |         Buena Park         |      California      |   82882    |     33.8675143     |     -117.9981181    |
|  13  |          Marietta          |       Georgia        |   59089    |     33.952602      |     -84.5499327     |
|  14  |           Parker           |       Colorado       |   48608    |     39.5186002     |     -104.7613633    |
|  15  |      West Palm Beach       |       Florida        |   102436   |     26.7153424     |     -80.0533746     |
|  16  |           Salem            |    Massachusetts     |   42544    |      42.51954      |     -70.8967155     |
|  17  |           Aurora           |       Illinois       |   199963   |     41.7605849     |     -88.3200715     |
|  18  |          Leesburg          |       Virginia       |   47673    |     39.1156615     |     -77.5636015     |
|  19  |           Doral            |       Florida        |   50213    |     25.8195424     |     -80.3553302     |
|  20  |        Westminster         |      California      |   91739    |     33.7513419     |     -117.9939921    |
|  21  |          Lubbock           |        Texas         |   239538   |     33.5778631     |     -101.8551665    |
|  22  |       Overland Park        |        Kansas        |   181260   |     38.9822282     |     -94.6707917     |
|  23  |          Jackson           |     Mississippi      |   172638   | 32.298757300000005 |     -90.1848103     |
|  24  |          Gastonia          |    North Carolina    |   73209    |     35.262082      |     -81.1873005     |
|  25  |       Daytona Beach        |       Florida        |   62316    |     29.2108147     |  -81.02283309999999 |
|  26  |        Kansas City         |       Missouri       |   467007   |     39.0997265     |     -94.5785667     |
|  27  |    Rancho Palos Verdes     |      California      |   42448    |     33.7444613     |     -118.3870173    |
|  28  |         Burnsville         |      Minnesota       |   61434    |     44.7677424     |     -93.2777226     |
|  29  |          Rowlett           |        Texas         |   58043    |     32.9029017     |      -96.56388      |
|  30  |          Roswell           |      New Mexico      |   48611    |     33.3942655     |     -104.5230242    |
|  31  |         Montgomery         |       Alabama        |   201332   | 32.366805199999995 |     -86.2999689     |
|  32  |           Logan            |         Utah         |   48913    |     41.7369803     |     -111.8338359    |
|  33  |           Woburn           |    Massachusetts     |   39083    |     42.4792618     |     -71.1522765     |
|  34  |         Allentown          |     Pennsylvania     |   118577   |     40.6084305     |     -75.4901833     |
|  35  |       Mount Pleasant       |    South Carolina    |   74885    |     32.8323225     |  -79.82842579999999 |
|  36  |          Columbus          |       Georgia        |   202824   |     32.4609764     |     -84.9877094     |
|  37  |          Buffalo           |       New York       |   258959   |     42.8864468     |     -78.8783689     |
|  38  |         New Berlin         |      Wisconsin       |   39834    |     42.9764027     |  -88.10842240000001 |
|  39  |    North Richland Hills    |        Texas         |   67317    |     32.8342952     |     -97.2289029     |
|  40  |            Lima            |         Ohio         |   38355    |     40.742551      |     -84.1052256     |
|  41  |         Sacramento         |      California      |   479686   |     38.5815719     |     -121.4943996    |
|  42  |         Fort Smith         |       Arkansas       |   87650    | 35.385924200000005 |     -94.3985475     |
|  43  |      East Providence       |     Rhode Island     |   47149    | 41.813711600000005 |  -71.37005450000001 |
|  44  |         Urbandale          |         Iowa         |   41776    |     41.6266555     |     -93.7121656     |
|  45  |        Mount Vernon        |       New York       |   68224    |     40.9125992     |     -73.8370786     |
|  46  |          Lakewood          |       Colorado       |   147214   |     39.7047095     | -105.08137340000002 |
|  47  |         Henderson          |        Nevada        |   270811   |     36.0395247     |     -114.9817213    |
|  48  |           Covina           |      California      |   48508    |     34.0900091     |     -117.8903397    |
|  49  |          Stamford          |     Connecticut      |   126456   |     41.0534302     |  -73.53873409999999 |
|  50  |        Bloomington         |       Indiana        |   82575    |     39.165325      |     -86.5263857     |
|  51  |         Kingsport          |      Tennessee       |   52962    |     36.548434      |     -82.5618186     |
|  52  |          Spokane           |      Washington      |   210721   |     47.6587802     |     -117.4260466    |
|  53  |         Kennewick          |      Washington      |   76762    |     46.2112458     |     -119.1372338    |
|  54  |        Philadelphia        |     Pennsylvania     |  1553165   |     39.9525839     |     -75.1652215     |
|  55  |         Bellingham         |      Washington      |   82631    |      48.74908      |     -122.4781473    |
|  56  |          Visalia           |      California      |   127763   |     36.3302284     |     -119.2920585    |
|  57  |         La Crosse          |      Wisconsin       |   51522    |     43.8013556     |     -91.2395807     |
|  58  |       Council Bluffs       |         Iowa         |   61969    |     41.2619444     |     -95.8608333     |
|  59  |      North Lauderdale      |       Florida        |   42757    |     26.217305      |     -80.2258811     |
|  60  |           Dallas           |        Texas         |  1257676   |     32.7766642     |     -96.7969879     |
|  61  |          Antioch           |      California      |   107100   |     38.0049214     |     -121.805789     |
|  62  |      Sterling Heights      |       Michigan       |   131224   |     42.5803122     |     -83.0302033     |
|  63  |      Deerfield Beach       |       Florida        |   78041    |     26.3184123     |     -80.0997657     |
|  64  |          Fishers           |       Indiana        |   83891    | 39.95675479999999  |      -86.01335      |
|  65  |          Cheyenne          |       Wyoming        |   62448    |     41.1399814     |     -104.8202462    |
|  66  |          Murrieta          |      California      |   107479   | 33.553914299999995 |     -117.2139232    |
|  67  |           Lenexa           |        Kansas        |   50344    |     38.9536174     |     -94.7335709     |
|  68  |        Noblesville         |       Indiana        |   56540    |     40.0455917     |     -86.0085955     |
|  69  |         Southaven          |     Mississippi      |   50997    |     34.9889818     |     -90.0125913     |
|  70  |           Chino            |      California      |   80988    |     34.0122346     |     -117.688944     |
|  71  |        Gaithersburg        |       Maryland       |   65690    | 39.143440600000005 |     -77.2013705     |
|  72  |      Fountain Valley       |      California      |   56707    |     33.7091847     |     -117.9536697    |
|  73  |         Frederick          |       Maryland       |   66893    |     39.4142688     |  -77.41054090000002 |
|  74  |         Greenville         |    North Carolina    |   89130    |     35.612661      |     -77.3663538     |
|  75  |           DeKalb           |       Illinois       |   43849    |     41.9294736     |     -88.7503647     |
|  76  |         West Allis         |      Wisconsin       |   60697    |     43.0166806     |     -88.0070315     |
|  77  |          Thornton          |       Colorado       |   127359   |     39.8680412     |     -104.9719243    |
|  78  |      West Des Moines       |         Iowa         |   61255    |     41.5772115     |      -93.711332     |
|  79  |         Fall River         |    Massachusetts     |   88697    |     41.7014912     |     -71.1550451     |
|  80  |           Tulare           |      California      |   61170    | 36.20772879999999  |     -119.3473379    |
|  81  |        Chula Vista         |      California      |   256780   |     32.6400541     |     -117.0841955    |
|  82  |       Coral Springs        |       Florida        |   126604   |     26.271192      |  -80.27060440000001 |
|  83  |          Concord           |    North Carolina    |   83506    |     35.4087517     |      -80.579511     |
|  84  |           Smyrna           |       Georgia        |   53438    | 33.883992600000006 |  -84.51437609999999 |
|  85  |           Apopka           |       Florida        |   45587    |     28.6934076     |  -81.53221490000001 |
|  86  |        Grand Forks         |     North Dakota     |   54932    |     47.9252568     |     -97.0328547     |
|  87  |         Lancaster          |         Ohio         |   39325    | 39.71367539999999  |  -82.59932940000002 |
|  88  |         Naperville         |       Illinois       |   144864   |     41.7508391     |  -88.15353520000001 |
|  89  |         Hollywood          |       Florida        |   146526   |     26.0112014     |     -80.1494901     |
|  90  |           Rogers           |       Arkansas       |   60112    |     36.3320196     |     -94.1185366     |
|  91  |        New Orleans         |      Louisiana       |   378715   |     29.9510658     |     -90.0715323     |
|  92  |          Lakewood          |      Washington      |   59097    |     47.1717649     |     -122.518458     |
|  93  |          Oak Lawn          |       Illinois       |   57073    | 41.719978000000005 |     -87.7479528     |
|  94  |          Caldwell          |        Idaho         |   48957    |     43.6629384     |     -116.6873596    |
|  95  |          Portland          |        Oregon        |   609456   | 45.523062200000005 |     -122.6764816    |
|  96  |          Concord           |      California      |   125880   |     37.9779776     |     -122.0310733    |
|  97  |           Burien           |      Washington      |   49858    |     47.4703767     |     -122.3467918    |
|  98  |        St. Charles         |       Missouri       |   67569    |     38.7881062     |     -90.4974359     |
|  99  |          Waukesha          |      Wisconsin       |   71016    |     43.0116784     |     -88.2314813     |
| 100  |         Flagstaff          |       Arizona        |   68667    |     35.1982836     |     -111.651302     |
| 101  |          Puyallup          |      Washington      |   38609    |     47.1853785     | -122.29289740000002 |
| 102  |        Schenectady         |       New York       |   65902    |     42.8142432     |  -73.93956870000001 |
| 103  |           Denver           |       Colorado       |   649495   |     39.7392358     |     -104.990251     |
| 104  |        Springfield         |       Illinois       |   117006   |     39.7817213     |     -89.6501481     |
| 105  |          Campbell          |      California      |   40584    |     37.2871651     |     -121.9499568    |
| 106  |       Moreno Valley        |      California      |   201175   |     33.9424658     |     -117.2296717    |
| 107  |         Kettering          |         Ohio         |   55870    |     39.6895036     |  -84.16882740000001 |
| 108  |        Lincoln Park        |       Michigan       |   37313    |     42.2505943     |  -83.17853609999999 |
| 109  |      Lake Havasu City      |       Arizona        |   52844    |     34.483901      |     -114.3224548    |
| 110  |     North Little Rock      |       Arkansas       |   66075    | 34.769535999999995 |     -92.2670941     |
| 111  |            Reno            |        Nevada        |   233294   |     39.5296329     |     -119.8138027    |
| 112  |         Littleton          |       Colorado       |   44275    |     39.613321      |     -105.0166498    |
| 113  |          Prescott          |       Arizona        |   40590    | 34.540024200000005 |     -112.4685025    |
| 114  |           Dublin           |      California      |   52105    |     37.7021521     |     -121.9357918    |
| 115  |         Texarkana          |        Texas         |   37442    |     33.425125      |     -94.0476882     |
| 116  |          Portland          |        Maine         |   66318    |     43.661471      |     -70.2553259     |
| 117  |       Brooklyn Park        |      Minnesota       |   78373    |     45.0941315     |     -93.3563405     |
| 118  |         West Haven         |     Connecticut      |   55046    |     41.2705484     |  -72.94697109999998 |
| 119  |         El Centro          |      California      |   43363    |       32.792       |     -115.5630514    |
| 120  |         The Colony         |        Texas         |   39458    |     33.0806083     |     -96.8928309     |
| 121  |           Flint            |       Michigan       |   99763    |     43.0125274     |     -83.6874562     |
| 122  |         Pittsburg          |      California      |   66695    | 38.027976200000005 | -121.88468059999998 |
| 123  |          Buckeye           |       Arizona        |   56683    |     33.3703197     | -112.58377659999998 |
| 124  |            Brea            |      California      |   40963    |     33.9166805     |     -117.9000604    |
| 125  |           Indio            |      California      |   83539    |     33.7205771     |     -116.2155619    |
| 126  |         Scottsdale         |       Arizona        |   226918   | 33.494170399999994 |     -111.9260519    |
| 127  |          Columbus          |         Ohio         |   822553   |     39.9611755     |     -82.9987942     |
| 128  |         Lancaster          |     Pennsylvania     |   59325    |     40.0378755     |     -76.3055144     |
| 129  |          Lincoln           |       Nebraska       |   268738   |     40.8257625     |     -96.6851982     |
| 130  |          Trenton           |      New Jersey      |   84349    |     40.2170534     |  -74.74293840000001 |
| 131  |           Boston           |    Massachusetts     |   645966   |     42.3600825     |     -71.0588801     |
| 132  |          Glendora          |      California      |   51074    | 34.136118700000004 |     -117.865339     |
| 133  |         Rochester          |      Minnesota       |   110742   |     44.0121221     |     -92.4801989     |
| 134  |         Florissant         |       Missouri       |   52363    |     38.789217      |      -90.322614     |
| 135  |         Annapolis          |       Maryland       |   38722    |     38.9784453     |     -76.4921829     |
| 136  |        Chapel Hill         |    North Carolina    |   59635    | 35.913199600000006 |  -79.05584449999999 |
| 137  |          Lawrence          |       Indiana        |   47135    |     39.8386516     |     -86.0252612     |
| 138  |          Calexico          |      California      |   39389    |     32.6789476     |     -115.4988834    |
| 139  |        Calumet City        |       Illinois       |   37240    |     41.6155909     |     -87.5294871     |
| 140  |          Missoula          |       Montana        |   69122    |     46.8787176     |     -113.996586     |
| 141  |           Clovis           |      California      |   99769    |     36.8252277     |     -119.7029194    |
| 142  |          Pearland          |        Texas         |   100065   |     29.5635666     |     -95.2860474     |
| 143  |          Gilbert           |       Arizona        |   229972   |     33.3528264     |     -111.789027     |
| 144  |           Wausau           |      Wisconsin       |   39309    |     44.9591352     |     -89.6301221     |
| 145  |          Raleigh           |    North Carolina    |   431746   |     35.7795897     |     -78.6381787     |
| 146  |           Orange           |      California      |   139969   |     33.7877944     |     -117.8531119    |
| 147  |        Walnut Creek        |      California      |   66900    |     37.9100783     |     -122.0651819    |
| 148  |         Bremerton          |      Washington      |   39056    | 47.567320200000005 |     -122.6329356    |
| 149  |        Porterville         |      California      |   55174    |      36.06523      |     -119.0167679    |
| 150  |           Marana           |       Arizona        |   38290    |     32.436381      |     -111.2224422    |
| 151  |        Tallahassee         |       Florida        |   186411   |     30.4382559     |     -84.2807329     |
| 152  |           Conroe           |        Texas         |   63032    |     30.3118769     |     -95.4560512     |
| 153  |         Blacksburg         |       Virginia       |   43609    |     37.2295733     |     -80.4139393     |
| 154  |        San Antonio         |        Texas         |  1409019   |     29.4241219     |     -98.4936282     |
| 155  |          Hartford          |     Connecticut      |   125017   |     41.7637111     |     -72.6850932     |
| 156  |          Waterloo          |         Iowa         |   68366    |     42.492786      |     -92.3425775     |
| 157  |         Binghamton         |       New York       |   46444    |     42.0986867     |     -75.9179738     |
| 158  |          Meridian          |        Idaho         |   83596    | 43.61210870000001  |     -116.3915131    |
| 159  |        Fond du Lac         |      Wisconsin       |   42970    |     43.7730448     |  -88.44705079999999 |
| 160  |          Baytown           |        Texas         |   75418    | 29.735504700000003 |     -94.9774274     |
| 161  |            Cary            |    North Carolina    |   151088   | 35.791540000000005 |  -78.78111690000001 |
| 162  |       Weymouth Town        |    Massachusetts     |   55419    |     42.2180724     |  -70.94103559999999 |
| 163  |           Tulsa            |       Oklahoma       |   398121   |     36.1539816     |      -95.992775     |
| 164  |          Mission           |        Texas         |   81050    |     26.2159066     |     -98.3252932     |
| 165  |       Cuyahoga Falls       |         Ohio         |   49267    |     41.1339449     |  -81.48455849999999 |
| 166  |           Malden           |    Massachusetts     |   60509    |     42.4250964     |      -71.066163     |
| 167  |           Allen            |        Texas         |   92020    |     33.1031744     |     -96.6705503     |

In [ ]:
%cd "/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/March24LC"

/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/March24LC

In [ ]:
%ls

City.db  March24_LC_Post.ipynb  March24_LC_Pre.html  tips.csv

In [ ]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/March24LC'

In [ ]:
# Q1
import pandas as pd

In [ ]:
tips_df = pd.read_csv("tips.csv")
tips_df # ram dataframe

      ID  total_bill   tip     sex smoker   day    time  size
0      1       16.99  1.01  Female     No   Sun  Dinner     2
1      2       10.34  1.66    Male     No   Sun  Dinner     3
2      3       21.01  3.50    Male     No   Sun  Dinner     3
3      4       23.68  3.31    Male     No   Sun  Dinner     2
4      5       24.59  3.61  Female     No   Sun  Dinner     4
..   ...         ...   ...     ...    ...   ...     ...   ...
239  240       29.03  5.92    Male     No   Sat  Dinner     3
240  241       27.18  2.00  Female    Yes   Sat  Dinner     2
241  242       22.67  2.00    Male    Yes   Sat  Dinner     2
242  243       17.82  1.75    Male     No   Sat  Dinner     2
243  244       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [ ]:
cols = tips_df.columns
print(cols)
n = len(cols)
print(f"There are {n} columns in df.")

Index(['ID', 'total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')
There are 8 columns in df.

In [ ]:
# T3
tips_sorted_df =tips_df.sort_values(by=["total_bill",'tip'],ascending=[False,False])
tips_sorted_df

      ID  total_bill    tip     sex smoker   day    time  size
170  171       50.81  10.00    Male    Yes   Sat  Dinner     3
212  213       48.33   9.00    Male     No   Sat  Dinner     4
59    60       48.27   6.73    Male     No   Sat  Dinner     4
156  157       48.17   5.00    Male     No   Sun  Dinner     6
182  183       45.35   3.50    Male    Yes   Sun  Dinner     3
..   ...         ...    ...     ...    ...   ...     ...   ...
149  150        7.51   2.00    Male     No  Thur   Lunch     2
172  173        7.25   5.15    Male    Yes   Sun  Dinner     2
111  112        7.25   1.00  Female     No   Sat  Dinner     1
92    93        5.75   1.00  Female    Yes   Fri  Dinner     2
67    68        3.07   1.00  Female    Yes   Sat  Dinner     1

[244 rows x 8 columns]

In [ ]:
tips_sorted_df.to_csv("tips_sorted.csv",index=False)

In [ ]:
%ls

City.db  March24_LC_Post.ipynb  March24_LC_Pre.html  tips.csv  tips_sorted.csv

In [ ]:
tips_sorted_df.head(10)

      ID  total_bill    tip     sex smoker   day    time  size
170  171       50.81  10.00    Male    Yes   Sat  Dinner     3
212  213       48.33   9.00    Male     No   Sat  Dinner     4
59    60       48.27   6.73    Male     No   Sat  Dinner     4
156  157       48.17   5.00    Male     No   Sun  Dinner     6
182  183       45.35   3.50    Male    Yes   Sun  Dinner     3
102  103       44.30   2.50  Female    Yes   Sat  Dinner     3
197  198       43.11   5.00  Female    Yes  Thur   Lunch     4
142  143       41.19   5.00    Male     No  Thur   Lunch     5
184  185       40.55   3.00    Male    Yes   Sun  Dinner     2
95    96       40.17   4.73    Male    Yes   Fri  Dinner     4

In [ ]:
tips_sorted_df.tail(10)

      ID  total_bill   tip     sex smoker   day    time  size
126  127        8.52  1.48    Male     No  Thur   Lunch     2
135  136        8.51  1.25  Female     No  Thur   Lunch     2
145  146        8.35  1.50  Female     No  Thur   Lunch     2
218  219        7.74  1.44    Male    Yes   Sat  Dinner     2
195  196        7.56  1.44    Male     No  Thur   Lunch     2
149  150        7.51  2.00    Male     No  Thur   Lunch     2
172  173        7.25  5.15    Male    Yes   Sun  Dinner     2
111  112        7.25  1.00  Female     No   Sat  Dinner     1
92    93        5.75  1.00  Female    Yes   Fri  Dinner     2
67    68        3.07  1.00  Female    Yes   Sat  Dinner     1

In [ ]:
# T4
days = tips_df["day"].unique()
print(days) #

n = len(days)
print(f"There are {n} days.")

['Sun' 'Sat' 'Thur' 'Fri']
There are 4 days.

In [ ]:
tips_df["day"].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [ ]:
tips_df["time"].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [ ]:
# T5
t = tips_df['total_bill'].sum()
print(f"The revenue is: ${t:.1f}")

The revenue is: $4827.8

In [ ]:
# T6
gs = tips_df.groupby(by=["sex"])

In [ ]:
gs.groups.keys()

dict_keys(['Female', 'Male'])

In [ ]:
df = gs.get_group("Female")
print(df)

      ID  total_bill   tip     sex smoker   day    time  size
0      1       16.99  1.01  Female     No   Sun  Dinner     2
4      5       24.59  3.61  Female     No   Sun  Dinner     4
11    12       35.26  5.00  Female     No   Sun  Dinner     4
14    15       14.83  3.02  Female     No   Sun  Dinner     2
16    17       10.33  1.67  Female     No   Sun  Dinner     3
..   ...         ...   ...     ...    ...   ...     ...   ...
226  227       10.09  2.00  Female    Yes   Fri   Lunch     2
229  230       22.12  2.88  Female    Yes   Sat  Dinner     2
238  239       35.83  4.67  Female     No   Sat  Dinner     3
240  241       27.18  2.00  Female    Yes   Sat  Dinner     2
243  244       18.78  3.00  Female     No  Thur  Dinner     2

[87 rows x 8 columns]

<ipython-input-39-bba68156c28d>:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = gs.get_group("Female")

In [ ]:
%%shell
jupyter nbconvert "March24_LC_Post.ipynb" --to html

[NbConvertApp] Converting notebook March24_LC_Pre.ipynb to html
[NbConvertApp] Writing 282933 bytes to March24_LC_Pre.html