In [ ]:
# your name and student id

In [ ]:
%cd "/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/Mar21LC"

/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/Mar21LC

In [ ]:
%ls

March21_LC_Pre.ipynb  us-cities-top-1k.csv

In [ ]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/Mar21LC'

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("us-cities-top-1k.csv")
df

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [ ]:
df.columns

Index(['City', 'State', 'Population', 'lat', 'lon'], dtype='object')

In [ ]:
# group by: divide one bid dataframe into small dataframes
gs = df.groupby(by=["State"]) # into small ones based on the states

In [ ]:
# gs: 51 dataframe

In [ ]:
gs.groups.keys()

dict_keys(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'])

In [ ]:
for s in gs.groups.keys():
  print(s)

Alabama
Alaska
Arizona
Arkansas
California
Colorado
Connecticut
Delaware
District of Columbia
Florida
Georgia
Hawaii
Idaho
Illinois
Indiana
Iowa
Kansas
Kentucky
Louisiana
Maine
Maryland
Massachusetts
Michigan
Minnesota
Mississippi
Missouri
Montana
Nebraska
Nevada
New Hampshire
New Jersey
New Mexico
New York
North Carolina
North Dakota
Ohio
Oklahoma
Oregon
Pennsylvania
Rhode Island
South Carolina
South Dakota
Tennessee
Texas
Utah
Vermont
Virginia
Washington
West Virginia
Wisconsin
Wyoming

In [ ]:
s_df = gs.get_group("Texas") # get the dataframe only contains cities in Texas
s_df

<ipython-input-10-e07ca19fa4f7>:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group("Texas") # get the dataframe only contains cities in Texas

                     City  State  Population        lat         lon
20                Lubbock  Texas      239538  33.577863 -101.855166
28                Rowlett  Texas       58043  32.902902  -96.563880
38   North Richland Hills  Texas       67317  32.834295  -97.228903
59                 Dallas  Texas     1257676  32.776664  -96.796988
114             Texarkana  Texas       37442  33.425125  -94.047688
..                    ...    ...         ...        ...         ...
921             Arlington  Texas      379577  32.735687  -97.108066
922            Lewisville  Texas      101074  33.046233  -96.994174
963           League City  Texas       90983  29.507454  -95.094930
968            Cedar Hill  Texas       46663  32.588469  -96.956115
976        Corpus Christi  Texas      316381  27.800583  -97.396381

[83 rows x 5 columns]

In [ ]:
s_df.to_csv("texas_city.csv",index=False)

In [ ]:
%ls

March21_LC_Pre.ipynb  texas_city.csv  us-cities-top-1k.csv

In [ ]:
%cd "/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/Mar21LC"

/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/Mar21LC

In [ ]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/Mar21LC'

In [ ]:
%ls

March21_LC_Pre.html  March21_LC_Pre.ipynb  texas_city.csv  us-cities-top-1k.csv

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("us-cities-top-1k.csv")
df# dataframe, table, sheet

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [ ]:
# groupby(by=[])
# divide a signle dataframe into small ones
df.columns

Index(['City', 'State', 'Population', 'lat', 'lon'], dtype='object')

In [ ]:
states = df["State"].unique() # indexer, collection, series
states

array(['Washington', 'California', 'Ohio', 'Massachusetts',
       'South Carolina', 'Connecticut', 'Minnesota', 'Michigan',
       'Louisiana', 'Idaho', 'Indiana', 'Georgia', 'Colorado', 'Florida',
       'Illinois', 'Virginia', 'Texas', 'Kansas', 'Mississippi',
       'North Carolina', 'Missouri', 'New Mexico', 'Alabama', 'Utah',
       'Pennsylvania', 'New York', 'Wisconsin', 'Arkansas',
       'Rhode Island', 'Iowa', 'Nevada', 'Tennessee', 'Wyoming',
       'Maryland', 'North Dakota', 'Oregon', 'Arizona', 'Maine',
       'Nebraska', 'New Jersey', 'Montana', 'Oklahoma', 'West Virginia',
       'South Dakota', 'District of Columbia', 'New Hampshire', 'Alaska',
       'Delaware', 'Kentucky', 'Hawaii', 'Vermont'], dtype=object)

In [ ]:
len(states)

51

In [ ]:
c1 = df["State"]=="Utah" # assignment
c1

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: State, Length: 1000, dtype: bool

In [ ]:
df[c1]

                 City State  Population        lat         lon
31              Logan  Utah       48913  41.736980 -111.833836
193      South Jordan  Utah       59366  40.562170 -111.929658
285         Bountiful  Utah       43023  40.889390 -111.880771
381             Provo  Utah      116288  40.233844 -111.658534
434      Spanish Fork  Utah       36956  40.114955 -111.654923
440      Taylorsville  Utah       60519  40.667725 -111.938826
466          Riverton  Utah       40921  40.521893 -111.939102
500              Lehi  Utah       54382  40.391617 -111.850766
533             Ogden  Utah       84249  41.223000 -111.973830
568            Layton  Utah       70790  41.060222 -111.971053
603            Murray  Utah       48612  40.666892 -111.887991
630             Sandy  Utah       90231  40.564978 -111.838973
673  West Valley City  Utah      133579  40.691613 -112.001050
676              Orem  Utah       91648  40.296898 -111.694648
737               Roy  Utah       37733  41.161611 -112.026331
762            Draper  Utah       45285  40.524671 -111.863823
856        St. George  Utah       76817  37.096528 -113.568416
955       West Jordan  Utah      110077  40.609670 -111.939103
964    Salt Lake City  Utah      191180  40.760779 -111.891047

In [ ]:
gs = df.groupby(by=["State"]) # 51 states,

In [ ]:
# all the labels (group names)
gs.groups.keys() # collection

dict_keys(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'])

In [ ]:
df1 = gs.get_group("Utah") #
df1

<ipython-input-20-2249208e60e2>:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df1 = gs.get_group("Utah") #

                 City State  Population        lat         lon
31              Logan  Utah       48913  41.736980 -111.833836
193      South Jordan  Utah       59366  40.562170 -111.929658
285         Bountiful  Utah       43023  40.889390 -111.880771
381             Provo  Utah      116288  40.233844 -111.658534
434      Spanish Fork  Utah       36956  40.114955 -111.654923
440      Taylorsville  Utah       60519  40.667725 -111.938826
466          Riverton  Utah       40921  40.521893 -111.939102
500              Lehi  Utah       54382  40.391617 -111.850766
533             Ogden  Utah       84249  41.223000 -111.973830
568            Layton  Utah       70790  41.060222 -111.971053
603            Murray  Utah       48612  40.666892 -111.887991
630             Sandy  Utah       90231  40.564978 -111.838973
673  West Valley City  Utah      133579  40.691613 -112.001050
676              Orem  Utah       91648  40.296898 -111.694648
737               Roy  Utah       37733  41.161611 -112.026331
762            Draper  Utah       45285  40.524671 -111.863823
856        St. George  Utah       76817  37.096528 -113.568416
955       West Jordan  Utah      110077  40.609670 -111.939103
964    Salt Lake City  Utah      191180  40.760779 -111.891047

In [ ]:
# sort_values()
df1.sort_values(by=["Population"],ascending=[False])

                 City State  Population        lat         lon
964    Salt Lake City  Utah      191180  40.760779 -111.891047
673  West Valley City  Utah      133579  40.691613 -112.001050
381             Provo  Utah      116288  40.233844 -111.658534
955       West Jordan  Utah      110077  40.609670 -111.939103
676              Orem  Utah       91648  40.296898 -111.694648
630             Sandy  Utah       90231  40.564978 -111.838973
533             Ogden  Utah       84249  41.223000 -111.973830
856        St. George  Utah       76817  37.096528 -113.568416
568            Layton  Utah       70790  41.060222 -111.971053
440      Taylorsville  Utah       60519  40.667725 -111.938826
193      South Jordan  Utah       59366  40.562170 -111.929658
500              Lehi  Utah       54382  40.391617 -111.850766
31              Logan  Utah       48913  41.736980 -111.833836
603            Murray  Utah       48612  40.666892 -111.887991
762            Draper  Utah       45285  40.524671 -111.863823
285         Bountiful  Utah       43023  40.889390 -111.880771
466          Riverton  Utah       40921  40.521893 -111.939102
737               Roy  Utah       37733  41.161611 -112.026331
434      Spanish Fork  Utah       36956  40.114955 -111.654923

In [ ]:
#
gs = df.groupby(by=["State"])

In [ ]:
states = gs.groups.keys() # collection
states#print(states)

dict_keys(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'])

In [ ]:
for i in states:
  print(i)
  s_df = gs.get_group(i)
  print(s_df)
  s_df.to_csv(f"d1/{i}.csv")

Alabama
            City    State  Population        lat        lon
30    Montgomery  Alabama      201332  32.366805 -86.299969
248   Birmingham  Alabama      212113  33.520661 -86.802490
306   Huntsville  Alabama      186254  34.730369 -86.586104
319      Madison  Alabama       45799  34.699258 -86.748332
388       Mobile  Alabama      194899  30.695366 -88.039891
412   Tuscaloosa  Alabama       95334  33.209841 -87.569174
415       Hoover  Alabama       84126  33.405387 -86.811378
455      Decatur  Alabama       55816  34.605925 -86.983342
614       Auburn  Alabama       58582  32.609857 -85.480782
742     Florence  Alabama       40059  34.799810 -87.677251
835  Phenix City  Alabama       37498  32.470976 -85.000765
934       Dothan  Alabama       68001  31.223231 -85.390489
Alaska
          City   State  Population        lat         lon
370  Anchorage  Alaska      300950  61.218056 -149.900278
Arizona
                 City    State  Population        lat         lon
99          Flagstaff  Arizona       68667  35.198284 -111.651302
108  Lake Havasu City  Arizona       52844  34.483901 -114.322455
112          Prescott  Arizona       40590  34.540024 -112.468502
122           Buckeye  Arizona       56683  33.370320 -112.583777
125        Scottsdale  Arizona      226918  33.494170 -111.926052
142           Gilbert  Arizona      229972  33.352826 -111.789027
149            Marana  Arizona       38290  32.436381 -111.222442
167            Tucson  Arizona      526116  32.221743 -110.926479
201        Oro Valley  Arizona       41627  32.390907 -110.966488
202              Mesa  Arizona      457587  33.415184 -111.831472
217          Maricopa  Arizona       45508  33.058106 -112.047642
235          Goodyear  Arizona       72864  33.435339 -112.357657
301      Sierra Vista  Arizona       45129  31.545500 -110.277286
394          Chandler  Arizona      249146  33.306160 -111.841250
401   Apache Junction  Arizona       37130  33.415048 -111.549578
418     Bullhead City  Arizona       39383  35.135939 -114.528598
437            Peoria  Arizona      162592  33.580596 -112.237378
438             Tempe  Arizona      168228  33.425510 -111.940005
480          Avondale  Arizona       78822  33.435598 -112.349602
518       Casa Grande  Arizona       50111  32.879502 -111.757352
574   Prescott Valley  Arizona       39791  34.610024 -112.315721
581          Surprise  Arizona      123546  33.629234 -112.367928
778              Yuma  Arizona       91923  32.692651 -114.627692
966           Phoenix  Arizona     1513367  33.448377 -112.074037
980          Glendale  Arizona      234632  33.538652 -112.185987
Arkansas
                  City     State  Population        lat        lon
41          Fort Smith  Arkansas       87650  35.385924 -94.398548
89              Rogers  Arkansas       60112  36.332020 -94.118537
109  North Little Rock  Arkansas       66075  34.769536 -92.267094
631        Bentonville  Arkansas       40167  36.372854 -94.208817
655         Springdale  Arkansas       75229  36.186744 -94.128814
680        Little Rock  Arkansas      197357  34.746481 -92.289595
867          Jonesboro  Arkansas       71551  35.842297 -90.704279
874         Pine Bluff  Arkansas       46094  34.228431 -92.003196
882       Fayetteville  Arkansas       78960  36.062579 -94.157426
884             Conway  Arkansas       63816  35.088696 -92.442101
California
                    City       State  Population        lat         lon
1                 Perris  California       72326  33.782519 -117.228648
11            Buena Park  California       82882  33.867514 -117.998118
19           Westminster  California       91739  33.751342 -117.993992
26   Rancho Palos Verdes  California       42448  33.744461 -118.387017
40            Sacramento  California      479686  38.581572 -121.494400
..                   ...         ...         ...        ...         ...
981              Stanton  California       38623  33.802516 -117.993116
991          Santa Clara  California      120245  37.354108 -121.955236
992            Oceanside  California      172794  33.195870 -117.379483
993          Lake Forest  California       79312  33.646966 -117.689218
999              Compton  California       97877  33.895849 -118.220071

[212 rows x 5 columns]
Colorado
                 City     State  Population        lat         lon
13             Parker  Colorado       48608  39.518600 -104.761363
45           Lakewood  Colorado      147214  39.704709 -105.081373
76           Thornton  Colorado      127359  39.868041 -104.971924
102            Denver  Colorado      649495  39.739236 -104.990251
111         Littleton  Colorado       44275  39.613321 -105.016650
182            Pueblo  Colorado      108249  38.254447 -104.609141
290     Commerce City  Colorado       49799  39.808320 -104.933868
292      Fort Collins  Colorado      152061  40.585260 -105.084423
340        Broomfield  Colorado       59471  39.920541 -105.086650
395            Arvada  Colorado      111707  39.802764 -105.087484
542            Aurora  Colorado      345803  39.729432 -104.831919
554  Colorado Springs  Colorado      439886  38.833882 -104.821363
561           Boulder  Colorado      103166  40.014986 -105.270546
770        Centennial  Colorado      106114  39.580745 -104.877173
803    Grand Junction  Colorado       59778  39.063871 -108.550649
849          Loveland  Colorado       71334  40.397761 -105.074980
864          Longmont  Colorado       89919  40.167207 -105.101928
893       Castle Rock  Colorado       53063  39.372212 -104.856090
901       Westminster  Colorado      110945  39.836653 -105.037205
904           Greeley  Colorado       96539  40.423314 -104.709132
941        Northglenn  Colorado       37499  39.896182 -104.981147
Connecticut
            City        State  Population        lat        lon
5      Waterbury  Connecticut      109676  41.558153 -73.051496
48      Stamford  Connecticut      126456  41.053430 -73.538734
117   West Haven  Connecticut       55046  41.270548 -72.946971
154     Hartford  Connecticut      125017  41.763711 -72.685093
203      Norwalk  Connecticut       87776  41.117744 -73.408158
228      Danbury  Connecticut       83684  41.394817 -73.454011
268      Norwich  Connecticut       40347  41.524265 -72.075910
598    New Haven  Connecticut      130660  41.308274 -72.927883
610      Shelton  Connecticut       40999  41.316486 -73.093164
710      Milford  Connecticut       51644  41.230698 -73.064036
859      Meriden  Connecticut       60456  41.538153 -72.807044
886   Middletown  Connecticut       47333  41.562321 -72.650649
911   Bridgeport  Connecticut      147216  41.186548 -73.195177
945      Bristol  Connecticut       60568  41.671765 -72.949270
985  New Britain  Connecticut       72939  41.661210 -72.779542
Delaware
           City     State  Population        lat        lon
439  Wilmington  Delaware       71525  39.739072 -75.539788
525       Dover  Delaware       37366  39.158168 -75.524368
District of Columbia
           City                 State  Population        lat        lon
323  Washington  District of Columbia      646449  38.907192 -77.036871
Florida
                 City    State  Population        lat        lon
14    West Palm Beach  Florida      102436  26.715342 -80.053375
18              Doral  Florida       50213  25.819542 -80.355330
24      Daytona Beach  Florida       62316  29.210815 -81.022833
58   North Lauderdale  Florida       42757  26.217305 -80.225881
62    Deerfield Beach  Florida       78041  26.318412 -80.099766
..                ...      ...         ...        ...        ...
961       Panama City  Florida       36877  30.158813 -85.660206
965       Fort Pierce  Florida       43074  27.446706 -80.325606
970             Ocala  Florida       57468  29.187199 -82.140092
984        Boca Raton  Florida       89407  26.368306 -80.128932
989        Lauderhill  Florida       69813  26.140363 -80.213381

[73 rows x 5 columns]
Georgia
                        City    State  Population        lat        lon
12                  Marietta  Georgia       59089  33.952602 -84.549933
35                  Columbus  Georgia      202824  32.460976 -84.987709
83                    Smyrna  Georgia       53438  33.883993 -84.514376
192     Athens-Clarke County  Georgia      119980  33.951935 -83.357567
360                    Macon  Georgia       89981  32.840695 -83.632402
382                  Atlanta  Georgia      447841  33.748995 -84.387982
406              Johns Creek  Georgia       82788  34.028926 -84.198579
449  Augusta-Richmond County  Georgia      197350  33.473498 -82.010515
451                   Albany  Georgia       76185  31.578507 -84.155741
495                 Savannah  Georgia      142772  32.083541 -81.099834
515        Peachtree Corners  Georgia       40059  33.969893 -84.221455
640                 Dunwoody  Georgia       47591  33.946213 -84.334647
739            Warner Robins  Georgia       72531  32.613001 -83.624201
817            Sandy Springs  Georgia       99770  33.930435 -84.373315
841               Alpharetta  Georgia       62298  34.075376 -84.294090
894                 Valdosta  Georgia       56481  30.832702 -83.278485
943               Brookhaven  Georgia       50603  33.865103 -84.336592
971                  Roswell  Georgia       94034  34.023243 -84.361556

<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)

Hawaii
         City   State  Population        lat         lon
785  Honolulu  Hawaii      347884  21.306944 -157.858333
Idaho
              City  State  Population        lat         lon
9       Boise City  Idaho      214237  43.618710 -116.214607
93        Caldwell  Idaho       48957  43.662938 -116.687360
157       Meridian  Idaho       83596  43.612109 -116.391513
231  Coeur d'Alene  Idaho       46402  47.677683 -116.780466
322          Nampa  Idaho       86518  43.540717 -116.563462
683    Idaho Falls  Idaho       58292  43.491651 -112.033964
812      Pocatello  Idaho       54350  42.871303 -112.445534
888     Twin Falls  Idaho       45981  42.562967 -114.460871
Illinois
                  City     State  Population        lat        lon
16              Aurora  Illinois      199963  41.760585 -88.320071
74              DeKalb  Illinois       43849  41.929474 -88.750365
87          Naperville  Illinois      144864  41.750839 -88.153535
92            Oak Lawn  Illinois       57073  41.719978 -87.747953
103        Springfield  Illinois      117006  39.781721 -89.650148
138       Calumet City  Illinois       37240  41.615591 -87.529487
184         Belleville  Illinois       42895  38.520050 -89.983994
233       Crystal Lake  Illinois       40388  42.241134 -88.316197
251            Addison  Illinois       37385  41.931696 -87.988956
253             Normal  Illinois       54664  40.514203 -88.990631
254         Romeoville  Illinois       39650  41.647531 -88.089506
265           Wheeling  Illinois       38015  42.139193 -87.928959
304      Buffalo Grove  Illinois       41778  42.166283 -87.963131
324            Wheaton  Illinois       53648  41.866140 -88.107013
328             Peoria  Illinois      116513  40.693649 -89.588986
345           Elmhurst  Illinois       45556  41.899474 -87.940342
353             Quincy  Illinois       40915  39.935602 -91.409873
356        Bloomington  Illinois       78902  40.484203 -88.993687
364         Streamwood  Illinois       40351  42.025583 -88.178409
386            Decatur  Illinois       74710  39.840315 -88.954800
402     Mount Prospect  Illinois       54771  42.066417 -87.937291
458           Bartlett  Illinois       41679  41.995028 -88.185630
484        Rock Island  Illinois       38877  41.509477 -90.578748
490        Des Plaines  Illinois       58918  42.033362 -87.883399
528           Palatine  Illinois       69350  42.110304 -88.034240
557           Oak Park  Illinois       52066  41.885032 -87.784503
569        Bolingbrook  Illinois       73936  41.698642 -88.068395
571           Glenview  Illinois       45417  42.069751 -87.787841
577         Schaumburg  Illinois       74907  42.033361 -88.083406
594            Chicago  Illinois     2718782  41.878114 -87.629798
597            Lombard  Illinois       43907  41.880030 -88.007844
641             Skokie  Illinois       65176  42.032403 -87.741625
662             Moline  Illinois       43116  41.506700 -90.515134
697  Arlington Heights  Illinois       75994  42.088360 -87.980626
706           Rockford  Illinois      150251  42.271131 -89.093995
709      Downers Grove  Illinois       49670  41.808919 -88.011175
780       Carol Stream  Illinois       40379  41.912529 -88.134793
781             Joliet  Illinois      147806  41.525031 -88.081725
790         Plainfield  Illinois       41734  41.632223 -88.212031
791    Hoffman Estates  Illinois       52398  42.062992 -88.122720
818          Champaign  Illinois       83424  40.116420 -88.243383
836             Berwyn  Illinois       56758  41.850587 -87.793669
850    Carpentersville  Illinois       38241  42.121136 -88.257858
862              Elgin  Illinois      110145  42.035408 -88.282567
919           Waukegan  Illinois       88826  42.363633 -87.844794
936        Tinley Park  Illinois       57282  41.573144 -87.793294
938             Urbana  Illinois       41752  40.110588 -88.207270
948        Orland Park  Illinois       58590  41.630310 -87.853943
951           Evanston  Illinois       75570  42.045072 -87.687697
959             Cicero  Illinois       84103  41.845588 -87.753945
972         Park Ridge  Illinois       37839  42.011141 -87.840619
978       Hanover Park  Illinois       38510  41.999472 -88.145073
Indiana
               City    State  Population        lat        lon
10          Elkhart  Indiana       51265  41.681993 -85.976667
49      Bloomington  Indiana       82575  39.165325 -86.526386
63          Fishers  Indiana       83891  39.956755 -86.013350
67      Noblesville  Indiana       56540  40.045592 -86.008595
136        Lawrence  Indiana       47135  39.838652 -86.025261
207       Mishawaka  Indiana       47989  41.661993 -86.158616
219      Fort Wayne  Indiana      256496  41.079273 -85.139351
276       Greenwood  Indiana       53665  39.613658 -86.106653
303         Hammond  Indiana       78967  41.583369 -87.500041
397          Kokomo  Indiana       56895  40.486427 -86.133603
399    Indianapolis  Indiana      843393  39.768403 -86.158068
404       Lafayette  Indiana       70373  40.416702 -86.875287
457  Jeffersonville  Indiana       45929  38.277570 -85.737185
499          Muncie  Indiana       70316  40.193377 -85.386360
517            Gary  Indiana       78450  41.593370 -87.346427
691          Carmel  Indiana       85927  39.978371 -86.118043
743     Terre Haute  Indiana       61025  39.466703 -87.413909
747        Columbus  Indiana       45775  39.201440 -85.921380
758      South Bend  Indiana      100886  41.676355 -86.251990
772        Anderson  Indiana       55670  40.105320 -85.680254
897      Evansville  Indiana      120310  37.971559 -87.571090
Iowa
                City State  Population        lat        lon
43         Urbandale  Iowa       41776  41.626655 -93.712166
57    Council Bluffs  Iowa       61969  41.261944 -95.860833
77   West Des Moines  Iowa       61255  41.577211 -93.711332
155         Waterloo  Iowa       68366  42.492786 -92.342578
413           Ankeny  Iowa       51567  41.731788 -93.600128
432       Sioux City  Iowa       82459  42.499994 -96.400307
520          Dubuque  Iowa       58253  42.500558 -90.664572
580             Ames  Iowa       61792  42.034722 -93.620000
611      Cedar Falls  Iowa       40566  42.534899 -92.445316
669        Iowa City  Iowa       71591  41.661128 -91.530168
715     Cedar Rapids  Iowa      128429  41.977880 -91.665623
760       Des Moines  Iowa      207510  41.600545 -93.609106
983        Davenport  Iowa      102157  41.523644 -90.577637
Kansas
              City   State  Population        lat        lon
21   Overland Park  Kansas      181260  38.982228 -94.670792
66          Lenexa  Kansas       50344  38.953617 -94.733571
198       Lawrence  Kansas       90811  38.971669 -95.235250
263    Kansas City  Kansas      148483  39.114053 -94.627464
331      Manhattan  Kansas       56143  39.183608 -96.571669
342        Wichita  Kansas      386552  37.688889 -97.336111
405         Olathe  Kansas      131885  38.881396 -94.819129
478     Hutchinson  Kansas       41889  38.060845 -97.929774
587        Shawnee  Kansas       64323  39.022849 -94.715187
720         Topeka  Kansas      127679  39.055824 -95.689019
831         Salina  Kansas       47846  38.840280 -97.611424
Kentucky
                  City     State  Population        lat        lon
530          Covington  Kentucky       40956  39.083671 -84.508554
591          Owensboro  Kentucky       58416  37.771907 -87.111168
728         Louisville  Kentucky      609893  38.252665 -85.758456
776  Lexington-Fayette  Kentucky      308428  38.040584 -84.503716
920      Bowling Green  Kentucky       61488  36.968522 -86.480804
Louisiana
             City      State  Population        lat        lon
8       Lafayette  Louisiana      124276  30.224090 -92.019843
90    New Orleans  Louisiana      378715  29.951066 -90.071532
270    Alexandria  Louisiana       48426  31.311294 -92.445137
486        Kenner  Louisiana       66975  29.994092 -90.241743
532    Shreveport  Louisiana      200327  32.525152 -93.750179
753  Lake Charles  Louisiana       74024  30.226595 -93.217376
815  Bossier City  Louisiana       66333  32.515985 -93.732123
871        Monroe  Louisiana       49761  32.509311 -92.119301
944   Baton Rouge  Louisiana      229426  30.458283 -91.140320
Maine
         City  State  Population        lat        lon
115  Portland  Maine       66318  43.661471 -70.255326
Maryland
             City     State  Population        lat        lon
70   Gaithersburg  Maryland       65690  39.143441 -77.201370
72      Frederick  Maryland       66893  39.414269 -77.410541
134     Annapolis  Maryland       38722  38.978445 -76.492183
227         Bowie  Maryland       56759  39.006777 -76.779136
297    Hagerstown  Maryland       40612  39.641763 -77.719993
794     Rockville  Maryland       64072  39.083997 -77.152758
872     Baltimore  Maryland      622104  39.290385 -76.612189
Massachusetts
                City          State  Population        lat        lon
3          Worcester  Massachusetts      182544  42.262593 -71.802293
15             Salem  Massachusetts       42544  42.519540 -70.896715
32            Woburn  Massachusetts       39083  42.479262 -71.152276
78        Fall River  Massachusetts       88697  41.701491 -71.155045
130           Boston  Massachusetts      645966  42.360082 -71.058880
161    Weymouth Town  Massachusetts       55419  42.218072 -70.941036
165           Malden  Massachusetts       60509  42.425096 -71.066163
183          Chelsea  Massachusetts       37670  42.391764 -71.032828
221          Medford  Massachusetts       57170  42.418430 -71.106164
264        Fitchburg  Massachusetts       40383  42.583423 -71.802295
266           Newton  Massachusetts       87971  42.337041 -71.209221
291      Springfield  Massachusetts      153703  42.101483 -72.589811
335           Lowell  Massachusetts      108861  42.633425 -71.316172
492          Taunton  Massachusetts       56069  41.900101 -71.089767
537         Lawrence  Massachusetts       77657  42.707035 -71.163114
547          Waltham  Massachusetts       62227  42.376485 -71.235611
564      Marlborough  Massachusetts       39414  42.345927 -71.552287
602  Barnstable Town  Massachusetts       44641  41.700321 -70.300202
639          Holyoke  Massachusetts       40249  42.204259 -72.616201
659         Brockton  Massachusetts       94089  42.083434 -71.018379
687          Peabody  Massachusetts       52044  42.527873 -70.928661
695           Revere  Massachusetts       53756  42.408430 -71.011995
717           Quincy  Massachusetts       93494  42.252877 -71.002270
749       Leominster  Massachusetts       41002  42.525091 -71.759794
768          Beverly  Massachusetts       40664  42.558428 -70.880049
787        Attleboro  Massachusetts       43886  41.944544 -71.285608
792          Methuen  Massachusetts       48514  42.726202 -71.190892
827       Pittsfield  Massachusetts       44057  42.450085 -73.245382
832       Somerville  Massachusetts       78804  42.387597 -71.099497
861        Westfield  Massachusetts       41301  42.125093 -72.749538
876             Lynn  Massachusetts       91589  42.466763 -70.949494
927      New Bedford  Massachusetts       95078  41.636215 -70.934205
969         Chicopee  Massachusetts       55717  42.148704 -72.607867
977        Haverhill  Massachusetts       62088  42.776201 -71.077280
979        Cambridge  Massachusetts      107289  42.373616 -71.109733
996          Everett  Massachusetts       42935  42.408430 -71.053663
Michigan
                 City     State  Population        lat        lon
7          Southfield  Michigan       73006  42.473369 -83.221873
61   Sterling Heights  Michigan      131224  42.580312 -83.030203
107      Lincoln Park  Michigan       37313  42.250594 -83.178536
120             Flint  Michigan       99763  43.012527 -83.687456
178  St. Clair Shores  Michigan       60070  42.497408 -82.896360
204          Kentwood  Michigan       50233  42.869473 -85.644749
225            Taylor  Michigan       61817  42.240872 -83.269651
239           Saginaw  Michigan       50303  43.419470 -83.950807
244           Detroit  Michigan      688701  42.331427 -83.045754
311           Pontiac  Michigan       59887  42.638922 -83.291047
368          Muskegon  Michigan       37213  43.234181 -86.248392
408         Kalamazoo  Michigan       75548  42.291707 -85.587229
420              Troy  Michigan       82821  42.606409 -83.149775
423         Royal Oak  Michigan       58946  42.489480 -83.144649
441          Westland  Michigan       82578  42.324204 -83.400211
482      Battle Creek  Michigan       51848  42.321152 -85.179714
556      Grand Rapids  Michigan      192294  42.963360 -85.668086
578            Warren  Michigan      134873  42.514457 -83.014653
583           Midland  Michigan       42181  43.615583 -84.247212
619   Rochester Hills  Michigan       72952  42.658366 -83.149932
648         Ann Arbor  Michigan      117025  42.280826 -83.743038
650      East Lansing  Michigan       48554  42.736979 -84.483865
692           Portage  Michigan       47523  42.201154 -85.580002
735           Wyoming  Michigan       74100  42.913360 -85.705309
764           Livonia  Michigan       95208  42.368370 -83.352710
784  Dearborn Heights  Michigan       56620  42.336982 -83.273263
799  Farmington Hills  Michigan       81295  42.498994 -83.367717
869          Dearborn  Michigan       95884  42.322260 -83.176315
947           Lansing  Michigan      113972  42.732535 -84.555535
986         Roseville  Michigan       47555  42.497258 -82.937141
994              Novi  Michigan       57960  42.480590 -83.475491
Minnesota
               City      State  Population        lat        lon
6             Eagan  Minnesota       65453  44.804132 -93.166886
27       Burnsville  Minnesota       61434  44.767742 -93.277723
116   Brooklyn Park  Minnesota       78373  45.094132 -93.356341
132       Rochester  Minnesota      110742  44.012122 -92.480199
169        Shakopee  Minnesota       39167  44.797396 -93.527286
185     Minneapolis  Minnesota      400070  44.977753 -93.265011
209       St. Cloud  Minnesota       66297  45.557945 -94.163240
243           Edina  Minnesota       49376  44.889687 -93.349949
255     Coon Rapids  Minnesota       62103  45.173239 -93.303006
271          Blaine  Minnesota       60407  45.160799 -93.234949
344       Lakeville  Minnesota       58562  44.649687 -93.242720
436    Eden Prairie  Minnesota       62603  44.854686 -93.470786
483     Bloomington  Minnesota       86319  44.840798 -93.298280
526        Moorhead  Minnesota       39398  46.873765 -96.767804
543          Duluth  Minnesota       86128  46.786672 -92.100485
606       Maplewood  Minnesota       39765  44.953022 -92.995215
666        St. Paul  Minnesota      294873  44.953703 -93.089958
671    Apple Valley  Minnesota       50201  44.731909 -93.217720
723      Minnetonka  Minnesota       51368  44.921184 -93.468749
757        Plymouth  Minnesota       73987  45.010519 -93.455509
807     Maple Grove  Minnesota       65415  45.072464 -93.455788
846         Mankato  Minnesota       40641  44.163578 -93.999400
877        Woodbury  Minnesota       65656  44.923855 -92.959380
912  St. Louis Park  Minnesota       47411  44.959738 -93.370219
Mississippi
            City        State  Population        lat        lon
22       Jackson  Mississippi      172638  32.298757 -90.184810
68     Southaven  Mississippi       50997  34.988982 -90.012591
469     Gulfport  Mississippi       71012  30.367420 -89.092816
472  Hattiesburg  Mississippi       47556  31.327119 -89.290339
663     Meridian  Mississippi       40921  32.364310 -88.703656
937       Biloxi  Mississippi       44820  30.396032 -88.885308

<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)

Missouri
               City     State  Population        lat        lon
25      Kansas City  Missouri      467007  39.099727 -94.578567
97      St. Charles  Missouri       67569  38.788106 -90.497436
133      Florissant  Missouri       52363  38.789217 -90.322614
189       St. Louis  Missouri      318416  38.627003 -90.199404
321  Cape Girardeau  Missouri       38816  37.305884 -89.518148
392  Jefferson City  Missouri       43330  38.576702 -92.173516
579      St. Peters  Missouri       54842  38.787470 -90.629892
628    Lee's Summit  Missouri       93184  38.910841 -94.382172
644      St. Joseph  Missouri       77147  39.767458 -94.846681
689        Columbia  Missouri      115276  38.951705 -92.334072
821    Blue Springs  Missouri       53294  39.016951 -94.281615
842        O'Fallon  Missouri       82809  38.810608 -90.699848
873     Springfield  Missouri      164122  37.208957 -93.292299
913    Chesterfield  Missouri       47749  38.663108 -90.577067
946    Independence  Missouri      117240  39.091116 -94.415507
962          Joplin  Missouri       50789  37.084227 -94.513281
Montana
            City    State  Population        lat         lon
139     Missoula  Montana       69122  46.878718 -113.996586
576      Bozeman  Montana       39860  45.676998 -111.042934
595     Billings  Montana      109059  45.783286 -108.500690
672  Great Falls  Montana       59351  47.494184 -111.283345
Nebraska
             City     State  Population        lat        lon
128       Lincoln  Nebraska      268738  40.825763 -96.685198
329         Omaha  Nebraska      434353  41.252363 -95.997988
653      Bellevue  Nebraska       53663  41.154362 -95.914557
688  Grand Island  Nebraska       50550  40.926396 -98.342012
Nevada
                City   State  Population        lat         lon
46         Henderson  Nevada      270811  36.039525 -114.981721
110             Reno  Nevada      233294  39.529633 -119.813803
194  North Las Vegas  Nevada      226877  36.198859 -115.117501
315           Sparks  Nevada       93282  39.534911 -119.752689
447      Carson City  Nevada       54080  39.163798 -119.767403
712        Las Vegas  Nevada      603488  36.169941 -115.139830
New Hampshire
           City          State  Population        lat        lon
359      Nashua  New Hampshire       87137  42.765366 -71.467566
829  Manchester  New Hampshire      110378  42.995640 -71.454789
973     Concord  New Hampshire       42419  43.208137 -71.537572
New Jersey
              City       State  Population        lat        lon
129        Trenton  New Jersey       84349  40.217053 -74.742938
171  Atlantic City  New Jersey       39551  39.364283 -74.422927
210        Passaic  New Jersey       70868  40.856766 -74.128476
236       Paterson  New Jersey      145948  40.916765 -74.171811
269         Newark  New Jersey      278427  40.735657 -74.172367
299     Union City  New Jersey       68247  40.697590 -74.263164
339     Hackensack  New Jersey       44113  40.885933 -74.043474
362         Camden  New Jersey       76903  39.925946 -75.119620
369      Elizabeth  New Jersey      127558  40.663992 -74.210701
452     Sayreville  New Jersey       44412  40.459402 -74.360846
507  New Brunswick  New Jersey       55831  40.486216 -74.451819
642         Kearny  New Jersey       41664  40.768434 -74.145421
660        Bayonne  New Jersey       65028  40.668714 -74.114309
665    Jersey City  New Jersey      257342  40.728158 -74.077642
686    Perth Amboy  New Jersey       51982  40.506772 -74.265423
775        Hoboken  New Jersey       52575  40.743991 -74.032363
819        Clifton  New Jersey       85390  40.858433 -74.163755
875     Plainfield  New Jersey       50588  40.633714 -74.407374
935    East Orange  New Jersey       64544  40.767323 -74.204868
949       Vineland  New Jersey       61050  39.486377 -75.025964
995  West New York  New Jersey       52122  40.787879 -74.014306
997         Linden  New Jersey       41301  40.622048 -74.244590
New Mexico
            City       State  Population        lat         lon
29       Roswell  New Mexico       48611  33.394266 -104.523024
191  Albuquerque  New Mexico      556495  35.085334 -106.605553
252   Rio Rancho  New Mexico       91956  35.232754 -106.663044
487       Clovis  New Mexico       39508  34.404799 -103.205227
562     Santa Fe  New Mexico       69976  35.686975 -105.937799
575   Las Cruces  New Mexico      101324  32.319940 -106.763654
923   Farmington  New Mexico       45426  36.728058 -108.218686
New York
              City     State  Population        lat        lon
36         Buffalo  New York      258959  42.886447 -78.878369
44    Mount Vernon  New York       68224  40.912599 -73.837079
101    Schenectady  New York       65902  42.814243 -73.939569
156     Binghamton  New York       46444  42.098687 -75.917974
223         Albany  New York       98424  42.652579 -73.756232
247      Rochester  New York      210358  43.161030 -77.610922
295        Yonkers  New York      199766  40.931210 -73.898747
314  Niagara Falls  New York       49468  43.096214 -79.037739
361      Hempstead  New York       55361  40.706213 -73.618740
421   New Rochelle  New York       79446  40.911488 -73.782355
488           Troy  New York       49974  42.728412 -73.691785
521       Syracuse  New York      144669  43.048122 -76.147424
524  Valley Stream  New York       37659  40.664270 -73.708465
668       Freeport  New York       43167  40.657602 -73.583183
682   White Plains  New York       57866  41.033986 -73.762910
870          Utica  New York       61808  43.100903 -75.232664
890       New York  New York     8405837  40.712784 -74.005941
North Carolina
              City           State  Population        lat        lon
23        Gastonia  North Carolina       73209  35.262082 -81.187301
73      Greenville  North Carolina       89130  35.612661 -77.366354
82         Concord  North Carolina       83506  35.408752 -80.579511
135    Chapel Hill  North Carolina       59635  35.913200 -79.055844
144        Raleigh  North Carolina      431746  35.779590 -78.638179
160           Cary  North Carolina      151088  35.791540 -78.781117
177   Huntersville  North Carolina       50458  35.410694 -80.842850
260     Wilmington  North Carolina      112067  34.225726 -77.944710
284         Wilson  North Carolina       49628  35.721269 -77.915540
310    Rocky Mount  North Carolina       56954  35.938210 -77.790534
341         Durham  North Carolina      245475  35.994033 -78.898619
407     Greensboro  North Carolina      279639  36.072635 -79.791975
410   Jacksonville  North Carolina       69079  34.754052 -77.430241
431           Apex  North Carolina       42214  35.732652 -78.850286
443     Burlington  North Carolina       51510  36.095692 -79.437799
450   Fayetteville  North Carolina      204408  35.052664 -78.878358
590      Charlotte  North Carolina      792862  35.227087 -80.843127
625     Kannapolis  North Carolina       44359  35.487361 -80.621734
699     High Point  North Carolina      107741  35.955692 -80.005318
755        Hickory  North Carolina       40361  35.734454 -81.344457
840  Winston-Salem  North Carolina      236441  36.099860 -80.244216
998      Asheville  North Carolina       87236  35.595058 -82.551487
North Dakota
            City         State  Population        lat         lon
85   Grand Forks  North Dakota       54932  47.925257  -97.032855
327        Fargo  North Dakota      113658  46.877186  -96.789803
371        Minot  North Dakota       46321  48.232967 -101.292291
446     Bismarck  North Dakota       67034  46.808327 -100.783739
Ohio
                  City State  Population        lat        lon
2            Cleveland  Ohio      390113  41.499320 -81.694361
39                Lima  Ohio       38355  40.742551 -84.105226
86           Lancaster  Ohio       39325  39.713675 -82.599329
106          Kettering  Ohio       55870  39.689504 -84.168827
126           Columbus  Ohio      822553  39.961176 -82.998794
164     Cuyahoga Falls  Ohio       49267  41.133945 -81.484558
197         Grove City  Ohio       37490  39.881452 -83.092964
245          Fairfield  Ohio       42635  39.345467 -84.560319
287              Parma  Ohio       80429  41.404774 -81.722909
296         Cincinnati  Ohio      297517  39.103118 -84.512020
300             Toledo  Ohio      282313  41.663938 -83.555212
318         Youngstown  Ohio       65184  41.099780 -80.649519
352          Mansfield  Ohio       46454  40.758390 -82.515447
366             Dublin  Ohio       43607  40.099229 -83.114077
376            Findlay  Ohio       41512  41.044220 -83.649932
384       Strongsville  Ohio       44730  41.314497 -81.835690
468             Dayton  Ohio      143355  39.758948 -84.191607
481             Euclid  Ohio       48139  41.593105 -81.526787
496             Warren  Ohio       40768  41.237557 -80.818417
506      Huber Heights  Ohio       38142  39.843947 -84.124661
512           Hamilton  Ohio       62258  39.399501 -84.561335
540        Springfield  Ohio       59357  39.924227 -83.808817
588             Mentor  Ohio       46979  41.666157 -81.339552
601             Elyria  Ohio       53956  41.368380 -82.107649
693         Middletown  Ohio       48630  39.515058 -84.398276
700             Newark  Ohio       47777  40.058121 -82.401264
705        Westerville  Ohio       37530  40.126174 -82.929070
724              Akron  Ohio      198100  41.081445 -81.519005
736             Lorain  Ohio       63710  41.452819 -82.182375
745        Beavercreek  Ohio       45712  39.709226 -84.063269
866           Lakewood  Ohio       51143  41.481993 -81.798191
942             Canton  Ohio       72535  40.798947 -81.378447
987  Cleveland Heights  Ohio       45394  41.520052 -81.556235
Oklahoma
              City     State  Population        lat        lon
162          Tulsa  Oklahoma      398121  36.153982 -95.992775
200  Oklahoma City  Oklahoma      610613  35.467560 -97.516428
215         Lawton  Oklahoma       97151  34.603567 -98.395929
336   Broken Arrow  Oklahoma      103500  36.060949 -95.797453
448       Muskogee  Oklahoma       38863  35.747877 -95.369691
658     Stillwater  Oklahoma       47186  36.115607 -97.058368
701   Midwest City  Oklahoma       56756  35.449506 -97.396702
759         Edmond  Oklahoma       87004  35.652832 -97.478095
804           Enid  Oklahoma       50725  36.395589 -97.878391
808         Norman  Oklahoma      118197  35.222567 -97.439478
820          Moore  Oklahoma       58414  35.339508 -97.486703
Oregon
            City   State  Population        lat         lon
94      Portland  Oregon      609456  45.523062 -122.676482
237        Salem  Oregon      160614  44.942898 -123.035096
409       Tigard  Oregon       50444  45.431229 -122.771486
473       Eugene  Oregon      159190  44.052069 -123.086754
485    Beaverton  Oregon       93542  45.487062 -122.803710
509    Hillsboro  Oregon       97368  45.522894 -122.989827
538  Lake Oswego  Oregon       37610  45.420675 -122.670650
545         Bend  Oregon       81236  44.058173 -121.315310
607      Medford  Oregon       77677  42.326515 -122.875595
711       Albany  Oregon       51583  44.636511 -123.105928
722       Keizer  Oregon       37064  44.990119 -123.026208
926  Springfield  Oregon       60177  44.046236 -123.022029
967    Corvallis  Oregon       55298  44.564566 -123.262044
988      Gresham  Oregon      109397  45.500136 -122.430201
Pennsylvania
              City         State  Population        lat        lon
33       Allentown  Pennsylvania      118577  40.608430 -75.490183
53    Philadelphia  Pennsylvania     1553165  39.952584 -75.165222
127      Lancaster  Pennsylvania       59325  40.037875 -76.305514
172           Erie  Pennsylvania      100671  42.129224 -80.085059
179     Harrisburg  Pennsylvania       49188  40.273191 -76.886701
351  State College  Pennsylvania       41757  40.793395 -77.860001
585   Wilkes-Barre  Pennsylvania       41108  41.245915 -75.881307
599           York  Pennsylvania       43935  39.962598 -76.727745
613       Scranton  Pennsylvania       75806  41.408969 -75.662412
643      Bethlehem  Pennsylvania       75018  40.625932 -75.370458
902        Reading  Pennsylvania       87893  40.335648 -75.926875
933        Altoona  Pennsylvania       45796  40.518681 -78.394736
957     Pittsburgh  Pennsylvania      305841  40.440625 -79.995886
Rhode Island
                City         State  Population        lat        lon
42   East Providence  Rhode Island       47149  41.813712 -71.370055
387       Woonsocket  Rhode Island       41026  42.002876 -71.514784
403         Cranston  Rhode Island       80566  41.779823 -71.437280
750          Warwick  Rhode Island       81971  41.700101 -71.416167
838        Pawtucket  Rhode Island       71172  41.878711 -71.382556
851       Providence  Rhode Island      177994  41.823989 -71.412834

<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)

South Carolina
                   City           State  Population        lat        lon
4              Columbia  South Carolina      133358  34.000710 -81.034814
34       Mount Pleasant  South Carolina       74885  32.832322 -79.828426
176          Greenville  South Carolina       61397  34.852618 -82.394010
358         Spartanburg  South Carolina       37647  34.949567 -81.932048
513            Florence  South Carolina       37792  34.195433 -79.762563
624          Charleston  South Carolina      127999  32.776475 -79.931051
679         Goose Creek  South Carolina       39823  32.981006 -80.032587
727    North Charleston  South Carolina      104054  32.854620 -79.974810
767              Sumter  South Carolina       41190  33.920435 -80.341469
782           Rock Hill  South Carolina       69103  34.924867 -81.025078
857  Hilton Head Island  South Carolina       39412  32.216316 -80.752608
982         Summerville  South Carolina       46074  33.018504 -80.175648
South Dakota
            City         State  Population        lat         lon
288   Rapid City  South Dakota       70812  44.080543 -103.231015
746  Sioux Falls  South Dakota      164676  43.544596  -96.731103
Tennessee
               City      State  Population        lat        lon
50        Kingsport  Tennessee       52962  36.548434 -82.561819
168        Franklin  Tennessee       68886  35.925064 -86.868890
186        Bartlett  Tennessee       58226  35.204533 -89.873975
338       Nashville  Tennessee      634464  36.162664 -86.781602
391    Collierville  Tennessee       47333  35.042036 -89.664527
456     Chattanooga  Tennessee      173366  35.045630 -85.309680
461         Jackson  Tennessee       67685  35.614517 -88.813947
494    Johnson City  Tennessee       65123  36.313440 -82.353473
522     Clarksville  Tennessee      142357  36.529771 -87.359453
600       Knoxville  Tennessee      183270  35.960638 -83.920739
608    Murfreesboro  Tennessee      117044  35.845621 -86.390270
612      Germantown  Tennessee       39375  35.086758 -89.810086
635         Memphis  Tennessee      653450  35.149534 -90.048980
664       Cleveland  Tennessee       42774  35.159518 -84.876611
899       Brentwood  Tennessee       40021  36.033116 -86.782777
932          Smyrna  Tennessee       43060  35.982841 -86.518605
990  Hendersonville  Tennessee       54068  36.304774 -86.619996
Texas
                     City  State  Population        lat         lon
20                Lubbock  Texas      239538  33.577863 -101.855166
28                Rowlett  Texas       58043  32.902902  -96.563880
38   North Richland Hills  Texas       67317  32.834295  -97.228903
59                 Dallas  Texas     1257676  32.776664  -96.796988
114             Texarkana  Texas       37442  33.425125  -94.047688
..                    ...    ...         ...        ...         ...
921             Arlington  Texas      379577  32.735687  -97.108066
922            Lewisville  Texas      101074  33.046233  -96.994174
963           League City  Texas       90983  29.507454  -95.094930
968            Cedar Hill  Texas       46663  32.588469  -96.956115
976        Corpus Christi  Texas      316381  27.800583  -97.396381

[83 rows x 5 columns]
Utah
                 City State  Population        lat         lon
31              Logan  Utah       48913  41.736980 -111.833836
193      South Jordan  Utah       59366  40.562170 -111.929658
285         Bountiful  Utah       43023  40.889390 -111.880771
381             Provo  Utah      116288  40.233844 -111.658534
434      Spanish Fork  Utah       36956  40.114955 -111.654923
440      Taylorsville  Utah       60519  40.667725 -111.938826
466          Riverton  Utah       40921  40.521893 -111.939102
500              Lehi  Utah       54382  40.391617 -111.850766
533             Ogden  Utah       84249  41.223000 -111.973830
568            Layton  Utah       70790  41.060222 -111.971053
603            Murray  Utah       48612  40.666892 -111.887991
630             Sandy  Utah       90231  40.564978 -111.838973
673  West Valley City  Utah      133579  40.691613 -112.001050
676              Orem  Utah       91648  40.296898 -111.694648
737               Roy  Utah       37733  41.161611 -112.026331
762            Draper  Utah       45285  40.524671 -111.863823
856        St. George  Utah       76817  37.096528 -113.568416
955       West Jordan  Utah      110077  40.609670 -111.939103
964    Salt Lake City  Utah      191180  40.760779 -111.891047
Vermont
           City    State  Population        lat        lon
887  Burlington  Vermont       42284  44.475882 -73.212072
Virginia
                City     State  Population        lat        lon
17          Leesburg  Virginia       47673  39.115662 -77.563602
152       Blacksburg  Virginia       43609  37.229573 -80.413939
226        Lynchburg  Virginia       78014  37.413754 -79.142246
229  Charlottesville  Virginia       44349  38.029306 -78.476678
302     Newport News  Virginia      182020  37.087082 -76.473012
365       Chesapeake  Virginia      230571  36.768209 -76.287493
429       Portsmouth  Virginia       96205  36.835426 -76.298274
508          Norfolk  Virginia      246139  36.850769 -76.285873
534     Harrisonburg  Virginia       51395  38.449569 -78.868915
544          Roanoke  Virginia       98465  37.270970 -79.941427
551         Danville  Virginia       42907  36.585972 -79.395023
615         Manassas  Virginia       41705  38.750949 -77.475267
618          Suffolk  Virginia       85728  36.728205 -76.583562
637       Alexandria  Virginia      148892  38.804836 -77.046921
674          Hampton  Virginia      136699  37.029869 -76.345222
771         Richmond  Virginia      214114  37.540725 -77.436048
830   Virginia Beach  Virginia      448479  36.852926 -75.977985
Washington
               City       State  Population        lat         lon
0        Marysville  Washington       63269  48.051764 -122.177082
51          Spokane  Washington      210721  47.658780 -117.426047
52        Kennewick  Washington       76762  46.211246 -119.137234
54       Bellingham  Washington       82631  48.749080 -122.478147
91         Lakewood  Washington       59097  47.171765 -122.518458
96           Burien  Washington       49858  47.470377 -122.346792
100        Puyallup  Washington       38609  47.185378 -122.292897
147       Bremerton  Washington       39056  47.567320 -122.632936
220       Shoreline  Washington       54790  47.755653 -122.341518
308         Edmonds  Washington       40727  47.810652 -122.377355
337            Kent  Washington      124435  47.380934 -122.234843
426  Spokane Valley  Washington       91113  47.673228 -117.239375
430           Lacey  Washington       44919  47.034263 -122.823191
467          Yakima  Washington       93257  46.602071 -120.505899
477         Everett  Washington      105370  47.978985 -122.202079
497       Vancouver  Washington      167405  45.638728 -122.661486
529         Seattle  Washington      652405  47.606209 -122.332071
684        Bellevue  Washington      133992  47.610377 -122.200679
754        Richland  Washington       52413  46.285691 -119.284462
766          Auburn  Washington       74860  47.307323 -122.228453
769          Renton  Washington       97003  47.482878 -122.217066
855        Kirkland  Washington       84430  47.681488 -122.208735
880       Sammamish  Washington       50169  47.616268 -122.035574
885          Tacoma  Washington      203446  47.252877 -122.444291
915           Pasco  Washington       67599  46.239579 -119.100566
928         Redmond  Washington       57530  47.673988 -122.121512
954     Federal Way  Washington       92734  47.322322 -122.312622
974         Olympia  Washington       48338  47.037874 -122.900695
West Virginia
           City          State  Population       lat        lon
279  Huntington  West Virginia       49177  38.41925 -82.445154
621  Charleston  West Virginia       50821  38.34982 -81.632623
Wisconsin
            City      State  Population        lat        lon
37    New Berlin  Wisconsin       39834  42.976403 -88.108422
56     La Crosse  Wisconsin       51522  43.801356 -91.239581
75    West Allis  Wisconsin       60697  43.016681 -88.007031
98      Waukesha  Wisconsin       71016  43.011678 -88.231481
143       Wausau  Wisconsin       39309  44.959135 -89.630122
158  Fond du Lac  Wisconsin       42970  43.773045 -88.447051
205   Brookfield  Wisconsin       37999  43.060567 -88.106479
216   Eau Claire  Wisconsin       67545  44.811349 -91.498494
347   Greenfield  Wisconsin       37159  42.961404 -88.012586
350      Kenosha  Wisconsin       99889  42.584742 -87.821185
552       Beloit  Wisconsin       36888  42.508348 -89.031777
586     Appleton  Wisconsin       73596  44.261931 -88.415385
596    Wauwatosa  Wisconsin       47134  43.049457 -88.007587
690       Racine  Wisconsin       78199  42.726131 -87.782852
765    Milwaukee  Wisconsin      599164  43.038902 -87.906474
797      Oshkosh  Wisconsin       66778  44.024706 -88.542614
814    Sheboygan  Wisconsin       48725  43.750828 -87.714530
917      Madison  Wisconsin      243344  43.073052 -89.401230
918   Janesville  Wisconsin       63820  42.682789 -89.018722
950    Green Bay  Wisconsin      104779  44.519159 -88.019826
Wyoming
         City    State  Population        lat         lon
64   Cheyenne  Wyoming       62448  41.139981 -104.820246
258    Casper  Wyoming       59628  42.866632 -106.313081

<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-31-2ec4e1a2736e>:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)

In [ ]:
%%shell
jupyter nbconvert "March21_LC_Post.ipynb" --to html

[NbConvertApp] WARNING | pattern 'March21_LC_Post.ipynb' matched no files
This application is used to convert notebook files (*.ipynb)
        to various other formats.

        WARNING: THE COMMANDLINE INTERFACE MAY CHANGE IN FUTURE RELEASES.

Options
=======
The options below are convenience aliases to configurable class-options,
as listed in the "Equivalent to" description-line of the aliases.
To see all configurable class-options for some <cmd>, use:
    <cmd> --help-all

--debug
    set log level to logging.DEBUG (maximize logging output)
    Equivalent to: [--Application.log_level=10]
--show-config
    Show the application's configuration (human-readable format)
    Equivalent to: [--Application.show_config=True]
--show-config-json
    Show the application's configuration (json format)
    Equivalent to: [--Application.show_config_json=True]
--generate-config
    generate default config file
    Equivalent to: [--JupyterApp.generate_config=True]
-y
    Answer yes to any questions instead of prompting.
    Equivalent to: [--JupyterApp.answer_yes=True]
--execute
    Execute the notebook prior to export.
    Equivalent to: [--ExecutePreprocessor.enabled=True]
--allow-errors
    Continue notebook execution even if one of the cells throws an error and include the error message in the cell output (the default behaviour is to abort conversion). This flag is only relevant if '--execute' was specified, too.
    Equivalent to: [--ExecutePreprocessor.allow_errors=True]
--stdin
    read a single notebook file from stdin. Write the resulting notebook with default basename 'notebook.*'
    Equivalent to: [--NbConvertApp.from_stdin=True]
--stdout
    Write notebook output to stdout instead of files.
    Equivalent to: [--NbConvertApp.writer_class=StdoutWriter]
--inplace
    Run nbconvert in place, overwriting the existing notebook (only
            relevant when converting to notebook format)
    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory=]
--clear-output
    Clear output of current file and save in place,
            overwriting the existing notebook.
    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory= --ClearOutputPreprocessor.enabled=True]
--coalesce-streams
    Coalesce consecutive stdout and stderr outputs into one stream (within each cell).
    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory= --CoalesceStreamsPreprocessor.enabled=True]
--no-prompt
    Exclude input and output prompts from converted document.
    Equivalent to: [--TemplateExporter.exclude_input_prompt=True --TemplateExporter.exclude_output_prompt=True]
--no-input
    Exclude input cells and output prompts from converted document.
            This mode is ideal for generating code-free reports.
    Equivalent to: [--TemplateExporter.exclude_output_prompt=True --TemplateExporter.exclude_input=True --TemplateExporter.exclude_input_prompt=True]
--allow-chromium-download
    Whether to allow downloading chromium if no suitable version is found on the system.
    Equivalent to: [--WebPDFExporter.allow_chromium_download=True]
--disable-chromium-sandbox
    Disable chromium security sandbox when converting to PDF..
    Equivalent to: [--WebPDFExporter.disable_sandbox=True]
--show-input
    Shows code input. This flag is only useful for dejavu users.
    Equivalent to: [--TemplateExporter.exclude_input=False]
--embed-images
    Embed the images as base64 dataurls in the output. This flag is only useful for the HTML/WebPDF/Slides exports.
    Equivalent to: [--HTMLExporter.embed_images=True]
--sanitize-html
    Whether the HTML in Markdown cells and cell outputs should be sanitized..
    Equivalent to: [--HTMLExporter.sanitize_html=True]
--log-level=<Enum>
    Set the log level by value or name.
    Choices: any of [0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL']
    Default: 30
    Equivalent to: [--Application.log_level]
--config=<Unicode>
    Full path of a config file.
    Default: ''
    Equivalent to: [--JupyterApp.config_file]
--to=<Unicode>
    The export format to be used, either one of the built-in formats
            ['asciidoc', 'custom', 'html', 'latex', 'markdown', 'notebook', 'pdf', 'python', 'qtpdf', 'qtpng', 'rst', 'script', 'slides', 'webpdf']
            or a dotted object name that represents the import path for an
            ``Exporter`` class
    Default: ''
    Equivalent to: [--NbConvertApp.export_format]
--template=<Unicode>
    Name of the template to use
    Default: ''
    Equivalent to: [--TemplateExporter.template_name]
--template-file=<Unicode>
    Name of the template file to use
    Default: None
    Equivalent to: [--TemplateExporter.template_file]
--theme=<Unicode>
    Template specific theme(e.g. the name of a JupyterLab CSS theme distributed
    as prebuilt extension for the lab template)
    Default: 'light'
    Equivalent to: [--HTMLExporter.theme]
--sanitize_html=<Bool>
    Whether the HTML in Markdown cells and cell outputs should be sanitized.This
    should be set to True by nbviewer or similar tools.
    Default: False
    Equivalent to: [--HTMLExporter.sanitize_html]
--writer=<DottedObjectName>
    Writer class used to write the
                                        results of the conversion
    Default: 'FilesWriter'
    Equivalent to: [--NbConvertApp.writer_class]
--post=<DottedOrNone>
    PostProcessor class used to write the
                                        results of the conversion
    Default: ''
    Equivalent to: [--NbConvertApp.postprocessor_class]
--output=<Unicode>
    Overwrite base name use for output files.
                Supports pattern replacements '{notebook_name}'.
    Default: '{notebook_name}'
    Equivalent to: [--NbConvertApp.output_base]
--output-dir=<Unicode>
    Directory to write output(s) to. Defaults
                                  to output to the directory of each notebook. To recover
                                  previous default behaviour (outputting to the current
                                  working directory) use . as the flag value.
    Default: ''
    Equivalent to: [--FilesWriter.build_directory]
--reveal-prefix=<Unicode>
    The URL prefix for reveal.js (version 3.x).
            This defaults to the reveal CDN, but can be any url pointing to a copy
            of reveal.js.
            For speaker notes to work, this must be a relative path to a local
            copy of reveal.js: e.g., "reveal.js".
            If a relative path is given, it must be a subdirectory of the
            current directory (from which the server is run).
            See the usage documentation
            (https://nbconvert.readthedocs.io/en/latest/usage.html#reveal-js-html-slideshow)
            for more details.
    Default: ''
    Equivalent to: [--SlidesExporter.reveal_url_prefix]
--nbformat=<Enum>
    The nbformat version to write.
            Use this to downgrade notebooks.
    Choices: any of [1, 2, 3, 4]
    Default: 4
    Equivalent to: [--NotebookExporter.nbformat_version]

Examples
--------

    The simplest way to use nbconvert is

            > jupyter nbconvert mynotebook.ipynb --to html

            Options include ['asciidoc', 'custom', 'html', 'latex', 'markdown', 'notebook', 'pdf', 'python', 'qtpdf', 'qtpng', 'rst', 'script', 'slides', 'webpdf'].

            > jupyter nbconvert --to latex mynotebook.ipynb

            Both HTML and LaTeX support multiple output templates. LaTeX includes
            'base', 'article' and 'report'.  HTML includes 'basic', 'lab' and
            'classic'. You can specify the flavor of the format used.

            > jupyter nbconvert --to html --template lab mynotebook.ipynb

            You can also pipe the output to stdout, rather than a file

            > jupyter nbconvert mynotebook.ipynb --stdout

            PDF is generated via latex

            > jupyter nbconvert mynotebook.ipynb --to pdf

            You can get (and serve) a Reveal.js-powered slideshow

            > jupyter nbconvert myslides.ipynb --to slides --post serve

            Multiple notebooks can be given at the command line in a couple of
            different ways:

            > jupyter nbconvert notebook*.ipynb
            > jupyter nbconvert notebook1.ipynb notebook2.ipynb

            or you can specify the notebooks list in a config file, containing::

                c.NbConvertApp.notebooks = ["my_notebook.ipynb"]

            > jupyter nbconvert --config mycfg.py

To see all available configurables, use `--help-all`.

CalledProcessError: Command 'jupyter nbconvert "March21_LC_Post.ipynb" --to html
' returned non-zero exit status 255.