**ANLY 2500 Practice - Pandas**

**All questions are based on the tips.csv dataset file.**

## Dataset Description
The dataset contains the following features:

- ID: A unique identifier for each order.
- day: The day of the week when the customer visited the restaurant (Thu, Fri, Sat, or Sun).
- time: The time of day when the customer visited the restaurant (Lunch or Dinner).
- size: The number of people present at the table.
- smoker: Whether the table included smokers (No: The table did not include smokers, Yes: The table included smokers).
- sex: The gender of the person who paid the bill (Male or Female).
- total_bill: The total bill amount in dollars.
- tip: The tip amount in dollars.

In [ ]:
# Mount your Google Drive

In [ ]:
# Change current directory
%cd "path of the new directory"

In [ ]:
# Verify the current directory
%pwd

In [ ]:
# Verify the current directory
%ls

## Task 1

Import pandas module. Use pandas to load the data from **tips.csv** into a dataframe called **tips_df**.

<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>ID</th>
      <th>total_bill</th>
      <th>tip</th>
      <th>sex</th>
      <th>smoker</th>
      <th>day</th>
      <th>time</th>
      <th>size</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>16.99</td>
      <td>1.01</td>
      <td>Female</td>
      <td>No</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>2</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2</td>
      <td>10.34</td>
      <td>1.66</td>
      <td>Male</td>
      <td>No</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>3</td>
    </tr>
    <tr>
      <th>2</th>
      <td>3</td>
      <td>21.01</td>
      <td>3.50</td>
      <td>Male</td>
      <td>No</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>3</td>
    </tr>
    <tr>
      <th>3</th>
      <td>4</td>
      <td>23.68</td>
      <td>3.31</td>
      <td>Male</td>
      <td>No</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>2</td>
    </tr>
    <tr>
      <th>4</th>
      <td>5</td>
      <td>24.59</td>
      <td>3.61</td>
      <td>Female</td>
      <td>No</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>4</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>239</th>
      <td>240</td>
      <td>29.03</td>
      <td>5.92</td>
      <td>Male</td>
      <td>No</td>
      <td>Sat</td>
      <td>Dinner</td>
      <td>3</td>
    </tr>
    <tr>
      <th>240</th>
      <td>241</td>
      <td>27.18</td>
      <td>2.00</td>
      <td>Female</td>
      <td>Yes</td>
      <td>Sat</td>
      <td>Dinner</td>
      <td>2</td>
    </tr>
    <tr>
      <th>241</th>
      <td>242</td>
      <td>22.67</td>
      <td>2.00</td>
      <td>Male</td>
      <td>Yes</td>
      <td>Sat</td>
      <td>Dinner</td>
      <td>2</td>
    </tr>
    <tr>
      <th>242</th>
      <td>243</td>
      <td>17.82</td>
      <td>1.75</td>
      <td>Male</td>
      <td>No</td>
      <td>Sat</td>
      <td>Dinner</td>
      <td>2</td>
    </tr>
    <tr>
      <th>243</th>
      <td>244</td>
      <td>18.78</td>
      <td>3.00</td>
      <td>Female</td>
      <td>No</td>
      <td>Thur</td>
      <td>Dinner</td>
      <td>2</td>
    </tr>
  </tbody>
</table>
<p>244 rows × 8 columns</p>
</div>

## Task 2
Print out all the column names in the dataframe **tips_df**.

```text
Index(['ID', 'total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')
```

## Task 3

1. Sort the dataframe **tips_df** using the `sort_values()` function by the columns '**total_bill**' and '**tip**' in descending orders and store the result into a dataframe called **tips_sorted_df**.
1. Save **tips_sorted_df** to a csv file named **tips_sorted.csv**.
1. Use `ls` command to show all files and folder in the current the folder.
1. Display the top 10 rows in the dataframe **tips_sorted_df**.
1. Display the last 10 rows in the dataframe **tips_sorted_df**.

**T3.3**

```text
ANLY2500_Pandas_Practice.ipynb  tips.csv  tips_sorted.csv
```

**T3.4**

<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>ID</th>
      <th>total_bill</th>
      <th>tip</th>
      <th>sex</th>
      <th>smoker</th>
      <th>day</th>
      <th>time</th>
      <th>size</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>170</th>
      <td>171</td>
      <td>50.81</td>
      <td>10.00</td>
      <td>Male</td>
      <td>Yes</td>
      <td>Sat</td>
      <td>Dinner</td>
      <td>3</td>
    </tr>
    <tr>
      <th>212</th>
      <td>213</td>
      <td>48.33</td>
      <td>9.00</td>
      <td>Male</td>
      <td>No</td>
      <td>Sat</td>
      <td>Dinner</td>
      <td>4</td>
    </tr>
    <tr>
      <th>59</th>
      <td>60</td>
      <td>48.27</td>
      <td>6.73</td>
      <td>Male</td>
      <td>No</td>
      <td>Sat</td>
      <td>Dinner</td>
      <td>4</td>
    </tr>
    <tr>
      <th>156</th>
      <td>157</td>
      <td>48.17</td>
      <td>5.00</td>
      <td>Male</td>
      <td>No</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>6</td>
    </tr>
    <tr>
      <th>182</th>
      <td>183</td>
      <td>45.35</td>
      <td>3.50</td>
      <td>Male</td>
      <td>Yes</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>3</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>149</th>
      <td>150</td>
      <td>7.51</td>
      <td>2.00</td>
      <td>Male</td>
      <td>No</td>
      <td>Thur</td>
      <td>Lunch</td>
      <td>2</td>
    </tr>
    <tr>
      <th>172</th>
      <td>173</td>
      <td>7.25</td>
      <td>5.15</td>
      <td>Male</td>
      <td>Yes</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>2</td>
    </tr>
    <tr>
      <th>111</th>
      <td>112</td>
      <td>7.25</td>
      <td>1.00</td>
      <td>Female</td>
      <td>No</td>
      <td>Sat</td>
      <td>Dinner</td>
      <td>1</td>
    </tr>
    <tr>
      <th>92</th>
      <td>93</td>
      <td>5.75</td>
      <td>1.00</td>
      <td>Female</td>
      <td>Yes</td>
      <td>Fri</td>
      <td>Dinner</td>
      <td>2</td>
    </tr>
    <tr>
      <th>67</th>
      <td>68</td>
      <td>3.07</td>
      <td>1.00</td>
      <td>Female</td>
      <td>Yes</td>
      <td>Sat</td>
      <td>Dinner</td>
      <td>1</td>
    </tr>
  </tbody>
</table>
<p>244 rows × 8 columns</p>
</div>

**T3.5**

<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>ID</th>
      <th>total_bill</th>
      <th>tip</th>
      <th>sex</th>
      <th>smoker</th>
      <th>day</th>
      <th>time</th>
      <th>size</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>126</th>
      <td>127</td>
      <td>8.52</td>
      <td>1.48</td>
      <td>Male</td>
      <td>No</td>
      <td>Thur</td>
      <td>Lunch</td>
      <td>2</td>
    </tr>
    <tr>
      <th>135</th>
      <td>136</td>
      <td>8.51</td>
      <td>1.25</td>
      <td>Female</td>
      <td>No</td>
      <td>Thur</td>
      <td>Lunch</td>
      <td>2</td>
    </tr>
    <tr>
      <th>145</th>
      <td>146</td>
      <td>8.35</td>
      <td>1.50</td>
      <td>Female</td>
      <td>No</td>
      <td>Thur</td>
      <td>Lunch</td>
      <td>2</td>
    </tr>
    <tr>
      <th>218</th>
      <td>219</td>
      <td>7.74</td>
      <td>1.44</td>
      <td>Male</td>
      <td>Yes</td>
      <td>Sat</td>
      <td>Dinner</td>
      <td>2</td>
    </tr>
    <tr>
      <th>195</th>
      <td>196</td>
      <td>7.56</td>
      <td>1.44</td>
      <td>Male</td>
      <td>No</td>
      <td>Thur</td>
      <td>Lunch</td>
      <td>2</td>
    </tr>
    <tr>
      <th>149</th>
      <td>150</td>
      <td>7.51</td>
      <td>2.00</td>
      <td>Male</td>
      <td>No</td>
      <td>Thur</td>
      <td>Lunch</td>
      <td>2</td>
    </tr>
    <tr>
      <th>172</th>
      <td>173</td>
      <td>7.25</td>
      <td>5.15</td>
      <td>Male</td>
      <td>Yes</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>2</td>
    </tr>
    <tr>
      <th>111</th>
      <td>112</td>
      <td>7.25</td>
      <td>1.00</td>
      <td>Female</td>
      <td>No</td>
      <td>Sat</td>
      <td>Dinner</td>
      <td>1</td>
    </tr>
    <tr>
      <th>92</th>
      <td>93</td>
      <td>5.75</td>
      <td>1.00</td>
      <td>Female</td>
      <td>Yes</td>
      <td>Fri</td>
      <td>Dinner</td>
      <td>2</td>
    </tr>
    <tr>
      <th>67</th>
      <td>68</td>
      <td>3.07</td>
      <td>1.00</td>
      <td>Female</td>
      <td>Yes</td>
      <td>Sat</td>
      <td>Dinner</td>
      <td>1</td>
    </tr>
  </tbody>
</table>
</div>

## Task 4

1. Use the `unique()` function to get the unique values of the **day** column in **tips_df**. Display the unique values in **day** column.  
1. Count the number of unique values in **day** column and print the result.
1. Use `value_counts()` function to count how many orders were made on each day (i.e., the number of orders on Thursday, Friday, Saturday, and Sunday, respectively).
1. Use the `value_counts()` function to count how many orders were made by males and females, respectively.  
2. Use the `value_counts()` function to count how many orders were made by smokers and non-smokers, respectively.  
3. Use the `value_counts()` function to count how many orders were made during lunch and dinner, respectively.

**T4.1 & T4.2**

```text
array(['Sun', 'Sat', 'Thur', 'Fri'], dtype=object)

There are 4 unique values in the day column.
```

**T4.3**

<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>count</th>
    </tr>
    <tr>
      <th>day</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Sat</th>
      <td>87</td>
    </tr>
    <tr>
      <th>Sun</th>
      <td>76</td>
    </tr>
    <tr>
      <th>Thur</th>
      <td>62</td>
    </tr>
    <tr>
      <th>Fri</th>
      <td>19</td>
    </tr>
  </tbody>
</table>
</div>

**T4.4**

<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>count</th>
    </tr>
    <tr>
      <th>sex</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Male</th>
      <td>157</td>
    </tr>
    <tr>
      <th>Female</th>
      <td>87</td>
    </tr>
  </tbody>
</table>
</div>

**T4.5**

<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>count</th>
    </tr>
    <tr>
      <th>smoker</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>No</th>
      <td>151</td>
    </tr>
    <tr>
      <th>Yes</th>
      <td>93</td>
    </tr>
  </tbody>
</table>
</div>

**T4.6**

<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>count</th>
    </tr>
    <tr>
      <th>time</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Dinner</th>
      <td>176</td>
    </tr>
    <tr>
      <th>Lunch</th>
      <td>68</td>
    </tr>
  </tbody>
</table>
</div>

## Task 5

Calcuate the sum of total_bill in **tips_df**.

```text
The sum of the total bills is $4827.77.
```

## Task 6

1. Use the `groupby()` function to group **tips_df** by the '**sex**' column.  
1. Use a for loop to extract the dataframe for each sex and save it as a separate CSV file, with the filename formatted as **sex_name_tips.csv**. The sex name should be replaced with the actual sex name.  
1. For each sex, calculate the sum of the '**size**' column, the sum of the '**total_bill**' column, the sum of the '**tip**' column, and the number of orders made and print the result.
1. Use `ls` command to show all files and folder in the current the folder.

**T6.2 & T6.3**

```text
Order paid by: Female
Total number of people served 214.
Sum of total bills: $1570.95.
Sum of tips: $246.51.
      ID  total_bill   tip     sex smoker   day    time  size
0      1       16.99  1.01  Female     No   Sun  Dinner     2
4      5       24.59  3.61  Female     No   Sun  Dinner     4
11    12       35.26  5.00  Female     No   Sun  Dinner     4
14    15       14.83  3.02  Female     No   Sun  Dinner     2
16    17       10.33  1.67  Female     No   Sun  Dinner     3
..   ...         ...   ...     ...    ...   ...     ...   ...
226  227       10.09  2.00  Female    Yes   Fri   Lunch     2
229  230       22.12  2.88  Female    Yes   Sat  Dinner     2
238  239       35.83  4.67  Female     No   Sat  Dinner     3
240  241       27.18  2.00  Female    Yes   Sat  Dinner     2
243  244       18.78  3.00  Female     No  Thur  Dinner     2

[87 rows x 8 columns]
Order paid by: Male
Total number of people served 413.
Sum of total bills: $3256.82.
Sum of tips: $485.07.
      ID  total_bill   tip   sex smoker  day    time  size
1      2       10.34  1.66  Male     No  Sun  Dinner     3
2      3       21.01  3.50  Male     No  Sun  Dinner     3
3      4       23.68  3.31  Male     No  Sun  Dinner     2
5      6       25.29  4.71  Male     No  Sun  Dinner     4
6      7        8.77  2.00  Male     No  Sun  Dinner     2
..   ...         ...   ...   ...    ...  ...     ...   ...
236  237       12.60  1.00  Male    Yes  Sat  Dinner     2
237  238       32.83  1.17  Male    Yes  Sat  Dinner     2
239  240       29.03  5.92  Male     No  Sat  Dinner     3
241  242       22.67  2.00  Male    Yes  Sat  Dinner     2
242  243       17.82  1.75  Male     No  Sat  Dinner     2

[157 rows x 8 columns]
```

**T6.4**

```text
ANLY2500_Pandas_Practice.ipynb  Female_tips.csv  Male_tips.csv  tips.csv  tips_sorted.csv
```

## Task 7

1. Use the `groupby()` function to group **tips_df** by the '**day**' column.  
1. Use a for loop to extract the dataframe for each day and save it as a separate CSV file, with the filename formatted as **day_name_tips.csv**. The day name should be replaced with the actual day name.  
1. For each day, calculate the sum of the '**size**' column, the sum of the '**total_bill**' column, the sum of the '**tip**' column, and the number of orders made and print the result.
1. Use `ls` command to show all files and folder in the current the folder.

**T7.2 & T7.3**

```text
Order made on: Fri
Total number of people served 40.
Sum of total bills: $325.88.
Sum of tips: $51.96.
      ID  total_bill   tip     sex smoker  day    time  size
90    91       28.97  3.00    Male    Yes  Fri  Dinner     2
91    92       22.49  3.50    Male     No  Fri  Dinner     2
92    93        5.75  1.00  Female    Yes  Fri  Dinner     2
93    94       16.32  4.30  Female    Yes  Fri  Dinner     2
94    95       22.75  3.25  Female     No  Fri  Dinner     2
95    96       40.17  4.73    Male    Yes  Fri  Dinner     4
96    97       27.28  4.00    Male    Yes  Fri  Dinner     2
97    98       12.03  1.50    Male    Yes  Fri  Dinner     2
98    99       21.01  3.00    Male    Yes  Fri  Dinner     2
99   100       12.46  1.50    Male     No  Fri  Dinner     2
100  101       11.35  2.50  Female    Yes  Fri  Dinner     2
101  102       15.38  3.00  Female    Yes  Fri  Dinner     2
220  221       12.16  2.20    Male    Yes  Fri   Lunch     2
221  222       13.42  3.48  Female    Yes  Fri   Lunch     2
222  223        8.58  1.92    Male    Yes  Fri   Lunch     1
223  224       15.98  3.00  Female     No  Fri   Lunch     3
224  225       13.42  1.58    Male    Yes  Fri   Lunch     2
225  226       16.27  2.50  Female    Yes  Fri   Lunch     2
226  227       10.09  2.00  Female    Yes  Fri   Lunch     2
Order made on: Sat
Total number of people served 219.
Sum of total bills: $1778.40.
Sum of tips: $260.40.
      ID  total_bill   tip     sex smoker  day    time  size
19    20       20.65  3.35    Male     No  Sat  Dinner     3
20    21       17.92  4.08    Male     No  Sat  Dinner     2
21    22       20.29  2.75  Female     No  Sat  Dinner     2
22    23       15.77  2.23  Female     No  Sat  Dinner     2
23    24       39.42  7.58    Male     No  Sat  Dinner     4
..   ...         ...   ...     ...    ...  ...     ...   ...
238  239       35.83  4.67  Female     No  Sat  Dinner     3
239  240       29.03  5.92    Male     No  Sat  Dinner     3
240  241       27.18  2.00  Female    Yes  Sat  Dinner     2
241  242       22.67  2.00    Male    Yes  Sat  Dinner     2
242  243       17.82  1.75    Male     No  Sat  Dinner     2

[87 rows x 8 columns]
Order made on: Sun
Total number of people served 216.
Sum of total bills: $1627.16.
Sum of tips: $247.39.
      ID  total_bill   tip     sex smoker  day    time  size
0      1       16.99  1.01  Female     No  Sun  Dinner     2
1      2       10.34  1.66    Male     No  Sun  Dinner     3
2      3       21.01  3.50    Male     No  Sun  Dinner     3
3      4       23.68  3.31    Male     No  Sun  Dinner     2
4      5       24.59  3.61  Female     No  Sun  Dinner     4
..   ...         ...   ...     ...    ...  ...     ...   ...
186  187       20.90  3.50  Female    Yes  Sun  Dinner     3
187  188       30.46  2.00    Male    Yes  Sun  Dinner     5
188  189       18.15  3.50  Female    Yes  Sun  Dinner     3
189  190       23.10  4.00    Male    Yes  Sun  Dinner     3
190  191       15.69  1.50    Male    Yes  Sun  Dinner     2

[76 rows x 8 columns]
Order made on: Thur
Total number of people served 152.
Sum of total bills: $1096.33.
Sum of tips: $171.83.
      ID  total_bill   tip     sex smoker   day    time  size
77    78       27.20  4.00    Male     No  Thur   Lunch     4
78    79       22.76  3.00    Male     No  Thur   Lunch     2
79    80       17.29  2.71    Male     No  Thur   Lunch     2
80    81       19.44  3.00    Male    Yes  Thur   Lunch     2
81    82       16.66  3.40    Male     No  Thur   Lunch     2
..   ...         ...   ...     ...    ...   ...     ...   ...
202  203       13.00  2.00  Female    Yes  Thur   Lunch     2
203  204       16.40  2.50  Female    Yes  Thur   Lunch     2
204  205       20.53  4.00    Male    Yes  Thur   Lunch     4
205  206       16.47  3.23  Female    Yes  Thur   Lunch     3
243  244       18.78  3.00  Female     No  Thur  Dinner     2

[62 rows x 8 columns]
```

**T7.4**

```text
ANLY2500_Pandas_Practice.ipynb  Fri_tips.csv   Sat_tips.csv  Thur_tips.csv  tips_sorted.csv
Female_tips.csv                 Male_tips.csv  Sun_tips.csv  tips.csv
```

## Task 8

1. Use the `groupby()` function to group **tips_df** by the '**smoker**' column.  
1. Use a for loop to extract the dataframe for each smoker category and save it as a separate CSV file, with the filename formatted as **smoker_name_tips.csv**. The smoker category name should be replaced with the actual smoker category name.  
1. For each smoker category, calculate the sum of the '**size**' column, the sum of the '**total_bill**' column, the sum of the '**tip**' column, and the number of orders made and print the result.
1. Use `ls` command to show all files and folder in the current the folder.

**T8.2 & T8.3**

```text
Order made by: Smokers No
Total number of people served 403.
Sum of total bills: $2897.43.
Sum of tips: $451.77.
      ID  total_bill   tip     sex smoker   day    time  size
0      1       16.99  1.01  Female     No   Sun  Dinner     2
1      2       10.34  1.66    Male     No   Sun  Dinner     3
2      3       21.01  3.50    Male     No   Sun  Dinner     3
3      4       23.68  3.31    Male     No   Sun  Dinner     2
4      5       24.59  3.61  Female     No   Sun  Dinner     4
..   ...         ...   ...     ...    ...   ...     ...   ...
235  236       10.07  1.25    Male     No   Sat  Dinner     2
238  239       35.83  4.67  Female     No   Sat  Dinner     3
239  240       29.03  5.92    Male     No   Sat  Dinner     3
242  243       17.82  1.75    Male     No   Sat  Dinner     2
243  244       18.78  3.00  Female     No  Thur  Dinner     2

[151 rows x 8 columns]
Order made by: Smokers Yes
Total number of people served 224.
Sum of total bills: $1930.34.
Sum of tips: $279.81.
      ID  total_bill   tip     sex smoker  day    time  size
56    57       38.01  3.00    Male    Yes  Sat  Dinner     4
58    59       11.24  1.76    Male    Yes  Sat  Dinner     2
60    61       20.29  3.21    Male    Yes  Sat  Dinner     2
61    62       13.81  2.00    Male    Yes  Sat  Dinner     2
62    63       11.02  1.98    Male    Yes  Sat  Dinner     2
..   ...         ...   ...     ...    ...  ...     ...   ...
234  235       15.53  3.00    Male    Yes  Sat  Dinner     2
236  237       12.60  1.00    Male    Yes  Sat  Dinner     2
237  238       32.83  1.17    Male    Yes  Sat  Dinner     2
240  241       27.18  2.00  Female    Yes  Sat  Dinner     2
241  242       22.67  2.00    Male    Yes  Sat  Dinner     2

[93 rows x 8 columns]
```

**T8.4**

```text
ANLY2500_Pandas_Practice.ipynb  Male_tips.csv        Smokers_Yes_tips.csv  tips.csv
Female_tips.csv                 Sat_tips.csv         Sun_tips.csv          tips_sorted.csv
Fri_tips.csv                    Smokers_No_tips.csv  Thur_tips.csv
```

## Task 9

1. Find the rows in **tips_df** that meet the following conditions: **sex is "Female", total_bill is above 20, and tip is above 5**.
1. Sort the resulting dataframe by '**total_bill**' and '**tip**' in descending order.
1. Save the resulting dataframe in the variable **female_filter_tips_df** and print it.
1. Save the result **female_filter_tips_df** to the file **female_filter_tips.csv**.
1. Write Python code to find the maximum '**tip**' in **female_filter_tips_df** and print the result.
1. Use `ls` command to show all files and folder in the current the folder.

**T9.3**

<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>ID</th>
      <th>total_bill</th>
      <th>tip</th>
      <th>sex</th>
      <th>smoker</th>
      <th>day</th>
      <th>time</th>
      <th>size</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>85</th>
      <td>86</td>
      <td>34.83</td>
      <td>5.17</td>
      <td>Female</td>
      <td>No</td>
      <td>Thur</td>
      <td>Lunch</td>
      <td>4</td>
    </tr>
    <tr>
      <th>52</th>
      <td>53</td>
      <td>34.81</td>
      <td>5.20</td>
      <td>Female</td>
      <td>No</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>4</td>
    </tr>
    <tr>
      <th>155</th>
      <td>156</td>
      <td>29.85</td>
      <td>5.14</td>
      <td>Female</td>
      <td>No</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>5</td>
    </tr>
    <tr>
      <th>214</th>
      <td>215</td>
      <td>28.17</td>
      <td>6.50</td>
      <td>Female</td>
      <td>Yes</td>
      <td>Sat</td>
      <td>Dinner</td>
      <td>3</td>
    </tr>
  </tbody>
</table>
</div>

**T9.5 & T9.6**

```text
The max tip in female_filter_tips_df is: $6.50.

ANLY2500_Pandas_Practice.ipynb  Fri_tips.csv   Smokers_No_tips.csv   Thur_tips.csv
female_filter_tips.csv          Male_tips.csv  Smokers_Yes_tips.csv  tips.csv
Female_tips.csv                 Sat_tips.csv   Sun_tips.csv          tips_sorted.csv
```

## Task 10

1. Find the rows in **tips_df** that meet the following conditions: **tip is between 5 and 10 (inclusive)**.
1. Sort the resulting dataframe by '**total_bill**' and '**tip**' in descending order.
1. Save the resulting dataframe in the variable **tips_5_10_df** and print it.
1. Save the result **tips_5_10_df** to the file **tips_5_10.csv**.
1. Write Python code to find the maximum '**total_bill**' in **tips_5_10_df** and print the result.
1. Use `ls` command to show all files and folder in the current the folder.

**T10.3**

<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>ID</th>
      <th>total_bill</th>
      <th>tip</th>
      <th>sex</th>
      <th>smoker</th>
      <th>day</th>
      <th>time</th>
      <th>size</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>170</th>
      <td>171</td>
      <td>50.81</td>
      <td>10.00</td>
      <td>Male</td>
      <td>Yes</td>
      <td>Sat</td>
      <td>Dinner</td>
      <td>3</td>
    </tr>
    <tr>
      <th>212</th>
      <td>213</td>
      <td>48.33</td>
      <td>9.00</td>
      <td>Male</td>
      <td>No</td>
      <td>Sat</td>
      <td>Dinner</td>
      <td>4</td>
    </tr>
    <tr>
      <th>59</th>
      <td>60</td>
      <td>48.27</td>
      <td>6.73</td>
      <td>Male</td>
      <td>No</td>
      <td>Sat</td>
      <td>Dinner</td>
      <td>4</td>
    </tr>
    <tr>
      <th>156</th>
      <td>157</td>
      <td>48.17</td>
      <td>5.00</td>
      <td>Male</td>
      <td>No</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>6</td>
    </tr>
    <tr>
      <th>197</th>
      <td>198</td>
      <td>43.11</td>
      <td>5.00</td>
      <td>Female</td>
      <td>Yes</td>
      <td>Thur</td>
      <td>Lunch</td>
      <td>4</td>
    </tr>
    <tr>
      <th>142</th>
      <td>143</td>
      <td>41.19</td>
      <td>5.00</td>
      <td>Male</td>
      <td>No</td>
      <td>Thur</td>
      <td>Lunch</td>
      <td>5</td>
    </tr>
    <tr>
      <th>23</th>
      <td>24</td>
      <td>39.42</td>
      <td>7.58</td>
      <td>Male</td>
      <td>No</td>
      <td>Sat</td>
      <td>Dinner</td>
      <td>4</td>
    </tr>
    <tr>
      <th>11</th>
      <td>12</td>
      <td>35.26</td>
      <td>5.00</td>
      <td>Female</td>
      <td>No</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>4</td>
    </tr>
    <tr>
      <th>85</th>
      <td>86</td>
      <td>34.83</td>
      <td>5.17</td>
      <td>Female</td>
      <td>No</td>
      <td>Thur</td>
      <td>Lunch</td>
      <td>4</td>
    </tr>
    <tr>
      <th>52</th>
      <td>53</td>
      <td>34.81</td>
      <td>5.20</td>
      <td>Female</td>
      <td>No</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>4</td>
    </tr>
    <tr>
      <th>141</th>
      <td>142</td>
      <td>34.30</td>
      <td>6.70</td>
      <td>Male</td>
      <td>No</td>
      <td>Thur</td>
      <td>Lunch</td>
      <td>6</td>
    </tr>
    <tr>
      <th>83</th>
      <td>84</td>
      <td>32.68</td>
      <td>5.00</td>
      <td>Male</td>
      <td>Yes</td>
      <td>Thur</td>
      <td>Lunch</td>
      <td>2</td>
    </tr>
    <tr>
      <th>47</th>
      <td>48</td>
      <td>32.40</td>
      <td>6.00</td>
      <td>Male</td>
      <td>No</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>4</td>
    </tr>
    <tr>
      <th>39</th>
      <td>40</td>
      <td>31.27</td>
      <td>5.00</td>
      <td>Male</td>
      <td>No</td>
      <td>Sat</td>
      <td>Dinner</td>
      <td>3</td>
    </tr>
    <tr>
      <th>44</th>
      <td>45</td>
      <td>30.40</td>
      <td>5.60</td>
      <td>Male</td>
      <td>No</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>4</td>
    </tr>
    <tr>
      <th>116</th>
      <td>117</td>
      <td>29.93</td>
      <td>5.07</td>
      <td>Male</td>
      <td>No</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>4</td>
    </tr>
    <tr>
      <th>155</th>
      <td>156</td>
      <td>29.85</td>
      <td>5.14</td>
      <td>Female</td>
      <td>No</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>5</td>
    </tr>
    <tr>
      <th>239</th>
      <td>240</td>
      <td>29.03</td>
      <td>5.92</td>
      <td>Male</td>
      <td>No</td>
      <td>Sat</td>
      <td>Dinner</td>
      <td>3</td>
    </tr>
    <tr>
      <th>214</th>
      <td>215</td>
      <td>28.17</td>
      <td>6.50</td>
      <td>Female</td>
      <td>Yes</td>
      <td>Sat</td>
      <td>Dinner</td>
      <td>3</td>
    </tr>
    <tr>
      <th>143</th>
      <td>144</td>
      <td>27.05</td>
      <td>5.00</td>
      <td>Female</td>
      <td>No</td>
      <td>Thur</td>
      <td>Lunch</td>
      <td>6</td>
    </tr>
    <tr>
      <th>211</th>
      <td>212</td>
      <td>25.89</td>
      <td>5.16</td>
      <td>Male</td>
      <td>Yes</td>
      <td>Sat</td>
      <td>Dinner</td>
      <td>4</td>
    </tr>
    <tr>
      <th>73</th>
      <td>74</td>
      <td>25.28</td>
      <td>5.00</td>
      <td>Female</td>
      <td>Yes</td>
      <td>Sat</td>
      <td>Dinner</td>
      <td>2</td>
    </tr>
    <tr>
      <th>88</th>
      <td>89</td>
      <td>24.71</td>
      <td>5.85</td>
      <td>Male</td>
      <td>No</td>
      <td>Thur</td>
      <td>Lunch</td>
      <td>2</td>
    </tr>
    <tr>
      <th>181</th>
      <td>182</td>
      <td>23.33</td>
      <td>5.65</td>
      <td>Male</td>
      <td>Yes</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>2</td>
    </tr>
    <tr>
      <th>183</th>
      <td>184</td>
      <td>23.17</td>
      <td>6.50</td>
      <td>Male</td>
      <td>Yes</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>4</td>
    </tr>
    <tr>
      <th>46</th>
      <td>47</td>
      <td>22.23</td>
      <td>5.00</td>
      <td>Male</td>
      <td>No</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>2</td>
    </tr>
    <tr>
      <th>185</th>
      <td>186</td>
      <td>20.69</td>
      <td>5.00</td>
      <td>Male</td>
      <td>No</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>5</td>
    </tr>
    <tr>
      <th>172</th>
      <td>173</td>
      <td>7.25</td>
      <td>5.15</td>
      <td>Male</td>
      <td>Yes</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>2</td>
    </tr>
  </tbody>
</table>
</div>

**T10.5 & T10.6**

```text
The max total bill in tips_5_10_df is: $50.81.

ANLY2500_Pandas_Practice.ipynb  Fri_tips.csv   Smokers_No_tips.csv   Thur_tips.csv  tips_sorted.csv
female_filter_tips.csv          Male_tips.csv  Smokers_Yes_tips.csv  tips_5_10.csv
Female_tips.csv                 Sat_tips.csv   Sun_tips.csv          tips.csv
```

## Task 11

1. In **tips_df**, create a new column called **tip_ratio**. The value in this column should be the result of dividing the **tip** value by the **total_bill** value in each corresponding row. Then, print the DataFrame information.
1. Use the `groupby()` function to group **tips_df** by the '**day**' column.
1. Use a for loop to extract the dataframe for each day and save it as a separate CSV file, with the filename formatted as **day_tip_ratio.csv**. The day name should be replaced with the actual day name.  
1. For each day, calculate the average of the '**tip_ratio**' column and print the result.
1. Use `ls` command to show all files and folder in the current the folder.
1. Retrieve the **Fri** group using the `get_group()` function and sort the resulting dataframe by '**tip_ratio**'  in ascending order. Save the result in the variable **fri_tip_ratio_df** and print the information.

**T11.1**

<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>ID</th>
      <th>total_bill</th>
      <th>tip</th>
      <th>sex</th>
      <th>smoker</th>
      <th>day</th>
      <th>time</th>
      <th>size</th>
      <th>tip_ratio</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>16.99</td>
      <td>1.01</td>
      <td>Female</td>
      <td>No</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>2</td>
      <td>0.059447</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2</td>
      <td>10.34</td>
      <td>1.66</td>
      <td>Male</td>
      <td>No</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>3</td>
      <td>0.160542</td>
    </tr>
    <tr>
      <th>2</th>
      <td>3</td>
      <td>21.01</td>
      <td>3.50</td>
      <td>Male</td>
      <td>No</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>3</td>
      <td>0.166587</td>
    </tr>
    <tr>
      <th>3</th>
      <td>4</td>
      <td>23.68</td>
      <td>3.31</td>
      <td>Male</td>
      <td>No</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>2</td>
      <td>0.139780</td>
    </tr>
    <tr>
      <th>4</th>
      <td>5</td>
      <td>24.59</td>
      <td>3.61</td>
      <td>Female</td>
      <td>No</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>4</td>
      <td>0.146808</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>239</th>
      <td>240</td>
      <td>29.03</td>
      <td>5.92</td>
      <td>Male</td>
      <td>No</td>
      <td>Sat</td>
      <td>Dinner</td>
      <td>3</td>
      <td>0.203927</td>
    </tr>
    <tr>
      <th>240</th>
      <td>241</td>
      <td>27.18</td>
      <td>2.00</td>
      <td>Female</td>
      <td>Yes</td>
      <td>Sat</td>
      <td>Dinner</td>
      <td>2</td>
      <td>0.073584</td>
    </tr>
    <tr>
      <th>241</th>
      <td>242</td>
      <td>22.67</td>
      <td>2.00</td>
      <td>Male</td>
      <td>Yes</td>
      <td>Sat</td>
      <td>Dinner</td>
      <td>2</td>
      <td>0.088222</td>
    </tr>
    <tr>
      <th>242</th>
      <td>243</td>
      <td>17.82</td>
      <td>1.75</td>
      <td>Male</td>
      <td>No</td>
      <td>Sat</td>
      <td>Dinner</td>
      <td>2</td>
      <td>0.098204</td>
    </tr>
    <tr>
      <th>243</th>
      <td>244</td>
      <td>18.78</td>
      <td>3.00</td>
      <td>Female</td>
      <td>No</td>
      <td>Thur</td>
      <td>Dinner</td>
      <td>2</td>
      <td>0.159744</td>
    </tr>
  </tbody>
</table>
<p>244 rows × 9 columns</p>
</div>

**T11.3 & T11.4**

```text
Order made on: Fri
Average tip ratio on Fri is: 16.99%.
      ID  total_bill   tip     sex smoker  day    time  size  tip_ratio
90    91       28.97  3.00    Male    Yes  Fri  Dinner     2   0.103555
91    92       22.49  3.50    Male     No  Fri  Dinner     2   0.155625
92    93        5.75  1.00  Female    Yes  Fri  Dinner     2   0.173913
93    94       16.32  4.30  Female    Yes  Fri  Dinner     2   0.263480
94    95       22.75  3.25  Female     No  Fri  Dinner     2   0.142857
95    96       40.17  4.73    Male    Yes  Fri  Dinner     4   0.117750
96    97       27.28  4.00    Male    Yes  Fri  Dinner     2   0.146628
97    98       12.03  1.50    Male    Yes  Fri  Dinner     2   0.124688
98    99       21.01  3.00    Male    Yes  Fri  Dinner     2   0.142789
99   100       12.46  1.50    Male     No  Fri  Dinner     2   0.120385
100  101       11.35  2.50  Female    Yes  Fri  Dinner     2   0.220264
101  102       15.38  3.00  Female    Yes  Fri  Dinner     2   0.195059
220  221       12.16  2.20    Male    Yes  Fri   Lunch     2   0.180921
221  222       13.42  3.48  Female    Yes  Fri   Lunch     2   0.259314
222  223        8.58  1.92    Male    Yes  Fri   Lunch     1   0.223776
223  224       15.98  3.00  Female     No  Fri   Lunch     3   0.187735
224  225       13.42  1.58    Male    Yes  Fri   Lunch     2   0.117735
225  226       16.27  2.50  Female    Yes  Fri   Lunch     2   0.153657
226  227       10.09  2.00  Female    Yes  Fri   Lunch     2   0.198216
Order made on: Sat
Average tip ratio on Sat is: 15.32%.
      ID  total_bill   tip     sex smoker  day    time  size  tip_ratio
19    20       20.65  3.35    Male     No  Sat  Dinner     3   0.162228
20    21       17.92  4.08    Male     No  Sat  Dinner     2   0.227679
21    22       20.29  2.75  Female     No  Sat  Dinner     2   0.135535
22    23       15.77  2.23  Female     No  Sat  Dinner     2   0.141408
23    24       39.42  7.58    Male     No  Sat  Dinner     4   0.192288
..   ...         ...   ...     ...    ...  ...     ...   ...        ...
238  239       35.83  4.67  Female     No  Sat  Dinner     3   0.130338
239  240       29.03  5.92    Male     No  Sat  Dinner     3   0.203927
240  241       27.18  2.00  Female    Yes  Sat  Dinner     2   0.073584
241  242       22.67  2.00    Male    Yes  Sat  Dinner     2   0.088222
242  243       17.82  1.75    Male     No  Sat  Dinner     2   0.098204

[87 rows x 9 columns]
Order made on: Sun
Average tip ratio on Sun is: 16.69%.
      ID  total_bill   tip     sex smoker  day    time  size  tip_ratio
0      1       16.99  1.01  Female     No  Sun  Dinner     2   0.059447
1      2       10.34  1.66    Male     No  Sun  Dinner     3   0.160542
2      3       21.01  3.50    Male     No  Sun  Dinner     3   0.166587
3      4       23.68  3.31    Male     No  Sun  Dinner     2   0.139780
4      5       24.59  3.61  Female     No  Sun  Dinner     4   0.146808
..   ...         ...   ...     ...    ...  ...     ...   ...        ...
186  187       20.90  3.50  Female    Yes  Sun  Dinner     3   0.167464
187  188       30.46  2.00    Male    Yes  Sun  Dinner     5   0.065660
188  189       18.15  3.50  Female    Yes  Sun  Dinner     3   0.192837
189  190       23.10  4.00    Male    Yes  Sun  Dinner     3   0.173160
190  191       15.69  1.50    Male    Yes  Sun  Dinner     2   0.095602

[76 rows x 9 columns]
Order made on: Thur
Average tip ratio on Thur is: 16.13%.
      ID  total_bill   tip     sex smoker   day    time  size  tip_ratio
77    78       27.20  4.00    Male     No  Thur   Lunch     4   0.147059
78    79       22.76  3.00    Male     No  Thur   Lunch     2   0.131810
79    80       17.29  2.71    Male     No  Thur   Lunch     2   0.156738
80    81       19.44  3.00    Male    Yes  Thur   Lunch     2   0.154321
81    82       16.66  3.40    Male     No  Thur   Lunch     2   0.204082
..   ...         ...   ...     ...    ...   ...     ...   ...        ...
202  203       13.00  2.00  Female    Yes  Thur   Lunch     2   0.153846
203  204       16.40  2.50  Female    Yes  Thur   Lunch     2   0.152439
204  205       20.53  4.00    Male    Yes  Thur   Lunch     4   0.194837
205  206       16.47  3.23  Female    Yes  Thur   Lunch     3   0.196114
243  244       18.78  3.00  Female     No  Thur  Dinner     2   0.159744

[62 rows x 9 columns]
```

**T11.5**

```text
ANLY2500_Pandas_Practice.ipynb  Male_tips.csv         Sun_tip_ratio.csv   tips.csv
female_filter_tips.csv          Sat_tip_ratio.csv     Sun_tips.csv        tips_sorted.csv
Female_tips.csv                 Sat_tips.csv          Thur_tip_ratio.csv
Fri_tip_ratio.csv               Smokers_No_tips.csv   Thur_tips.csv
Fri_tips.csv                    Smokers_Yes_tips.csv  tips_5_10.csv
```

**T11.6**

<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>ID</th>
      <th>total_bill</th>
      <th>tip</th>
      <th>sex</th>
      <th>smoker</th>
      <th>day</th>
      <th>time</th>
      <th>size</th>
      <th>tip_ratio</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>90</th>
      <td>91</td>
      <td>28.97</td>
      <td>3.00</td>
      <td>Male</td>
      <td>Yes</td>
      <td>Fri</td>
      <td>Dinner</td>
      <td>2</td>
      <td>0.103555</td>
    </tr>
    <tr>
      <th>224</th>
      <td>225</td>
      <td>13.42</td>
      <td>1.58</td>
      <td>Male</td>
      <td>Yes</td>
      <td>Fri</td>
      <td>Lunch</td>
      <td>2</td>
      <td>0.117735</td>
    </tr>
    <tr>
      <th>95</th>
      <td>96</td>
      <td>40.17</td>
      <td>4.73</td>
      <td>Male</td>
      <td>Yes</td>
      <td>Fri</td>
      <td>Dinner</td>
      <td>4</td>
      <td>0.117750</td>
    </tr>
    <tr>
      <th>99</th>
      <td>100</td>
      <td>12.46</td>
      <td>1.50</td>
      <td>Male</td>
      <td>No</td>
      <td>Fri</td>
      <td>Dinner</td>
      <td>2</td>
      <td>0.120385</td>
    </tr>
    <tr>
      <th>97</th>
      <td>98</td>
      <td>12.03</td>
      <td>1.50</td>
      <td>Male</td>
      <td>Yes</td>
      <td>Fri</td>
      <td>Dinner</td>
      <td>2</td>
      <td>0.124688</td>
    </tr>
    <tr>
      <th>98</th>
      <td>99</td>
      <td>21.01</td>
      <td>3.00</td>
      <td>Male</td>
      <td>Yes</td>
      <td>Fri</td>
      <td>Dinner</td>
      <td>2</td>
      <td>0.142789</td>
    </tr>
    <tr>
      <th>94</th>
      <td>95</td>
      <td>22.75</td>
      <td>3.25</td>
      <td>Female</td>
      <td>No</td>
      <td>Fri</td>
      <td>Dinner</td>
      <td>2</td>
      <td>0.142857</td>
    </tr>
    <tr>
      <th>96</th>
      <td>97</td>
      <td>27.28</td>
      <td>4.00</td>
      <td>Male</td>
      <td>Yes</td>
      <td>Fri</td>
      <td>Dinner</td>
      <td>2</td>
      <td>0.146628</td>
    </tr>
    <tr>
      <th>225</th>
      <td>226</td>
      <td>16.27</td>
      <td>2.50</td>
      <td>Female</td>
      <td>Yes</td>
      <td>Fri</td>
      <td>Lunch</td>
      <td>2</td>
      <td>0.153657</td>
    </tr>
    <tr>
      <th>91</th>
      <td>92</td>
      <td>22.49</td>
      <td>3.50</td>
      <td>Male</td>
      <td>No</td>
      <td>Fri</td>
      <td>Dinner</td>
      <td>2</td>
      <td>0.155625</td>
    </tr>
    <tr>
      <th>92</th>
      <td>93</td>
      <td>5.75</td>
      <td>1.00</td>
      <td>Female</td>
      <td>Yes</td>
      <td>Fri</td>
      <td>Dinner</td>
      <td>2</td>
      <td>0.173913</td>
    </tr>
    <tr>
      <th>220</th>
      <td>221</td>
      <td>12.16</td>
      <td>2.20</td>
      <td>Male</td>
      <td>Yes</td>
      <td>Fri</td>
      <td>Lunch</td>
      <td>2</td>
      <td>0.180921</td>
    </tr>
    <tr>
      <th>223</th>
      <td>224</td>
      <td>15.98</td>
      <td>3.00</td>
      <td>Female</td>
      <td>No</td>
      <td>Fri</td>
      <td>Lunch</td>
      <td>3</td>
      <td>0.187735</td>
    </tr>
    <tr>
      <th>101</th>
      <td>102</td>
      <td>15.38</td>
      <td>3.00</td>
      <td>Female</td>
      <td>Yes</td>
      <td>Fri</td>
      <td>Dinner</td>
      <td>2</td>
      <td>0.195059</td>
    </tr>
    <tr>
      <th>226</th>
      <td>227</td>
      <td>10.09</td>
      <td>2.00</td>
      <td>Female</td>
      <td>Yes</td>
      <td>Fri</td>
      <td>Lunch</td>
      <td>2</td>
      <td>0.198216</td>
    </tr>
    <tr>
      <th>100</th>
      <td>101</td>
      <td>11.35</td>
      <td>2.50</td>
      <td>Female</td>
      <td>Yes</td>
      <td>Fri</td>
      <td>Dinner</td>
      <td>2</td>
      <td>0.220264</td>
    </tr>
    <tr>
      <th>222</th>
      <td>223</td>
      <td>8.58</td>
      <td>1.92</td>
      <td>Male</td>
      <td>Yes</td>
      <td>Fri</td>
      <td>Lunch</td>
      <td>1</td>
      <td>0.223776</td>
    </tr>
    <tr>
      <th>221</th>
      <td>222</td>
      <td>13.42</td>
      <td>3.48</td>
      <td>Female</td>
      <td>Yes</td>
      <td>Fri</td>
      <td>Lunch</td>
      <td>2</td>
      <td>0.259314</td>
    </tr>
    <tr>
      <th>93</th>
      <td>94</td>
      <td>16.32</td>
      <td>4.30</td>
      <td>Female</td>
      <td>Yes</td>
      <td>Fri</td>
      <td>Dinner</td>
      <td>2</td>
      <td>0.263480</td>
    </tr>
  </tbody>
</table>
</div>