**ANLY 2500 Practice - SQL**

**Write SQL queries to answer all the questions.**

**All questions are based on the sales.db sqlite database file.**

**Sales Data Analysis**

### Dataset Description

File: **sales.db**

There is one **sale** table in **sales.db** database file and the **sale** table consists of **12,569** sales records, structured with **12 columns** containing details of customer purchases. Below is an overview of the dataset:

- **RowNO**: Unique identifier for each row.
- **SaleDate**: Date of the sale, formatted as MM/DD/YYYY.
- **CustomerID**: Unique ID assigned to each customer.
- **FirstName**: First name of the customer.
- **LastName**: Last name of the customer.
- **OrderID**: Unique ID for each order (multiple rows can share an OrderID if they are part of the same order).
- **ProductName**: Name of the product sold.
- **Category**: Category of the product (e.g., sneakers, boots, wedges).
- **Color**: Color of the product.
- **SalePrice**: Price of the product at the time of sale.
- **Quantity**: Number of units purchased in the transaction.
- **ManufacturerName**: Name of the manufacturer.

In [ ]:
# Mount your Google Drive
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# Change current directory
%cd "path of the new directory"

In [ ]:
# Verify the current directory
%pwd

In [ ]:
# Verify the current directory
%ls

In [ ]:
%pip install jupysql duckdb duckdb-engine --quiet
# Load the SQL extension
%load_ext sql
# Setting: Show all rows
%config SqlMagic.displaylimit = None

In [ ]:
# Connect to SQLite database
%sql sqlite:///sqlite_db_filename

In [ ]:
# Show tables
%sqlcmd tables

In [ ]:
# Show columns in a table
%sqlcmd columns -t tablename

<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>RowNO</th>
      <th>SaleDate</th>
      <th>CustomerID</th>
      <th>FirstName</th>
      <th>LastName</th>
      <th>OrderID</th>
      <th>ProductName</th>
      <th>Category</th>
      <th>Color</th>
      <th>SalePrice</th>
      <th>Quantity</th>
      <th>ManufacturerName</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>12/31/2013</td>
      <td>1134</td>
      <td>Xiafeng</td>
      <td>Wang</td>
      <td>191228</td>
      <td>be mini vulc wns sneakers</td>
      <td>sneakers</td>
      <td>Black</td>
      <td>57.65</td>
      <td>1</td>
      <td>Puma</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2</td>
      <td>12/31/2013</td>
      <td>1134</td>
      <td>Xiafeng</td>
      <td>Wang</td>
      <td>191228</td>
      <td>liga sneakers</td>
      <td>sneakers</td>
      <td>Blue</td>
      <td>63.05</td>
      <td>1</td>
      <td>Puma</td>
    </tr>
    <tr>
      <th>2</th>
      <td>3</td>
      <td>12/31/2013</td>
      <td>1134</td>
      <td>Xiafeng</td>
      <td>Wang</td>
      <td>191228</td>
      <td>nike air max correlate sneakers</td>
      <td>sneakers</td>
      <td>Black</td>
      <td>96.60</td>
      <td>1</td>
      <td>Nike</td>
    </tr>
    <tr>
      <th>3</th>
      <td>4</td>
      <td>12/31/2013</td>
      <td>1134</td>
      <td>Xiafeng</td>
      <td>Wang</td>
      <td>191228</td>
      <td>timberland icon 6" premium boots</td>
      <td>boots</td>
      <td>Black</td>
      <td>116.99</td>
      <td>1</td>
      <td>Timberland</td>
    </tr>
    <tr>
      <th>4</th>
      <td>5</td>
      <td>12/31/2013</td>
      <td>1134</td>
      <td>Xiafeng</td>
      <td>Wang</td>
      <td>191228</td>
      <td>torry wedge tapestry wedge</td>
      <td>wedges</td>
      <td>Green,Multi</td>
      <td>15.29</td>
      <td>2</td>
      <td>Fashion Lab</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>12564</th>
      <td>12565</td>
      <td>11/7/2015</td>
      <td>9345</td>
      <td>Lorene</td>
      <td>Charles</td>
      <td>195505</td>
      <td>metal beads sandal</td>
      <td>sandals</td>
      <td>Black</td>
      <td>37.60</td>
      <td>1</td>
      <td>Apple Bottoms</td>
    </tr>
    <tr>
      <th>12565</th>
      <td>12566</td>
      <td>11/7/2015</td>
      <td>9345</td>
      <td>Lorene</td>
      <td>Charles</td>
      <td>195505</td>
      <td>nike flight one sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>84.63</td>
      <td>1</td>
      <td>Nike</td>
    </tr>
    <tr>
      <th>12566</th>
      <td>12567</td>
      <td>11/7/2015</td>
      <td>9345</td>
      <td>Lorene</td>
      <td>Charles</td>
      <td>195505</td>
      <td>nm camp leather boots</td>
      <td>boots</td>
      <td>Black</td>
      <td>74.68</td>
      <td>1</td>
      <td>Timberland</td>
    </tr>
    <tr>
      <th>12567</th>
      <td>12568</td>
      <td>11/7/2015</td>
      <td>9345</td>
      <td>Lorene</td>
      <td>Charles</td>
      <td>195505</td>
      <td>the cage hightop sneaker</td>
      <td>sneakers</td>
      <td>Lime Green,Charcoal,Grey</td>
      <td>67.90</td>
      <td>1</td>
      <td>Fila</td>
    </tr>
    <tr>
      <th>12568</th>
      <td>12569</td>
      <td>11/7/2015</td>
      <td>9345</td>
      <td>Lorene</td>
      <td>Charles</td>
      <td>195505</td>
      <td>wmns sweet classic leather sneakers</td>
      <td>sneakers</td>
      <td>Black</td>
      <td>50.39</td>
      <td>1</td>
      <td>Nike</td>
    </tr>
  </tbody>
</table>
<p>12569 rows × 12 columns</p>
</div>

## Task 1

What are all the distinct product categories sold?

<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Category</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>sneakers</td>
    </tr>
    <tr>
      <th>1</th>
      <td>boots</td>
    </tr>
    <tr>
      <th>2</th>
      <td>wedges</td>
    </tr>
    <tr>
      <th>3</th>
      <td>flats</td>
    </tr>
    <tr>
      <th>4</th>
      <td>sandals</td>
    </tr>
    <tr>
      <th>5</th>
      <td>heels</td>
    </tr>
    <tr>
      <th>6</th>
      <td>casual shoes</td>
    </tr>
    <tr>
      <th>7</th>
      <td>slippers</td>
    </tr>
  </tbody>
</table>
</div>

## Task 2

List all sales transactions made by a customer named **Lorene	Charles**.

<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>RowNO</th>
      <th>SaleDate</th>
      <th>CustomerID</th>
      <th>FirstName</th>
      <th>LastName</th>
      <th>OrderID</th>
      <th>ProductName</th>
      <th>Category</th>
      <th>Color</th>
      <th>SalePrice</th>
      <th>Quantity</th>
      <th>ManufacturerName</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>12563</td>
      <td>11/7/2015</td>
      <td>9345</td>
      <td>Lorene</td>
      <td>Charles</td>
      <td>195505</td>
      <td>doubleback classic sneakers</td>
      <td>sneakers</td>
      <td>Black</td>
      <td>28.19</td>
      <td>1</td>
      <td>Buyers Picks</td>
    </tr>
    <tr>
      <th>1</th>
      <td>12564</td>
      <td>11/7/2015</td>
      <td>9345</td>
      <td>Lorene</td>
      <td>Charles</td>
      <td>195505</td>
      <td>earthkeepers hookset handcrafted fabric oxford...</td>
      <td>sneakers</td>
      <td>Brown</td>
      <td>75.00</td>
      <td>2</td>
      <td>Timberland</td>
    </tr>
    <tr>
      <th>2</th>
      <td>12565</td>
      <td>11/7/2015</td>
      <td>9345</td>
      <td>Lorene</td>
      <td>Charles</td>
      <td>195505</td>
      <td>metal beads sandal</td>
      <td>sandals</td>
      <td>Black</td>
      <td>37.60</td>
      <td>1</td>
      <td>Apple Bottoms</td>
    </tr>
    <tr>
      <th>3</th>
      <td>12566</td>
      <td>11/7/2015</td>
      <td>9345</td>
      <td>Lorene</td>
      <td>Charles</td>
      <td>195505</td>
      <td>nike flight one sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>84.63</td>
      <td>1</td>
      <td>Nike</td>
    </tr>
    <tr>
      <th>4</th>
      <td>12567</td>
      <td>11/7/2015</td>
      <td>9345</td>
      <td>Lorene</td>
      <td>Charles</td>
      <td>195505</td>
      <td>nm camp leather boots</td>
      <td>boots</td>
      <td>Black</td>
      <td>74.68</td>
      <td>1</td>
      <td>Timberland</td>
    </tr>
    <tr>
      <th>5</th>
      <td>12568</td>
      <td>11/7/2015</td>
      <td>9345</td>
      <td>Lorene</td>
      <td>Charles</td>
      <td>195505</td>
      <td>the cage hightop sneaker</td>
      <td>sneakers</td>
      <td>Lime Green,Charcoal,Grey</td>
      <td>67.90</td>
      <td>1</td>
      <td>Fila</td>
    </tr>
    <tr>
      <th>6</th>
      <td>12569</td>
      <td>11/7/2015</td>
      <td>9345</td>
      <td>Lorene</td>
      <td>Charles</td>
      <td>195505</td>
      <td>wmns sweet classic leather sneakers</td>
      <td>sneakers</td>
      <td>Black</td>
      <td>50.39</td>
      <td>1</td>
      <td>Nike</td>
    </tr>
  </tbody>
</table>
</div>

## Task 3

Show the total number of sales records.

<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>NRows</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>12569</td>
    </tr>
  </tbody>
</table>
</div>

## Task 4

What is the total revenue generated from all sales?

<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>TotalRevenue</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>777599.28</td>
    </tr>
  </tbody>
</table>
</div>

## Task 5

How many pairs (units) of each product category have been sold?

<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Category</th>
      <th>TotalPairsSold</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>boots</td>
      <td>1148</td>
    </tr>
    <tr>
      <th>1</th>
      <td>casual shoes</td>
      <td>525</td>
    </tr>
    <tr>
      <th>2</th>
      <td>flats</td>
      <td>357</td>
    </tr>
    <tr>
      <th>3</th>
      <td>heels</td>
      <td>382</td>
    </tr>
    <tr>
      <th>4</th>
      <td>sandals</td>
      <td>1187</td>
    </tr>
    <tr>
      <th>5</th>
      <td>slippers</td>
      <td>8</td>
    </tr>
    <tr>
      <th>6</th>
      <td>sneakers</td>
      <td>10293</td>
    </tr>
    <tr>
      <th>7</th>
      <td>wedges</td>
      <td>569</td>
    </tr>
  </tbody>
</table>
</div>

## Task 6

Which product has the highest individual sale price?

<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>ProductName</th>
      <th>SalePrice</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>wmns air max 2013 + sneakers</td>
      <td>180.0</td>
    </tr>
  </tbody>
</table>
</div>

## Task 7

Find total revenue generated by each manufacturer.

<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>ManufacturerName</th>
      <th>TotalRevenue</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Nike</td>
      <td>109599.57</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Adidas</td>
      <td>104418.25</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Fashion Lab</td>
      <td>73795.86</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Creative Recreation</td>
      <td>50428.98</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Puma</td>
      <td>44206.17</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>57</th>
      <td>Greedy Geniu$</td>
      <td>44.14</td>
    </tr>
    <tr>
      <th>58</th>
      <td>Ed Hardy</td>
      <td>41.98</td>
    </tr>
    <tr>
      <th>59</th>
      <td>DVS Shoe Co.</td>
      <td>30.99</td>
    </tr>
    <tr>
      <th>60</th>
      <td>Generic Surplus</td>
      <td>21.33</td>
    </tr>
    <tr>
      <th>61</th>
      <td>Baby Phat</td>
      <td>18.79</td>
    </tr>
  </tbody>
</table>
<p>62 rows × 2 columns</p>
</div>

## Task 8

Which customer made the most purchases (by quantity)?

<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>CustomerID</th>
      <th>FirstName</th>
      <th>LastName</th>
      <th>TotalPairs</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1134</td>
      <td>Xiafeng</td>
      <td>Wang</td>
      <td>10293</td>
    </tr>
  </tbody>
</table>
</div>

## Task 9

Find all orders with more than 5 items sold in a single order.

<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>OrderID</th>
      <th>TotalPairsSold</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>195381</td>
      <td>11</td>
    </tr>
    <tr>
      <th>1</th>
      <td>193256</td>
      <td>11</td>
    </tr>
    <tr>
      <th>2</th>
      <td>192262</td>
      <td>11</td>
    </tr>
    <tr>
      <th>3</th>
      <td>195442</td>
      <td>10</td>
    </tr>
    <tr>
      <th>4</th>
      <td>195360</td>
      <td>10</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>1147</th>
      <td>191270</td>
      <td>6</td>
    </tr>
    <tr>
      <th>1148</th>
      <td>191267</td>
      <td>6</td>
    </tr>
    <tr>
      <th>1149</th>
      <td>191265</td>
      <td>6</td>
    </tr>
    <tr>
      <th>1150</th>
      <td>191255</td>
      <td>6</td>
    </tr>
    <tr>
      <th>1151</th>
      <td>191228</td>
      <td>6</td>
    </tr>
  </tbody>
</table>
<p>1152 rows × 2 columns</p>
</div>

## Task 10

Find all **green** products sold with a sale price lower than $20.

<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>ProductName</th>
      <th>Color</th>
      <th>SalePrice</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>knight lo</td>
      <td>Green</td>
      <td>19.99</td>
    </tr>
    <tr>
      <th>1</th>
      <td>knight lo</td>
      <td>Green</td>
      <td>19.39</td>
    </tr>
    <tr>
      <th>2</th>
      <td>wmns solarsoft thong ii sandals</td>
      <td>Green</td>
      <td>16.99</td>
    </tr>
    <tr>
      <th>3</th>
      <td>jayda sandal wedge w/print</td>
      <td>Green</td>
      <td>16.82</td>
    </tr>
    <tr>
      <th>4</th>
      <td>wmns solarsoft thong ii sandals</td>
      <td>Green</td>
      <td>16.48</td>
    </tr>
    <tr>
      <th>5</th>
      <td>wmns solarsoft thong ii sandals</td>
      <td>Green</td>
      <td>15.97</td>
    </tr>
    <tr>
      <th>6</th>
      <td>wmns solarsoft thong ii sandals</td>
      <td>Green</td>
      <td>15.80</td>
    </tr>
    <tr>
      <th>7</th>
      <td>wmns solarsoft thong ii sandals</td>
      <td>Green</td>
      <td>15.46</td>
    </tr>
    <tr>
      <th>8</th>
      <td>wmns solarsoft thong ii sandals</td>
      <td>Green</td>
      <td>15.29</td>
    </tr>
    <tr>
      <th>9</th>
      <td>anne platform bottom heel w/print</td>
      <td>Green</td>
      <td>9.49</td>
    </tr>
  </tbody>
</table>
</div>

## Task 11

Find all products sold with a sale price between 100 and 150 (inclusive).

<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>ProductName</th>
      <th>SalePrice</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>jack frost boots</td>
      <td>150.00</td>
    </tr>
    <tr>
      <th>1</th>
      <td>reebok pump fury sneakers</td>
      <td>149.99</td>
    </tr>
    <tr>
      <th>2</th>
      <td>6" premium boots</td>
      <td>149.99</td>
    </tr>
    <tr>
      <th>3</th>
      <td>basquiat : curated by swizz beatz pump omni li...</td>
      <td>149.99</td>
    </tr>
    <tr>
      <th>4</th>
      <td>basquiat : curated by swizz beatz pump omni li...</td>
      <td>148.49</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>320</th>
      <td>mega softcell hi</td>
      <td>100.00</td>
    </tr>
    <tr>
      <th>321</th>
      <td>good luck charm sneakers</td>
      <td>100.00</td>
    </tr>
    <tr>
      <th>322</th>
      <td>cesario x sneaker</td>
      <td>100.00</td>
    </tr>
    <tr>
      <th>323</th>
      <td>air force 1 mid sneakers</td>
      <td>100.00</td>
    </tr>
    <tr>
      <th>324</th>
      <td>natalia boots w/ faux interior fur lining</td>
      <td>100.00</td>
    </tr>
  </tbody>
</table>
<p>325 rows × 2 columns</p>
</div>