**ANLY 2500 Homework Pandas**


**Use what we learned in the Python Pandas lectures to answer the questions below. Write Python code to solve the questions.**

**Sales Data Analysis**

### Dataset Description

File: **SalesData.csv**

The dataset consists of **12,569** sales records, structured with **12 columns** containing details of customer purchases. Below is an overview of the dataset:

- **RowNO**: Unique identifier for each row.
- **SaleDate**: Date of the sale, formatted as MM/DD/YYYY.
- **CustomerID**: Unique ID assigned to each customer.
- **FirstName**: First name of the customer.
- **LastName**: Last name of the customer.
- **OrderID**: Unique ID for each order (multiple rows can share an OrderID if they are part of the same order).
- **ProductName**: Name of the product sold.
- **Category**: Category of the product (e.g., sneakers, boots, wedges).
- **Color**: Color of the product.
- **SalePrice**: Price of the product at the time of sale.
- **Quantity**: Number of units purchased in the transaction.
- **ManufacturerName**: Name of the manufacturer.

## Q1. (0.1 points)
Put your name and student ID in the comment.

## Q2. (0.1 points)

Mount google drive. Use command cd, pwd,and ls to change the current folder and show the files and folders inside the current folder.

## Q3. (0.1 points)

Import pandas module.

## Q4. (0.1 points)
Use pandas to load the data from **SalesData.csv** into a dataframe called **sales_df**.

## Q5. (0.1 points)
Print out all the column names in the dataframe **sales_df**.

```text
Index(['RowNO', 'SaleDate', 'CustomerID', 'FirstName', 'LastName', 'OrderID',
       'ProductName', 'Category', 'Color', 'SalePrice', 'Quantity',
       'ManufacturerName'],
      dtype='object')
```

## Q6. (1.4 points)

1. (1 point) Sort the dataframe **sales_df** using the `sort_values()` function by the column '**SalePrice**' in descending order and store the result into a dataframe called **sales_sorted_df**.
1. (0.1 points) Save **sales_sorted_df** to a csv file named **sales_data_sorted.csv**.
1. (0.1 points) Use ls command to show all files and folder in the current the folder.
1. (0.1 points) Display the top 5 rows in the dataframe **sales_sorted_df**.
1. (0.1 points) Display the last 3 rows in the dataframe **sales_sorted_df**.

**Q6.4**
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>RowNO</th>
      <th>SaleDate</th>
      <th>CustomerID</th>
      <th>FirstName</th>
      <th>LastName</th>
      <th>OrderID</th>
      <th>ProductName</th>
      <th>Category</th>
      <th>Color</th>
      <th>SalePrice</th>
      <th>Quantity</th>
      <th>ManufacturerName</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>7147</th>
      <td>7148</td>
      <td>1/13/2015</td>
      <td>8458</td>
      <td>Eula</td>
      <td>Mills</td>
      <td>193661</td>
      <td>wmns air max 2013 + sneakers</td>
      <td>sneakers</td>
      <td>Blue</td>
      <td>180.0</td>
      <td>2</td>
      <td>Nike</td>
    </tr>
    <tr>
      <th>7815</th>
      <td>7816</td>
      <td>2/17/2015</td>
      <td>11852</td>
      <td>Ken</td>
      <td>Carey</td>
      <td>193895</td>
      <td>wmns air max 2013 + sneakers</td>
      <td>sneakers</td>
      <td>Blue</td>
      <td>180.0</td>
      <td>1</td>
      <td>Nike</td>
    </tr>
    <tr>
      <th>5551</th>
      <td>5552</td>
      <td>11/13/2014</td>
      <td>17778</td>
      <td>Xinlin</td>
      <td>Tang</td>
      <td>193120</td>
      <td>wmns air max 2013 + sneakers</td>
      <td>sneakers</td>
      <td>Blue</td>
      <td>178.2</td>
      <td>1</td>
      <td>Nike</td>
    </tr>
    <tr>
      <th>6519</th>
      <td>6520</td>
      <td>12/18/2014</td>
      <td>8493</td>
      <td>Nicole</td>
      <td>Garcia</td>
      <td>193459</td>
      <td>wmns air max 2013 + sneakers</td>
      <td>sneakers</td>
      <td>Blue</td>
      <td>171.0</td>
      <td>1</td>
      <td>Nike</td>
    </tr>
    <tr>
      <th>4237</th>
      <td>4238</td>
      <td>9/3/2014</td>
      <td>7825</td>
      <td>Eberhard</td>
      <td>Hilf</td>
      <td>192657</td>
      <td>nike air griffey max 360 sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>170.0</td>
      <td>2</td>
      <td>Nike</td>
    </tr>
  </tbody>
</table>
</div>

**Q6.5**

<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>RowNO</th>
      <th>SaleDate</th>
      <th>CustomerID</th>
      <th>FirstName</th>
      <th>LastName</th>
      <th>OrderID</th>
      <th>ProductName</th>
      <th>Category</th>
      <th>Color</th>
      <th>SalePrice</th>
      <th>Quantity</th>
      <th>ManufacturerName</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>3403</th>
      <td>3404</td>
      <td>7/16/2014</td>
      <td>5196</td>
      <td>Petri</td>
      <td>Hallikainen</td>
      <td>192382</td>
      <td>braidy thong sandal</td>
      <td>sandals</td>
      <td>Black,Green,Pink</td>
      <td>6.99</td>
      <td>1</td>
      <td>Fashion Lab</td>
    </tr>
    <tr>
      <th>1216</th>
      <td>1217</td>
      <td>3/18/2014</td>
      <td>17530</td>
      <td>Louise</td>
      <td>Klein</td>
      <td>191638</td>
      <td>braidy thong sandal</td>
      <td>sandals</td>
      <td>Black,Green,Pink</td>
      <td>6.99</td>
      <td>1</td>
      <td>Fashion Lab</td>
    </tr>
    <tr>
      <th>12117</th>
      <td>12118</td>
      <td>10/14/2015</td>
      <td>11814</td>
      <td>Debora</td>
      <td>Rosa</td>
      <td>195359</td>
      <td>tianna sandal</td>
      <td>sandals</td>
      <td>Red</td>
      <td>6.29</td>
      <td>1</td>
      <td>Fashion Lab</td>
    </tr>
  </tbody>
</table>
</div>

## Q7. (4.9 points)

1. (1 point) Use the `groupby()` function to group **sales_df** by the '**Category**' column.  
1. (2.5 points) Use a for loop to extract the dataframe for each category and save it as a separate CSV file, with the filename formatted as **category_name.csv**. The category name should be replaced with the actual category name.  
1. (1.3 points) For each category, calculate the sum of the '**Quantity**' column and print the result.
1. (0.1 points) Use ls command to show all files and folder in the current the folder.

```text
Category: boots, Sum quantity sold: 1148
       RowNO    SaleDate  CustomerID FirstName LastName  OrderID  \
3          4  12/31/2013        1134   Xiafeng     Wang   191228   
5          6  12/31/2013       14958   Russell    Baker   191229   
7          8    1/1/2014       17448   Margret  Gilmore   191231   
25        26    1/2/2014       14473      Anne  Matheus   191239   
77        78    1/5/2014        2092      Dena   Acosta   191259   
...      ...         ...         ...       ...      ...      ...   
12519  12520   11/5/2015        2937   Barbara   Foster   195490   
12536  12537   11/7/2015        3200     Robin  Johnson   195497   
12554  12555   11/7/2015       11921   Tabitha    James   195502   
12559  12560   11/7/2015       11921   Tabitha    James   195502   
12566  12567   11/7/2015        9345    Lorene  Charles   195505   

                                             ProductName Category  \
3                       timberland icon 6" premium boots    boots   
5                  juno buckle animal trim wedge sneaker    boots   
7                natalia high platform suede fringe boot    boots   
25                         dean leather and canvas boots    boots   
77                       luga strappy over the knee boot    boots   
...                                                  ...      ...   
12519  nadia short lace up boot w/ faux interior fur ...    boots   
12536                                        ahanu boots    boots   
12554                                       berry bootie    boots   
12559                   timberland icon 6" premium boots    boots   
12566                              nm camp leather boots    boots   

              Color  SalePrice  Quantity ManufacturerName  
3             Black     116.99         1       Timberland  
5      Animal Print      22.99         1    Apple Bottoms  
7             Black      50.04         2           Dereon  
25            Black      79.20         1             Levi  
77            Black      20.15         1      Fashion Lab  
...             ...        ...       ...              ...  
12519         white      32.89         1    Apple Bottoms  
12536         Black      20.36         1      Fashion Lab  
12554         Black      32.66         1    Apple Bottoms  
12559         Black     105.29         1       Timberland  
12566         Black      74.68         1       Timberland  

[986 rows x 12 columns]
Category: casual shoes, Sum quantity sold: 525
       RowNO   SaleDate  CustomerID    FirstName     LastName  OrderID  \
21        22   1/2/2014         653         John      Hebeler   191238   
28        29   1/2/2014        3724       Jarrod        Moran   191241   
60        61   1/4/2014        7881  Christopher        Jones   191251   
75        76   1/5/2014        8135      Richard       Hauser   191257   
93        94   1/6/2014       17519     Matthias   Roggendorf   191264   
...      ...        ...         ...          ...          ...      ...   
12436  12437  11/3/2015       14625       Israel      Aguilar   195469   
12448  12449  11/4/2015       11291       Jeanie       Kinney   195473   
12457  12458  11/4/2015       13665      Jarrett      Michael   195475   
12472  12473  11/4/2015         731        Helen       Mobley   195478   
12513  12514  11/5/2015       16836          Joe  Nandhakumar   195488   

                                         ProductName      Category  Color  \
21                           fred slip on dress shoe  casual shoes  Black   
28                                      driver shoes  casual shoes  Beige   
60              sergeant major low ultra woven shoes  casual shoes  Black   
75                               docksides boat shoe  casual shoes  Black   
93                               docksides boat shoe  casual shoes  Black   
...                                              ...           ...    ...   
12436                                nicoletti shoes  casual shoes  Brown   
12448  earthkeepers hookset handcrafted slip on shoe  casual shoes  Black   
12457                            casual comfort shoe  casual shoes  Black   
12472                                  driving shoes  casual shoes  Black   
12513                            casual comfort shoe  casual shoes  Black   

       SalePrice  Quantity      ManufacturerName  
21         20.69         1          Buyers Picks  
28         29.09         2          Buyers Picks  
60         31.49         1  Unstitched Utilities  
75         95.00         1                Sebago  
93         96.00         1                Sebago  
...          ...       ...                   ...  
12436      16.19         1      Basic Essentials  
12448      71.25         1            Timberland  
12457      19.10         1          Buyers Picks  
12472      72.00         1          Buyers Picks  
12513      20.15         1          Buyers Picks  

[456 rows x 12 columns]
Category: flats, Sum quantity sold: 357
       RowNO   SaleDate  CustomerID FirstName        LastName  OrderID  \
10        11   1/2/2014       14956    Lorena  Gomez-Martinez   191234   
13        14   1/2/2014       10767   Anthony          Hooper   191235   
14        15   1/2/2014       10767   Anthony          Hooper   191235   
18        19   1/2/2014        8907  Jermaine           Piper   191236   
73        74   1/4/2014       10402     Lewis         Leeburg   191255   
...      ...        ...         ...       ...             ...      ...   
12498  12499  11/5/2015        5838     Kathy        Faggiani   195483   
12500  12501  11/5/2015       16928   Zhaohao             Sun   195484   
12502  12503  11/5/2015        2400      Ross           Oneal   195485   
12527  12528  11/6/2015       15123        Jo         Smedley   195494   
12557  12558  11/7/2015       11921   Tabitha           James   195502   

                                   ProductName Category        Color  \
10     melissa ballet flat w/bow toe metal hit    flats        Black   
13                        frostine spike flats    flats        Black   
14              olga moch bootie w/real suede!    flats        Black   
18                 damia stripe canvas sneaker    flats  Black,White   
73              rula tribal print smoking shoe    flats        Black   
...                                        ...      ...          ...   
12498         no place like home glitter flats    flats       Bronze   
12500  melissa ballet flat w/bow toe metal hit    flats        Black   
12502                     frostine spike flats    flats        Black   
12527            shiny animal print comfy flat    flats         Gold   
12557                                 hastings    flats         Grey   

       SalePrice  Quantity ManufacturerName  
10         18.99         1      Fashion Lab  
13         29.39         1      Fashion Lab  
14         12.73         1      Fashion Lab  
18         28.70         1    Apple Bottoms  
73         13.79         2      Fashion Lab  
...          ...       ...              ...  
12498      20.45         1      Fashion Lab  
12500      19.19         1      Fashion Lab  
12502      28.19         1      Fashion Lab  
12527      32.39         1        Not Rated  
12557      16.55         1   Royal Elastics  

[308 rows x 12 columns]
Category: heels, Sum quantity sold: 382
       RowNO    SaleDate  CustomerID FirstName  LastName  OrderID  \
20        21    1/2/2014       12110       Luz  Mcnamara   191237   
24        25    1/2/2014         653      John   Hebeler   191238   
54        55    1/4/2014       13696       May   Vaughan   191249   
86        87    1/5/2014       15733      Lupe   Cabrera   191261   
87        88    1/5/2014       15733      Lupe   Cabrera   191261   
...      ...         ...         ...       ...       ...      ...   
12315  12316  10/26/2015        3223    Carrie   Sargent   195428   
12316  12317  10/26/2015        3223    Carrie   Sargent   195428   
12453  12454   11/4/2015        6077   Hossein    Safari   195474   
12479  12480   11/4/2015        4616   Leticia     Heard   195480   
12543  12544   11/7/2015       10779    Ismael  Mcintyre   195499   

                                             ProductName Category  Color  \
20                                     pump w/toe detail    heels  Black   
24                                  velvet wedge booties    heels  Black   
54                                 tina color block pump    heels   Teal   
86                                    finola spike pumps    heels  Black   
87                                        liz pump w/bow    heels  Black   
...                                                  ...      ...    ...   
12315                 city girl ruffle & bow detail pump    heels  Black   
12316  neva pump w/ankle strap mix fabrication faux s...    heels  Black   
12453                           chain trim platform pump    heels  Beige   
12479                          gladiator pump w/side zip    heels  Beige   
12543                  lux life pump w/ankle strap studs    heels  Black   

       SalePrice  Quantity ManufacturerName  
20         23.51         1      Fashion Lab  
24         20.99         1      Fashion Lab  
54         21.33         1      Fashion Lab  
86         52.07         1      Fashion Lab  
87         22.55         1      Fashion Lab  
...          ...       ...              ...  
12315      19.99         1      Fashion Lab  
12316      58.88         1      Fashion Lab  
12453      14.84         1    Apple Bottoms  
12479      27.54         1      Fashion Lab  
12543      48.50         2      Fashion Lab  

[342 rows x 12 columns]
Category: sandals, Sum quantity sold: 1187
       RowNO   SaleDate  CustomerID FirstName  LastName  OrderID  \
15        16   1/2/2014       10767   Anthony    Hooper   191235   
17        18   1/2/2014       10767   Anthony    Hooper   191235   
19        20   1/2/2014       12110       Luz  Mcnamara   191237   
27        28   1/2/2014        3724    Jarrod     Moran   191241   
36        37   1/2/2014        3852    Billie    Hunter   191242   
...      ...        ...         ...       ...       ...      ...   
12496  12497  11/5/2015        5838     Kathy  Faggiani   195483   
12503  12504  11/5/2015        2400      Ross     Oneal   195485   
12506  12507  11/5/2015        2400      Ross     Oneal   195485   
12538  12539  11/7/2015       14901     Penny     Boyce   195498   
12564  12565  11/7/2015        9345    Lorene   Charles   195505   

                              ProductName Category  Color  SalePrice  \
15      pat trico leather sandal w/straps  sandals  Brown      62.10   
17     wedge sandal w/animal print detail  sandals  Black      36.62   
19                           clear sandal  sandals  Black      16.73   
27                     braided bee sandal  sandals  Black      23.51   
36                   whitley wedge sandal  sandals    Tan      44.17   
...                                   ...      ...    ...        ...   
12496            braided gladiator sandal  sandals  Black      20.78   
12503           hava studded flat sandals  sandals  Black      32.99   
12506        perforated studded gladiator  sandals  Black      34.19   
12538         braided strap w/back zipper  sandals  Black      27.29   
12564                  metal beads sandal  sandals  Black      37.60   

       Quantity ManufacturerName  
15            1        Diba True  
17            1      Fashion Lab  
19            1      Fashion Lab  
27            1      Fashion Lab  
36            1      Fashion Lab  
...         ...              ...  
12496         1      Fashion Lab  
12503         2      Fashion Lab  
12506         1      Fashion Lab  
12538         1      Fashion Lab  
12564         1    Apple Bottoms  

[1042 rows x 12 columns]
Category: slippers, Sum quantity sold: 8
       RowNO    SaleDate  CustomerID  FirstName   LastName  OrderID  \
5306    5307  10/31/2014       18320       Doug  Orendorff   193026   
5531    5532  11/12/2014        8214     Hollis       Meza   193110   
5799    5800  11/23/2014        8746     Junior    Anthony   193214   
5886    5887  11/25/2014       13719      Reyes  Rodriquez   193242   
6457    6458  12/16/2014        9819      Pearl    Metcalf   193441   
9254    9255   5/16/2015       13967      Shawn      Helms   194420   
11093  11094   8/22/2015       12262     Manoel       Neto   195055   
11277  11278   8/31/2015       11936  Dominique     Maurel   195110   

                               ProductName  Category  Color  SalePrice  \
5306   loki suede sheepskin lined slippers  slippers  Black      37.59   
5531   loki suede sheepskin lined slippers  slippers  Black      39.19   
5799   loki suede sheepskin lined slippers  slippers  Black      38.79   
5886   loki suede sheepskin lined slippers  slippers  Black      38.79   
6457   loki suede sheepskin lined slippers  slippers  Black      39.99   
9254   loki suede sheepskin lined slippers  slippers  Black      36.79   
11093  loki suede sheepskin lined slippers  slippers  Black      37.59   
11277  loki suede sheepskin lined slippers  slippers  Black      35.99   

       Quantity ManufacturerName  
5306          1          Bearpaw  
5531          1          Bearpaw  
5799          1          Bearpaw  
5886          1          Bearpaw  
6457          1          Bearpaw  
9254          1          Bearpaw  
11093         1          Bearpaw  
11277         1          Bearpaw  
Category: sneakers, Sum quantity sold: 10293
       RowNO    SaleDate  CustomerID FirstName LastName  OrderID  \
0          1  12/31/2013        1134   Xiafeng     Wang   191228   
1          2  12/31/2013        1134   Xiafeng     Wang   191228   
2          3  12/31/2013        1134   Xiafeng     Wang   191228   
6          7  12/31/2013        3275  Herschel  Webster   191230   
8          9    1/1/2014       11852       Ken    Carey   191232   
...      ...         ...         ...       ...      ...      ...   
12562  12563   11/7/2015        9345    Lorene  Charles   195505   
12563  12564   11/7/2015        9345    Lorene  Charles   195505   
12565  12566   11/7/2015        9345    Lorene  Charles   195505   
12567  12568   11/7/2015        9345    Lorene  Charles   195505   
12568  12569   11/7/2015        9345    Lorene  Charles   195505   

                                             ProductName  Category  \
0                              be mini vulc wns sneakers  sneakers   
1                                          liga sneakers  sneakers   
2                        nike air max correlate sneakers  sneakers   
6                                 suede classic sneakers  sneakers   
8                                    nyc 83 vlc sneakers  sneakers   
...                                                  ...       ...   
12562                        doubleback classic sneakers  sneakers   
12563  earthkeepers hookset handcrafted fabric oxford...  sneakers   
12565                           nike flight one sneakers  sneakers   
12567                           the cage hightop sneaker  sneakers   
12568                wmns sweet classic leather sneakers  sneakers   

                          Color  SalePrice  Quantity ManufacturerName  
0                         Black      57.65         1             Puma  
1                          Blue      63.05         1             Puma  
2                         Black      96.60         1             Nike  
6                        Purple      53.10         1             Puma  
8                         Black      72.00         1           Osiris  
...                         ...        ...       ...              ...  
12562                     Black      28.19         1     Buyers Picks  
12563                     Brown      75.00         2       Timberland  
12565                     White      84.63         1             Nike  
12567  Lime Green,Charcoal,Grey      67.90         1             Fila  
12568                     Black      50.39         1             Nike  

[8940 rows x 12 columns]
Category: wedges, Sum quantity sold: 569
       RowNO    SaleDate  CustomerID FirstName LastName  OrderID  \
4          5  12/31/2013        1134   Xiafeng     Wang   191228   
12        13    1/2/2014       10767   Anthony   Hooper   191235   
38        39    1/3/2014         411     Diane     Knox   191244   
61        62    1/4/2014       14209   Hartmut   Hoehle   191252   
79        80    1/5/2014        6102     Jared     Mack   191260   
...      ...         ...         ...       ...      ...      ...   
12524  12525   11/6/2015       15123        Jo  Smedley   195494   
12530  12531   11/6/2015        2682  Paulette    Horne   195495   
12531  12532   11/6/2015        2682  Paulette    Horne   195495   
12539  12540   11/7/2015       14901     Penny    Boyce   195498   
12556  12557   11/7/2015       11921   Tabitha    James   195502   

                                ProductName Category        Color  SalePrice  \
4                torry wedge tapestry wedge   wedges  Green,Multi      15.29   
12     deondra donut wedge laceup w/buckles   wedges        Beige      31.61   
38       kiss the sky sneaker wedge w/studs   wedges        Black      38.99   
61              dorinda wedge w/ankle strap   wedges        Beige      23.24   
79                         cork screw wedge   wedges        Beige      15.19   
...                                     ...      ...          ...        ...   
12524       padme donut wedge shoe w/laceup   wedges        Black      30.37   
12530  deondra donut wedge laceup w/buckles   wedges        Beige      32.29   
12531                 peep toe fringe wedge   wedges        Beige      20.01   
12539           dorinda wedge w/ankle strap   wedges        Beige      23.99   
12556                           hakea wedge   wedges        Beige      21.99   

       Quantity ManufacturerName  
4             2      Fashion Lab  
12            1      Fashion Lab  
38            2      Fashion Lab  
61            1      Fashion Lab  
79            1      Fashion Lab  
...         ...              ...  
12524         1      Fashion Lab  
12530         1      Fashion Lab  
12531         1      Fashion Lab  
12539         2      Fashion Lab  
12556         2      Fashion Lab  

[487 rows x 12 columns]
```

## Q8. (1.2 points)

1. (1 point) Use the `unique()` function to get the unique values of the **manufacturer** names in **sales_df**. Display the unique manufacturer names.  
2. (0.2 points) Count the number of unique manufacturers and print the result.

```text
['Puma' 'Nike' 'Timberland' 'Fashion Lab' 'Apple Bottoms' 'Dereon'
 'Osiris' 'Royal Elastics' 'Supra' 'Diba True' 'Radii Footwear'
 'Buyers Picks' 'Adidas' 'Levi' 'Grenade' 'Akademiks' 'Keds' 'Lugz'
 'Creative Recreation' 'Cadillac Footwear' 'Reebok' 'AH by Android Homme'
 'Unstitched Utilities' 'Fila' 'Mecca' 'Rocawear' 'Sebago' 'Gourmet'
 'Steve Madden' 'Pelle Pelle' 'COOGI' 'Basic Essentials' 'LRG' 'DC Shoes'
 'Ed Hardy' 'Bearpaw' 'Y.R.U.' 'Lakai' 'Converse' 'Two Lip Shoes'
 'Luichiny' 'Emerica' 'Not Rated' 'Mountain Gear' 'MO7' 'Psyberia'
 'Greedy Geniu$' 'New Balance' 'Famous Stars & Straps' 'HUF' 'Rothco'
 'Pastry' 'Cute To The Core' 'Crooks & Castles' 'XOXO' 'The Skate Shop'
 'Shmack' 'Ralph Lauren' 'Generic Surplus' 'DVS Shoe Co.' 'Baby Phat'
 'Florsheim Limited']
```

```text
There are 62 manufacturers.
```

## Q9. (2.3 points)

1. (1 point) Find the rows in **sales_df** that meet the following conditions: **Category is "sneakers", Color is "White", and ManufacturerName is "Nike"**.
1. (0.5 points) Sort the resulting dataframe by '**SalePrice**' in descending order.
1. (0.1 points) Save the resulting dataframe in the variable **nike_sales_df** and print it.
1. (0.1 points) Save the result **nike_sales_df** to the file **nike_sales.csv**.
1. (0.5 points) Write Python code to find the maximum '**SalePrice**' in **nike_sales_df** and print the result.
1. (0.1 points) Use ls command to show all files and folder in the current the folder.

**Q9.3**
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>RowNO</th>
      <th>SaleDate</th>
      <th>CustomerID</th>
      <th>FirstName</th>
      <th>LastName</th>
      <th>OrderID</th>
      <th>ProductName</th>
      <th>Category</th>
      <th>Color</th>
      <th>SalePrice</th>
      <th>Quantity</th>
      <th>ManufacturerName</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>4237</th>
      <td>4238</td>
      <td>9/3/2014</td>
      <td>7825</td>
      <td>Eberhard</td>
      <td>Hilf</td>
      <td>192657</td>
      <td>nike air griffey max 360 sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>170.00</td>
      <td>2</td>
      <td>Nike</td>
    </tr>
    <tr>
      <th>2195</th>
      <td>2196</td>
      <td>5/12/2014</td>
      <td>3965</td>
      <td>Rafael</td>
      <td>Adams</td>
      <td>191969</td>
      <td>nike air griffey max 360 sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>168.30</td>
      <td>1</td>
      <td>Nike</td>
    </tr>
    <tr>
      <th>284</th>
      <td>285</td>
      <td>1/17/2014</td>
      <td>13002</td>
      <td>Brett</td>
      <td>Shaffer</td>
      <td>191330</td>
      <td>nike air griffey max 360 sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>164.90</td>
      <td>1</td>
      <td>Nike</td>
    </tr>
    <tr>
      <th>10627</th>
      <td>10628</td>
      <td>7/29/2015</td>
      <td>12891</td>
      <td>Shahriar</td>
      <td>Murshed</td>
      <td>194892</td>
      <td>nike air griffey max 360 sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>164.90</td>
      <td>1</td>
      <td>Nike</td>
    </tr>
    <tr>
      <th>6680</th>
      <td>6681</td>
      <td>12/24/2014</td>
      <td>4482</td>
      <td>Liliane</td>
      <td>Esnault</td>
      <td>193512</td>
      <td>nike air griffey max 360 sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>159.80</td>
      <td>1</td>
      <td>Nike</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>8439</th>
      <td>8440</td>
      <td>3/29/2015</td>
      <td>1150</td>
      <td>Stacy</td>
      <td>Lane</td>
      <td>194124</td>
      <td>wmns view iii sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>41.39</td>
      <td>1</td>
      <td>Nike</td>
    </tr>
    <tr>
      <th>1096</th>
      <td>1097</td>
      <td>3/9/2014</td>
      <td>6486</td>
      <td>Victor</td>
      <td>Perotti</td>
      <td>191592</td>
      <td>t lite vii sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>34.99</td>
      <td>1</td>
      <td>Nike</td>
    </tr>
    <tr>
      <th>7156</th>
      <td>7157</td>
      <td>1/14/2015</td>
      <td>12406</td>
      <td>Jasmine</td>
      <td>Munoz</td>
      <td>193664</td>
      <td>t lite vii sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>34.99</td>
      <td>1</td>
      <td>Nike</td>
    </tr>
    <tr>
      <th>9153</th>
      <td>9154</td>
      <td>5/10/2015</td>
      <td>11817</td>
      <td>Katharine</td>
      <td>Owen</td>
      <td>194386</td>
      <td>t lite vii sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>33.94</td>
      <td>1</td>
      <td>Nike</td>
    </tr>
    <tr>
      <th>6396</th>
      <td>6397</td>
      <td>12/13/2014</td>
      <td>790</td>
      <td>Margie</td>
      <td>Rhodes</td>
      <td>193416</td>
      <td>t lite vii sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>32.89</td>
      <td>1</td>
      <td>Nike</td>
    </tr>
  </tbody>
</table>
<p>106 rows × 12 columns</p>
</div>

```text
The max SalePrice in nike_sales_df is $170.00.
```

## Q10. (2.3 points)

1. (1 point) Find the rows in **sales_df** that meet the following conditions: **Category is "sneakers", Color is "White", and SalePrice is between 100 and 150 (inclusive)**.
1. (0.5 points) Sort the resulting dataframe by '**SalePrice**' in ascending order.
1. (0.1 points) Save the resulting dataframe in the variable **sales_100_150_df** and print it.
1. (0.1 points) Save the result to the file **sales_100_150.csv**.
1. (0.5 points) Find the average '**SalePrice**' in **sales_100_150_df** and print the result.
1. (0.1 points) Use ls command to show all files and folder in the current the folder.

**Q10.3**
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>RowNO</th>
      <th>SaleDate</th>
      <th>CustomerID</th>
      <th>FirstName</th>
      <th>LastName</th>
      <th>OrderID</th>
      <th>ProductName</th>
      <th>Category</th>
      <th>Color</th>
      <th>SalePrice</th>
      <th>Quantity</th>
      <th>ManufacturerName</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>755</th>
      <td>756</td>
      <td>2/16/2014</td>
      <td>3577</td>
      <td>Sarah</td>
      <td>Fish</td>
      <td>191478</td>
      <td>question low sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>100.10</td>
      <td>1</td>
      <td>Reebok</td>
    </tr>
    <tr>
      <th>662</th>
      <td>663</td>
      <td>2/10/2014</td>
      <td>15027</td>
      <td>Deniz</td>
      <td>Tuna</td>
      <td>191447</td>
      <td>adidas mens rose 2.0 sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>101.20</td>
      <td>1</td>
      <td>Adidas</td>
    </tr>
    <tr>
      <th>1457</th>
      <td>1458</td>
      <td>4/2/2014</td>
      <td>7287</td>
      <td>Ricardo</td>
      <td>Ferris</td>
      <td>191720</td>
      <td>adidas mens rose 2.0 sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>102.30</td>
      <td>1</td>
      <td>Adidas</td>
    </tr>
    <tr>
      <th>5520</th>
      <td>5521</td>
      <td>11/12/2014</td>
      <td>4946</td>
      <td>Laverne</td>
      <td>Keller</td>
      <td>193108</td>
      <td>question low sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>102.30</td>
      <td>1</td>
      <td>Reebok</td>
    </tr>
    <tr>
      <th>9330</th>
      <td>9331</td>
      <td>5/20/2015</td>
      <td>12694</td>
      <td>Jessie</td>
      <td>Hodge</td>
      <td>194448</td>
      <td>adidas mens rose 2.0 sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>102.30</td>
      <td>2</td>
      <td>Adidas</td>
    </tr>
    <tr>
      <th>10568</th>
      <td>10569</td>
      <td>7/26/2015</td>
      <td>10820</td>
      <td>Myrna</td>
      <td>Hutchins</td>
      <td>194873</td>
      <td>question low sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>103.40</td>
      <td>1</td>
      <td>Reebok</td>
    </tr>
    <tr>
      <th>12546</th>
      <td>12547</td>
      <td>11/7/2015</td>
      <td>10779</td>
      <td>Ismael</td>
      <td>Mcintyre</td>
      <td>195499</td>
      <td>question low sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>103.40</td>
      <td>1</td>
      <td>Reebok</td>
    </tr>
    <tr>
      <th>2183</th>
      <td>2184</td>
      <td>5/12/2014</td>
      <td>14846</td>
      <td>David</td>
      <td>Brown</td>
      <td>191965</td>
      <td>question low sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>104.50</td>
      <td>1</td>
      <td>Reebok</td>
    </tr>
    <tr>
      <th>9021</th>
      <td>9022</td>
      <td>5/5/2015</td>
      <td>17725</td>
      <td>Michael</td>
      <td>Shaw</td>
      <td>194347</td>
      <td>adidas mens rose 2.0 sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>105.60</td>
      <td>1</td>
      <td>Adidas</td>
    </tr>
    <tr>
      <th>10401</th>
      <td>10402</td>
      <td>7/19/2015</td>
      <td>13145</td>
      <td>David</td>
      <td>Wainwright</td>
      <td>194811</td>
      <td>question low sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>105.60</td>
      <td>1</td>
      <td>Reebok</td>
    </tr>
    <tr>
      <th>6770</th>
      <td>6771</td>
      <td>12/27/2014</td>
      <td>10665</td>
      <td>Marvin</td>
      <td>Flores</td>
      <td>193542</td>
      <td>question low sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>106.70</td>
      <td>1</td>
      <td>Reebok</td>
    </tr>
    <tr>
      <th>1242</th>
      <td>1243</td>
      <td>3/19/2014</td>
      <td>9918</td>
      <td>Hunter</td>
      <td>Boone</td>
      <td>191646</td>
      <td>adidas mens rose 2.0 sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>106.70</td>
      <td>1</td>
      <td>Adidas</td>
    </tr>
    <tr>
      <th>9255</th>
      <td>9256</td>
      <td>5/16/2015</td>
      <td>13967</td>
      <td>Shawn</td>
      <td>Helms</td>
      <td>194420</td>
      <td>question low sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>107.80</td>
      <td>1</td>
      <td>Reebok</td>
    </tr>
    <tr>
      <th>7398</th>
      <td>7399</td>
      <td>1/27/2015</td>
      <td>14464</td>
      <td>Terry</td>
      <td>Gonzalez</td>
      <td>193758</td>
      <td>question low sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>107.80</td>
      <td>1</td>
      <td>Reebok</td>
    </tr>
    <tr>
      <th>7844</th>
      <td>7845</td>
      <td>2/19/2015</td>
      <td>17815</td>
      <td>Harley</td>
      <td>Mendoza</td>
      <td>193904</td>
      <td>question low sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>107.80</td>
      <td>2</td>
      <td>Reebok</td>
    </tr>
    <tr>
      <th>11360</th>
      <td>11361</td>
      <td>9/5/2015</td>
      <td>13631</td>
      <td>Althea</td>
      <td>Hatcher</td>
      <td>195139</td>
      <td>dmx run 10 ice bottom sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>108.00</td>
      <td>1</td>
      <td>Reebok</td>
    </tr>
    <tr>
      <th>5236</th>
      <td>5237</td>
      <td>10/28/2014</td>
      <td>15451</td>
      <td>Shawn</td>
      <td>Moss</td>
      <td>193004</td>
      <td>question low sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>108.90</td>
      <td>1</td>
      <td>Reebok</td>
    </tr>
    <tr>
      <th>926</th>
      <td>927</td>
      <td>3/1/2014</td>
      <td>8085</td>
      <td>Jesse</td>
      <td>Donahue</td>
      <td>191537</td>
      <td>question low sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>108.90</td>
      <td>1</td>
      <td>Reebok</td>
    </tr>
    <tr>
      <th>9834</th>
      <td>9835</td>
      <td>6/19/2015</td>
      <td>1242</td>
      <td>Leonard</td>
      <td>Branson</td>
      <td>194623</td>
      <td>question low sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>108.90</td>
      <td>1</td>
      <td>Reebok</td>
    </tr>
    <tr>
      <th>9939</th>
      <td>9940</td>
      <td>6/27/2015</td>
      <td>10552</td>
      <td>Shelby</td>
      <td>Humphrey</td>
      <td>194663</td>
      <td>air trainer sc high sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>109.04</td>
      <td>1</td>
      <td>Nike</td>
    </tr>
    <tr>
      <th>2163</th>
      <td>2164</td>
      <td>5/10/2014</td>
      <td>7166</td>
      <td>Mary</td>
      <td>Granger</td>
      <td>191959</td>
      <td>question low sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>110.00</td>
      <td>1</td>
      <td>Reebok</td>
    </tr>
    <tr>
      <th>65</th>
      <td>66</td>
      <td>1/4/2014</td>
      <td>14209</td>
      <td>Hartmut</td>
      <td>Hoehle</td>
      <td>191252</td>
      <td>question low sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>110.00</td>
      <td>2</td>
      <td>Reebok</td>
    </tr>
    <tr>
      <th>4433</th>
      <td>4434</td>
      <td>9/15/2014</td>
      <td>1981</td>
      <td>Johnnie</td>
      <td>Gross</td>
      <td>192724</td>
      <td>question low sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>110.00</td>
      <td>2</td>
      <td>Reebok</td>
    </tr>
    <tr>
      <th>11520</th>
      <td>11521</td>
      <td>9/13/2015</td>
      <td>5871</td>
      <td>Darrell</td>
      <td>Glass</td>
      <td>195184</td>
      <td>question low sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>110.00</td>
      <td>1</td>
      <td>Reebok</td>
    </tr>
    <tr>
      <th>11401</th>
      <td>11402</td>
      <td>9/7/2015</td>
      <td>17307</td>
      <td>Juanita</td>
      <td>Mcgowan</td>
      <td>195151</td>
      <td>question low sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>110.00</td>
      <td>1</td>
      <td>Reebok</td>
    </tr>
    <tr>
      <th>10607</th>
      <td>10608</td>
      <td>7/28/2015</td>
      <td>6574</td>
      <td>Calvin</td>
      <td>Mccormick</td>
      <td>194884</td>
      <td>air trainer sc high sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>110.20</td>
      <td>1</td>
      <td>Nike</td>
    </tr>
    <tr>
      <th>10065</th>
      <td>10066</td>
      <td>7/5/2015</td>
      <td>1394</td>
      <td>Ronnie</td>
      <td>Park</td>
      <td>194707</td>
      <td>air trainer sc high sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>110.20</td>
      <td>1</td>
      <td>Nike</td>
    </tr>
    <tr>
      <th>4741</th>
      <td>4742</td>
      <td>10/3/2014</td>
      <td>6845</td>
      <td>Adrian</td>
      <td>Schneider</td>
      <td>192837</td>
      <td>dmx run 10 ice bottom sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>110.40</td>
      <td>1</td>
      <td>Reebok</td>
    </tr>
    <tr>
      <th>11409</th>
      <td>11410</td>
      <td>9/8/2015</td>
      <td>14506</td>
      <td>Alexander</td>
      <td>Kofinas</td>
      <td>195154</td>
      <td>dmx run 10 ice bottom sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>111.60</td>
      <td>1</td>
      <td>Reebok</td>
    </tr>
    <tr>
      <th>4133</th>
      <td>4134</td>
      <td>8/28/2014</td>
      <td>5976</td>
      <td>Kevin</td>
      <td>Bush</td>
      <td>192619</td>
      <td>air trainer sc high sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>112.52</td>
      <td>1</td>
      <td>Nike</td>
    </tr>
    <tr>
      <th>11050</th>
      <td>11051</td>
      <td>8/19/2015</td>
      <td>11967</td>
      <td>Alisha</td>
      <td>Belcher</td>
      <td>195036</td>
      <td>dmx run 10 ice bottom sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>112.80</td>
      <td>1</td>
      <td>Reebok</td>
    </tr>
    <tr>
      <th>3768</th>
      <td>3769</td>
      <td>8/4/2014</td>
      <td>17778</td>
      <td>Xinlin</td>
      <td>Tang</td>
      <td>192499</td>
      <td>air trainer sc high sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>113.68</td>
      <td>2</td>
      <td>Nike</td>
    </tr>
    <tr>
      <th>4461</th>
      <td>4462</td>
      <td>9/16/2014</td>
      <td>2903</td>
      <td>Hilario</td>
      <td>Baker</td>
      <td>192735</td>
      <td>dmx run 10 ice bottom sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>114.00</td>
      <td>1</td>
      <td>Reebok</td>
    </tr>
    <tr>
      <th>10399</th>
      <td>10400</td>
      <td>7/19/2015</td>
      <td>13145</td>
      <td>David</td>
      <td>Wainwright</td>
      <td>194811</td>
      <td>air trainer sc high sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>114.84</td>
      <td>1</td>
      <td>Nike</td>
    </tr>
    <tr>
      <th>5054</th>
      <td>5055</td>
      <td>10/18/2014</td>
      <td>8315</td>
      <td>Dawn</td>
      <td>Booker</td>
      <td>192945</td>
      <td>dmx run 10 ice bottom sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>115.20</td>
      <td>1</td>
      <td>Reebok</td>
    </tr>
    <tr>
      <th>5133</th>
      <td>5134</td>
      <td>10/23/2014</td>
      <td>6992</td>
      <td>Elroy</td>
      <td>Buck</td>
      <td>192971</td>
      <td>air trainer sc high sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>116.00</td>
      <td>1</td>
      <td>Nike</td>
    </tr>
    <tr>
      <th>9002</th>
      <td>9003</td>
      <td>5/4/2015</td>
      <td>18093</td>
      <td>Karin</td>
      <td>Rosen</td>
      <td>194340</td>
      <td>air trainer sc high sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>116.00</td>
      <td>1</td>
      <td>Nike</td>
    </tr>
    <tr>
      <th>3397</th>
      <td>3398</td>
      <td>7/16/2014</td>
      <td>6449</td>
      <td>Ifeanyi</td>
      <td>Ochiagha</td>
      <td>192380</td>
      <td>dmx run 10 ice bottom sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>117.60</td>
      <td>1</td>
      <td>Reebok</td>
    </tr>
    <tr>
      <th>4896</th>
      <td>4897</td>
      <td>10/10/2014</td>
      <td>17336</td>
      <td>Georg</td>
      <td>Peters</td>
      <td>192887</td>
      <td>evospeed mid mamgp nm formula 1 racing sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>118.30</td>
      <td>1</td>
      <td>Puma</td>
    </tr>
    <tr>
      <th>5050</th>
      <td>5051</td>
      <td>10/18/2014</td>
      <td>835</td>
      <td>Dominic</td>
      <td>Thomas</td>
      <td>192944</td>
      <td>evospeed mid mamgp nm formula 1 racing sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>119.60</td>
      <td>1</td>
      <td>Puma</td>
    </tr>
    <tr>
      <th>11654</th>
      <td>11655</td>
      <td>9/22/2015</td>
      <td>8918</td>
      <td>Arthur</td>
      <td>Tatnall</td>
      <td>195224</td>
      <td>dmx run 10 ice bottom sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>120.00</td>
      <td>1</td>
      <td>Reebok</td>
    </tr>
    <tr>
      <th>5707</th>
      <td>5708</td>
      <td>11/19/2014</td>
      <td>15081</td>
      <td>Hugh</td>
      <td>May</td>
      <td>193179</td>
      <td>evospeed mid mamgp nm formula 1 racing sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>120.90</td>
      <td>1</td>
      <td>Puma</td>
    </tr>
    <tr>
      <th>11815</th>
      <td>11816</td>
      <td>9/30/2015</td>
      <td>7556</td>
      <td>Dion</td>
      <td>Miner</td>
      <td>195272</td>
      <td>evospeed mid mamgp nm formula 1 racing sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>123.50</td>
      <td>1</td>
      <td>Puma</td>
    </tr>
    <tr>
      <th>10717</th>
      <td>10718</td>
      <td>8/3/2015</td>
      <td>5056</td>
      <td>Cody</td>
      <td>Whitney</td>
      <td>194926</td>
      <td>evospeed mid mamgp nm formula 1 racing sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>128.70</td>
      <td>1</td>
      <td>Puma</td>
    </tr>
    <tr>
      <th>11489</th>
      <td>11490</td>
      <td>9/11/2015</td>
      <td>17226</td>
      <td>Maurice</td>
      <td>Steele</td>
      <td>195174</td>
      <td>evospeed mid mamgp nm formula 1 racing sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>130.00</td>
      <td>1</td>
      <td>Puma</td>
    </tr>
    <tr>
      <th>5975</th>
      <td>5976</td>
      <td>11/29/2014</td>
      <td>14716</td>
      <td>Yao-Hua</td>
      <td>Tan</td>
      <td>193278</td>
      <td>air force max 2013 sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>136.30</td>
      <td>1</td>
      <td>Nike</td>
    </tr>
  </tbody>
</table>
</div>

```text
The average SalePrice in sales_100_150_df is $111.60.
```

## Q11 (7.4 point)

1. (1 point) In **sales_df**, create a new column called '**Subtotal**'. The value in this column should be the multiplication of SalePrice value and Quantity value in the each corresponding row in the original **sales_df**. Print the information.
1. (1 point) Use the `groupby()` function to group **sales_df** by the '**ManufacturerName**' column.
1. (2.5 points) Use a for loop to extract the dataframe for each manufacturer and save it as a separate CSV file, with the filename formatted as **manufacturer_name.csv**. The manufacturer name should be replaced with the actual manufacturer name.  
1. (1.3 points) For each manufacturer, calculate the sum of the '**Subtotal**' column and print the result.
1. (0.1 points) Use ls command to show all files and folder in the current the folder.
1. (1.5 points) Retrieve the **Nike** group using the `get_group()` function and sort the resulting dataframe by '**Subtotal**' in ascending order. Save the result in the variable **nike_sales_df** and print the information.

**Q11.1**
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>RowNO</th>
      <th>SaleDate</th>
      <th>CustomerID</th>
      <th>FirstName</th>
      <th>LastName</th>
      <th>OrderID</th>
      <th>ProductName</th>
      <th>Category</th>
      <th>Color</th>
      <th>SalePrice</th>
      <th>Quantity</th>
      <th>ManufacturerName</th>
      <th>Subtotal</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>12/31/2013</td>
      <td>1134</td>
      <td>Xiafeng</td>
      <td>Wang</td>
      <td>191228</td>
      <td>be mini vulc wns sneakers</td>
      <td>sneakers</td>
      <td>Black</td>
      <td>57.65</td>
      <td>1</td>
      <td>Puma</td>
      <td>57.65</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2</td>
      <td>12/31/2013</td>
      <td>1134</td>
      <td>Xiafeng</td>
      <td>Wang</td>
      <td>191228</td>
      <td>liga sneakers</td>
      <td>sneakers</td>
      <td>Blue</td>
      <td>63.05</td>
      <td>1</td>
      <td>Puma</td>
      <td>63.05</td>
    </tr>
    <tr>
      <th>2</th>
      <td>3</td>
      <td>12/31/2013</td>
      <td>1134</td>
      <td>Xiafeng</td>
      <td>Wang</td>
      <td>191228</td>
      <td>nike air max correlate sneakers</td>
      <td>sneakers</td>
      <td>Black</td>
      <td>96.60</td>
      <td>1</td>
      <td>Nike</td>
      <td>96.60</td>
    </tr>
    <tr>
      <th>3</th>
      <td>4</td>
      <td>12/31/2013</td>
      <td>1134</td>
      <td>Xiafeng</td>
      <td>Wang</td>
      <td>191228</td>
      <td>timberland icon 6" premium boots</td>
      <td>boots</td>
      <td>Black</td>
      <td>116.99</td>
      <td>1</td>
      <td>Timberland</td>
      <td>116.99</td>
    </tr>
    <tr>
      <th>4</th>
      <td>5</td>
      <td>12/31/2013</td>
      <td>1134</td>
      <td>Xiafeng</td>
      <td>Wang</td>
      <td>191228</td>
      <td>torry wedge tapestry wedge</td>
      <td>wedges</td>
      <td>Green,Multi</td>
      <td>15.29</td>
      <td>2</td>
      <td>Fashion Lab</td>
      <td>30.58</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>12564</th>
      <td>12565</td>
      <td>11/7/2015</td>
      <td>9345</td>
      <td>Lorene</td>
      <td>Charles</td>
      <td>195505</td>
      <td>metal beads sandal</td>
      <td>sandals</td>
      <td>Black</td>
      <td>37.60</td>
      <td>1</td>
      <td>Apple Bottoms</td>
      <td>37.60</td>
    </tr>
    <tr>
      <th>12565</th>
      <td>12566</td>
      <td>11/7/2015</td>
      <td>9345</td>
      <td>Lorene</td>
      <td>Charles</td>
      <td>195505</td>
      <td>nike flight one sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>84.63</td>
      <td>1</td>
      <td>Nike</td>
      <td>84.63</td>
    </tr>
    <tr>
      <th>12566</th>
      <td>12567</td>
      <td>11/7/2015</td>
      <td>9345</td>
      <td>Lorene</td>
      <td>Charles</td>
      <td>195505</td>
      <td>nm camp leather boots</td>
      <td>boots</td>
      <td>Black</td>
      <td>74.68</td>
      <td>1</td>
      <td>Timberland</td>
      <td>74.68</td>
    </tr>
    <tr>
      <th>12567</th>
      <td>12568</td>
      <td>11/7/2015</td>
      <td>9345</td>
      <td>Lorene</td>
      <td>Charles</td>
      <td>195505</td>
      <td>the cage hightop sneaker</td>
      <td>sneakers</td>
      <td>Lime Green,Charcoal,Grey</td>
      <td>67.90</td>
      <td>1</td>
      <td>Fila</td>
      <td>67.90</td>
    </tr>
    <tr>
      <th>12568</th>
      <td>12569</td>
      <td>11/7/2015</td>
      <td>9345</td>
      <td>Lorene</td>
      <td>Charles</td>
      <td>195505</td>
      <td>wmns sweet classic leather sneakers</td>
      <td>sneakers</td>
      <td>Black</td>
      <td>50.39</td>
      <td>1</td>
      <td>Nike</td>
      <td>50.39</td>
    </tr>
  </tbody>
</table>
<p>12569 rows × 13 columns</p>
</div>

**Q11.3 & Q11.4**
```text
Manufacturer: AH by Android Homme, Sum of subtotals: $6524.44.
       RowNO    SaleDate  CustomerID    FirstName LastName  OrderID  \
56        57    1/4/2014        7881  Christopher    Jones   191251   
169      170   1/11/2014       17725      Michael     Shaw   191294   
275      276   1/17/2014        1355       Ashish   Tewary   191328   
404      405   1/23/2014       11796       Kelsey   Franks   191363   
575      576    2/4/2014       13275      Richard  Fulford   191416   
...      ...         ...         ...          ...      ...      ...   
11984  11985   10/5/2015        1492      Harriet   Weaver   195315   
12018  12019   10/7/2015        2411    Pei-Cheng      Sun   195328   
12098  12099  10/12/2015        6584       Roscoe  Goodwin   195351   
12308  12309  10/25/2015        2411    Pei-Cheng      Sun   195427   
12480  12481   11/4/2015        4616      Leticia    Heard   195480   

                    ProductName  Category               Color  SalePrice  \
56     ah athletic mid sneakers  sneakers               Black      52.19   
169          modern mid sneaker  sneakers  Animal Print,White      63.70   
275               propulsion hi  sneakers               Black      73.71   
404    ah athletic mid sneakers  sneakers               Black      57.99   
575    propulsion hi 2 sneakers  sneakers              Maroon      62.55   
...                         ...       ...                 ...        ...   
11984  ah athletic mid sneakers  sneakers               Black      57.99   
12018  ah athletic mid sneakers  sneakers               Black      56.83   
12098  ah athletic mid sneakers  sneakers               Black      52.19   
12308              ah future lo  sneakers                 Tan      53.34   
12480  propulsion hi 2 sneakers  sneakers              Maroon      67.99   

       Quantity     ManufacturerName  Subtotal  
56            1  AH by Android Homme     52.19  
169           1  AH by Android Homme     63.70  
275           1  AH by Android Homme     73.71  
404           1  AH by Android Homme     57.99  
575           2  AH by Android Homme    125.10  
...         ...                  ...       ...  
11984         1  AH by Android Homme     57.99  
12018         1  AH by Android Homme     56.83  
12098         2  AH by Android Homme    104.38  
12308         1  AH by Android Homme     53.34  
12480         1  AH by Android Homme     67.99  

[98 rows x 13 columns]
Manufacturer: Adidas, Sum of subtotals: $104418.25.
       RowNO   SaleDate  CustomerID FirstName  LastName  OrderID  \
23        24   1/2/2014         653      John   Hebeler   191238   
42        43   1/3/2014        6238    Gerard    Cannoo   191246   
44        45   1/3/2014        6238    Gerard    Cannoo   191246   
62        63   1/4/2014       14209   Hartmut    Hoehle   191252   
66        67   1/4/2014       14209   Hartmut    Hoehle   191252   
...      ...        ...         ...       ...       ...      ...   
12507  12508  11/5/2015       10793      Mark   Vluggen   195486   
12509  12510  11/5/2015       10793      Mark   Vluggen   195486   
12518  12519  11/5/2015       14246   Johanna    Holmes   195489   
12525  12526  11/6/2015       15123        Jo   Smedley   195494   
12547  12548  11/7/2015       10779    Ismael  Mcintyre   195499   

                   ProductName  Category  Color  SalePrice  Quantity  \
23       top ten 2000 sneakers  sneakers  Black     104.75         1   
42     commander td 3 sneakers  sneakers  Black      67.90         1   
44           forum lo sneakers  sneakers   Navy      75.00         1   
62           forum lo sneakers  sneakers   Navy      69.00         1   
66       top ten 2000 sneakers  sneakers  Black     103.67         1   
...                        ...       ...    ...        ...       ...   
12507          ar 3.0 sneakers  sneakers  Black      93.10         1   
12509     gazelle 2 w sneakers  sneakers   Pink      34.91         1   
12518         samoa w sneakers  sneakers  Black      59.80         2   
12525     pitch suede sneakers  sneakers   Grey      65.10         1   
12547     superstar 2 sneakers  sneakers  Black      70.00         1   

      ManufacturerName  Subtotal  
23              Adidas    104.75  
42              Adidas     67.90  
44              Adidas     75.00  
62              Adidas     69.00  
66              Adidas    103.67  
...                ...       ...  
12507           Adidas     93.10  
12509           Adidas     34.91  
12518           Adidas    119.60  
12525           Adidas     65.10  
12547           Adidas     70.00  

[1253 rows x 13 columns]
Manufacturer: Akademiks, Sum of subtotals: $9135.85.
       RowNO    SaleDate  CustomerID FirstName   LastName  OrderID  \
31        32    1/2/2014        3724    Jarrod      Moran   191241   
40        41    1/3/2014        6238    Gerard     Cannoo   191246   
194      195   1/14/2014        6523    Rodger   Jamieson   191304   
220      221   1/15/2014       16731  Rosalind       Wood   191313   
223      224   1/15/2014       16731  Rosalind       Wood   191313   
...      ...         ...         ...       ...        ...      ...   
12287  12288  10/23/2015        7287   Ricardo     Ferris   195420   
12321  12322  10/26/2015       10468    Javier     Bender   195430   
12358  12359  10/28/2015        5449    Philip       Ball   195441   
12522  12523   11/6/2015         774     Hasan  Cavusoglu   195493   
12542  12543   11/7/2015       10779    Ismael   Mcintyre   195499   

                                 ProductName  Category       Color  SalePrice  \
31                 round toe hightop sneaker  sneakers   Black,Red      19.31   
40        akademiks mud guard lowtop sneaker  sneakers       Black      47.49   
194           akademiks true classic sneaker  sneakers       Black      39.99   
220    akademiks houndstooth hightop sneaker  sneakers       Black      19.31   
223                   chukka hightop sneaker  sneakers  Black,Blue      19.79   
...                                      ...       ...         ...        ...   
12287         akademiks true classic sneaker  sneakers       Black      39.99   
12321  akademiks houndstooth hightop sneaker  sneakers       Black      20.78   
12358                rolodex hightop sneaker  sneakers       Black      41.15   
12522         akademiks true classic sneaker  sneakers       Black      36.39   
12542         akademiks true classic sneaker  sneakers       Black      36.79   

       Quantity ManufacturerName  Subtotal  
31            1        Akademiks     19.31  
40            1        Akademiks     47.49  
194           1        Akademiks     39.99  
220           1        Akademiks     19.31  
223           1        Akademiks     19.79  
...         ...              ...       ...  
12287         1        Akademiks     39.99  
12321         1        Akademiks     20.78  
12358         2        Akademiks     82.30  
12522         2        Akademiks     72.78  
12542         1        Akademiks     36.79  

[244 rows x 13 columns]
Manufacturer: Apple Bottoms, Sum of subtotals: $25684.05.
       RowNO    SaleDate  CustomerID    FirstName LastName  OrderID  \
5          6  12/31/2013       14958      Russell    Baker   191229   
18        19    1/2/2014        8907     Jermaine    Piper   191236   
34        35    1/2/2014        3852       Billie   Hunter   191242   
53        54    1/4/2014       13696          May  Vaughan   191249   
57        58    1/4/2014        7881  Christopher    Jones   191251   
...      ...         ...         ...          ...      ...      ...   
12519  12520   11/5/2015        2937      Barbara   Foster   195490   
12520  12521   11/5/2015        1291        Randy    Ryker   195491   
12537  12538   11/7/2015       14901        Penny    Boyce   195498   
12554  12555   11/7/2015       11921      Tabitha    James   195502   
12564  12565   11/7/2015        9345       Lorene  Charles   195505   

                                             ProductName  Category  \
5                  juno buckle animal trim wedge sneaker     boots   
18                           damia stripe canvas sneaker     flats   
34                                elektra python sneaker  sneakers   
53                                  thong jeweled sandal   sandals   
57               blossom floral fold down canvas sneaker  sneakers   
...                                                  ...       ...   
12519  nadia short lace up boot w/ faux interior fur ...     boots   
12520                    natty perforated canvas sneaker  sneakers   
12537            blossom floral fold down canvas sneaker  sneakers   
12554                                       berry bootie     boots   
12564                                 metal beads sandal   sandals   

              Color  SalePrice  Quantity ManufacturerName  Subtotal  
5      Animal Print      22.99         1    Apple Bottoms     22.99  
18      Black,White      28.70         1    Apple Bottoms     28.70  
34            Black      19.39         1    Apple Bottoms     19.39  
53            Black      37.20         1    Apple Bottoms     37.20  
57            Black      40.95         1    Apple Bottoms     40.95  
...             ...        ...       ...              ...       ...  
12519         white      32.89         1    Apple Bottoms     32.89  
12520         Black      40.00         1    Apple Bottoms     40.00  
12537         Black      42.75         1    Apple Bottoms     42.75  
12554         Black      32.66         1    Apple Bottoms     32.66  
12564         Black      37.60         1    Apple Bottoms     37.60  

[766 rows x 13 columns]
Manufacturer: Baby Phat, Sum of subtotals: $18.79.
      RowNO   SaleDate  CustomerID  FirstName  LastName  OrderID  \
7323   7324  1/24/2015        4464  Monideepa  Tarafdar   193729   

              ProductName Category Color  SalePrice  Quantity  \
7323  chance sueded pumps    heels  Pink      18.79         1   

     ManufacturerName  Subtotal  
7323        Baby Phat     18.79  
Manufacturer: Basic Essentials, Sum of subtotals: $1430.05.
       RowNO    SaleDate  CustomerID FirstName   LastName  OrderID  \
104      105    1/6/2014        3173      Yair       Levy   191267   
151      152   1/10/2014        9709     Dewey      Nance   191286   
456      457   1/25/2014        8118      Ivan    Ratliff   191378   
720      721   2/15/2014        8416    Grover      Haney   191467   
724      725   2/15/2014        3115   Abraham   Kendrick   191469   
...      ...         ...         ...       ...        ...      ...   
11482  11483   9/11/2015        6306    Robert     Willis   195173   
11963  11964   10/4/2015        4303      John  Tillquist   195307   
12013  12014   10/7/2015       12191     Vikas       Nath   195323   
12345  12346  10/27/2015       14396     Sally   Richmond   195437   
12436  12437   11/3/2015       14625    Israel    Aguilar   195469   

                              ProductName      Category  Color  SalePrice  \
104                     mini wedge sandal        wedges  Black      15.63   
151                           dandy shoes  casual shoes  Black      31.67   
456    basket weave espedrill upper wedge        wedges  Black      22.76   
720                         antonio shoes  casual shoes  Black      15.67   
724                 wedge w/laser cut out        wedges   Pink      17.99   
...                                   ...           ...    ...        ...   
11482                     deck boat shoes  casual shoes  Black      25.99   
11963                       sedutto shoes  casual shoes  Black      21.77   
12013               wedge w/laser cut out        wedges   Pink      17.81   
12345                       sedutto shoes  casual shoes  Black      21.55   
12436                     nicoletti shoes  casual shoes  Brown      16.19   

       Quantity  ManufacturerName  Subtotal  
104           1  Basic Essentials     15.63  
151           1  Basic Essentials     31.67  
456           1  Basic Essentials     22.76  
720           1  Basic Essentials     15.67  
724           1  Basic Essentials     17.99  
...         ...               ...       ...  
11482         1  Basic Essentials     25.99  
11963         1  Basic Essentials     21.77  
12013         1  Basic Essentials     17.81  
12345         1  Basic Essentials     21.55  
12436         1  Basic Essentials     16.19  

[68 rows x 13 columns]
Manufacturer: Bearpaw, Sum of subtotals: $1717.14.
       RowNO    SaleDate  CustomerID  FirstName    LastName  OrderID  \
166      167   1/11/2014        2385    Ignacio       Lemos   191293   
421      422   1/23/2014       14315     Alyssa       Darby   191366   
544      545    2/3/2014        7264     Shuqin         Cai   191410   
745      746   2/16/2014        1002      Angel     Salazar   191474   
1539    1540    4/6/2014       15654       Mark   Madrilejo   191747   
1555    1556    4/7/2014       12437  Francesco      Folino   191751   
1974    1975    5/2/2014       15651   Kathleen     Hartzel   191901   
2098    2099    5/7/2014       12262     Manoel        Neto   191942   
2416    2417   5/25/2014        3528     Robert       Minch   192040   
2671    2672    6/6/2014       14483      Craig       Britt   192124   
2695    2696    6/6/2014        8921     Graham     Leedham   192131   
3544    3545   7/23/2014         832     Albert    Boonstra   192426   
3587    3588   7/26/2014       15064     Kieran   Mathieson   192447   
4465    4466   9/16/2014        5482  Chienting         Lin   192736   
4723    4724   10/2/2014        6755      Wayne       Motha   192830   
4895    4896  10/10/2014        9676      Scott       Dynes   192886   
5039    5040  10/18/2014       17733    Malcolm      Taylor   192940   
5306    5307  10/31/2014       18320       Doug   Orendorff   193026   
5531    5532  11/12/2014        8214     Hollis        Meza   193110   
5709    5710  11/19/2014       15081       Hugh         May   193179   
5799    5800  11/23/2014        8746     Junior     Anthony   193214   
5838    5839  11/24/2014         961     Sylvia    Alvarado   193227   
5849    5850  11/24/2014        8791     Michal     Zaremba   193232   
5886    5887  11/25/2014       13719      Reyes   Rodriquez   193242   
6014    6015  11/30/2014       15733       Lupe     Cabrera   193292   
6161    6162   12/5/2014       18166        Dee   Mcpherson   193340   
6176    6177   12/6/2014       15394       Neil       Lynch   193345   
6457    6458  12/16/2014        9819      Pearl     Metcalf   193441   
6985    6986    1/4/2015       16958      Kriaa      Salima   193604   
7673    7674   2/11/2015        2875     Shafiz       Yusof   193855   
8042    8043    3/4/2015       16899       Jaak     Jurison   193977   
8586    8587    4/6/2015       15200      Maria      Madsen   194176   
8612    8613    4/8/2015        1096     Meliha     Handzic   194184   
8899    8900   4/25/2015       14463       Qian        Peng   194295   
9254    9255   5/16/2015       13967      Shawn       Helms   194420   
9297    9298   5/18/2015        5321     Eileen        Ross   194435   
9488    9489   5/28/2015        2899      Beryl  Cunningham   194495   
9792    9793   6/16/2015        7443      Sheri        Lowe   194611   
9906    9907   6/24/2015       17231   Catalina     Terrell   194650   
9995    9996    7/1/2015       10483      Julio       Keith   194683   
10170  10171   7/11/2015        4231   Jongwook        Yoon   194751   
10764  10765    8/4/2015       14175      Peiji        Shao   194940   
11093  11094   8/22/2015       12262     Manoel        Neto   195055   
11277  11278   8/31/2015       11936  Dominique      Maurel   195110   
11633  11634   9/20/2015        3449     Thomas     Marbach   195215   
11839  11840   10/1/2015       16702       Cary      Gagnon   195279   
12464  12465   11/4/2015        5727    Pauline   Mcdermott   195476   

                                ProductName  Category     Color  SalePrice  \
166    scarlet fringe detail suede moc flat     flats     Black      29.69   
421             holly washed canvas sneaker  sneakers     Black      28.99   
544    hanna contrast stitch suede moc flat     flats     Black      39.60   
745        erica vintage dot canvas sneaker  sneakers    Orange      23.00   
1539            holly washed canvas sneaker  sneakers     Black      28.99   
1555       erica vintage dot canvas sneaker  sneakers    Orange      22.75   
1974   scarlet fringe detail suede moc flat     flats     Black      32.00   
2098   scarlet fringe detail suede moc flat     flats     Black      31.67   
2416   scarlet fringe detail suede moc flat     flats     Black      32.66   
2671   scarlet fringe detail suede moc flat     flats     Black      32.99   
2695   hanna contrast stitch suede moc flat     flats     Black      38.40   
3544   scarlet fringe detail suede moc flat     flats     Black      31.01   
3587   hanna contrast stitch suede moc flat     flats     Black      39.20   
4465       erica vintage dot canvas sneaker  sneakers    Orange      24.50   
4723       erica vintage dot canvas sneaker  sneakers    Orange      23.00   
4895   scarlet fringe detail suede moc flat     flats     Black      31.67   
5039       erica vintage dot canvas sneaker  sneakers    Orange      22.75   
5306    loki suede sheepskin lined slippers  slippers     Black      37.59   
5531    loki suede sheepskin lined slippers  slippers     Black      39.19   
5709   scarlet fringe detail suede moc flat     flats     Black      31.67   
5799    loki suede sheepskin lined slippers  slippers     Black      38.79   
5838   hanna contrast stitch suede moc flat     flats     Black      40.00   
5849                         emma 10" boots     boots  Charcoal      46.99   
5886    loki suede sheepskin lined slippers  slippers     Black      38.79   
6014   hanna contrast stitch suede moc flat     flats     Black      38.40   
6161   scarlet fringe detail suede moc flat     flats     Black      31.67   
6176   hanna contrast stitch suede moc flat     flats     Black      38.40   
6457    loki suede sheepskin lined slippers  slippers     Black      39.99   
6985   hanna contrast stitch suede moc flat     flats     Black      37.20   
7673   hanna contrast stitch suede moc flat     flats     Black      36.80   
8042   hanna contrast stitch suede moc flat     flats     Black      39.20   
8586            holly washed canvas sneaker  sneakers     Black      28.41   
8612   hanna contrast stitch suede moc flat     flats     Black      38.40   
8899   hanna contrast stitch suede moc flat     flats     Black      36.00   
9254    loki suede sheepskin lined slippers  slippers     Black      36.79   
9297   scarlet fringe detail suede moc flat     flats     Black      32.99   
9488            holly washed canvas sneaker  sneakers     Black      27.83   
9792                         emma 10" boots     boots  Charcoal      45.11   
9906   scarlet fringe detail suede moc flat     flats     Black      31.34   
9995   hanna contrast stitch suede moc flat     flats     Black      36.40   
10170           holly washed canvas sneaker  sneakers     Black      26.09   
10764  scarlet fringe detail suede moc flat     flats     Black      31.67   
11093   loki suede sheepskin lined slippers  slippers     Black      37.59   
11277   loki suede sheepskin lined slippers  slippers     Black      35.99   
11633  scarlet fringe detail suede moc flat     flats     Black      31.01   
11839  scarlet fringe detail suede moc flat     flats     Black      30.35   
12464                        emma 10" boots     boots  Charcoal      46.05   

       Quantity ManufacturerName  Subtotal  
166           1          Bearpaw     29.69  
421           1          Bearpaw     28.99  
544           1          Bearpaw     39.60  
745           1          Bearpaw     23.00  
1539          1          Bearpaw     28.99  
1555          1          Bearpaw     22.75  
1974          1          Bearpaw     32.00  
2098          1          Bearpaw     31.67  
2416          1          Bearpaw     32.66  
2671          2          Bearpaw     65.98  
2695          1          Bearpaw     38.40  
3544          1          Bearpaw     31.01  
3587          1          Bearpaw     39.20  
4465          2          Bearpaw     49.00  
4723          1          Bearpaw     23.00  
4895          1          Bearpaw     31.67  
5039          1          Bearpaw     22.75  
5306          1          Bearpaw     37.59  
5531          1          Bearpaw     39.19  
5709          1          Bearpaw     31.67  
5799          1          Bearpaw     38.79  
5838          1          Bearpaw     40.00  
5849          1          Bearpaw     46.99  
5886          1          Bearpaw     38.79  
6014          1          Bearpaw     38.40  
6161          1          Bearpaw     31.67  
6176          1          Bearpaw     38.40  
6457          1          Bearpaw     39.99  
6985          1          Bearpaw     37.20  
7673          1          Bearpaw     36.80  
8042          1          Bearpaw     39.20  
8586          2          Bearpaw     56.82  
8612          1          Bearpaw     38.40  
8899          1          Bearpaw     36.00  
9254          1          Bearpaw     36.79  
9297          1          Bearpaw     32.99  
9488          1          Bearpaw     27.83  
9792          1          Bearpaw     45.11  
9906          1          Bearpaw     31.34  
9995          1          Bearpaw     36.40  
10170         1          Bearpaw     26.09  
10764         2          Bearpaw     63.34  
11093         1          Bearpaw     37.59  
11277         1          Bearpaw     35.99  
11633         1          Bearpaw     31.01  
11839         1          Bearpaw     30.35  
12464         1          Bearpaw     46.05  
Manufacturer: Buyers Picks, Sum of subtotals: $21863.17.
       RowNO   SaleDate  CustomerID   FirstName     LastName  OrderID  \
21        22   1/2/2014         653        John      Hebeler   191238   
28        29   1/2/2014        3724      Jarrod        Moran   191241   
46        47   1/3/2014        3325      Jeffry         Babb   191248   
50        51   1/4/2014       13696         May      Vaughan   191249   
69        70   1/4/2014       10402       Lewis      Leeburg   191255   
...      ...        ...         ...         ...          ...      ...   
12472  12473  11/4/2015         731       Helen       Mobley   195478   
12475  12476  11/4/2015         731       Helen       Mobley   195478   
12511  12512  11/5/2015       14839  Jiah-Shing         Chen   195487   
12513  12514  11/5/2015       16836         Joe  Nandhakumar   195488   
12562  12563  11/7/2015        9345      Lorene      Charles   195505   

                            ProductName      Category  Color  SalePrice  \
21              fred slip on dress shoe  casual shoes  Black      20.69   
28                         driver shoes  casual shoes  Beige      29.09   
46                      hightop sneaker      sneakers  Black      24.99   
50     dual retro strap hightop sneaker      sneakers  Black      34.29   
69                 asics gt-xl sneakers      sneakers  Black      48.59   
...                                 ...           ...    ...        ...   
12472                     driving shoes  casual shoes  Black      72.00   
12475      the stay fresh canvas chukka      sneakers  Black      30.35   
12511       doubleback classic sneakers      sneakers  Black      27.89   
12513               casual comfort shoe  casual shoes  Black      20.15   
12562       doubleback classic sneakers      sneakers  Black      28.19   

       Quantity ManufacturerName  Subtotal  
21            1     Buyers Picks     20.69  
28            2     Buyers Picks     58.18  
46            1     Buyers Picks     24.99  
50            1     Buyers Picks     34.29  
69            1     Buyers Picks     48.59  
...         ...              ...       ...  
12472         1     Buyers Picks     72.00  
12475         1     Buyers Picks     30.35  
12511         1     Buyers Picks     27.89  
12513         1     Buyers Picks     20.15  
12562         1     Buyers Picks     28.19  

[558 rows x 13 columns]
Manufacturer: COOGI, Sum of subtotals: $15867.98.
       RowNO    SaleDate  CustomerID FirstName     LastName  OrderID  \
91        92    1/6/2014        4696      Eula         Wong   191262   
115      116    1/7/2014        8546    Laurie    Carpenter   191272   
121      122    1/7/2014        5135    Magnus       Ramage   191273   
129      130    1/7/2014        9020      Leon     Schwartz   191275   
144      145    1/8/2014       10345     Royce        Seals   191280   
...      ...         ...         ...       ...          ...      ...   
12271  12272  10/22/2015       11536      Yong         Yeow   195414   
12340  12341  10/27/2015       14396     Sally     Richmond   195437   
12389  12390  10/31/2015       17483     Julio      Carlton   195452   
12514  12515   11/5/2015       16836       Joe  Nandhakumar   195488   
12532  12533   11/6/2015        2682  Paulette        Horne   195495   

                      ProductName  Category         Color  SalePrice  \
91              ryan high sneaker  sneakers         Black      55.99   
115     coogified hightop sneaker  sneakers  Black,Yellow      51.51   
121      monaco 2 hightop sneaker  sneakers         Black      59.99   
129        profly hightop sneaker  sneakers         Black      72.75   
144         soros hightop sneaker  sneakers         Black      56.83   
...                           ...       ...           ...        ...   
12271       soros hightop sneaker  sneakers         Black      52.19   
12340        jettison hi sneakers  sneakers         Black      43.69   
12389  monarque strap hi sneakers  sneakers         Black      49.49   
12514   coogified hightop sneaker  sneakers  Black,Yellow      53.75   
12532      profly hightop sneaker  sneakers         Black      67.50   

       Quantity ManufacturerName  Subtotal  
91            1            COOGI     55.99  
115           1            COOGI     51.51  
121           1            COOGI     59.99  
129           1            COOGI     72.75  
144           1            COOGI     56.83  
...         ...              ...       ...  
12271         1            COOGI     52.19  
12340         2            COOGI     87.38  
12389         1            COOGI     49.49  
12514         1            COOGI     53.75  
12532         2            COOGI    135.00  

[262 rows x 13 columns]
Manufacturer: Cadillac Footwear, Sum of subtotals: $1106.40.
       RowNO    SaleDate  CustomerID  FirstName        LastName  OrderID  \
47        48    1/3/2014        3325     Jeffry            Babb   191248   
146      147    1/8/2014        9670      Lloyd         Walters   191281   
202      203   1/14/2014        9891       Tina        Reynolds   191306   
534      535   1/31/2014       12861     Carlos          Ferran   191402   
1738    1739   4/18/2014       14955     Thomas         Abraham   191822   
1806    1807   4/23/2014       17357     Steven            Curl   191844   
1872    1873   4/28/2014       16843  Siddharth            Kaza   191868   
2408    2409   5/24/2014        8172      Felix           Lewis   192039   
2939    2940   6/21/2014       15002    Patrica           Rubio   192212   
3081    3082   6/30/2014       17437       Heng              Xu   192274   
3172    3173    7/4/2014        3961     Andrew         Kotulic   192309   
3346    3347   7/12/2014       15402      Lilia            Rose   192364   
3358    3359   7/13/2014       17357     Steven            Curl   192366   
3520    3521   7/22/2014        4230       Greg           Mckay   192418   
3521    3522   7/22/2014        9453      Layne         Wallace   192419   
4167    4168   8/30/2014        4803     Josiah           Mills   192629   
4355    4356   9/11/2014        7928    Roxanne          Whalen   192701   
4454    4455   9/16/2014        2046     Cecile            Dodd   192734   
4468    4469   9/16/2014        5482  Chienting             Lin   192736   
4549    4550   9/21/2014        5601     Martin          Wiener   192765   
4853    4854   10/8/2014       11181     Freida         Kimball   192871   
4928    4929  10/11/2014       15125    Jasmine            Dahl   192899   
5098    5099  10/21/2014       16913    Phyllis          Gillis   192961   
5202    5203  10/26/2014       14700      Steve          Reames   192993   
5694    5695  11/18/2014        1320    Kirsten          Ibarra   193173   
5889    5890  11/26/2014       16554    Shannon        Tompkins   193243   
6062    6063   12/1/2014        1916     Judith        Carlisle   193310   
6591    6592  12/20/2014       12327     Robert            Keim   193479   
7397    7398   1/27/2015       14464      Terry        Gonzalez   193758   
7608    7609    2/6/2015        6312    Michael         Herbert   193821   
7785    7786   2/16/2015       15044       Sang             Lee   193887   
7841    7842   2/19/2015       11269      Niels  Bjorn-Andersen   193903   
9480    9481   5/28/2015       15556      Kathy          Arroyo   194493   
9973    9974   6/30/2015        6844      Haley          Howard   194675   
10039  10040    7/2/2015         727     Zhiyan              Hu   194697   
10217  10218   7/13/2015        5107      Mehdi      Beheshtian   194766   
10639  10640   7/30/2015       12129    Ganesan         Shankar   194897   
10715  10716    8/2/2015       12455     Bernie          Thomas   194924   
10902  10903   8/13/2015         596      Kerry          Willis   194994   
11026  11027   8/17/2015        9579     Stefan        Strecker   195028   
11334  11335    9/4/2015       12338  Ernestine       Singleton   195130   
12118  12119  10/14/2015       11814     Debora            Rosa   195359   

                            ProductName  Category     Color  SalePrice  \
47        hops hightop athletic sneaker  sneakers     Black      13.01   
146               whiz athletic sneaker  sneakers  Charcoal      16.73   
202    express hightop athletic sneaker  sneakers     Black      15.80   
534                                rock     boots     Black      23.27   
1738      vital hi top athletic sneaker  sneakers     Black      14.69   
1806   express hightop athletic sneaker  sneakers     Black      16.65   
1872      hops hightop athletic sneaker  sneakers     Black      12.73   
2408      hops hightop athletic sneaker  sneakers     Black      12.87   
2939              whiz athletic sneaker  sneakers  Charcoal      17.81   
3081          aero mid athletic sneaker  sneakers     Black      27.89   
3172          aero mid athletic sneaker  sneakers     Black      28.20   
3346          aero mid athletic sneaker  sneakers     Black      30.99   
3358   express hightop athletic sneaker  sneakers     Black      16.65   
3520                               rock     boots     Black      21.59   
3521          aero mid athletic sneaker  sneakers     Black      30.99   
4167                               rock     boots     Black      23.99   
4355      hops hightop athletic sneaker  sneakers     Black      13.99   
4454   express hightop athletic sneaker  sneakers     Black      15.63   
4468                               rock     boots     Black      23.27   
4549      hops hightop athletic sneaker  sneakers     Black      13.71   
4853                               rock     boots     Black      23.51   
4928      vital hi top athletic sneaker  sneakers     Black      14.09   
5098              whiz athletic sneaker  sneakers  Charcoal      16.73   
5202                               rock     boots     Black      23.99   
5694      hops hightop athletic sneaker  sneakers     Black      13.15   
5889          aero mid athletic sneaker  sneakers     Black      30.06   
6062          aero mid athletic sneaker  sneakers     Black      27.89   
6591          aero mid athletic sneaker  sneakers     Black      27.89   
7397      hops hightop athletic sneaker  sneakers     Black      12.59   
7608      hops hightop athletic sneaker  sneakers     Black      13.29   
7785      hops hightop athletic sneaker  sneakers     Black      13.99   
7841              whiz athletic sneaker  sneakers  Charcoal      17.09   
9480          aero mid athletic sneaker  sneakers     Black      30.99   
9973      hops hightop athletic sneaker  sneakers     Black      13.99   
10039             whiz athletic sneaker  sneakers  Charcoal      16.73   
10217     hops hightop athletic sneaker  sneakers     Black      13.85   
10639     vital hi top athletic sneaker  sneakers     Black      13.49   
10715             whiz athletic sneaker  sneakers  Charcoal      17.63   
10902     hops hightop athletic sneaker  sneakers     Black      12.59   
11026                              rock     boots     Black      23.27   
11334     hops hightop athletic sneaker  sneakers     Black      13.71   
12118             whiz athletic sneaker  sneakers  Charcoal      17.27   

       Quantity   ManufacturerName  Subtotal  
47            2  Cadillac Footwear     26.02  
146           2  Cadillac Footwear     33.46  
202           2  Cadillac Footwear     31.60  
534           1  Cadillac Footwear     23.27  
1738          1  Cadillac Footwear     14.69  
1806          1  Cadillac Footwear     16.65  
1872          1  Cadillac Footwear     12.73  
2408          1  Cadillac Footwear     12.87  
2939          2  Cadillac Footwear     35.62  
3081          1  Cadillac Footwear     27.89  
3172          2  Cadillac Footwear     56.40  
3346          1  Cadillac Footwear     30.99  
3358          1  Cadillac Footwear     16.65  
3520          1  Cadillac Footwear     21.59  
3521          1  Cadillac Footwear     30.99  
4167          2  Cadillac Footwear     47.98  
4355          1  Cadillac Footwear     13.99  
4454          1  Cadillac Footwear     15.63  
4468          1  Cadillac Footwear     23.27  
4549          2  Cadillac Footwear     27.42  
4853          2  Cadillac Footwear     47.02  
4928          2  Cadillac Footwear     28.18  
5098          1  Cadillac Footwear     16.73  
5202          1  Cadillac Footwear     23.99  
5694          1  Cadillac Footwear     13.15  
5889          1  Cadillac Footwear     30.06  
6062          2  Cadillac Footwear     55.78  
6591          2  Cadillac Footwear     55.78  
7397          1  Cadillac Footwear     12.59  
7608          1  Cadillac Footwear     13.29  
7785          1  Cadillac Footwear     13.99  
7841          1  Cadillac Footwear     17.09  
9480          2  Cadillac Footwear     61.98  
9973          2  Cadillac Footwear     27.98  
10039         1  Cadillac Footwear     16.73  
10217         1  Cadillac Footwear     13.85  
10639         1  Cadillac Footwear     13.49  
10715         1  Cadillac Footwear     17.63  
10902         1  Cadillac Footwear     12.59  
11026         2  Cadillac Footwear     46.54  
11334         1  Cadillac Footwear     13.71  
12118         2  Cadillac Footwear     34.54  
Manufacturer: Converse, Sum of subtotals: $16741.42.
       RowNO    SaleDate  CustomerID    FirstName       LastName  OrderID  \
206      207   1/14/2014        7928      Roxanne         Whalen   191307   
214      215   1/15/2014        3030        Edson         Riccio   191310   
227      228   1/16/2014       17667     Emmanuel           Ross   191315   
267      268   1/17/2014        8926        Byron         Werner   191327   
339      340   1/21/2014         724  Epaminondas     Kapetanios   191345   
...      ...         ...         ...          ...            ...      ...   
12365  12366  10/29/2015        8334      Maritza         Dotson   195442   
12404  12405  10/31/2015        9279         Kurt  Fenstermacher   195458   
12444  12445   11/3/2015        4610     Annemijn           Gorp   195471   
12471  12472   11/4/2015         731        Helen         Mobley   195478   
12526  12527   11/6/2015       15123           Jo        Smedley   195494   

                                  ProductName  Category  Color  SalePrice  \
206                 star player rise sneakers  sneakers  Black      70.00   
214                  chuck taylor hi sneakers  sneakers    Red      55.00   
227            chuck taylor all star sneakers  sneakers   Camo      55.80   
267                 pro leather vulc sneakers  sneakers  Black      63.05   
339                  chuck taylor hi sneakers  sneakers    Red      54.45   
...                                       ...       ...    ...        ...   
12365               star player rise sneakers  sneakers  Black      70.00   
12404          chuck taylor all star sneakers  sneakers   Camo      56.40   
12444  chuck taylor all star hi ness sneakers  sneakers  Black      50.75   
12471       chuck taylor all star lp sneakers  sneakers  White      51.70   
12526               pro leather vulc sneakers  sneakers  Black      64.35   

       Quantity ManufacturerName  Subtotal  
206           1         Converse     70.00  
214           1         Converse     55.00  
227           1         Converse     55.80  
267           1         Converse     63.05  
339           1         Converse     54.45  
...         ...              ...       ...  
12365         2         Converse    140.00  
12404         1         Converse     56.40  
12444         2         Converse    101.50  
12471         1         Converse     51.70  
12526         1         Converse     64.35  

[263 rows x 13 columns]
Manufacturer: Creative Recreation, Sum of subtotals: $50428.98.
       RowNO    SaleDate  CustomerID FirstName       LastName  OrderID  \
41        42    1/3/2014        6238    Gerard         Cannoo   191246   
51        52    1/4/2014       13696       May        Vaughan   191249   
63        64    1/4/2014       14209   Hartmut         Hoehle   191252   
102      103    1/6/2014        3173      Yair           Levy   191267   
135      136    1/8/2014        4725  Diederik          Liere   191278   
...      ...         ...         ...       ...            ...      ...   
12406  12407  10/31/2015        9279      Kurt  Fenstermacher   195458   
12419  12420   11/2/2015       13618     Linda         Levine   195464   
12446  12447   11/3/2015         316    Gerard          Beard   195472   
12463  12464   11/4/2015        5727   Pauline      Mcdermott   195476   
12490  12491   11/4/2015        5509   Colleen           Page   195482   

                   ProductName  Category  Color  SalePrice  Quantity  \
41      cesario lo xvi sneaker  sneakers  Black      63.00         1   
51          profaci lo sneaker  sneakers  Black      80.00         1   
63              lacava sneaker  sneakers  Beige      60.45         1   
102    cesario hightop sneaker  sneakers  Black      83.70         1   
135             lacava sneaker  sneakers  Beige      60.45         1   
...                        ...       ...    ...        ...       ...   
12406           lacava sneaker  sneakers  Beige      62.40         2   
12419        cesario x sneaker  sneakers  Black     100.00         1   
12446   cesario lo xvi sneaker  sneakers  Black      67.20         1   
12463   cesario lo xvi sneaker  sneakers  Black      65.10         1   
12490        cesario x sneaker  sneakers  Black      98.00         1   

          ManufacturerName  Subtotal  
41     Creative Recreation     63.00  
51     Creative Recreation     80.00  
63     Creative Recreation     60.45  
102    Creative Recreation     83.70  
135    Creative Recreation     60.45  
...                    ...       ...  
12406  Creative Recreation    124.80  
12419  Creative Recreation    100.00  
12446  Creative Recreation     67.20  
12463  Creative Recreation     65.10  
12490  Creative Recreation     98.00  

[686 rows x 13 columns]
Manufacturer: Crooks & Castles, Sum of subtotals: $997.28.
       RowNO    SaleDate  CustomerID  FirstName LastName  OrderID  \
1262    1263   3/20/2014       15961    Lindsey   Oliver   191652   
1557    1558    4/7/2014       12437  Francesco   Folino   191751   
1679    1680   4/15/2014        1293      Rashi   Sehgal   191802   
1881    1882   4/28/2014       16327       Ming     Yuan   191871   
3893    3894   8/10/2014        9909       Josh  Cabrera   192539   
4000    4001   8/17/2014        2278    Kirstin   Krauss   192565   
5072    5073  10/19/2014        6584     Roscoe  Goodwin   192951   
5309    5310  10/31/2014       14126      Leola     Cote   193027   
5329    5330   11/2/2014        5683     Stuart     Wood   193036   
5746    5747  11/21/2014        3553       Jami    Myers   193197   
6151    6152   12/4/2014       10843       Paul  Forster   193336   
6283    6284  12/10/2014       15167      Magda  Huisman   193371   
6986    6987    1/4/2015       16958      Kriaa   Salima   193604   
8225    8226   3/16/2015         815  Heriberto     Lamb   194045   
10257  10258   7/14/2015        1258      Qiang       Ye   194777   
10335  10336   5/30/2015        8350      Kevin    Duffy   194509   
10358  10359   5/30/2015        7861       Omar     Tate   194513   
10718  10719    8/3/2015       14338         Ed   Watson   194927   
11129  11130   8/24/2015       13021      Myron  Wallace   195067   

               ProductName  Category  Color  SalePrice  Quantity  \
1262          isa sneakers  sneakers  Black      41.70         1   
1557        recon sneakers  sneakers  Black      57.99         1   
1679          isa sneakers  sneakers  Black      40.84         2   
1881          isa sneakers  sneakers  Black      41.27         1   
3893   isa canvas sneakers  sneakers   Grey      41.85         1   
4000          isa sneakers  sneakers  Black      41.70         2   
5072        recon sneakers  sneakers  Black      57.41         1   
5309         nort sneakers  sneakers   Navy      42.76         2   
5329   isa canvas sneakers  sneakers   Grey      43.69         1   
5746         nort sneakers  sneakers   Navy      44.17         1   
6151         nort sneakers  sneakers   Navy      44.64         1   
6283         nort sneakers  sneakers   Navy      45.11         1   
6986          isa sneakers  sneakers  Black      40.84         1   
8225          isa sneakers  sneakers  Black      39.12         1   
10257       recon sneakers  sneakers  Black      53.93         1   
10335        nort sneakers  sneakers   Navy      46.99         1   
10358       recon sneakers  sneakers  Black      53.93         1   
10718         isa sneakers  sneakers  Black      41.27         1   
11129       recon sneakers  sneakers  Black      52.77         1   

       ManufacturerName  Subtotal  
1262   Crooks & Castles     41.70  
1557   Crooks & Castles     57.99  
1679   Crooks & Castles     81.68  
1881   Crooks & Castles     41.27  
3893   Crooks & Castles     41.85  
4000   Crooks & Castles     83.40  
5072   Crooks & Castles     57.41  
5309   Crooks & Castles     85.52  
5329   Crooks & Castles     43.69  
5746   Crooks & Castles     44.17  
6151   Crooks & Castles     44.64  
6283   Crooks & Castles     45.11  
6986   Crooks & Castles     40.84  
8225   Crooks & Castles     39.12  
10257  Crooks & Castles     53.93  
10335  Crooks & Castles     46.99  
10358  Crooks & Castles     53.93  
10718  Crooks & Castles     41.27  
11129  Crooks & Castles     52.77  
Manufacturer: Cute To The Core, Sum of subtotals: $551.15.
       RowNO    SaleDate  CustomerID   FirstName     LastName  OrderID  \
1220    1221   3/18/2014       17530      Louise        Klein   191638   
1833    1834   4/25/2014       12971        Fadi         Deek   191857   
3243    3244    7/8/2014       10121     Subrata  Chakrabarty   192332   
4263    4264    9/5/2014       15071      Joanne        Pratt   192670   
4826    4827   10/7/2014       16315         Xia         Zhao   192863   
6249    6250   12/9/2014       17483       Julio      Carlton   193363   
6556    6557  12/19/2014       18189     Suzanne         Penn   193470   
7054    7055    1/7/2015        5886     Natalia    Falaleeva   193627   
7137    7138   1/13/2015        9692  Olanrewaju       Luther   193656   
7151    7152   1/14/2015        8249       Josef       Vargas   193663   
7303    7304   1/23/2015       14228       Bryan        Parks   193720   
7439    7440   1/30/2015       13068      Ulrich        Frank   193773   
7949    7950   2/26/2015       10937        Rene      Andrade   193943   
8923    8924   4/27/2015        9184      Melvin       Newell   194304   
9009    9010    5/4/2015       15328      Kelley      Donalds   194343   
10281  10282   7/15/2015        2723      Beulah         Hurd   194790   
10336  10337   5/30/2015        8350       Kevin        Duffy   194509   
12041  12042   10/8/2015       13649      Dolphy      Abraham   195333   

                           ProductName  Category         Color  SalePrice  \
1220    phine slip-on sneaker w/spikes  sneakers    Black,Gold      29.43   
1833             prime leopard sneaker  sneakers  Animal Print      22.07   
3243   thrill fold down sneaker w/camo  sneakers          Camo      58.99   
4263    phine slip-on sneaker w/spikes  sneakers    Black,Gold      30.07   
4826    phine slip-on sneaker w/spikes  sneakers    Black,Gold      29.43   
6249    phine slip-on sneaker w/spikes  sneakers    Black,Gold      31.99   
6556    phine slip-on sneaker w/spikes  sneakers    Black,Gold      31.99   
7054    phine slip-on sneaker w/spikes  sneakers    Black,Gold      31.35   
7137              prime burger sneaker  sneakers         Multi      18.61   
7151              prime burger sneaker  sneakers         Multi      17.28   
7303              prime burger sneaker  sneakers         Multi      17.66   
7439   thrill fold down sneaker w/camo  sneakers          Camo      53.09   
7949             prime leopard sneaker  sneakers  Animal Print      23.03   
8923             prime leopard sneaker  sneakers  Animal Print      22.07   
9009   thrill fold down sneaker w/camo  sneakers          Camo      57.22   
10281            prime leopard sneaker  sneakers  Animal Print      23.51   
10336             prime burger sneaker  sneakers         Multi      17.66   
12041             prime burger sneaker  sneakers         Multi      17.09   

       Quantity  ManufacturerName  Subtotal  
1220          1  Cute To The Core     29.43  
1833          1  Cute To The Core     22.07  
3243          1  Cute To The Core     58.99  
4263          1  Cute To The Core     30.07  
4826          1  Cute To The Core     29.43  
6249          1  Cute To The Core     31.99  
6556          1  Cute To The Core     31.99  
7054          1  Cute To The Core     31.35  
7137          2  Cute To The Core     37.22  
7151          1  Cute To The Core     17.28  
7303          1  Cute To The Core     17.66  
7439          1  Cute To The Core     53.09  
7949          1  Cute To The Core     23.03  
8923          1  Cute To The Core     22.07  
9009          1  Cute To The Core     57.22  
10281         1  Cute To The Core     23.51  
10336         1  Cute To The Core     17.66  
12041         1  Cute To The Core     17.09  
Manufacturer: DC Shoes, Sum of subtotals: $8250.01.
       RowNO    SaleDate  CustomerID   FirstName   LastName  OrderID  \
116      117    1/7/2014        8546      Laurie  Carpenter   191272   
236      237   1/16/2014        2090    Kimberly   Mcmillan   191316   
282      283   1/17/2014       13002       Brett    Shaffer   191330   
410      411   1/23/2014       10697      Stella     Mecwan   191364   
507      508   1/29/2014       12558        Leon  Kappelman   191395   
...      ...         ...         ...         ...        ...      ...   
12043  12044   10/8/2015        9417     Jeffrey     Bohler   195335   
12058  12059   10/9/2015       17573       Leigh     Potter   195339   
12300  12301  10/25/2015        3647  Thian-Huat        Ong   195425   
12344  12345  10/27/2015       14396       Sally   Richmond   195437   
12425  12426   11/3/2015        7201       Oscar      Saenz   195465   

               ProductName  Category       Color  SalePrice  Quantity  \
116    court vulc sneakers  sneakers       Black      51.70         2   
236       pool le sneakers  sneakers       Black      54.45         1   
282        bridge sneakers  sneakers  Black,Grey      49.50         1   
410        bridge sneakers  sneakers  Black,Grey      55.00         1   
507        bridge sneakers  sneakers  Black,Grey      53.90         2   
...                    ...       ...         ...        ...       ...   
12043  villain tx sneakers  sneakers        Grey      45.00         2   
12058     pool le sneakers  sneakers       Black      53.35         1   
12300     pool le sneakers  sneakers       Black      55.00         1   
12344     pool le sneakers  sneakers       Black      53.35         1   
12425     pool le sneakers  sneakers       Black      53.90         2   

      ManufacturerName  Subtotal  
116           DC Shoes    103.40  
236           DC Shoes     54.45  
282           DC Shoes     49.50  
410           DC Shoes     55.00  
507           DC Shoes    107.80  
...                ...       ...  
12043         DC Shoes     90.00  
12058         DC Shoes     53.35  
12300         DC Shoes     55.00  
12344         DC Shoes     53.35  
12425         DC Shoes    107.80  

[130 rows x 13 columns]
Manufacturer: DVS Shoe Co., Sum of subtotals: $30.99.
      RowNO    SaleDate  CustomerID FirstName LastName  OrderID  \
5078   5079  10/21/2014       17852     Randy   Wooten   192953   

                 ProductName  Category Color  SalePrice  Quantity  \
5078  inmate canvas sneakers  sneakers  Grey      30.99         1   

     ManufacturerName  Subtotal  
5078     DVS Shoe Co.     30.99  
Manufacturer: Dereon, Sum of subtotals: $1180.03.
       RowNO    SaleDate  CustomerID  FirstName      LastName  OrderID  \
7          8    1/1/2014       17448    Margret       Gilmore   191231   
736      737   2/16/2014         292    Numbers     Gallagher   191472   
976      977    3/3/2014       10422    Michael         Munoz   191554   
1141    1142   3/12/2014        9198      Lewis       Burnett   191612   
1585    1586    4/9/2014       10438     Curtis      Ferguson   191765   
2366    2367   5/21/2014       17113     Thomas        Mccabe   192021   
2931    2932   6/20/2014       16320    Hyunjoo            Oh   192211   
3662    3663   7/29/2014       14621       Gary       Barling   192468   
4158    4159   8/29/2014        9800     Vernon         Maher   192625   
4181    4182   8/30/2014       17774       Tara      Chappell   192632   
4979    4980  10/13/2014        8011     Godwin        Tetteh   192914   
6501    6502  12/17/2014       16914    Xiaowei            Xu   193453   
6531    6532  12/19/2014       16391    Kenneth         Walsh   193465   
7202    7203   1/16/2015        9782  Gwendolyn         Watts   193684   
9015    9016    5/4/2015        4447       Joey  Wolfenbarger   194345   
9816    9817   6/17/2015        3876  Guillermo      Thornton   194617   
10171  10172   7/11/2015        7864   Jennifer        Thomas   194752   
10470  10471   7/22/2015        4899    Stanley        Barron   194840   
10919  10920   8/13/2015        4146     Violet       Gilmore   194997   
11738  11739   9/26/2015        8808   Lingling            Xu   195249   
11996  11997   10/5/2015       10780    Luciano       Andrews   195319   
12032  12033   10/8/2015       10952        Val        Albert   195331   
12252  12253  10/21/2015       12252    Gerardo         Suggs   195409   
12431  12432   11/3/2015       11161     Hattie        Bowers   195468   
12461  12462   11/4/2015       13665    Jarrett       Michael   195475   

                                      ProductName Category   Color  SalePrice  \
7         natalia high platform suede fringe boot    boots   Black      50.04   
736                    explosion high sequin boot    boots  Silver      29.44   
976       natalia high platform suede fringe boot    boots   Black      54.99   
1141      natalia high platform suede fringe boot    boots   Black      53.89   
1585      natalia high platform suede fringe boot    boots   Black      52.24   
2366      natalia high platform suede fringe boot    boots   Black      52.79   
2931         rosalia fringe rings platform bootie    boots   Black      30.35   
3662      natalia high platform suede fringe boot    boots   Black      51.69   
4158                              dynamite bootie    boots    Gold      19.52   
4181          wild knee high sequin platform boot    boots  Silver      54.99   
4979                              dynamite bootie    boots    Gold      19.52   
6501       eva faux suede platform w studded heel    heels   Black      32.00   
6531   camila peep toe high platform glitter pump    heels     Tan      22.99   
7202      natalia high platform suede fringe boot    boots   Black      54.99   
9015         rosalia fringe rings platform bootie    boots   Black      30.02   
9816                              dynamite bootie    boots    Gold      20.99   
10171      eva faux suede platform w studded heel    heels   Black      31.67   
10470        rosalia fringe rings platform bootie    boots   Black      31.01   
10919        rosalia fringe rings platform bootie    boots   Black      32.33   
11738                             dynamite bootie    boots    Gold      20.99   
11996        rosalia fringe rings platform bootie    boots   Black      32.99   
12032        rosalia fringe rings platform bootie    boots   Black      32.33   
12252                             dynamite bootie    boots    Gold      20.36   
12431                             dynamite bootie    boots    Gold      19.31   
12461         wild knee high sequin platform boot    boots  Silver      54.99   

       Quantity ManufacturerName  Subtotal  
7             2           Dereon    100.08  
736           1           Dereon     29.44  
976           2           Dereon    109.98  
1141          2           Dereon    107.78  
1585          1           Dereon     52.24  
2366          1           Dereon     52.79  
2931          2           Dereon     60.70  
3662          1           Dereon     51.69  
4158          1           Dereon     19.52  
4181          1           Dereon     54.99  
4979          1           Dereon     19.52  
6501          1           Dereon     32.00  
6531          1           Dereon     22.99  
7202          1           Dereon     54.99  
9015          1           Dereon     30.02  
9816          2           Dereon     41.98  
10171         1           Dereon     31.67  
10470         2           Dereon     62.02  
10919         2           Dereon     64.66  
11738         1           Dereon     20.99  
11996         1           Dereon     32.99  
12032         1           Dereon     32.33  
12252         1           Dereon     20.36  
12431         1           Dereon     19.31  
12461         1           Dereon     54.99  
Manufacturer: Diba True, Sum of subtotals: $3515.12.
       RowNO    SaleDate  CustomerID FirstName  LastName  OrderID  \
15        16    1/2/2014       10767   Anthony    Hooper   191235   
334      335   1/19/2014       17389   Barbara    Broome   191344   
505      506   1/28/2014        1606    Evelyn    Holman   191394   
631      632    2/7/2014       13587  Brittney  Anderson   191436   
1035    1036    3/5/2014        4378     Cheri     Duffy   191574   
...      ...         ...         ...       ...       ...      ...   
11791  11792   9/29/2015        1738      Cleo   Elliott   195263   
11880  11881   10/2/2015        7482   Dewayne  Martinez   195288   
11890  11891   10/3/2015        5844     Lucio  Morosini   195291   
11953  11954   10/4/2015        1561     Harry    Atkins   195306   
12065  12066  10/10/2015       17487    Lyndon     Logan   195341   

                                ProductName Category        Color  SalePrice  \
15        pat trico leather sandal w/straps  sandals        Brown      62.10   
334       bride lane slip on flat w/cap toe    flats        Black      34.55   
505       pat trico leather sandal w/straps  sandals        Brown      62.79   
631        car mind sandal w/faux pony hair  sandals       Bronze      21.77   
1035   pat trico leather sandal with straps  sandals        Black      67.62   
...                                     ...      ...          ...        ...   
11791  jelly bean leather and beaded sandal  sandals  Brown,Multi      40.47   
11880            kesha woven leather sandal  sandals         Gold      55.46   
11890  jelly bean leather and beaded sandal  sandals  Brown,Multi      40.91   
11953     pat trico leather sandal w/straps  sandals        Brown      64.86   
12065  pat trico leather sandal with straps  sandals        Black      68.31   

       Quantity ManufacturerName  Subtotal  
15            1        Diba True     62.10  
334           1        Diba True     34.55  
505           1        Diba True     62.79  
631           1        Diba True     21.77  
1035          1        Diba True     67.62  
...         ...              ...       ...  
11791         2        Diba True     80.94  
11880         1        Diba True     55.46  
11890         1        Diba True     40.91  
11953         1        Diba True     64.86  
12065         1        Diba True     68.31  

[62 rows x 13 columns]
Manufacturer: Ed Hardy, Sum of subtotals: $41.98.
      RowNO    SaleDate  CustomerID FirstName      LastName  OrderID  \
127     128    1/7/2014        9020      Leon      Schwartz   191275   
5026   5027  10/16/2014        2761    Audrey  Moran-Murphy   192934   

           ProductName  Category  Color  SalePrice  Quantity ManufacturerName  \
127   low rise sneaker  sneakers  Black      19.19         1         Ed Hardy   
5026   mid top sneaker  sneakers  Black      22.79         1         Ed Hardy   

      Subtotal  
127      19.19  
5026     22.79  
Manufacturer: Emerica, Sum of subtotals: $6946.01.
       RowNO    SaleDate  CustomerID   FirstName  LastName  OrderID  \
326      327   1/19/2014        7170        Stan      Hahn   191342   
555      556    2/3/2014        3825   Bernadine     Reece   191412   
692      693   2/12/2014        3918      Murray    Jennex   191455   
744      745   2/16/2014         675     Uchenna        Sr   191473   
784      785   2/18/2014        5479      Alfred     Banks   191487   
...      ...         ...         ...         ...       ...      ...   
12101  12102  10/12/2015        6584      Roscoe   Goodwin   195351   
12302  12303  10/25/2015        3647  Thian-Huat       Ong   195425   
12371  12372  10/29/2015       13618       Linda    Levine   195443   
12497  12498   11/5/2015        5838       Kathy  Faggiani   195483   
12553  12554   11/7/2015        3341      Tanvir    Goraya   195501   

                                             ProductName  Category  \
326                           wino cotton twill sneakers  sneakers   
555                                the tempster sneakers  sneakers   
692          the herman g6 premium smooth suede sneakers  sneakers   
744    the romero troubadour waxed canvas/premium smo...  sneakers   
784          the herman g6 premium smooth suede sneakers  sneakers   
...                                                  ...       ...   
12101                 the westgate smooth suede sneakers  sneakers   
12302        the herman g6 premium smooth suede sneakers  sneakers   
12371                         wino cotton twill sneakers  sneakers   
12497     laced x baker x figueroa smooth suede sneakers  sneakers   
12553                         wino cotton twill sneakers  sneakers   

             Color  SalePrice  Quantity ManufacturerName  Subtotal  
326          Black      36.85         1          Emerica     36.85  
555          white      34.77         1          Emerica     34.77  
692    Black,White      68.15         1          Emerica     68.15  
744          white      58.23         1          Emerica     58.23  
784    Black,White      67.44         1          Emerica     67.44  
...            ...        ...       ...              ...       ...  
12101   Black,Teal      63.99         1          Emerica     63.99  
12302  Black,White      70.28         1          Emerica     70.28  
12371        Black      36.47         1          Emerica     36.47  
12497        white      42.23         1          Emerica     42.23  
12553        Black      37.99         1          Emerica     37.99  

[111 rows x 13 columns]
Manufacturer: Famous Stars & Straps, Sum of subtotals: $2043.60.
       RowNO    SaleDate  CustomerID  FirstName    LastName  OrderID  \
517      518   1/29/2014       15210       Noah       Johns   191396   
868      869   2/24/2014        7945       Seth       Lyons   191516   
2129    2130    5/8/2014       14306   Clarissa    Alvarado   191950   
2435    2436   5/26/2014       16355       Olga     Petkova   192047   
3147    3148    7/2/2014        7111       Rudy  Hirschheim   192299   
3215    3216    7/6/2014       16881    Richard    Swanborg   192323   
3958    3959   8/13/2014       10724       Leah      Pearce   192554   
4511    4512   9/19/2014        7080        Lee      Lawson   192756   
4586    4587   9/25/2014       17086    Stefano    Basaglia   192782   
4903    4904  10/11/2014         304  Roosevelt     Morales   192891   
5109    5110  10/22/2014       13696        May     Vaughan   192965   
6369    6370  12/13/2014       18085      Tammy      Abbott   193408   
7271    7272   1/22/2015       17909   Winifred     Richard   193713   
8068    8069    3/6/2015        6753      Cheri    Bartlett   193991   
8096    8097   3/10/2015        5973     Khalid      Lootah   194003   
8359    8360   3/25/2015       13399      Corey      Bowden   194092   
9031    9032    5/5/2015        3917     Stefan       Figge   194349   
9524    9525    6/1/2015        7709       Josh      Palmer   194527   
9557    9558    6/4/2015        4572      Buraj  Patrakosol   194541   
10027  10028    7/2/2015         144     Murray      Turoff   194694   
10514  10515   7/23/2015        7654     Wilson  Williamson   194853   
10580  10581   7/27/2015       12981     Hollis    Bautista   194877   
11525  11526   9/13/2015        8633       John       Burke   195185   
12433  12434   11/3/2015       14625     Israel     Aguilar   195469   

                   ProductName  Category Color  SalePrice  Quantity  \
517    real tree endo sneakers  sneakers  Camo      57.60         1   
868              bama sneakers  sneakers   Red      85.36         1   
2129   real tree endo sneakers  sneakers  Camo      55.20         1   
2435   real tree endo sneakers  sneakers  Camo      55.20         2   
3147   real tree endo sneakers  sneakers  Camo      55.80         1   
3215   real tree endo sneakers  sneakers  Camo      60.00         1   
3958             bama sneakers  sneakers   Red      87.12         1   
4511             bama sneakers  sneakers   Red      83.60         1   
4586   real tree endo sneakers  sneakers  Camo      60.00         1   
4903             bama sneakers  sneakers   Red      80.08         1   
5109             bama sneakers  sneakers   Red      88.00         2   
6369   real tree endo sneakers  sneakers  Camo      55.20         1   
7271             bama sneakers  sneakers   Red      83.60         1   
8068   real tree endo sneakers  sneakers  Camo      57.60         2   
8096             bama sneakers  sneakers   Red      88.00         2   
8359   real tree endo sneakers  sneakers  Camo      59.40         1   
9031   real tree endo sneakers  sneakers  Camo      55.20         1   
9524             bama sneakers  sneakers   Red      88.00         1   
9557             bama sneakers  sneakers   Red      81.84         1   
10027            bama sneakers  sneakers   Red      84.48         1   
10514            bama sneakers  sneakers   Red      79.20         1   
10580  real tree endo sneakers  sneakers  Camo      58.20         2   
11525  real tree endo sneakers  sneakers  Camo      55.20         1   
12433            bama sneakers  sneakers   Red      82.72         1   

            ManufacturerName  Subtotal  
517    Famous Stars & Straps     57.60  
868    Famous Stars & Straps     85.36  
2129   Famous Stars & Straps     55.20  
2435   Famous Stars & Straps    110.40  
3147   Famous Stars & Straps     55.80  
3215   Famous Stars & Straps     60.00  
3958   Famous Stars & Straps     87.12  
4511   Famous Stars & Straps     83.60  
4586   Famous Stars & Straps     60.00  
4903   Famous Stars & Straps     80.08  
5109   Famous Stars & Straps    176.00  
6369   Famous Stars & Straps     55.20  
7271   Famous Stars & Straps     83.60  
8068   Famous Stars & Straps    115.20  
8096   Famous Stars & Straps    176.00  
8359   Famous Stars & Straps     59.40  
9031   Famous Stars & Straps     55.20  
9524   Famous Stars & Straps     88.00  
9557   Famous Stars & Straps     81.84  
10027  Famous Stars & Straps     84.48  
10514  Famous Stars & Straps     79.20  
10580  Famous Stars & Straps    116.40  
11525  Famous Stars & Straps     55.20  
12433  Famous Stars & Straps     82.72  
Manufacturer: Fashion Lab, Sum of subtotals: $73795.86.
       RowNO    SaleDate  CustomerID FirstName        LastName  OrderID  \
4          5  12/31/2013        1134   Xiafeng            Wang   191228   
10        11    1/2/2014       14956    Lorena  Gomez-Martinez   191234   
12        13    1/2/2014       10767   Anthony          Hooper   191235   
13        14    1/2/2014       10767   Anthony          Hooper   191235   
14        15    1/2/2014       10767   Anthony          Hooper   191235   
...      ...         ...         ...       ...             ...      ...   
12536  12537   11/7/2015        3200     Robin         Johnson   195497   
12538  12539   11/7/2015       14901     Penny           Boyce   195498   
12539  12540   11/7/2015       14901     Penny           Boyce   195498   
12543  12544   11/7/2015       10779    Ismael        Mcintyre   195499   
12556  12557   11/7/2015       11921   Tabitha           James   195502   

                                   ProductName Category        Color  \
4                   torry wedge tapestry wedge   wedges  Green,Multi   
10     melissa ballet flat w/bow toe metal hit    flats        Black   
12        deondra donut wedge laceup w/buckles   wedges        Beige   
13                        frostine spike flats    flats        Black   
14              olga moch bootie w/real suede!    flats        Black   
...                                        ...      ...          ...   
12536                              ahanu boots    boots        Black   
12538              braided strap w/back zipper  sandals        Black   
12539              dorinda wedge w/ankle strap   wedges        Beige   
12543        lux life pump w/ankle strap studs    heels        Black   
12556                              hakea wedge   wedges        Beige   

       SalePrice  Quantity ManufacturerName  Subtotal  
4          15.29         2      Fashion Lab     30.58  
10         18.99         1      Fashion Lab     18.99  
12         31.61         1      Fashion Lab     31.61  
13         29.39         1      Fashion Lab     29.39  
14         12.73         1      Fashion Lab     12.73  
...          ...       ...              ...       ...  
12536      20.36         1      Fashion Lab     20.36  
12538      27.29         1      Fashion Lab     27.29  
12539      23.99         2      Fashion Lab     47.98  
12543      48.50         2      Fashion Lab     97.00  
12556      21.99         2      Fashion Lab     43.98  

[2211 rows x 13 columns]
Manufacturer: Fila, Sum of subtotals: $32040.12.
       RowNO   SaleDate  CustomerID FirstName     LastName  OrderID  \
67        68   1/4/2014        3433      Hugo        Ayers   191253   
96        97   1/6/2014       17811      Lois  Fitz-Gerald   191265   
109      110   1/6/2014        6863      Dave        Yates   191270   
118      119   1/7/2014        5135    Magnus       Ramage   191273   
120      121   1/7/2014        5135    Magnus       Ramage   191273   
...      ...        ...         ...       ...          ...      ...   
12473  12474  11/4/2015         731     Helen       Mobley   195478   
12499  12500  11/5/2015        5838     Kathy     Faggiani   195483   
12523  12524  11/6/2015       15123        Jo      Smedley   195494   
12560  12561  11/7/2015        3941   Johnnie       Fisher   195503   
12567  12568  11/7/2015        9345    Lorene      Charles   195505   

                       ProductName  Category                     Color  \
67                 f-13 sl sneaker  sneakers                     Black   
96        f-13 lightweight sneaker  sneakers                     Black   
109           cage hightop sneaker  sneakers                     Black   
118     75 fitness hightop sneaker  sneakers                     Black   
120     hi profile hightop sneaker  sneakers                     Black   
...                            ...       ...                       ...   
12473   hi profile hightop sneaker  sneakers                     Black   
12499  original fitness sl sneaker  sneakers                     Black   
12523    f-13 lite hightop sneaker  sneakers                Black,Blue   
12560            f-13 lite sneaker  sneakers                     Black   
12567     the cage hightop sneaker  sneakers  Lime Green,Charcoal,Grey   

       SalePrice  Quantity ManufacturerName  Subtotal  
67         65.00         1             Fila     65.00  
96         47.49         1             Fila     47.49  
109        75.00         1             Fila     75.00  
118        54.59         1             Fila     54.59  
120        41.35         1             Fila     41.35  
...          ...       ...              ...       ...  
12473      43.55         1             Fila     43.55  
12499      40.58         2             Fila     81.16  
12523      64.99         1             Fila     64.99  
12560      59.39         2             Fila    118.78  
12567      67.90         1             Fila     67.90  

[511 rows x 13 columns]
Manufacturer: Florsheim Limited, Sum of subtotals: $44.15.
       RowNO  SaleDate  CustomerID FirstName LastName  OrderID  \
10008  10009  7/2/2015        3032      Earl    Banks   194688   

                            ProductName      Category Color  SalePrice  \
10008  florsheim limited berkley loafer  casual shoes  Navy      44.15   

       Quantity   ManufacturerName  Subtotal  
10008         1  Florsheim Limited     44.15  
Manufacturer: Generic Surplus, Sum of subtotals: $21.33.
      RowNO   SaleDate  CustomerID FirstName LastName  OrderID   ProductName  \
4491   4492  9/18/2014        6755     Wayne    Motha   192748  the workboot   

     Category   Color  SalePrice  Quantity ManufacturerName  Subtotal  
4491    boots  Orange      21.33         1  Generic Surplus     21.33  
Manufacturer: Gourmet, Sum of subtotals: $4502.71.
       RowNO    SaleDate  CustomerID  FirstName    LastName  OrderID  \
78        79    1/5/2014        6102      Jared        Mack   191260   
396      397   1/22/2014        5845   Chandana    Unnithan   191359   
788      789   2/18/2014        7806       Moez     Limayem   191489   
991      992    3/3/2014        9234    Natalie        Horn   191559   
1067    1068    3/8/2014       11409      Vives       Josep   191582   
1179    1180   3/14/2014       12335        Ira    Rudowsky   191624   
1180    1181   3/14/2014       12335        Ira    Rudowsky   191624   
1197    1198   3/15/2014        6166    Rodrigo       Lopez   191629   
1221    1222   3/18/2014       17530     Louise       Klein   191638   
1428    1429    4/2/2014       11379   Fletcher      Albert   191712   
1983    1984    5/2/2014        2054   Birgitta    Bergvall   191904   
2179    2180   5/12/2014       14846      David       Brown   191965   
2363    2364   5/21/2014       13439  Christian       Heine   192020   
2401    2402   5/24/2014        8072    Sherrie       Price   192037   
2711    2712    6/6/2014        4156     Grover      Hollis   192135   
2767    2768    6/9/2014        8465      David       Kraay   192150   
2777    2778   6/10/2014       15437      Craig  Carmichael   192153   
2853    2854   6/14/2014       11876    Deborah    Bradford   192177   
3254    3255    7/9/2014       12198       Jeff        Wynn   192338   
3344    3345   7/12/2014       13168      Megan      Powers   192363   
4048    4049   8/21/2014        4616    Leticia       Heard   192581   
4056    4057   8/22/2014        1889        Tom       Burks   192585   
4250    4251    9/4/2014        5408     Robert      Denker   192663   
4486    4487   9/17/2014        2334      Fiona     Darroch   192745   
4878    4879   10/9/2014       14610     Roscoe         Cox   192880   
5280    5281  10/30/2014       17869      Denis      Protti   193019   
5465    5466   11/9/2014        8587     Krista       Daley   193091   
5853    5854  11/24/2014        8791     Michal     Zaremba   193232   
6074    6075   12/2/2014       17371       Cruz  Williamson   193314   
6550    6551  12/19/2014        3200      Robin     Johnson   193468   
6600    6601  12/21/2014        8765      Denis   Armstrong   193482   
6900    6901  12/31/2014       12393  Elisabeth    Townsend   193579   
7049    7050    1/7/2015        7176        Ted      Surynt   193626   
7130    7131   1/12/2015        1130      Trent      Gentry   193654   
7419    7420   1/29/2015       14798       Cara        Dunn   193768   
7453    7454   1/30/2015       17963       Vera      Whaley   193776   
7505    7506    2/1/2015        8259      Sofia      Barker   193792   
7601    7602    2/5/2015        1860       Eric     Bridges   193819   
7676    7677   2/11/2015        2875     Shafiz       Yusof   193855   
7850    7851   2/20/2015        3250      Sunil      Wattal   193908   
7868    7869   2/21/2015        4708   Kristine      Meyers   193915   
7919    7920   2/25/2015        2881    Rinette       Roets   193933   
8105    8106   3/10/2015       12714    Vanessa       Welch   194005   
8608    8609    4/8/2015       14036     Norris       Doyle   194183   
9271    9272   5/17/2015        9769     Gladys        Wade   194425   
9427    9428   5/26/2015        4622    Rodrigo       Craig   194478   
9463    9464   5/28/2015       11486      Leona       Engel   194488   
9498    9499   5/29/2015       14983   Margaret         Luo   194499   
9738    9739   6/12/2015       17686     Elwood      Reilly   194592   
9773    9774   6/15/2015        7583       John     Farrish   194605   
9833    9834   6/19/2015        1242    Leonard     Branson   194623   
10109  10110    7/8/2015        7978   Jeremiah     Wilkins   194726   
10139  10140    7/9/2015       10758     Stefan     Jakoubi   194735   
10626  10627   7/29/2015        9865      Rocco     Bentley   194891   
11022  11023   8/17/2015        9579     Stefan    Strecker   195028   
11095  11096   8/22/2015       12262     Manoel        Neto   195055   
11412  11413    9/8/2015       14506  Alexander     Kofinas   195154   
11794  11795   9/29/2015       16177    Rolando       Dixon   195265   

                                             ProductName  Category   Color  \
78     cinque 2 mp pyramid studded calf leather sneakers  sneakers     Tan   
396                             cinque 2 mid lx sneakers  sneakers  Silver   
788                                    rossi lx sneakers  sneakers    Camo   
991                             quattro skate c sneakers  sneakers     Red   
1067                            cinque 2 mid lx sneakers  sneakers  Silver   
1179   cinque 2 mp pyramid studded calf leather sneakers  sneakers     Tan   
1180   cinque 2 mp pyramid studded calf leather sneakers  sneakers     Tan   
1197                                   rossi lx sneakers  sneakers    Camo   
1221                                      quattro sl mid  sneakers   Black   
1428                                           dieci mid  sneakers   Green   
1983                                   quattro skate mid  sneakers   Brown   
2179                                      35 lx sneakers  sneakers   Brown   
2363                                   rossi lx sneakers  sneakers    Camo   
2401                                   rossi lx sneakers  sneakers    Camo   
2711                            quattro skate c sneakers  sneakers     Red   
2767                                   quattro skate mid  sneakers   Brown   
2777                                      quattro sl mid  sneakers   Black   
2853                                    nove l strap mid  sneakers   Black   
3254                                      35 lx sneakers  sneakers   Brown   
3344                           quattro skate lx sneakers  sneakers   Brown   
4048                                           dieci mid  sneakers   Green   
4056                                   rossi ap sneakers  sneakers     Tan   
4250                                   rossi lx sneakers  sneakers    Camo   
4486                                      35 lx sneakers  sneakers   Brown   
4878                                           dieci mid  sneakers   Green   
5280                                      35 lx sneakers  sneakers   Brown   
5465                                      quattro sl mid  sneakers   Black   
5853                           quattro skate lx sneakers  sneakers   Brown   
6074   cinque 2 mp pyramid studded calf leather sneakers  sneakers     Tan   
6550                                      quattro sl mid  sneakers   Black   
6600                                      35 lx sneakers  sneakers   Brown   
6900                                      35 lx sneakers  sneakers   Brown   
7049                                      quattro sl mid  sneakers   Black   
7130                            quattro skate c sneakers  sneakers     Red   
7419                           quattro skate lx sneakers  sneakers   Brown   
7453                            cinque 2 mid lx sneakers  sneakers  Silver   
7505                                      quattro sl mid  sneakers   Black   
7601                                    nove l strap mid  sneakers   Black   
7676                                      quattro sl mid  sneakers   Black   
7850                            cinque 2 mid lx sneakers  sneakers  Silver   
7868                                      35 lx sneakers  sneakers   Brown   
7919                                      35 lx sneakers  sneakers   Brown   
8105   cinque 2 mp pyramid studded calf leather sneakers  sneakers     Tan   
8608                            quattro skate c sneakers  sneakers     Red   
9271                            cinque 2 mid lx sneakers  sneakers  Silver   
9427                                      quattro sl mid  sneakers   Black   
9463                             gourmet the 22 sneakers  sneakers    Navy   
9498   cinque 2 mp pyramid studded calf leather sneakers  sneakers     Tan   
9738   cinque 2 mp pyramid studded calf leather sneakers  sneakers     Tan   
9773   cinque 2 mp pyramid studded calf leather sneakers  sneakers     Tan   
9833                                      quattro sl mid  sneakers   Black   
10109                                          dieci mid  sneakers   Green   
10139                                     quattro sl mid  sneakers   Black   
10626                                     35 lx sneakers  sneakers   Brown   
11022                                     35 lx sneakers  sneakers   Brown   
11095                                  rossi lx sneakers  sneakers    Camo   
11412                                     quattro sl mid  sneakers   Black   
11794                                     35 lx sneakers  sneakers   Brown   

       SalePrice  Quantity ManufacturerName  Subtotal  
78         84.59         1          Gourmet     84.59  
396        51.86         2          Gourmet    103.72  
788        65.99         2          Gourmet    131.98  
991        78.40         1          Gourmet     78.40  
1067       56.99         1          Gourmet     56.99  
1179       89.99         1          Gourmet     89.99  
1180       86.39         2          Gourmet    172.78  
1197       63.35         1          Gourmet     63.35  
1221       21.99         1          Gourmet     21.99  
1428       30.99         2          Gourmet     61.98  
1983       20.36         1          Gourmet     20.36  
2179      127.40         1          Gourmet    127.40  
2363       59.39         1          Gourmet     59.39  
2401       61.37         1          Gourmet     61.37  
2711       79.20         1          Gourmet     79.20  
2767       19.10         1          Gourmet     19.10  
2777       21.99         1          Gourmet     21.99  
2853       32.97         1          Gourmet     32.97  
3254      119.60         1          Gourmet    119.60  
3344       76.00         1          Gourmet     76.00  
4048       29.13         1          Gourmet     29.13  
4056       72.26         1          Gourmet     72.26  
4250       64.01         1          Gourmet     64.01  
4486      127.40         1          Gourmet    127.40  
4878       30.99         1          Gourmet     30.99  
5280      118.30         1          Gourmet    118.30  
5465       20.89         1          Gourmet     20.89  
5853       79.20         2          Gourmet    158.40  
6074       86.39         1          Gourmet     86.39  
6550       21.77         1          Gourmet     21.77  
6600      127.40         1          Gourmet    127.40  
6900      124.80         1          Gourmet    124.80  
7049       20.23         2          Gourmet     40.46  
7130       80.00         1          Gourmet     80.00  
7419       76.80         1          Gourmet     76.80  
7453       56.99         2          Gourmet    113.98  
7505       21.99         1          Gourmet     21.99  
7601       33.65         1          Gourmet     33.65  
7676       21.11         1          Gourmet     21.11  
7850       51.29         1          Gourmet     51.29  
7868      127.40         1          Gourmet    127.40  
7919      122.20         2          Gourmet    244.40  
8105       86.39         2          Gourmet    172.78  
8608       72.00         1          Gourmet     72.00  
9271       56.99         1          Gourmet     56.99  
9427       20.45         1          Gourmet     20.45  
9463       15.99         1          Gourmet     15.99  
9498       85.49         2          Gourmet    170.98  
9738       86.39         1          Gourmet     86.39  
9773       89.09         1          Gourmet     89.09  
9833       21.55         1          Gourmet     21.55  
10109      30.99         1          Gourmet     30.99  
10139      21.55         1          Gourmet     21.55  
10626     130.00         1          Gourmet    130.00  
11022     122.20         1          Gourmet    122.20  
11095      64.67         1          Gourmet     64.67  
11412      21.11         1          Gourmet     21.11  
11794     130.00         1          Gourmet    130.00  
Manufacturer: Greedy Geniu$, Sum of subtotals: $44.14.
       RowNO   SaleDate  CustomerID FirstName LastName  OrderID   ProductName  \
493      494  1/28/2014       16553    Harley   Starks   191392  duckboot mid   
11814  11815  9/30/2015         175   Freeman   Lowery   195271  duckboot mid   

      Category Color  SalePrice  Quantity ManufacturerName  Subtotal  
493      boots   Tan      21.38         1    Greedy Geniu$     21.38  
11814    boots   Tan      22.76         1    Greedy Geniu$     22.76  
Manufacturer: Grenade, Sum of subtotals: $2114.47.
       RowNO    SaleDate  CustomerID   FirstName          LastName  OrderID  \
30        31    1/2/2014        3724      Jarrod             Moran   191241   
253      254   1/16/2014        8011      Godwin            Tetteh   191320   
425      426   1/24/2014       12270       Odell              Mora   191369   
444      445   1/24/2014       14929    Danielle         Rodriguez   191372   
806      807   2/18/2014       10199        Sang             Cowan   191493   
839      840   2/20/2014        6945    Caroline              Bell   191504   
1068    1069    3/8/2014       11409       Vives             Josep   191582   
1156    1157   3/13/2014       18243    Qianqian               Liu   191616   
1694    1695   4/16/2014        9798      Alfred         Yarbrough   191807   
2432    2433   5/25/2014       12224      Marvin            Garner   192045   
2481    2482   5/28/2014       17733     Malcolm            Taylor   192062   
2585    2586    6/1/2014       12920        Toby            Austin   192098   
3076    3077   6/30/2014        6568  Athanasios  Chatzimouratidis   192269   
3213    3214    7/6/2014       16881     Richard          Swanborg   192323   
3419    3420   7/17/2014        8576    Florence           Rodhain   192386   
3476    3477   7/20/2014       12582      Laurie             Beach   192404   
3888    3889   8/10/2014        1021        Anto           Nugroho   192538   
4369    4370   9/13/2014       13087       Allen           Landers   192707   
4577    4578   9/24/2014       16789    Gregorio             James   192775   
4610    4611   9/27/2014        7670         Sam              Gill   192789   
4888    4889  10/10/2014       13787       James           Worrell   192882   
5285    5286  10/30/2014       18387       Diane          Hamilton   193020   
5310    5311  10/31/2014       16934         Jan            Segura   193028   
5337    5338   11/2/2014        4925        Glen              Gray   193040   
5630    5631  11/16/2014        3306    Geoffrey          Brewster   193145   
5757    5758  11/22/2014       15558        Gail             Moody   193202   
6125    6126   12/3/2014        6931    Clarence           Robbins   193329   
6157    6158   12/5/2014        6138      Daniel             Chang   193339   
6399    6400  12/13/2014       15342       Sharm           Manwani   193418   
6747    6748  12/27/2014       14834        Yang              Park   193537   
7072    7073    1/8/2015       17287     Maryann          Costello   193634   
7182    7183   1/15/2015        4725    Diederik             Liere   193676   
7504    7505    2/1/2015        8259       Sofia            Barker   193792   
7744    7745   2/15/2015       11490      Vernon           Dempsey   193875   
7956    7957   2/27/2015       12393   Elisabeth          Townsend   193944   
8125    8126   3/11/2015        4077     Willard             Drake   194010   
8131    8132   3/11/2015       16396   Christian           Seeling   194012   
8235    8236   3/16/2015        8011      Godwin            Tetteh   194046   
8352    8353   3/24/2015        9932       Xueqi               Wei   194090   
9217    9218   5/13/2015        1440         Jan        Leimeister   194410   
9371    9372   5/22/2015       14019        Eric             David   194460   
9858    9859   6/21/2015       15071      Joanne             Pratt   194632   
9951    9952   6/28/2015        3695     Samiaji            Sarosa   194666   
10254  10255   7/14/2015       10476        Elma             Helms   194776   
10311  10312   5/29/2015       17387       Clyde             Bynum   194501   
10374  10375   7/18/2015        3331        Jose          Baitello   194803   
10439  10440   7/21/2015        4906      Maxine            Church   194829   
11114  11115   8/22/2015        4338       Grace          Castillo   195061   
11541  11542   9/13/2015       17424      Haiyan             Huang   195189   
11780  11781   9/29/2015       12639     Marilyn           Kimball   195261   
12268  12269  10/22/2015       11536        Yong              Yeow   195414   
12337  12338  10/26/2015       16198         Tim           Shaftel   195435   

                                ProductName  Category   Color  SalePrice  \
30          kung fu battle slip-on sneakers  sneakers   Black      26.87   
253    no strings attached slip-on sneakers  sneakers   Black      40.00   
425                         layback loafers  sneakers   Black      31.27   
444    no strings attached slip-on sneakers  sneakers   Black      40.00   
806    no strings attached slip-on sneakers  sneakers   Black      36.80   
839    no strings attached slip-on sneakers  sneakers   Black      38.40   
1068                        layback loafers  sneakers   Black      33.99   
1156              urban trekker suede boots     boots   Black      50.95   
1694        kung fu battle slip-on sneakers  sneakers   Black      27.43   
2432              urban trekker suede boots     boots   Black      48.87   
2481   no strings attached slip-on sneakers  sneakers   Black      39.60   
2585            urban trekker leather boots     boots  Maroon      42.74   
3076                        layback loafers  sneakers   Black      33.31   
3213                    dirty vulc sneakers  sneakers   Black      34.99   
3419                  standard isshoe boots     boots    Grey      47.32   
3476        kung fu battle slip-on sneakers  sneakers   Black      25.75   
3888   no strings attached slip-on sneakers  sneakers   Black      36.80   
4369                        layback loafers  sneakers   Black      32.97   
4577              urban trekker suede boots     boots   Black      46.79   
4610        kung fu battle slip-on sneakers  sneakers   Black      27.43   
4888                        layback loafers  sneakers   Black      31.27   
5285                        layback loafers  sneakers   Black      33.31   
5310                  heavy artillery boots     boots   Black      24.95   
5337            urban trekker leather boots     boots  Maroon      42.29   
5630                        layback loafers  sneakers   Black      33.99   
5757                  standard isshoe boots     boots    Grey      49.92   
6125              dirty vulc solid sneakers  sneakers   Black      20.45   
6157        kung fu battle slip-on sneakers  sneakers   Black      26.31   
6399        kung fu battle slip-on sneakers  sneakers   Black      25.19   
6747                        layback loafers  sneakers   Black      32.63   
7072                    dirty vulc sneakers  sneakers   Black      33.59   
7182                        layback loafers  sneakers   Black      33.99   
7504                        layback loafers  sneakers   Black      30.59   
7744              urban trekker suede boots     boots   Black      46.79   
7956                        layback loafers  sneakers   Black      31.95   
8125                        layback loafers  sneakers   Black      33.65   
8131                        layback loafers  sneakers   Black      33.31   
8235              urban trekker suede boots     boots   Black      47.83   
8352                        layback loafers  sneakers   Black      33.99   
9217              urban trekker suede boots     boots   Black      51.99   
9371              urban trekker suede boots     boots   Black      51.47   
9858   no strings attached slip-on sneakers  sneakers   Black      37.20   
9951   no strings attached slip-on sneakers  sneakers   Black      36.00   
10254       kung fu battle slip-on sneakers  sneakers   Black      27.43   
10311  no strings attached slip-on sneakers  sneakers   Black      36.80   
10374  no strings attached slip-on sneakers  sneakers   Black      36.40   
10439             urban trekker suede boots     boots   Black      51.99   
11114           urban trekker leather boots     boots  Maroon      44.99   
11541       kung fu battle slip-on sneakers  sneakers   Black      25.19   
11780       kung fu battle slip-on sneakers  sneakers   Black      26.59   
12268       kung fu battle slip-on sneakers  sneakers   Black      26.87   
12337                       layback loafers  sneakers   Black      30.93   

       Quantity ManufacturerName  Subtotal  
30            1          Grenade     26.87  
253           1          Grenade     40.00  
425           1          Grenade     31.27  
444           1          Grenade     40.00  
806           1          Grenade     36.80  
839           1          Grenade     38.40  
1068          2          Grenade     67.98  
1156          1          Grenade     50.95  
1694          1          Grenade     27.43  
2432          1          Grenade     48.87  
2481          1          Grenade     39.60  
2585          1          Grenade     42.74  
3076          1          Grenade     33.31  
3213          1          Grenade     34.99  
3419          1          Grenade     47.32  
3476          1          Grenade     25.75  
3888          1          Grenade     36.80  
4369          1          Grenade     32.97  
4577          1          Grenade     46.79  
4610          1          Grenade     27.43  
4888          1          Grenade     31.27  
5285          1          Grenade     33.31  
5310          1          Grenade     24.95  
5337          1          Grenade     42.29  
5630          1          Grenade     33.99  
5757          1          Grenade     49.92  
6125          1          Grenade     20.45  
6157          2          Grenade     52.62  
6399          1          Grenade     25.19  
6747          2          Grenade     65.26  
7072          1          Grenade     33.59  
7182          1          Grenade     33.99  
7504          1          Grenade     30.59  
7744          1          Grenade     46.79  
7956          1          Grenade     31.95  
8125          1          Grenade     33.65  
8131          1          Grenade     33.31  
8235          1          Grenade     47.83  
8352          2          Grenade     67.98  
9217          2          Grenade    103.98  
9371          1          Grenade     51.47  
9858          1          Grenade     37.20  
9951          2          Grenade     72.00  
10254         2          Grenade     54.86  
10311         1          Grenade     36.80  
10374         1          Grenade     36.40  
10439         1          Grenade     51.99  
11114         1          Grenade     44.99  
11541         1          Grenade     25.19  
11780         1          Grenade     26.59  
12268         1          Grenade     26.87  
12337         1          Grenade     30.93  
Manufacturer: HUF, Sum of subtotals: $1503.49.
       RowNO    SaleDate  CustomerID  FirstName    LastName  OrderID  \
672      673   2/10/2014        8393    Brandon      Jensen   191449   
925      926    3/1/2014       16284       Jane     Barrett   191536   
1840    1841   4/26/2014        6798      Steve      Howard   191860   
2001    2002    5/3/2014        2875     Shafiz       Yusof   191911   
3023    3024   6/26/2014        8270     Debora    Valentin   192245   
3063    3064   6/29/2014       11525        Win      Mlambo   192262   
3843    3844    8/9/2014        6258        Ana     Azevedo   192528   
4604    4605   9/27/2014       18345    Michael      Morris   192786   
4659    4660   9/29/2014       13836     Mathew    Anderson   192805   
5487    5488  11/11/2014        7869    William      Golden   193099   
5621    5622  11/16/2014        4946    Laverne      Keller   193141   
6419    6420  12/14/2014        3832     Colton      Currie   193427   
6706    6707  12/26/2014       12311     Sergio     Davalos   193524   
7170    7171   1/14/2015         762   Kendrick     Wallace   193673   
7767    7768   2/16/2015       10712  Katsunori      Ishida   193881   
8248    8249   3/18/2015        1790    Jocelyn     Freeman   194055   
8634    8635    4/9/2015        6376     Rafael      Holley   194193   
9233    9234   5/15/2015        2383    Gregory     Donahue   194415   
11579  11580   9/16/2015        7885   Garfield  Washington   195201   
11803  11804   9/29/2015        4112     Mattie      Hinton   195266   
11923  11924   10/4/2015       10752      David        Chao   195299   

                                       ProductName  Category           Color  \
672      hupper canvas/leather tiger camo sneakers  sneakers     Black,Green   
925      hupper canvas/leather tiger camo sneakers  sneakers     Black,Green   
1840              genuine canvas flip out sneakers  sneakers  Blue,Red,White   
2001     hupper canvas/leather tiger camo sneakers  sneakers     Black,Green   
3023              genuine canvas flip out sneakers  sneakers  Blue,Red,White   
3063   pepper pro suede/canvas/worn nylon sneakers  sneakers          Maroon   
3843   pepper pro suede/canvas/worn nylon sneakers  sneakers          Maroon   
4604   pepper pro suede/canvas/worn nylon sneakers  sneakers          Maroon   
4659   pepper pro suede/canvas/worn nylon sneakers  sneakers          Maroon   
5487     hupper canvas/leather tiger camo sneakers  sneakers     Black,Green   
5621     hupper canvas/leather tiger camo sneakers  sneakers     Black,Green   
6419     hupper canvas/leather tiger camo sneakers  sneakers     Black,Green   
6706     hupper canvas/leather tiger camo sneakers  sneakers     Black,Green   
7170     hupper canvas/leather tiger camo sneakers  sneakers     Black,Green   
7767     hupper canvas/leather tiger camo sneakers  sneakers     Black,Green   
8248   pepper pro suede/canvas/worn nylon sneakers  sneakers          Maroon   
8634   pepper pro suede/canvas/worn nylon sneakers  sneakers          Maroon   
9233     hupper canvas/leather tiger camo sneakers  sneakers     Black,Green   
11579    hupper canvas/leather tiger camo sneakers  sneakers     Black,Green   
11803  pepper pro suede/canvas/worn nylon sneakers  sneakers          Maroon   
11923    hupper canvas/leather tiger camo sneakers  sneakers     Black,Green   

       SalePrice  Quantity ManufacturerName  Subtotal  
672        53.99         1              HUF     53.99  
925        56.39         2              HUF    112.78  
1840       47.49         2              HUF     94.98  
2001       56.99         1              HUF     56.99  
3023       47.99         1              HUF     47.99  
3063       52.63         1              HUF     52.63  
3843       53.75         2              HUF    107.50  
4604       52.07         1              HUF     52.07  
4659       54.31         1              HUF     54.31  
5487       59.99         2              HUF    119.98  
5621       55.19         1              HUF     55.19  
6419       58.79         1              HUF     58.79  
6706       59.99         1              HUF     59.99  
7170       59.39         2              HUF    118.78  
7767       59.99         1              HUF     59.99  
8248       55.43         1              HUF     55.43  
8634       52.07         1              HUF     52.07  
9233       58.79         2              HUF    117.58  
11579      57.59         1              HUF     57.59  
11803      54.87         1              HUF     54.87  
11923      59.99         1              HUF     59.99  
Manufacturer: Keds, Sum of subtotals: $2426.70.
       RowNO    SaleDate  CustomerID FirstName    LastName  OrderID  \
37        38    1/2/2014       14932   Naohiro      Terase   191243   
240      241   1/16/2014        9673    Patrik  Appelqvist   191317   
681      682   2/11/2014       14537    German      Howell   191452   
719      720   2/14/2014       15796   Hsin-Lu       Chang   191466   
727      728   2/15/2014       12641  Salvador     Fuentes   191470   
...      ...         ...         ...       ...         ...      ...   
12305  12306  10/25/2015        7861      Omar        Tate   195426   
12351  12352  10/28/2015        5654   Christa        Chen   195440   
12401  12402  10/31/2015        2632     Rosie     Ramirez   195457   
12416  12417   11/2/2015        5788    Valeri    Arseniev   195463   
12485  12486   11/4/2015       10928    Robert      Barrow   195481   

                               ProductName  Category            Color  \
37              champion oxford cvo canvas  sneakers            Cream   
240            keds anchor canvas sneakers  sneakers              Red   
681                  champion dot chambray  sneakers             Blue   
719           double dutch seasonal solids  sneakers             Blue   
727                       keds floral shoe  sneakers             Blue   
...                                    ...       ...              ...   
12305           champion oxford cvo canvas  sneakers            Cream   
12351                champion dot chambray  sneakers             Blue   
12401        rookie laceless candy buttons  sneakers      Black,Multi   
12416  keds champion metallic lace sneaker  sneakers            Black   
12485                  double dutch stripe  sneakers  Lime Green,Blue   

       SalePrice  Quantity ManufacturerName  Subtotal  
37         22.74         1             Keds     22.74  
240        19.99         1             Keds     19.99  
681        27.59         1             Keds     27.59  
719        26.03         1             Keds     26.03  
727        24.17         1             Keds     24.17  
...          ...       ...              ...       ...  
12305      23.49         1             Keds     23.49  
12351      27.89         1             Keds     27.89  
12401      37.59         1             Keds     37.59  
12416      18.99         1             Keds     18.99  
12485      31.99         1             Keds     31.99  

[74 rows x 13 columns]
Manufacturer: LRG, Sum of subtotals: $5779.03.
       RowNO    SaleDate  CustomerID FirstName  LastName  OrderID  \
106      107    1/6/2014        3173      Yair      Levy   191267   
185      186   1/12/2014        2447     Shaun  Richards   191300   
273      274   1/17/2014        1355    Ashish    Tewary   191328   
348      349   1/21/2014        7709      Josh    Palmer   191346   
363      364   1/21/2014        3325    Jeffry      Babb   191351   
...      ...         ...         ...       ...       ...      ...   
11952  11953   10/4/2015        1561     Harry    Atkins   195306   
11993  11994   10/5/2015       17120       Ron     Craig   195318   
12051  12052   10/9/2015        6102     Jared      Mack   195337   
12135  12136  10/14/2015        3634      Thad   Metcalf   195363   
12200  12201  10/19/2015        4090     Pedro    Horton   195387   

                          ProductName  Category       Color  SalePrice  \
106                        tupelo low  sneakers       Black      32.39   
185                iroko rugged boots     boots       Black      43.19   
273            juniper slip - on camo  sneakers        Camo      43.64   
348                     maple low t x  sneakers        Navy      50.75   
363                        tupelo low  sneakers       Black      34.55   
...                               ...       ...         ...        ...   
11952                       maple low  sneakers  Light Grey      46.99   
11993                       maple low  sneakers  Light Grey      46.99   
12051                      tupelo low  sneakers       Black      34.91   
12135  sycamore nubuck/canvas boot hi     boots       Black      39.19   
12200                       maple low  sneakers  Light Grey      45.58   

       Quantity ManufacturerName  Subtotal  
106           2              LRG     64.78  
185           1              LRG     43.19  
273           1              LRG     43.64  
348           1              LRG     50.75  
363           1              LRG     34.55  
...         ...              ...       ...  
11952         1              LRG     46.99  
11993         1              LRG     46.99  
12051         1              LRG     34.91  
12135         2              LRG     78.38  
12200         2              LRG     91.16  

[121 rows x 13 columns]
Manufacturer: Lakai, Sum of subtotals: $2862.24.
       RowNO    SaleDate  CustomerID   FirstName       LastName  OrderID  \
199      200   1/14/2014         769      Miguel   Olivas-Lujan   191305   
900      901   2/27/2014       13428      Stuart         Barnes   191527   
1151    1152   3/13/2014       15273      Bertha           Levy   191614   
1608    1609   4/10/2014       12252     Gerardo          Suggs   191776   
1670    1671   4/14/2014        1440         Jan     Leimeister   191797   
2863    2864   6/15/2014       17497       Vicky       Phillips   192181   
2889    2890   6/16/2014       11025      Nathan         Pierre   192188   
3006    3007   6/25/2014       12268     Sameera        Mubarak   192239   
3119    3120    7/1/2014       16881     Richard       Swanborg   192286   
3653    3654   7/28/2014         656      Julian        Newsome   192465   
3656    3657   7/28/2014       15133       Nabie         Conteh   192466   
3767    3768    8/4/2014        7181        Jeff            Teo   192498   
3920    3921   8/12/2014       14955      Thomas        Abraham   192544   
4055    4056   8/21/2014        8594        Wade          Cline   192584   
4397    4398   9/14/2014       14437        Jane         Klobas   192716   
4430    4431   9/15/2014        1981     Johnnie          Gross   192724   
4493    4494   9/18/2014       13683      Andrew       Bagdanov   192749   
4593    4594   9/25/2014        7163       Leona        Douglas   192783   
4680    4681   9/30/2014       16016  Subhajyoti  Bandyopadhyay   192814   
4693    4694   10/1/2014       13978      Elnora        Elliott   192821   
4892    4893  10/10/2014       13576       Faith           Lade   192884   
4983    4984  10/13/2014        5479      Alfred          Banks   192915   
5238    5239  10/28/2014         913       Harry         Coates   193005   
5790    5791  11/23/2014       18372      Calvin         Austin   193212   
5883    5884  11/25/2014       13719       Reyes      Rodriquez   193242   
6168    6169   12/5/2014       13137      Reuben          Boyer   193341   
6248    6249   12/9/2014       17483       Julio        Carlton   193363   
6505    6506  12/17/2014        3350       Barry          Mayer   193454   
6657    6658  12/23/2014         953       Elton       Bartlett   193501   
7402    7403   1/28/2015       11409       Vives          Josep   193761   
8070    8071    3/7/2015       17389     Barbara         Broome   193993   
8335    8336   3/23/2015       13720     Heather          Smith   194083   
8427    8428   3/29/2015       17242         Mia      Lancaster   194120   
8527    8528    4/4/2015        1291       Randy          Ryker   194158   
8536    8537    4/4/2015       11317        Alan           Byrd   194159   
8585    8586    4/6/2015       15200       Maria         Madsen   194176   
8645    8646    4/9/2015        5240         Pat         Palmer   194198   
8798    8799   4/20/2015       14974     Miranda        Stewart   194258   
8888    8889   4/25/2015       10339     Lakshmi           Iyer   194293   
9379    9380   5/22/2015        7761      Philip          Yates   194463   
9419    9420   5/26/2015       11048     Marcelo        Richter   194477   
9571    9572    6/4/2015        5820        John         Fisher   194543   
9654    9655    6/9/2015        6059      Willie      Rodriguez   194568   
9886    9887   6/24/2015       17338        John       Anderson   194643   
10047  10048    7/3/2015        4592     Gregory     Schechtman   194700   
10291  10292   7/16/2015        5137          Li           Wang   194793   
10623  10624   7/29/2015        8070        Lupe       Anderson   194888   
10628  10629   7/29/2015        3578      Regina       Hargrove   194893   
10704  10705    8/1/2015       17732       Sally          Heard   194922   
10841  10842    8/9/2015       16723        John            Yen   194969   
11422  11423    9/9/2015       15203     Hilario           Lang   195157   
11757  11758   9/27/2015        5661      Takuro       Munezawa   195255   
11991  11992   10/5/2015       17120         Ron          Craig   195318   
12014  12015   10/7/2015       12890    Kimberly        Trevino   195324   
12062  12063  10/10/2015       17976     Eugenio        Camacho   195340   
12299  12300  10/25/2015        3647  Thian-Huat            Ong   195425   
12304  12305  10/25/2015        7861        Omar           Tate   195426   
12452  12453   11/4/2015       11291      Jeanie         Kinney   195473   
12551  12552   11/7/2015        3341      Tanvir         Goraya   195501   

                                   ProductName  Category       Color  \
199                 bb3 tobacco suede sneakers  sneakers       Brown   
900                 bb3 tobacco suede sneakers  sneakers       Brown   
1151               howard black suede sneakers  sneakers       Black   
1608   telford xlk lichen green suede sneakers  sneakers       Green   
1670         griffin black/grey suede sneakers  sneakers       Black   
2863                bb3 tobacco suede sneakers  sneakers       Brown   
2889                bb3 tobacco suede sneakers  sneakers       Brown   
3006          brea mandarin/gum suede sneakers  sneakers      Orange   
3119      manchester black/grey suede sneakers  sneakers       Black   
3653        manchester red/lime suede sneakers  sneakers         Red   
3656          brea mandarin/gum suede sneakers  sneakers      Orange   
3767   telford xlk lichen green suede sneakers  sneakers       Green   
3920         griffin black/grey suede sneakers  sneakers       Black   
4055          brea mandarin/gum suede sneakers  sneakers      Orange   
4397                bb3 tobacco suede sneakers  sneakers       Brown   
4430                 howard red suede sneakers  sneakers         Red   
4493                bb3 tobacco suede sneakers  sneakers       Brown   
4593   telford xlk lichen green suede sneakers  sneakers       Green   
4680          brea mandarin/gum suede sneakers  sneakers      Orange   
4693        manchester red/lime suede sneakers  sneakers         Red   
4892        manchester red/lime suede sneakers  sneakers         Red   
4983                bb3 tobacco suede sneakers  sneakers       Brown   
5238          brea mandarin/gum suede sneakers  sneakers      Orange   
5790          brea mandarin/gum suede sneakers  sneakers      Orange   
5883                bb3 tobacco suede sneakers  sneakers       Brown   
6168   telford xlk lichen green suede sneakers  sneakers       Green   
6248        manchester red/lime suede sneakers  sneakers         Red   
6505                bb3 tobacco suede sneakers  sneakers       Brown   
6657                 marc black suede sneakers  sneakers       Black   
7402          brea mandarin/gum suede sneakers  sneakers      Orange   
8070                bb3 tobacco suede sneakers  sneakers       Brown   
8335          brea mandarin/gum suede sneakers  sneakers      Orange   
8427               howard black suede sneakers  sneakers       Black   
8527                bb3 tobacco suede sneakers  sneakers       Brown   
8536                 howard red suede sneakers  sneakers         Red   
8585         griffin black/grey suede sneakers  sneakers       Black   
8645      manchester black/grey suede sneakers  sneakers       Black   
8798        manchester red/lime suede sneakers  sneakers         Red   
8888                bb3 tobacco suede sneakers  sneakers       Brown   
9379                 marc black suede sneakers  sneakers       Black   
9419               howard black suede sneakers  sneakers       Black   
9571                bb3 tobacco suede sneakers  sneakers       Brown   
9654               howard black suede sneakers  sneakers       Black   
9886          brea mandarin/gum suede sneakers  sneakers      Orange   
10047         telford xlk black suede sneakers  sneakers         Red   
10291         telford xlk black suede sneakers  sneakers         Red   
10623         telford xlk black suede sneakers  sneakers         Red   
10628     manchester black/grey suede sneakers  sneakers       Black   
10704     manchester black/grey suede sneakers  sneakers       Black   
10841         brea mandarin/gum suede sneakers  sneakers      Orange   
11422               bb3 tobacco suede sneakers  sneakers       Brown   
11757                howard red suede sneakers  sneakers         Red   
11991               bb3 tobacco suede sneakers  sneakers       Brown   
12014         telford xlk black suede sneakers  sneakers         Red   
12062       manchester red/lime suede sneakers  sneakers         Red   
12299                marc black suede sneakers  sneakers       Black   
12304               bb3 tobacco suede sneakers  sneakers       Brown   
12452         telford xlk black suede sneakers  sneakers         Red   
12551            pico grey/blue suede sneakers  sneakers  Multi,Blue   

       SalePrice  Quantity ManufacturerName  Subtotal  
199        51.47         1            Lakai     51.47  
900        46.79         2            Lakai     93.58  
1151       33.66         2            Lakai     67.32  
1608       34.03         1            Lakai     34.03  
1670       31.84         2            Lakai     63.68  
2863       51.47         2            Lakai    102.94  
2889       51.47         1            Lakai     51.47  
3006       52.63         1            Lakai     52.63  
3119       40.17         1            Lakai     40.17  
3653       32.99         1            Lakai     32.99  
3656       50.39         1            Lakai     50.39  
3767       34.77         1            Lakai     34.77  
3920       31.84         1            Lakai     31.84  
4055       52.63         1            Lakai     52.63  
4397       47.83         1            Lakai     47.83  
4430       33.94         1            Lakai     33.94  
4493       51.99         1            Lakai     51.99  
4593       34.77         1            Lakai     34.77  
4680       54.31         1            Lakai     54.31  
4693       32.66         1            Lakai     32.66  
4892       29.69         1            Lakai     29.69  
4983       47.31         2            Lakai     94.62  
5238       53.19         1            Lakai     53.19  
5790       52.07         1            Lakai     52.07  
5883       48.35         1            Lakai     48.35  
6168       35.51         1            Lakai     35.51  
6248       30.35         1            Lakai     30.35  
6505       48.35         1            Lakai     48.35  
6657       36.39         1            Lakai     36.39  
7402       55.99         1            Lakai     55.99  
8070       51.99         1            Lakai     51.99  
8335       51.51         1            Lakai     51.51  
8427       34.40         1            Lakai     34.40  
8527       48.87         1            Lakai     48.87  
8536       31.84         1            Lakai     31.84  
8585       31.49         1            Lakai     31.49  
8645       40.58         1            Lakai     40.58  
8798       32.99         1            Lakai     32.99  
8888       50.43         1            Lakai     50.43  
9379       39.99         1            Lakai     39.99  
9419       34.40         1            Lakai     34.40  
9571       50.43         1            Lakai     50.43  
9654       35.14         1            Lakai     35.14  
9886       52.63         1            Lakai     52.63  
10047      36.85         1            Lakai     36.85  
10291      36.09         1            Lakai     36.09  
10623      37.99         1            Lakai     37.99  
10628      39.76         2            Lakai     79.52  
10704      36.89         1            Lakai     36.89  
10841      52.63         1            Lakai     52.63  
11422      49.91         2            Lakai     99.82  
11757      31.49         1            Lakai     31.49  
11991      51.99         1            Lakai     51.99  
12014      37.23         1            Lakai     37.23  
12062      31.67         1            Lakai     31.67  
12299      39.59         1            Lakai     39.59  
12304      49.91         2            Lakai     99.82  
12452      34.95         1            Lakai     34.95  
12551      34.55         2            Lakai     69.10  
Manufacturer: Levi, Sum of subtotals: $2690.90.
       RowNO    SaleDate  CustomerID  FirstName    LastName  OrderID  \
25        26    1/2/2014       14473       Anne     Matheus   191239   
198      199   1/14/2014        6523     Rodger    Jamieson   191304   
798      799   2/18/2014       17919     Vaughn         Fox   191492   
1732    1733   4/18/2014        9189  Dominique        Crum   191818   
1812    1813   4/24/2014       15402      Lilia        Rose   191846   
2123    2124    5/8/2014        8090     Samira     Si-Said   191948   
2486    2487   5/28/2014        3149     Sherri     Crowder   192064   
3090    3091   6/30/2014        7038      Tyler  Livingston   192275   
3813    3814    8/6/2014        3097        Ron       Mills   192515   
3934    3935   8/12/2014       15655   Roderick      Jensen   192547   
4153    4154   8/29/2014       15439     Joseph       Smart   192624   
4541    4542   9/20/2014        9420     Tamara     Francis   192764   
4959    4960  10/13/2014        5643     Trisha        Cash   192910   
5665    5666  11/18/2014       10092  Christian        Kurz   193166   
5864    5865  11/24/2014       13155       Dave      Arnold   193235   
6229    6230   12/8/2014       11252      Brett      Landry   193359   
6854    6855  12/30/2014       11353     Jinhua        Wang   193565   
7759    7760   2/15/2015       15502      David        Rhee   193879   
7819    7820   2/17/2015       16540      Allen       Biggs   193896   
8063    8064    3/6/2015         791   Kristine       Craig   193990   
8331    8332   3/22/2015       10932      Trina        Winn   194080   
8712    8713   4/14/2015        1641       Mary     Darking   194227   
9289    9290   5/18/2015        1460       Nena         Lim   194432   
9791    9792   6/16/2015        4752    Afolabi    Adekunle   194610   
9990    9991    7/1/2015        9982     Bettie    Robinson   194682   
10315  10316   5/29/2015        1081       Opal     Delgado   194502   
10377  10378   7/18/2015        3331       Jose    Baitello   194803   
10590  10591   7/28/2015       15654       Mark   Madrilejo   194880   
10769  10770    8/5/2015       14464      Terry    Gonzalez   194944   
10971  10972   8/15/2015       13992       Joao     Furtado   195012   
11329  11330    9/3/2015        1355     Ashish      Tewary   195128   
11470  11471   9/11/2015        5135     Magnus      Ramage   195168   
12087  12088  10/11/2015       18182    Yanjuan        Yang   195348   
12359  12360  10/28/2015        5449     Philip        Ball   195441   

                         ProductName Category  Color  SalePrice  Quantity  \
25     dean leather and canvas boots    boots  Black       79.2         1   
198        sahara coated twill boots    boots  Green       68.6         1   
798        sahara coated twill boots    boots  Green       70.0         1   
1732   dean leather and canvas boots    boots  Black       77.6         1   
1812   dean leather and canvas boots    boots  Black       76.0         1   
2123       sahara coated twill boots    boots  Green       70.0         1   
2486       sahara coated twill boots    boots  Green       65.8         2   
3090   dean leather and canvas boots    boots  Black       77.6         1   
3813   dean leather and canvas boots    boots  Black       75.2         1   
3934       sahara coated twill boots    boots  Green       63.0         1   
4153   dean leather and canvas boots    boots  Black       80.0         1   
4541   dean leather and canvas boots    boots  Black       73.6         1   
4959   dean leather and canvas boots    boots  Black       76.0         1   
5665   dean leather and canvas boots    boots  Black       80.0         1   
5864       sahara coated twill boots    boots  Green       66.5         1   
6229       sahara coated twill boots    boots  Green       69.3         1   
6854       sahara coated twill boots    boots  Green       66.5         1   
7759   dean leather and canvas boots    boots  Black       80.0         1   
7819       sahara coated twill boots    boots  Green       67.2         1   
8063   dean leather and canvas boots    boots  Black       76.0         2   
8331       sahara coated twill boots    boots  Green       64.4         1   
8712       sahara coated twill boots    boots  Green       67.2         1   
9289       sahara coated twill boots    boots  Green       64.4         1   
9791   dean leather and canvas boots    boots  Black       80.0         1   
9990   dean leather and canvas boots    boots  Black       74.4         1   
10315      sahara coated twill boots    boots  Green       63.7         1   
10377      sahara coated twill boots    boots  Green       70.0         1   
10590  dean leather and canvas boots    boots  Black       74.4         1   
10769  dean leather and canvas boots    boots  Black       76.8         1   
10971      sahara coated twill boots    boots  Green       66.5         1   
11329      sahara coated twill boots    boots  Green       70.0         1   
11470      sahara coated twill boots    boots  Green       65.1         2   
12087      sahara coated twill boots    boots  Green       63.0         1   
12359      sahara coated twill boots    boots  Green       63.0         2   

      ManufacturerName  Subtotal  
25                Levi      79.2  
198               Levi      68.6  
798               Levi      70.0  
1732              Levi      77.6  
1812              Levi      76.0  
2123              Levi      70.0  
2486              Levi     131.6  
3090              Levi      77.6  
3813              Levi      75.2  
3934              Levi      63.0  
4153              Levi      80.0  
4541              Levi      73.6  
4959              Levi      76.0  
5665              Levi      80.0  
5864              Levi      66.5  
6229              Levi      69.3  
6854              Levi      66.5  
7759              Levi      80.0  
7819              Levi      67.2  
8063              Levi     152.0  
8331              Levi      64.4  
8712              Levi      67.2  
9289              Levi      64.4  
9791              Levi      80.0  
9990              Levi      74.4  
10315             Levi      63.7  
10377             Levi      70.0  
10590             Levi      74.4  
10769             Levi      76.8  
10971             Levi      66.5  
11329             Levi      70.0  
11470             Levi     130.2  
12087             Levi      63.0  
12359             Levi     126.0  
Manufacturer: Lugz, Sum of subtotals: $3254.90.
       RowNO    SaleDate  CustomerID FirstName   LastName  OrderID  \
39        40    1/3/2014         317   Alfredo     Valdez   191245   
90        91    1/5/2014       15733      Lupe    Cabrera   191261   
286      287   1/18/2014        6168     Barry      Stein   191332   
415      416   1/23/2014       10697    Stella     Mecwan   191364   
527      528   1/30/2014       13156    Jerome     Franks   191398   
...      ...         ...         ...       ...        ...      ...   
11282  11283    9/1/2015        5447   Luciano    Batista   195113   
11300  11301    9/2/2015        3808   William      Lekse   195121   
11806  11807   9/30/2015        3750    Antwan    Willard   195268   
11964  11965   10/4/2015        4303      John  Tillquist   195307   
12147  12148  10/16/2015        7831   Heather    McClain   195368   

                   ProductName  Category  Color  SalePrice  Quantity  \
39        strider ripstop shoe  sneakers  Black      40.84         1   
90     strider ripstop sneaker  sneakers   Grey      33.11         1   
286       burke lowtop sneaker  sneakers   Grey      32.33         1   
415           zrocs dx sneaker  sneakers  White      44.61         1   
527           zrocs dx sneaker  sneakers  White      44.15         2   
...                        ...       ...    ...        ...       ...   
11282     burke lowtop sneaker  sneakers   Grey      29.69         1   
11300       gypsum mid sneaker  sneakers  Olive      37.79         1   
11806       gypsum mid sneaker  sneakers  Olive      39.47         1   
11964         zrocs dx sneaker  sneakers  White      42.77         1   
12147     burke lowtop sneaker  sneakers   Grey      31.67         1   

      ManufacturerName  Subtotal  
39                Lugz     40.84  
90                Lugz     33.11  
286               Lugz     32.33  
415               Lugz     44.61  
527               Lugz     88.30  
...                ...       ...  
11282             Lugz     29.69  
11300             Lugz     37.79  
11806             Lugz     39.47  
11964             Lugz     42.77  
12147             Lugz     31.67  

[69 rows x 13 columns]
Manufacturer: Luichiny, Sum of subtotals: $2209.22.
       RowNO    SaleDate  CustomerID  FirstName    LastName  OrderID  \
322      323   1/19/2014        7170       Stan        Hahn   191342   
374      375   1/21/2014        8713     Judith       Segal   191355   
797      798   2/18/2014       17919     Vaughn         Fox   191492   
1080    1081    3/8/2014        1916     Judith    Carlisle   191587   
2920    2921   6/20/2014       13057     Aideen      Keaney   192207   
3266    3267   7/10/2014        7426      Scott        Boss   192343   
3923    3924   8/12/2014        1758      Jiunn         Lee   192545   
4087    4088   8/24/2014       17132       Gwen      Castle   192597   
4280    4281    9/7/2014        2778      Bjorn   Johansson   192677   
4313    4314    9/8/2014       15128    Antonio       Bates   192687   
4672    4673   9/29/2014        6079      Clark     Sanchez   192811   
4686    4687   9/30/2014       11967     Alisha     Belcher   192816   
5180    5181  10/25/2014        8035    Maribel      Fulton   192986   
5583    5584  11/14/2014        3119     Thomas       Kelly   193131   
5768    5769  11/22/2014       12872    Shannon     Emerson   193204   
5817    5818  11/23/2014        2517      Terri       Davis   193221   
6080    6081   12/2/2014        1082        Sri   Vasudevan   193315   
7220    7221   1/17/2015       14318       Dawn       Bruce   193690   
7435    7436   1/30/2015       13068     Ulrich       Frank   193773   
7506    7507    2/1/2015        8259      Sofia      Barker   193792   
7771    7772   2/16/2015        5012  Alexander      Oneill   193882   
7786    7787   2/16/2015       15044       Sang         Lee   193887   
8216    8217   3/15/2015        7902    Wilfred   Armstrong   194040   
8488    8489    4/2/2015        5115      Brent        West   194145   
8733    8734   4/15/2015        1827     Kirill       Yurov   194238   
9435    9436   5/26/2015        4182     Steven  Seilheimer   194480   
9502    9503   5/31/2015       12335        Ira    Rudowsky   194518   
9661    9662    6/9/2015        2766    Wilbert     Mcbride   194570   
9772    9773   6/15/2015        5077      David   Henderson   194604   
9911    9912   6/24/2015       11361      Vijay    Raghavan   194652   
10049  10050    7/4/2015       13020     Gordon      Stokes   194702   
10912  10913   8/13/2015        3176       Lars  Mathiassen   194996   
11156  11157   8/26/2015       10276      Alvin       Chang   195076   
11167  11168   8/26/2015        3258     Miguel    Martinez   195079   
11182  11183   8/27/2015       13564     Shelia    Stringer   195084   
11336  11337    9/4/2015       12338  Ernestine   Singleton   195130   
11711  11712   9/25/2015        4583     Edward    Friedman   195242   
11718  11719   9/25/2015       10619      Pearl      Ingram   195244   

                                ProductName Category         Color  SalePrice  \
322            laura jean pump w/toe detail    heels          Pink      57.99   
374            laura jean pump w/toe detail    heels          Pink      57.99   
797    falling for you studded smoking shoe    flats         Black      49.91   
1080   falling for you studded smoking shoe    flats         Black      49.39   
2920                      must be bow wedge   wedges  Brown,Orange      56.99   
3266   falling for you studded smoking shoe    flats         Black      46.79   
3923           laura jean pump w/toe detail    heels          Pink      53.35   
4087                      ready or not pump    heels         Beige      58.55   
4280                      ready or not pump    heels         Beige      58.55   
4313           laura jean pump w/toe detail    heels          Pink      52.77   
4672   falling for you studded smoking shoe    flats         Black      46.79   
4686                      ready or not pump    heels         Beige      55.50   
5180           laura jean pump w/toe detail    heels          Pink      57.99   
5583        meant to be fringe suede sandal  sandals         Beige      32.29   
5768                      ready or not pump    heels         Beige      55.50   
5817           laura jean pump w/toe detail    heels          Pink      55.09   
6080           laura jean pump w/toe detail    heels          Pink      53.93   
7220   falling for you studded smoking shoe    flats         Black      47.31   
7435   falling for you studded smoking shoe    flats         Black      48.87   
7506                      ready or not pump    heels         Beige      57.94   
7771        meant to be fringe suede sandal  sandals         Beige      30.93   
7786           laura jean pump w/toe detail    heels          Pink      56.83   
8216   falling for you studded smoking shoe    flats         Black      50.43   
8488                      ready or not pump    heels         Beige      58.55   
8733                      must be bow wedge   wedges  Brown,Orange      55.85   
9435                      must be bow wedge   wedges  Brown,Orange      55.28   
9502        meant to be fringe suede sandal  sandals         Beige      33.99   
9661           laura jean pump w/toe detail    heels          Pink      53.93   
9772                      ready or not pump    heels         Beige      56.11   
9911                      must be bow wedge   wedges  Brown,Orange      53.57   
10049  falling for you studded smoking shoe    flats         Black      50.95   
10912       meant to be fringe suede sandal  sandals         Beige      32.29   
11156  falling for you studded smoking shoe    flats         Black      49.91   
11167       meant to be fringe suede sandal  sandals         Beige      30.59   
11182                     must be bow wedge   wedges  Brown,Orange      56.99   
11336          laura jean pump w/toe detail    heels          Pink      52.19   
11711                     must be bow wedge   wedges  Brown,Orange      55.28   
11718                     must be bow wedge   wedges  Brown,Orange      51.29   

       Quantity ManufacturerName  Subtotal  
322           1         Luichiny     57.99  
374           1         Luichiny     57.99  
797           1         Luichiny     49.91  
1080          2         Luichiny     98.78  
2920          2         Luichiny    113.98  
3266          1         Luichiny     46.79  
3923          1         Luichiny     53.35  
4087          1         Luichiny     58.55  
4280          1         Luichiny     58.55  
4313          1         Luichiny     52.77  
4672          1         Luichiny     46.79  
4686          2         Luichiny    111.00  
5180          1         Luichiny     57.99  
5583          1         Luichiny     32.29  
5768          1         Luichiny     55.50  
5817          1         Luichiny     55.09  
6080          1         Luichiny     53.93  
7220          1         Luichiny     47.31  
7435          1         Luichiny     48.87  
7506          2         Luichiny    115.88  
7771          1         Luichiny     30.93  
7786          1         Luichiny     56.83  
8216          1         Luichiny     50.43  
8488          1         Luichiny     58.55  
8733          1         Luichiny     55.85  
9435          1         Luichiny     55.28  
9502          1         Luichiny     33.99  
9661          1         Luichiny     53.93  
9772          1         Luichiny     56.11  
9911          1         Luichiny     53.57  
10049         2         Luichiny    101.90  
10912         1         Luichiny     32.29  
11156         1         Luichiny     49.91  
11167         1         Luichiny     30.59  
11182         1         Luichiny     56.99  
11336         1         Luichiny     52.19  
11711         1         Luichiny     55.28  
11718         1         Luichiny     51.29  
Manufacturer: MO7, Sum of subtotals: $329.64.
       RowNO    SaleDate  CustomerID  FirstName    LastName  OrderID  \
454      455   1/25/2014       15635      Viola       Dixon   191376   
3053    3054   6/29/2014       10975        Jan      Seruga   192257   
3226    3227    7/6/2014        9029        Ian      Searle   192328   
3853    3854   8/10/2014       14830      Steve        Hunt   192530   
5633    5634  11/16/2014       11281       Dora      Norris   193146   
6800    6801  12/28/2014       14535     Angelo       Hicks   193551   
7102    7103   1/10/2015        1224      Kevin        Ryan   193642   
8466    8467   3/30/2015       11405       Theo     Renkema   194135   
8732    8733   4/15/2015        7526     Nestor      Deleon   194237   
9436    9437   5/26/2015        4182     Steven  Seilheimer   194480   
10106  10107    7/7/2015        9782  Gwendolyn       Watts   194724   
10312  10313   5/29/2015       17387      Clyde       Bynum   194501   
10442  10443   7/21/2015        3218    Loretta    Trujillo   194831   
11429  11430    9/9/2015       11411      Gregg       Welch   195158   

                                         ProductName  Category   Color  \
454    the canon outdoor boot w/ faux fur insulation     boots   Brown   
3053                     the swagger hightop sneaker  sneakers  Silver   
3226                     the swagger hightop sneaker  sneakers  Silver   
3853                     the swagger hightop sneaker  sneakers  Silver   
5633                     the swagger hightop sneaker  sneakers  Silver   
6800   the canon outdoor boot w/ faux fur insulation     boots   Brown   
7102                         the fly hightop sneaker  sneakers   Black   
8466                     the swagger hightop sneaker  sneakers  Silver   
8732                     the swagger hightop sneaker  sneakers  Silver   
9436                     the swagger hightop sneaker  sneakers  Silver   
10106                    the swagger hightop sneaker  sneakers  Silver   
10312  the canon outdoor boot w/ faux fur insulation     boots   Brown   
10442                    the swagger hightop sneaker  sneakers  Silver   
11429                    the swagger hightop sneaker  sneakers  Silver   

       SalePrice  Quantity ManufacturerName  Subtotal  
454        34.19         1              MO7     34.19  
3053       17.66         2              MO7     35.32  
3226       18.99         1              MO7     18.99  
3853       17.66         1              MO7     17.66  
5633       18.42         1              MO7     18.42  
6800       32.75         1              MO7     32.75  
7102       11.82         1              MO7     11.82  
8466       18.04         2              MO7     36.08  
8732       17.28         1              MO7     17.28  
9436       18.99         1              MO7     18.99  
10106      18.23         1              MO7     18.23  
10312      33.83         1              MO7     33.83  
10442      17.28         1              MO7     17.28  
11429      18.80         1              MO7     18.80  
Manufacturer: Mecca, Sum of subtotals: $787.35.
       RowNO    SaleDate  CustomerID  FirstName    LastName  OrderID  \
68        69    1/4/2014       17996     Palter       Dobay   191254   
721      722   2/15/2014        9603      Peter       Nyame   191468   
789      790   2/18/2014       10950     Brooke       Nance   191490   
1133    1134   3/12/2014        2875     Shafiz       Yusof   191608   
1919    1920   4/29/2014        9325      Tanya     Gilliam   191881   
2589    2590    6/1/2014       12911       Jung        Choi   192100   
2724    2725    6/7/2014       13925   Gertrude       Walls   192137   
3288    3289   7/11/2014       15437      Craig  Carmichael   192349   
3322    3323   7/12/2014       10665     Marvin      Flores   192358   
3388    3389   7/15/2014       12508     Wesley         Shu   192378   
3444    3445   7/17/2014       16862     Bonnie     Blevins   192394   
3605    3606   7/26/2014        2856      Frank     Roberts   192450   
3655    3656   7/28/2014         656     Julian     Newsome   192465   
3762    3763    8/4/2014       16334     Paulus     Santosa   192495   
3915    3916   8/11/2014       13317    Kenneth       Kozar   192543   
4302    4303    9/8/2014       11411      Gregg       Welch   192683   
4660    4661   9/29/2014       13836     Mathew    Anderson   192805   
4695    4696   10/1/2014        8977      Madhu       Reddy   192822   
4762    4763   10/4/2014       16004   Christer   Ljungberg   192842   
5220    5221  10/26/2014       11788     Genaro    Caldwell   192997   
5279    5280  10/30/2014        2103      Vijay   Mookerjee   193018   
5462    5463   11/8/2014       17132       Gwen      Castle   193090   
5552    5553  11/13/2014       17778     Xinlin        Tang   193120   
5647    5648  11/17/2014       14695        Ewa   Zimmerman   193153   
5702    5703  11/19/2014        4186        Ake    Gronlund   193176   
5926    5927  11/26/2014       17782   Garfield      Guzman   193256   
6104    6105   12/3/2014        3258     Miguel    Martinez   193324   
6418    6419  12/14/2014        1130      Trent      Gentry   193426   
6691    6692  12/25/2014       12865      Janie      Harvey   193517   
7059    7060    1/7/2015       16355       Olga     Petkova   193628   
7300    7301   1/23/2015       14228      Bryan       Parks   193720   
7472    7473   1/31/2015        6845     Adrian   Schneider   193783   
7661    7662    2/9/2015       11316    Kenneth     Trimmer   193844   
7689    7690   2/11/2015        8334    Maritza      Dotson   193859   
7736    7737   2/15/2015         267  Athanasia    Pouloudi   193874   
7990    7991    3/2/2015        5548      Clair      Snider   193959   
8284    8285   3/20/2015        5278   Hiroyuki    Tokuyama   194067   
8414    8415   3/29/2015        3991   Angelica      Golden   194118   
8513    8514    4/4/2015       17553    Kenneth        Kemp   194155   
8708    8709   4/14/2015        1641       Mary     Darking   194227   
8846    8847   4/23/2015       12037      Heath      Davila   194278   
8934    8935   4/28/2015       12352    Yinghui        Yang   194310   
8987    8988    5/2/2015        3358        Wei         Yue   194335   
9378    9379   5/22/2015        7761     Philip       Yates   194463   
9500    9501   5/31/2015       15796    Hsin-Lu       Chang   194517   
9526    9527    6/1/2015        7709       Josh      Palmer   194527   
9565    9566    6/4/2015         144     Murray      Turoff   194542   
9695    9696   6/11/2015       11331       Cleo       Lewis   194581   
9992    9993    7/1/2015       10483      Julio       Keith   194683   
10165  10166   7/11/2015        3008       Kirk   Jaramillo   194749   
11083  11084   8/21/2015       10077     Rickey    Holloway   195049   
11234  11235   8/30/2015         791   Kristine       Craig   195097   
11332  11333    9/4/2015       12338  Ernestine   Singleton   195130   
11695  11696   9/24/2015       18185      Freda        Weir   195236   
11720  11721   9/25/2015       10619      Pearl      Ingram   195244   
11859  11860   10/1/2015        1695   Vincenzo    D'Andrea   195284   

                         ProductName  Category       Color  SalePrice  \
68         mecca low profile sneaker  sneakers       White      10.44   
721           jackson midtop sneaker  sneakers       Black      12.99   
789        boxer low profile sneaker  sneakers   Red,Black      14.71   
1133          jackson midtop sneaker  sneakers       Black      11.82   
1919       sneak low profile sneaker  sneakers       Black      14.55   
2589          jackson midtop sneaker  sneakers       Black      12.21   
2724       sneak low profile sneaker  sneakers       Black      14.55   
3288        sean low profile sneaker  sneakers  Gold,Black       7.99   
3322        sean low profile sneaker  sneakers  Gold,Black       7.43   
3388                mecca 1 sneakers  sneakers       Black       8.18   
3444   sneak high midprofile sneaker  sneakers         Red      19.99   
3605   sneak high midprofile sneaker  sneakers         Red      19.59   
3655       sonny low profile sneaker  sneakers       Black      10.99   
3762        sean low profile sneaker  sneakers  Gold,Black       7.91   
3915          jackson midtop sneaker  sneakers       Black      12.99   
4302       boxer low profile sneaker  sneakers   Red,Black      15.67   
4660        sean low profile sneaker  sneakers  Gold,Black       7.51   
4695      marvin low profile sneaker  sneakers       Black      10.99   
4762        sean low profile sneaker  sneakers  Gold,Black       7.67   
5220          jackson midtop sneaker  sneakers       Black      11.95   
5279      marvin low profile sneaker  sneakers       Black      10.00   
5462        sean low profile sneaker  sneakers  Gold,Black       7.43   
5552       zeus low profile sneakers  sneakers       Black      13.43   
5647       boxer low profile sneaker  sneakers   Red,Black      14.55   
5702       sneak low profile sneaker  sneakers       Black      15.51   
5926       sneak low profile sneaker  sneakers       Black      14.39   
6104          jackson midtop sneaker  sneakers       Black      12.73   
6418      marvin low profile sneaker  sneakers       Black      10.00   
6691       sneak low profile sneaker  sneakers       Black      15.99   
7059          jackson midtop sneaker  sneakers       Black      11.82   
7300          jackson midtop sneaker  sneakers       Black      12.86   
7472       sneak low profile sneaker  sneakers       Black      15.99   
7661      marvin low profile sneaker  sneakers       Black      10.99   
7689   sneak high midprofile sneaker  sneakers         Red      18.39   
7736          jackson midtop sneaker  sneakers       Black      12.21   
7990       mecca low profile sneaker  sneakers       White      10.99   
8284       sonny low profile sneaker  sneakers       Black      10.55   
8414      marvin low profile sneaker  sneakers       Black      10.44   
8513          jackson midtop sneaker  sneakers       Black      12.34   
8708       boxer low profile sneaker  sneakers   Red,Black      14.71   
8846        sean low profile sneaker  sneakers  Gold,Black       7.59   
8934        sean low profile sneaker  sneakers  Gold,Black       7.91   
8987        sean low profile sneaker  sneakers  Gold,Black       7.99   
9378          jackson midtop sneaker  sneakers       Black      12.99   
9500   sneak high midprofile sneaker  sneakers         Red      19.19   
9526       sneak low profile sneaker  sneakers       Black      14.71   
9565          jackson midtop sneaker  sneakers       Black      12.73   
9695       boxer low profile sneaker  sneakers   Red,Black      15.19   
9992       boxer low profile sneaker  sneakers   Red,Black      15.19   
10165      boxer low profile sneaker  sneakers   Red,Black      15.35   
11083      sneak low profile sneaker  sneakers       Black      14.55   
11234  sneak high midprofile sneaker  sneakers         Red      18.59   
11332      boxer low profile sneaker  sneakers   Red,Black      15.03   
11695         jackson midtop sneaker  sneakers       Black      11.69   
11720      sonny low profile sneaker  sneakers       Black      10.33   
11859         jackson midtop sneaker  sneakers       Black      12.73   

       Quantity ManufacturerName  Subtotal  
68            2            Mecca     20.88  
721           1            Mecca     12.99  
789           1            Mecca     14.71  
1133          1            Mecca     11.82  
1919          1            Mecca     14.55  
2589          2            Mecca     24.42  
2724          1            Mecca     14.55  
3288          2            Mecca     15.98  
3322          1            Mecca      7.43  
3388          1            Mecca      8.18  
3444          1            Mecca     19.99  
3605          1            Mecca     19.59  
3655          1            Mecca     10.99  
3762          1            Mecca      7.91  
3915          1            Mecca     12.99  
4302          1            Mecca     15.67  
4660          2            Mecca     15.02  
4695          1            Mecca     10.99  
4762          2            Mecca     15.34  
5220          1            Mecca     11.95  
5279          1            Mecca     10.00  
5462          1            Mecca      7.43  
5552          1            Mecca     13.43  
5647          1            Mecca     14.55  
5702          1            Mecca     15.51  
5926          2            Mecca     28.78  
6104          1            Mecca     12.73  
6418          1            Mecca     10.00  
6691          1            Mecca     15.99  
7059          1            Mecca     11.82  
7300          1            Mecca     12.86  
7472          1            Mecca     15.99  
7661          1            Mecca     10.99  
7689          1            Mecca     18.39  
7736          1            Mecca     12.21  
7990          1            Mecca     10.99  
8284          1            Mecca     10.55  
8414          1            Mecca     10.44  
8513          2            Mecca     24.68  
8708          1            Mecca     14.71  
8846          2            Mecca     15.18  
8934          1            Mecca      7.91  
8987          1            Mecca      7.99  
9378          1            Mecca     12.99  
9500          1            Mecca     19.19  
9526          1            Mecca     14.71  
9565          1            Mecca     12.73  
9695          1            Mecca     15.19  
9992          1            Mecca     15.19  
10165         1            Mecca     15.35  
11083         1            Mecca     14.55  
11234         1            Mecca     18.59  
11332         1            Mecca     15.03  
11695         1            Mecca     11.69  
11720         1            Mecca     10.33  
11859         1            Mecca     12.73  
Manufacturer: Mountain Gear, Sum of subtotals: $93.43.
       RowNO   SaleDate  CustomerID FirstName LastName  OrderID  \
405      406  1/23/2014       11796    Kelsey   Franks   191363   
4251    4252   9/4/2014        5408    Robert   Denker   192663   
10998  10999  8/17/2015        2547     Jerry   Flatto   195020   

                    ProductName Category       Color  SalePrice  Quantity  \
405     anvil mid mountain boot    boots       Black      24.24         1   
4251     viper le mountain boot    boots       Black      39.12         1   
10998  rugger mid mountain boot    boots  Black,Grey      30.07         1   

      ManufacturerName  Subtotal  
405      Mountain Gear     24.24  
4251     Mountain Gear     39.12  
10998    Mountain Gear     30.07  
Manufacturer: New Balance, Sum of subtotals: $8860.22.
       RowNO    SaleDate  CustomerID FirstName    LastName  OrderID  \
501      502   1/28/2014        1606    Evelyn      Holman   191394   
739      740   2/16/2014         675   Uchenna          Sr   191473   
842      843   2/22/2014       10973    Donald      Payton   191506   
1054    1055    3/5/2014        5107     Mehdi  Beheshtian   191578   
1281    1282   3/22/2014        1535       Gus       Major   191661   
...      ...         ...         ...       ...         ...      ...   
12158  12159  10/17/2015       10937      Rene     Andrade   195372   
12267  12268  10/22/2015        4430    Andrea    Carugati   195413   
12381  12382  10/30/2015        1972    Cecile    Clergeau   195450   
12477  12478   11/4/2015        1391  Theodore     Glasser   195479   
12481  12482   11/4/2015        4616   Leticia       Heard   195480   

                            ProductName  Category   Color  SalePrice  \
501             574 yacht club sneakers  sneakers   Black      74.95   
739             574 yacht club sneakers  sneakers   Black      68.20   
842             574 yacht club sneakers  sneakers   Black      68.20   
1054           w1080v3 running sneakers  sneakers  Silver     108.90   
1281   women's windbreaker 574 sneakers  sneakers  Purple      68.60   
...                                 ...       ...     ...        ...   
12158            574 core plus sneakers  sneakers   Black      68.95   
12267  women's windbreaker 574 sneakers  sneakers  Purple      63.00   
12381          574 windbreaker sneakers  sneakers   Black      71.20   
12477  women's windbreaker 574 sneakers  sneakers  Purple      63.00   
12481          w1080v3 running sneakers  sneakers  Silver     108.90   

       Quantity ManufacturerName  Subtotal  
501           1      New Balance     74.95  
739           1      New Balance     68.20  
842           1      New Balance     68.20  
1054          1      New Balance    108.90  
1281          1      New Balance     68.60  
...         ...              ...       ...  
12158         2      New Balance    137.90  
12267         2      New Balance    126.00  
12381         1      New Balance     71.20  
12477         1      New Balance     63.00  
12481         1      New Balance    108.90  

[101 rows x 13 columns]
Manufacturer: Nike, Sum of subtotals: $109599.57.
       RowNO    SaleDate  CustomerID FirstName  LastName  OrderID  \
2          3  12/31/2013        1134   Xiafeng      Wang   191228   
22        23    1/2/2014         653      John   Hebeler   191238   
33        34    1/2/2014        3852    Billie    Hunter   191242   
45        46    1/3/2014        5054      Ravi   Vatrapu   191247   
64        65    1/4/2014       14209   Hartmut    Hoehle   191252   
...      ...         ...         ...       ...       ...      ...   
12533  12534   11/6/2015        2682  Paulette     Horne   195495   
12540  12541   11/7/2015       14901     Penny     Boyce   195498   
12545  12546   11/7/2015       10779    Ismael  Mcintyre   195499   
12565  12566   11/7/2015        9345    Lorene   Charles   195505   
12568  12569   11/7/2015        9345    Lorene   Charles   195505   

                               ProductName  Category              Color  \
2          nike air max correlate sneakers  sneakers              Black   
22             nike lunar edge 15 sneakers  sneakers                Red   
33                air pegasus +29 sneakers  sneakers               Blue   
45              nike zoom elite + sneakers  sneakers  Yellow,Lime Green   
64         nike air max correlate sneakers  sneakers              Black   
...                                    ...       ...                ...   
12533       sweet classic premium sneakers  sneakers               Grey   
12540       sweet classic premium sneakers  sneakers               Grey   
12545              nike lunar tr1 sneakers  sneakers              Black   
12565             nike flight one sneakers  sneakers              White   
12568  wmns sweet classic leather sneakers  sneakers              Black   

       SalePrice  Quantity ManufacturerName  Subtotal  
2          96.60         1             Nike     96.60  
22         63.99         2             Nike    127.98  
33         80.90         1             Nike     80.90  
45         59.14         1             Nike     59.14  
64        105.00         1             Nike    105.00  
...          ...       ...              ...       ...  
12533      71.28         1             Nike     71.28  
12540      72.00         1             Nike     72.00  
12545      77.99         1             Nike     77.99  
12565      84.63         1             Nike     84.63  
12568      50.39         1             Nike     50.39  

[1314 rows x 13 columns]
Manufacturer: Not Rated, Sum of subtotals: $2122.30.
       RowNO    SaleDate  CustomerID  FirstName   LastName  OrderID  \
364      365   1/21/2014        1002      Angel    Salazar   191352   
592      593    2/6/2014        2441    Bridget       Kane   191426   
754      755   2/16/2014        3577      Sarah       Fish   191478   
1124    1125   3/12/2014       16878       Ross       Hyde   191605   
1309    1310   3/24/2014       16655    Mohamad     Saraee   191676   
1634    1635   4/12/2014        9843   Myungsin       Chae   191782   
1945    1946    5/1/2014       15733       Lupe    Cabrera   191895   
2037    2038    5/4/2014        8040     Blanca    Winston   191926   
2597    2598    6/2/2014       16771     Willie      Eaton   192103   
3082    3083   6/30/2014       17437       Heng         Xu   192274   
3502    3503   7/21/2014        6219      Oscar      Mills   192415   
3546    3547   7/23/2014       15420     Miguel      Nolan   192427   
3635    3636   7/28/2014        9957      Abram      Moody   192460   
3738    3739    8/3/2014         697      Carol   Abatelli   192491   
4560    4561   9/22/2014         660    Jeannie     Murphy   192770   
4932    4933  10/12/2014       11018       Mary       Lind   192902   
5088    5089  10/21/2014         367       Andy  Mcdonough   192957   
5937    5938  11/27/2014       15163     Dalton    Hopkins   193259   
6264    6265   12/9/2014        9982     Bettie   Robinson   193366   
6688    6689  12/25/2014       12865      Janie     Harvey   193517   
6838    6839  12/30/2014       12910     Eugene  Rathswohl   193563   
6903    6904  12/31/2014       12393  Elisabeth   Townsend   193579   
6963    6964    1/2/2015        9252     Magnus  Andersson   193596   
7159    7160   1/14/2015        2905      Henry      Foley   193666   
7478    7479   1/31/2015       18001   Jonathan     Trower   193784   
8003    8004    3/2/2015        5425     Darren     Dawson   193962   
8112    8113   3/10/2015       16638        Guy      Gable   194007   
8197    8198   3/15/2015         812     Delmar    Ramirez   194037   
8366    8367   3/26/2015        8954       Jack      Zheng   194096   
8489    8490    4/2/2015        5115      Brent       West   194145   
8500    8501    4/3/2015       15439     Joseph      Smart   194150   
8560    8561    4/6/2015        6074        Ian     Parkin   194168   
8644    8645    4/9/2015        5240        Pat     Palmer   194198   
9072    9073    5/6/2015        7035        Jun       Yuan   194363   
9396    9397   5/24/2015       16445      Agnes    Simmons   194469   
10602  10603   7/28/2015        5026      Kevin   Kobelsky   194883   
10742  10743    8/4/2015       10910    Chester    Hickman   194934   
11201  11202   8/29/2015        7709       Josh     Palmer   195089   
11350  11351    9/4/2015       13662       Pete    Holland   195137   
11607  11608   9/18/2015       12849      Paige   Fletcher   195209   
12003  12004   10/6/2015        3097        Ron      Mills   195320   
12527  12528   11/6/2015       15123         Jo    Smedley   195494   

                                   ProductName Category        Color  \
364    americana print espadrille wedge sandal  sandals     Blue,Red   
592              braided platform wedge sandal  sandals        Black   
754              braided platform wedge sandal  sandals        Black   
1124       bordeline fancy lace up oxford shoe    flats  Black,White   
1309   americana print espadrille wedge sandal  sandals     Blue,Red   
1634             shiny animal print comfy flat    flats         Gold   
1945   americana print espadrille wedge sandal  sandals     Blue,Red   
2037     graphic print espadrille wedge sandal  sandals        Black   
2597             shiny animal print comfy flat    flats         Gold   
3082       bordeline fancy lace up oxford shoe    flats  Black,White   
3502   americana print espadrille wedge sandal  sandals     Blue,Red   
3546     graphic print espadrille wedge sandal  sandals        Black   
3635   americana print espadrille wedge sandal  sandals     Blue,Red   
3738             braided platform wedge sandal  sandals        Black   
4560       bordeline fancy lace up oxford shoe    flats  Black,White   
4932       bordeline fancy lace up oxford shoe    flats  Black,White   
5088     graphic print espadrille wedge sandal  sandals        Black   
5937             shiny animal print comfy flat    flats         Gold   
6264     graphic print espadrille wedge sandal  sandals        Black   
6688     graphic print espadrille wedge sandal  sandals        Black   
6838     graphic print espadrille wedge sandal  sandals        Black   
6903             shiny animal print comfy flat    flats         Gold   
6963   americana print espadrille wedge sandal  sandals     Blue,Red   
7159             braided platform wedge sandal  sandals        Black   
7478             shiny animal print comfy flat    flats         Gold   
8003   americana print espadrille wedge sandal  sandals     Blue,Red   
8112             braided platform wedge sandal  sandals        Black   
8197       bordeline fancy lace up oxford shoe    flats  Black,White   
8366             braided platform wedge sandal  sandals        Black   
8489             shiny animal print comfy flat    flats         Gold   
8500             shiny animal print comfy flat    flats         Gold   
8560   americana print espadrille wedge sandal  sandals     Blue,Red   
8644       bordeline fancy lace up oxford shoe    flats  Black,White   
9072       bordeline fancy lace up oxford shoe    flats  Black,White   
9396             shiny animal print comfy flat    flats         Gold   
10602      bordeline fancy lace up oxford shoe    flats  Black,White   
10742            shiny animal print comfy flat    flats         Gold   
11201      bordeline fancy lace up oxford shoe    flats  Black,White   
11350    graphic print espadrille wedge sandal  sandals        Black   
11607      bordeline fancy lace up oxford shoe    flats  Black,White   
12003            shiny animal print comfy flat    flats         Gold   
12527            shiny animal print comfy flat    flats         Gold   

       SalePrice  Quantity ManufacturerName  Subtotal  
364        43.69         1        Not Rated     43.69  
592        56.40         1        Not Rated     56.40  
754        55.20         1        Not Rated     55.20  
1124       35.99         1        Not Rated     35.99  
1309       44.15         1        Not Rated     44.15  
1634       35.27         1        Not Rated     35.27  
1945       42.77         1        Not Rated     42.77  
2037       45.99         1        Not Rated     45.99  
2597       33.47         1        Not Rated     33.47  
3082       39.99         2        Not Rated     79.98  
3502       45.99         1        Not Rated     45.99  
3546       41.39         1        Not Rated     41.39  
3635       41.39         1        Not Rated     41.39  
3738       55.20         1        Not Rated     55.20  
4560       35.99         1        Not Rated     35.99  
4932       37.19         1        Not Rated     37.19  
5088       44.15         1        Not Rated     44.15  
5937       32.39         1        Not Rated     32.39  
6264       43.23         1        Not Rated     43.23  
6688       44.15         2        Not Rated     88.30  
6838       45.53         1        Not Rated     45.53  
6903       34.91         2        Not Rated     69.82  
6963       45.53         1        Not Rated     45.53  
7159       58.20         1        Not Rated     58.20  
7478       33.11         1        Not Rated     33.11  
8003       44.15         1        Not Rated     44.15  
8112       58.80         2        Not Rated    117.60  
8197       39.59         1        Not Rated     39.59  
8366       60.00         2        Not Rated    120.00  
8489       34.55         1        Not Rated     34.55  
8500       33.47         1        Not Rated     33.47  
8560       45.99         2        Not Rated     91.98  
8644       39.59         2        Not Rated     79.18  
9072       37.99         2        Not Rated     75.98  
9396       34.19         1        Not Rated     34.19  
10602      37.59         1        Not Rated     37.59  
10742      34.91         1        Not Rated     34.91  
11201      38.79         1        Not Rated     38.79  
11350      44.15         1        Not Rated     44.15  
11607      39.99         1        Not Rated     39.99  
12003      33.47         1        Not Rated     33.47  
12527      32.39         1        Not Rated     32.39  
Manufacturer: Osiris, Sum of subtotals: $28991.08.
       RowNO   SaleDate  CustomerID FirstName     LastName  OrderID  \
8          9   1/1/2014       11852       Ken        Carey   191232   
29        30   1/2/2014        3724    Jarrod        Moran   191241   
35        36   1/2/2014        3852    Billie       Hunter   191242   
49        50   1/3/2014        3325    Jeffry         Babb   191248   
143      144   1/8/2014       10345     Royce        Seals   191280   
...      ...        ...         ...       ...          ...      ...   
12493  12494  11/4/2015        5509   Colleen         Page   195482   
12505  12506  11/5/2015        2400      Ross        Oneal   195485   
12516  12517  11/5/2015       16836       Joe  Nandhakumar   195488   
12535  12536  11/6/2015       11505      Joan        Ayala   195496   
12558  12559  11/7/2015       11921   Tabitha        James   195502   

                         ProductName  Category       Color  SalePrice  \
8                nyc 83 vlc sneakers  sneakers       Black      72.00   
29                   effect sneakers  sneakers       Black      47.93   
35                   nyc 83 sneakers  sneakers       Black      77.60   
49                     mith sneakers  sneakers       Black      31.35   
143              nyc 83 vlc sneakers  sneakers       Black      68.25   
...                              ...       ...         ...        ...   
12493                nyc 83 sneakers  sneakers       Black      77.60   
12505  nyc 83 mid shearling sneakers  sneakers   Black,Red      48.50   
12516            nyc 83 vlc sneakers  sneakers       Black      70.50   
12535               grounds sneakers  sneakers  Black,Teal      37.23   
12558            nyc 83 vlc sneakers  sneakers       Black      75.00   

       Quantity ManufacturerName  Subtotal  
8             1           Osiris     72.00  
29            1           Osiris     47.93  
35            2           Osiris    155.20  
49            1           Osiris     31.35  
143           1           Osiris     68.25  
...         ...              ...       ...  
12493         1           Osiris     77.60  
12505         1           Osiris     48.50  
12516         2           Osiris    141.00  
12535         2           Osiris     74.46  
12558         1           Osiris     75.00  

[392 rows x 13 columns]
Manufacturer: Pastry, Sum of subtotals: $2817.22.
       RowNO    SaleDate  CustomerID   FirstName     LastName  OrderID  \
914      915   2/28/2014       17048       Melba     Villegas   191531   
1036    1037    3/5/2014        4378       Cheri        Duffy   191574   
1318    1319   3/25/2014        9846        Wade     Harrison   191678   
1363    1364   3/30/2014        7194      Luther       Lovett   191694   
1509    1510    4/5/2014        3788      Amanda  Witherspoon   191736   
2168    2169   5/11/2014        2723      Beulah         Hurd   191961   
2249    2250   5/16/2014        2118       Dezhi           Wu   191989   
2782    2783   6/10/2014       12327      Robert         Keim   192154   
2932    2933   6/20/2014       16320     Hyunjoo           Oh   192211   
3527    3528   7/22/2014        2064     Jae-Nam          Lee   192422   
3529    3530   7/22/2014        2064     Jae-Nam          Lee   192422   
4165    4166   8/30/2014        4803      Josiah        Mills   192629   
4360    4361   9/12/2014        5984     Charles        Chong   192704   
4361    4362   9/12/2014        5984     Charles        Chong   192704   
4509    4510   9/18/2014        8716       Lynne      Garrett   192755   
4810    4811   10/7/2014       10324  Abdelmalek     Boularas   192861   
4904    4905  10/11/2014         189     Ibrahim      Kushchu   192892   
5134    5135  10/23/2014       12345      Martin         West   192972   
5642    5643  11/16/2014        2609       Rajiv       Banker   193150   
5739    5740  11/20/2014       12749       Brady      Mcgowan   193190   
6072    6073   12/2/2014        2185    Nicholas      Conrads   193312   
6138    6139   12/4/2014        2261        Sara       Talley   193332   
6598    6599  12/20/2014        1224       Kevin         Ryan   193481   
6858    6859  12/30/2014       11536        Yong         Yeow   193567   
7653    7654    2/8/2015        7095        Jack        Gowan   193836   
7792    7793   2/16/2015       13327   Prabuddha           De   193888   
7941    7942   2/26/2015        5163   Gwendolyn        House   193940   
7972    7973   2/28/2015        1385       Peter        Pille   193952   
8075    8076    3/7/2015        5733     Claudia        Hicks   193994   
8121    8122   3/10/2015        6599       Brett       Ladner   194008   
8184    8185   3/15/2015        1744   Matthaeus     Sielecki   194032   
8523    8524    4/4/2015        2096       Ralph   Sutherland   194156   
9139    9140   5/10/2015        4537       Young         Park   194383   
9140    9141   5/10/2015        4537       Young         Park   194383   
9316    9317   5/19/2015       11759   Rigoberto         Pace   194443   
9322    9323   5/20/2015        7199        Mike      Uretsky   194445   
9684    9685   6/10/2015       12077      Damion      Simmons   194576   
10098  10099    7/7/2015       17616     Aurelio      Cornett   194718   
10154  10155   7/10/2015        3804       Grant      Barnett   194743   
10338  10339   5/30/2015        8350       Kevin        Duffy   194509   
10463  10464   7/22/2015        7056   Guadalupe         Soto   194838   
10565  10566   7/26/2015       11299      Edmond     Triplett   194871   
10643  10644   7/30/2015       11056        Otha       Garcia   194898   
10844  10845    8/9/2015          47       Penny       Patton   194972   
10855  10856   8/10/2015        5095        John      Bradley   194975   
11013  11014   8/17/2015         505  Jacqueline       Cooper   195025   
11031  11032   8/18/2015        8033       Frank      Beasley   195030   
11038  11039   8/18/2015       17939     Christy     Cummings   195031   
11380  11381    9/6/2015        9969        Jian           Ma   195145   
11669  11670   9/23/2015        5510        Jose         Kern   195228   
11822  11823   9/30/2015         402     Emanuel       Jacobs   195273   
11982  11983   10/5/2015       17132        Gwen       Castle   195314   
12348  12349  10/27/2015       16495      Doreen  Christopher   195438   

                         ProductName  Category             Color  SalePrice  \
914            strudel wedge sneaker  sneakers             Black      54.60   
1036   pop tart strap spikes sneaker  sneakers             Black      50.99   
1318           strudel wedge sneaker  sneakers             Black      60.00   
1363   pop tart strap spikes sneaker  sneakers             Black      45.89   
1509         cosmic mid cool sneaker  sneakers             Black      52.99   
2168       sugar rush spikes sneaker  sneakers  Animal Print,Tan      60.00   
2249   pop tart strap spikes sneaker  sneakers             Black      50.48   
2782           strudel wedge sneaker  sneakers             Black      57.00   
2932           strudel wedge sneaker  sneakers             Black      60.00   
3527         cosmic mid cool sneaker  sneakers             Black      51.40   
3529         parfait quilted sneaker  sneakers             Black      42.56   
4165         parfait quilted sneaker  sneakers             Black      39.55   
4360         cosmic mid cool sneaker  sneakers             Black      51.40   
4361         cosmic mid cool sneaker  sneakers             Black      51.40   
4509           strudel wedge sneaker  sneakers             Black      58.20   
4810         cosmic mid cool sneaker  sneakers             Black      49.81   
4904         cosmic mid cool sneaker  sneakers             Black      52.46   
5134         cosmic mid cool sneaker  sneakers             Black      52.99   
5642      sire varsity sheek sneaker  sneakers             Black      42.13   
5739      sire varsity sheek sneaker  sneakers             Black      42.13   
6072           strudel wedge sneaker  sneakers             Black      59.40   
6138           strudel wedge sneaker  sneakers             Black      54.60   
6598   pop tart strap spikes sneaker  sneakers             Black      49.46   
6858         parfait quilted sneaker  sneakers             Black      40.41   
7653   pop tart strap spikes sneaker  sneakers             Black      46.40   
7792         cosmic mid cool sneaker  sneakers             Black      47.69   
7941         cosmic mid cool sneaker  sneakers             Black      49.28   
7972           strudel wedge sneaker  sneakers             Black      60.00   
8075       sugar rush spikes sneaker  sneakers  Animal Print,Tan      60.00   
8121           strudel wedge sneaker  sneakers             Black      57.60   
8184   pop tart strap spikes sneaker  sneakers             Black      49.46   
8523      sire varsity sheek sneaker  sneakers             Black      40.84   
9139         parfait quilted sneaker  sneakers             Black      42.56   
9140       sire varsity punk sneaker  sneakers            Silver      55.80   
9316       sugar rush spikes sneaker  sneakers  Animal Print,Tan      57.00   
9322   pop tart strap spikes sneaker  sneakers             Black      47.42   
9684           strudel wedge sneaker  sneakers             Black      58.80   
10098     sire varsity sheek sneaker  sneakers             Black      39.55   
10154  pop tart strap spikes sneaker  sneakers             Black      49.97   
10338     sire varsity sheek sneaker  sneakers             Black      40.84   
10463  pop tart strap spikes sneaker  sneakers             Black      46.40   
10565  pop tart strap spikes sneaker  sneakers             Black      50.48   
10643          strudel wedge sneaker  sneakers             Black      60.00   
10844          strudel wedge sneaker  sneakers             Black      56.40   
10855     sire varsity sheek sneaker  sneakers             Black      42.99   
11013     sire varsity sheek sneaker  sneakers             Black      42.99   
11031        cosmic mid cool sneaker  sneakers             Black      49.28   
11038          strudel wedge sneaker  sneakers             Black      55.80   
11380        parfait quilted sneaker  sneakers             Black      42.99   
11669        cosmic mid cool sneaker  sneakers             Black      51.93   
11822          strudel wedge sneaker  sneakers             Black      59.40   
11982        parfait quilted sneaker  sneakers             Black      42.99   
12348     sire varsity sheek sneaker  sneakers             Black      41.70   

       Quantity ManufacturerName  Subtotal  
914           1           Pastry     54.60  
1036          1           Pastry     50.99  
1318          1           Pastry     60.00  
1363          2           Pastry     91.78  
1509          1           Pastry     52.99  
2168          1           Pastry     60.00  
2249          1           Pastry     50.48  
2782          1           Pastry     57.00  
2932          1           Pastry     60.00  
3527          1           Pastry     51.40  
3529          1           Pastry     42.56  
4165          1           Pastry     39.55  
4360          1           Pastry     51.40  
4361          1           Pastry     51.40  
4509          1           Pastry     58.20  
4810          1           Pastry     49.81  
4904          1           Pastry     52.46  
5134          1           Pastry     52.99  
5642          1           Pastry     42.13  
5739          1           Pastry     42.13  
6072          1           Pastry     59.40  
6138          1           Pastry     54.60  
6598          1           Pastry     49.46  
6858          1           Pastry     40.41  
7653          1           Pastry     46.40  
7792          1           Pastry     47.69  
7941          1           Pastry     49.28  
7972          1           Pastry     60.00  
8075          1           Pastry     60.00  
8121          1           Pastry     57.60  
8184          1           Pastry     49.46  
8523          1           Pastry     40.84  
9139          1           Pastry     42.56  
9140          1           Pastry     55.80  
9316          1           Pastry     57.00  
9322          1           Pastry     47.42  
9684          1           Pastry     58.80  
10098         1           Pastry     39.55  
10154         1           Pastry     49.97  
10338         1           Pastry     40.84  
10463         1           Pastry     46.40  
10565         1           Pastry     50.48  
10643         1           Pastry     60.00  
10844         1           Pastry     56.40  
10855         2           Pastry     85.98  
11013         1           Pastry     42.99  
11031         1           Pastry     49.28  
11038         1           Pastry     55.80  
11380         1           Pastry     42.99  
11669         2           Pastry    103.86  
11822         1           Pastry     59.40  
11982         1           Pastry     42.99  
12348         1           Pastry     41.70  
Manufacturer: Pelle Pelle, Sum of subtotals: $9642.60.
       RowNO    SaleDate  CustomerID FirstName     LastName  OrderID  \
84        85    1/5/2014        6102     Jared         Mack   191260   
217      218   1/15/2014        3030     Edson       Riccio   191310   
268      269   1/17/2014        8926     Byron       Werner   191327   
369      370   1/21/2014       12905      Jill         Witt   191354   
548      549    2/3/2014        3264    Sandra    Gustavson   191411   
...      ...         ...         ...       ...          ...      ...   
12151  12152  10/16/2015       13819   Chengqi        Zhang   195369   
12225  12226  10/20/2015        1033   Shankar   Sundaresan   195397   
12253  12254  10/21/2015       12252   Gerardo        Suggs   195409   
12347  12348  10/27/2015       16495    Doreen  Christopher   195438   
12383  12384  10/30/2015        4592   Gregory   Schechtman   195451   

                                ProductName      Category            Color  \
84                   pelle overtime sneaker      sneakers  Black,Red,White   
217                    sole low top sneaker      sneakers             Blue   
268                suede toe casual sneaker      sneakers            Black   
369                   crest lace up sneaker      sneakers            Black   
548                   crest lace up sneaker      sneakers            Black   
...                                     ...           ...              ...   
12151                  sole low top sneaker      sneakers             Blue   
12225              suede toe casual sneaker      sneakers            Black   
12253  pelle pelle classic driving moccasin  casual shoes              Red   
12347               pelle half time sneaker      sneakers            Black   
12383                 crest lace up sneaker      sneakers            Black   

       SalePrice  Quantity ManufacturerName  Subtotal  
84         56.25         1      Pelle Pelle     56.25  
217        38.94         1      Pelle Pelle     38.94  
268        56.99         1      Pelle Pelle     56.99  
369        67.90         2      Pelle Pelle    135.80  
548        65.80         1      Pelle Pelle     65.80  
...          ...       ...              ...       ...  
12151      37.71         1      Pelle Pelle     37.71  
12225      58.79         1      Pelle Pelle     58.79  
12253      35.14         1      Pelle Pelle     35.14  
12347      75.00         1      Pelle Pelle     75.00  
12383      69.30         1      Pelle Pelle     69.30  

[145 rows x 13 columns]
Manufacturer: Psyberia, Sum of subtotals: $5949.00.
       RowNO    SaleDate  CustomerID  FirstName     LastName  OrderID  \
474      475   1/27/2014        4805    Gabriel        Ochoa   191385   
651      652    2/8/2014        6077    Hossein       Safari   191444   
1000    1001    3/3/2014        1642   Kendrick         Ames   191562   
1532    1533    4/6/2014        9751       Nora        Bragg   191745   
2112    2113    5/8/2014       16993    Soonjae         Kwon   191946   
2339    2340   5/20/2014        4611     Dustin       Hebert   192015   
2517    2518   5/29/2014       14574   Benjamin        Ngugi   192071   
2654    2655    6/4/2014       18419       Jean        Means   192119   
2861    2862   6/15/2014        2963     Lottie    Broussard   192179   
3029    3030   6/27/2014       16237     Lillie    Mcdonough   192249   
3052    3053   6/29/2014       10975        Jan       Seruga   192257   
3347    3348   7/12/2014       15402      Lilia         Rose   192364   
3357    3358   7/13/2014       17357     Steven         Curl   192366   
3699    3700   7/31/2014        9107   Mei-Chun           Wu   192483   
3705    3706    8/1/2014        3991   Angelica       Golden   192484   
3712    3713    8/1/2014        3449     Thomas      Marbach   192486   
3977    3978   8/14/2014        1112      Deana      Madison   192560   
4183    4184   8/30/2014         350    Michele         Vang   192634   
4408    4409   9/14/2014       18426     Efrain  Hendrickson   192718   
6030    6031   12/1/2014       15401    Alberto     Mcdonald   193299   
8329    8330   3/22/2015       10932      Trina         Winn   194080   
8510    8511    4/3/2015        6306     Robert       Willis   194153   
8613    8614    4/8/2015        1096     Meliha      Handzic   194184   
9281    9282   5/18/2015        4577      Joeri        Laere   194428   
9485    9486   5/28/2015       15556      Kathy       Arroyo   194493   
9566    9567    6/4/2015         144     Murray       Turoff   194542   
9883    9884   6/24/2015       12010     Daphne     Phillips   194641   
10079  10080    7/6/2015       15587      Misty       Latham   194714   
10258  10259   7/14/2015        3388      Enoch         King   194778   
10301  10302   7/17/2015       17032      Bryan        Huber   194798   
10705  10706    8/1/2015       17732      Sally        Heard   194922   
10721  10722    8/3/2015       13438       Donn        Rocha   194929   
11161  11162   8/26/2015       16708      Henry     Mcfadden   195077   
11335  11336    9/4/2015       12338  Ernestine    Singleton   195130   
11659  11660   9/23/2015       13576      Faith         Lade   195225   
12187  12188  10/18/2015        2334      Fiona      Darroch   195381   
12429  12430   11/3/2015        8466      David      Skelton   195467   

            ProductName Category        Color  SalePrice  Quantity  \
474       mudguard boot    boots        Black     138.00         1   
651       mudguard boot    boots        Black     125.58         1   
1000   jack frost boots    boots        Black     150.00         1   
1532   jack frost boots    boots        Black     144.00         1   
2112       endura boots    boots  Brown,Olive     117.60         1   
2339         hiker boot    boots        Brown     168.00         1   
2517      mudguard boot    boots        Black     126.96         1   
2654         hiker boot    boots        Brown     157.92         1   
2861   jack frost boots    boots        Black     147.00         1   
3029      mudguard boot    boots        Black     132.48         1   
3052   jack frost boots    boots        Black     139.50         1   
3347        endura boot    boots        Black     120.00         1   
3357        endura boot    boots        Black     116.40         1   
3699   jack frost boots    boots        Black     139.50         2   
3705      mudguard boot    boots        Black     138.00         2   
3712      mudguard boot    boots        Black     138.00         1   
3977   jack frost boots    boots        Black     144.00         1   
4183   jack frost boots    boots        Black     138.00         1   
4408   jack frost boots    boots        Black     145.50         1   
6030         hiker boot    boots        Brown     168.00         1   
8329         hiker boot    boots        Brown     168.00         2   
8510        endura boot    boots        Black     112.80         1   
8613         hiker boot    boots        Brown     151.20         1   
9281      mudguard boot    boots        Black     138.00         1   
9485      mudguard boot    boots        Black     136.62         1   
9566      mudguard boot    boots        Black     126.96         1   
9883        endura boot    boots        Black     111.60         1   
10079  jack frost boots    boots        Black     136.50         1   
10258     mudguard boot    boots        Black     129.72         2   
10301        hiker boot    boots        Brown     161.28         1   
10705     mudguard boot    boots        Black     133.86         2   
10721       endura boot    boots        Black     110.40         1   
11161  jack frost boots    boots        Black     147.00         1   
11335  jack frost boots    boots        Black     147.00         1   
11659  jack frost boots    boots        Black     144.00         1   
12187     mudguard boot    boots        Black     131.10         2   
12429     mudguard boot    boots        Black     128.34         1   

      ManufacturerName  Subtotal  
474           Psyberia    138.00  
651           Psyberia    125.58  
1000          Psyberia    150.00  
1532          Psyberia    144.00  
2112          Psyberia    117.60  
2339          Psyberia    168.00  
2517          Psyberia    126.96  
2654          Psyberia    157.92  
2861          Psyberia    147.00  
3029          Psyberia    132.48  
3052          Psyberia    139.50  
3347          Psyberia    120.00  
3357          Psyberia    116.40  
3699          Psyberia    279.00  
3705          Psyberia    276.00  
3712          Psyberia    138.00  
3977          Psyberia    144.00  
4183          Psyberia    138.00  
4408          Psyberia    145.50  
6030          Psyberia    168.00  
8329          Psyberia    336.00  
8510          Psyberia    112.80  
8613          Psyberia    151.20  
9281          Psyberia    138.00  
9485          Psyberia    136.62  
9566          Psyberia    126.96  
9883          Psyberia    111.60  
10079         Psyberia    136.50  
10258         Psyberia    259.44  
10301         Psyberia    161.28  
10705         Psyberia    267.72  
10721         Psyberia    110.40  
11161         Psyberia    147.00  
11335         Psyberia    147.00  
11659         Psyberia    144.00  
12187         Psyberia    262.20  
12429         Psyberia    128.34  
Manufacturer: Puma, Sum of subtotals: $44206.17.
       RowNO    SaleDate  CustomerID FirstName   LastName  OrderID  \
0          1  12/31/2013        1134   Xiafeng       Wang   191228   
1          2  12/31/2013        1134   Xiafeng       Wang   191228   
6          7  12/31/2013        3275  Herschel    Webster   191230   
111      112    1/6/2014        6863      Dave      Yates   191270   
142      143    1/8/2014       10345     Royce      Seals   191280   
...      ...         ...         ...       ...        ...      ...   
12361  12362  10/29/2015        8334   Maritza     Dotson   195442   
12462  12463   11/4/2015        5727   Pauline  Mcdermott   195476   
12534  12535   11/6/2015        2682  Paulette      Horne   195495   
12552  12553   11/7/2015        3341    Tanvir     Goraya   195501   
12555  12556   11/7/2015       11921   Tabitha      James   195502   

                        ProductName  Category   Color  SalePrice  Quantity  \
0         be mini vulc wns sneakers  sneakers   Black      57.65         1   
1                     liga sneakers  sneakers    Blue      63.05         1   
6            suede classic sneakers  sneakers  Purple      53.10         1   
111    the bharrington mid sneakers  sneakers   Brown     130.95         2   
142       evospeed mid bmw sneakers  sneakers    Blue     128.70         1   
...                             ...       ...     ...        ...       ...   
12361        el rey future sneakers  sneakers   Black      78.20         1   
12462      ansbach slip on sneakers  sneakers   Black      80.08         1   
12534          toori run c sneakers  sneakers   Black      99.00         1   
12552          rs 100 city sneakers  sneakers   Black      54.14         1   
12555      el ace 2 pn mid sneakers  sneakers    Grey      63.99         2   

      ManufacturerName  Subtotal  
0                 Puma     57.65  
1                 Puma     63.05  
6                 Puma     53.10  
111               Puma    261.90  
142               Puma    128.70  
...                ...       ...  
12361             Puma     78.20  
12462             Puma     80.08  
12534             Puma     99.00  
12552             Puma     54.14  
12555             Puma    127.98  

[513 rows x 13 columns]
Manufacturer: Radii Footwear, Sum of subtotals: $15772.93.
       RowNO    SaleDate  CustomerID FirstName   LastName  OrderID  \
16        17    1/2/2014       10767   Anthony     Hooper   191235   
140      141    1/8/2014        4948     Wiley      Dolan   191279   
162      163   1/11/2014       14726     Pablo  Rodriguez   191291   
276      277   1/17/2014        1355    Ashish     Tewary   191328   
320      321   1/19/2014        8791    Michal    Zaremba   191341   
...      ...         ...         ...       ...        ...      ...   
12240  12241  10/20/2015        5795    Freddy      Booth   195402   
12314  12315  10/26/2015        3223    Carrie    Sargent   195428   
12411  12412  10/31/2015         350   Michele       Vang   195460   
12455  12456   11/4/2015        6077   Hossein     Safari   195474   
12460  12461   11/4/2015       13665   Jarrett    Michael   195475   

                        ProductName  Category               Color  SalePrice  \
16     straight jacket vlc sneakers  sneakers    Animal Print,Red      106.7   
140    straight jacket vlc sneakers  sneakers    Animal Print,Red      110.0   
162    straight jacket vlc sneakers  sneakers    Animal Print,Red      107.8   
276    straight jacket vlc sneakers  sneakers    Animal Print,Red      104.5   
320    straight jacket vlc sneakers  sneakers    Animal Print,Red      103.4   
...                             ...       ...                 ...        ...   
12240               simple sneakers  sneakers  Animal Print,Black       80.0   
12314            briefcase sneakers  sneakers               Black       65.8   
12411  straight jacket vlc sneakers  sneakers    Animal Print,Red      105.6   
12455               simple sneakers  sneakers  Animal Print,Black       76.0   
12460  straight jacket vlc sneakers  sneakers    Animal Print,Red      105.6   

       Quantity ManufacturerName  Subtotal  
16            1   Radii Footwear     106.7  
140           1   Radii Footwear     110.0  
162           1   Radii Footwear     107.8  
276           1   Radii Footwear     104.5  
320           1   Radii Footwear     103.4  
...         ...              ...       ...  
12240         1   Radii Footwear      80.0  
12314         1   Radii Footwear      65.8  
12411         1   Radii Footwear     105.6  
12455         1   Radii Footwear      76.0  
12460         1   Radii Footwear     105.6  

[165 rows x 13 columns]
Manufacturer: Ralph Lauren, Sum of subtotals: $113.44.
      RowNO  SaleDate  CustomerID FirstName LastName  OrderID  \
2759   2760  6/9/2014       13168     Megan   Powers   192148   
3817   3818  8/7/2014        3843    Sylvia  Edwards   192517   

                             ProductName  Category  Color  SalePrice  \
2759  polo ralph lauren barnham sneakers  sneakers  Black      56.72   
3817  polo ralph lauren barnham sneakers  sneakers  Black      56.72   

      Quantity ManufacturerName  Subtotal  
2759         1     Ralph Lauren     56.72  
3817         1     Ralph Lauren     56.72  
Manufacturer: Reebok, Sum of subtotals: $39640.06.
       RowNO   SaleDate  CustomerID FirstName  LastName  OrderID  \
48        49   1/3/2014        3325    Jeffry      Babb   191248   
65        66   1/4/2014       14209   Hartmut    Hoehle   191252   
85        86   1/5/2014       15733      Lupe   Cabrera   191261   
108      109   1/6/2014       17245       Tim   Preston   191269   
112      113   1/6/2014        6863      Dave     Yates   191270   
...      ...        ...         ...       ...       ...      ...   
12508  12509  11/5/2015       10793      Mark   Vluggen   195486   
12541  12542  11/7/2015       14901     Penny     Boyce   195498   
12546  12547  11/7/2015       10779    Ismael  Mcintyre   195499   
12549  12550  11/7/2015        3341    Tanvir    Goraya   195501   
12561  12562  11/7/2015       14880    Steven  Mcdowell   195504   

                        ProductName  Category         Color  SalePrice  \
48        kamikaze ii rain sneakers  sneakers          Grey     108.90   
65            question low sneakers  sneakers         White     110.00   
85     exofit hi clean r12 sneakers  sneakers         White      74.40   
108          exofit plus hi txt r13  sneakers         Black      79.05   
112            workout mid sneakers  sneakers  Orange,White      72.00   
...                             ...       ...           ...        ...   
12508     dance urlead mid sneakers  sneakers         Black      82.44   
12541          workout mid sneakers  sneakers  Orange,White      71.25   
12546         question low sneakers  sneakers         White     103.40   
12549         freestyle hi sneakers  sneakers           Red      59.16   
12561    freestyle hi intl sneakers  sneakers        Purple      65.99   

       Quantity ManufacturerName  Subtotal  
48            1           Reebok    108.90  
65            2           Reebok    220.00  
85            2           Reebok    148.80  
108           1           Reebok     79.05  
112           2           Reebok    144.00  
...         ...              ...       ...  
12508         1           Reebok     82.44  
12541         2           Reebok    142.50  
12546         1           Reebok    103.40  
12549         1           Reebok     59.16  
12561         1           Reebok     65.99  

[413 rows x 13 columns]
Manufacturer: Rocawear, Sum of subtotals: $6259.53.
       RowNO   SaleDate  CustomerID FirstName   LastName  OrderID  \
70        71   1/4/2014       10402     Lewis    Leeburg   191255   
126      127   1/7/2014        9020      Leon   Schwartz   191275   
180      181  1/12/2014        1950      Jack     Freund   191298   
308      309  1/18/2014        5708     James     Downey   191337   
350      351  1/21/2014        7709      Josh     Palmer   191346   
...      ...        ...         ...       ...        ...      ...   
11547  11548  9/14/2015       15873   Tomoaki    Shimada   195191   
11749  11750  9/26/2015       14856    Gerald        Fry   195251   
11911  11912  10/3/2015       14405  Tongxiao      Zhang   195296   
12426  12427  11/3/2015        7201     Oscar      Saenz   195465   
12467  12468  11/4/2015        5727   Pauline  Mcdermott   195476   

                    ProductName  Category      Color  SalePrice  Quantity  \
70         city roc hi sneakers  sneakers      Black      59.52         1   
126        city roc hi sneakers  sneakers      Black      60.16         1   
180       roc the boat sneakers  sneakers      Black      55.20         1   
308         roc a million boots     boots  Black,Red      28.99         1   
350       roc the boat sneakers  sneakers      Black      54.00         1   
...                         ...       ...        ...        ...       ...   
11547    roc a million sneakers  sneakers  Blue,Grey      46.79         1   
11749  roc a million hi sneaker  sneakers      Black      60.45         1   
11911     roc the boat sneakers  sneakers      Black      54.60         1   
12426           roc royal boots  sneakers  Blue,Grey      52.79         1   
12467     roc the boat sneakers  sneakers      Black      57.60         1   

      ManufacturerName  Subtotal  
70            Rocawear     59.52  
126           Rocawear     60.16  
180           Rocawear     55.20  
308           Rocawear     28.99  
350           Rocawear     54.00  
...                ...       ...  
11547         Rocawear     46.79  
11749         Rocawear     60.45  
11911         Rocawear     54.60  
12426         Rocawear     52.79  
12467         Rocawear     57.60  

[98 rows x 13 columns]
Manufacturer: Rothco, Sum of subtotals: $1365.87.
       RowNO    SaleDate  CustomerID FirstName    LastName  OrderID  \
793      794   2/18/2014        6590    Robert   Nickerson   191491   
2274    2275   5/16/2014        3667  Michelle      Carter   191996   
3453    3454   7/18/2014       14617      Uday    Kulkarni   192397   
3995    3996   8/17/2014        4820      Mark      Silver   192564   
4578    4579   9/25/2014       11143      Glen   Mansfield   192776   
5924    5925  11/26/2014       17782  Garfield      Guzman   193256   
6427    6428  12/14/2014       13674      John     Lindsay   193429   
7589    7590    2/5/2015         249     Lorna    Robinson   193815   
7632    7633    2/8/2015        4802      Pete        Cobb   193832   
8564    8565    4/6/2015        1790   Jocelyn     Freeman   194170   
9277    9278   5/18/2015        1048   Michael      Sutton   194427   
10504  10505   7/23/2015       13925  Gertrude       Walls   194850   
11761  11762   9/27/2015        4725  Diederik       Liere   195256   
11864  11865   10/2/2015        3176      Lars  Mathiassen   195285   
11914  11915   10/3/2015         388   Tiffany       Braun   195297   
12449  12450   11/4/2015       11291    Jeanie      Kinney   195473   

                                   ProductName Category  Color  SalePrice  \
793      rothco black cold weather hiking boot    boots  Black      46.99   
2274     rothco black cold weather hiking boot    boots  Black      47.99   
3453                              jungle boots    boots  Black      63.69   
3995     rothco black cold weather hiking boot    boots  Black      49.99   
4578     rothco black cold weather hiking boot    boots  Black      49.99   
5924                              jungle boots    boots  Black      65.79   
6427     rothco black cold weather hiking boot    boots  Black      45.99   
7589                              jungle boots    boots  Black      65.09   
7632                              jungle boots    boots  Black      66.49   
8564     rothco black cold weather hiking boot    boots  Black      45.99   
9277   g.i. type desert tan 6” deployment boot    boots  Wheat      63.69   
10504                             jungle boots    boots  Black      69.99   
11761                             jungle boots    boots  Black      67.89   
11864                             combat boots    boots  Black      63.69   
11914                             combat boots    boots  Black      65.79   
12449  g.i. type desert tan 6” deployment boot    boots  Wheat      65.79   

       Quantity ManufacturerName  Subtotal  
793           2           Rothco     93.98  
2274          1           Rothco     47.99  
3453          1           Rothco     63.69  
3995          1           Rothco     49.99  
4578          2           Rothco     99.98  
5924          2           Rothco    131.58  
6427          1           Rothco     45.99  
7589          2           Rothco    130.18  
7632          1           Rothco     66.49  
8564          1           Rothco     45.99  
9277          2           Rothco    127.38  
10504         1           Rothco     69.99  
11761         1           Rothco     67.89  
11864         2           Rothco    127.38  
11914         2           Rothco    131.58  
12449         1           Rothco     65.79  
Manufacturer: Royal Elastics, Sum of subtotals: $3943.18.
       RowNO    SaleDate  CustomerID    FirstName     LastName  OrderID  \
9         10    1/1/2014        5230         Toru    Sakaguchi   191233   
26        27    1/2/2014       14396        Sally     Richmond   191240   
58        59    1/4/2014        7881  Christopher        Jones   191251   
81        82    1/5/2014        6102        Jared         Mack   191260   
248      249   1/16/2014        1719      Richard      Trimble   191318   
...      ...         ...         ...          ...          ...      ...   
12387  12388  10/30/2015        4592      Gregory   Schechtman   195451   
12443  12444   11/3/2015       16495       Doreen  Christopher   195470   
12489  12490   11/4/2015        5509      Colleen         Page   195482   
12528  12529   11/6/2015       15123           Jo      Smedley   195494   
12557  12558   11/7/2015       11921      Tabitha        James   195502   

          ProductName  Category  Color  SalePrice  Quantity ManufacturerName  \
9            chehalis  sneakers  Black      16.48         1   Royal Elastics   
26       sister kelly  sneakers  Black      31.95         1   Royal Elastics   
58          jomei mid  sneakers  Brown      18.99         1   Royal Elastics   
81          jomei mid  sneakers  Brown      17.47         1   Royal Elastics   
248          hastings     flats   Grey      16.55         1   Royal Elastics   
...               ...       ...    ...        ...       ...              ...   
12387    sister kelly  sneakers  Black      31.61         2   Royal Elastics   
12443       wellfrank  sneakers   Blue      16.99         1   Royal Elastics   
12489  brother roland  sneakers  Black      14.39         1   Royal Elastics   
12528    sister kelly  sneakers  Black      33.65         1   Royal Elastics   
12557        hastings     flats   Grey      16.55         1   Royal Elastics   

       Subtotal  
9         16.48  
26        31.95  
58        18.99  
81        17.47  
248       16.55  
...         ...  
12387     63.22  
12443     16.99  
12489     14.39  
12528     33.65  
12557     16.55  

[154 rows x 13 columns]
Manufacturer: Sebago, Sum of subtotals: $10764.54.
       RowNO    SaleDate  CustomerID  FirstName    LastName  OrderID  \
75        76    1/5/2014        8135    Richard      Hauser   191257   
93        94    1/6/2014       17519   Matthias  Roggendorf   191264   
285      286   1/17/2014       15556      Kathy      Arroyo   191331   
370      371   1/21/2014       12905       Jill        Witt   191354   
381      382   1/21/2014       14782       Hong       Huang   191356   
...      ...         ...         ...        ...         ...      ...   
11957  11958   10/4/2015        1561      Harry      Atkins   195306   
11998  11999   10/6/2015        3097        Ron       Mills   195320   
12030  12031   10/8/2015       10952        Val      Albert   195331   
12141  12142  10/15/2015       12099    Michael     Hahsler   195366   
12215  12216  10/20/2015       12393  Elisabeth    Townsend   195393   

                     ProductName      Category  Color  SalePrice  Quantity  \
75           docksides boat shoe  casual shoes  Black      95.00         1   
93           docksides boat shoe  casual shoes  Black      96.00         1   
285          wentworth boat shoe  casual shoes   Grey      96.99         1   
370          docksides boat shoe  casual shoes  Black      90.00         1   
381             the warf slip on  casual shoes  Brown      87.11         1   
...                          ...           ...    ...        ...       ...   
11957        wentworth boat shoe  casual shoes   Grey      97.99         1   
11998  docksides waxed boat shoe  casual shoes  Brown      85.55         1   
12030            lighthouse boot         boots  Black      17.99         1   
12141        docksides boat shoe  casual shoes  Black      90.00         1   
12215        wentworth boat shoe  casual shoes   Grey      94.99         1   

      ManufacturerName  Subtotal  
75              Sebago     95.00  
93              Sebago     96.00  
285             Sebago     96.99  
370             Sebago     90.00  
381             Sebago     87.11  
...                ...       ...  
11957           Sebago     97.99  
11998           Sebago     85.55  
12030           Sebago     17.99  
12141           Sebago     90.00  
12215           Sebago     94.99  

[114 rows x 13 columns]
Manufacturer: Shmack, Sum of subtotals: $85.76.
      RowNO   SaleDate  CustomerID FirstName LastName  OrderID  ProductName  \
2316   2317  5/19/2014       17357    Steven     Curl   192007  hatchet mid   
2400   2401  5/24/2014        7916     Betsy   Vaughn   192036  hatchet mid   
4455   4456  9/16/2014        2046    Cecile     Dodd   192734  hatchet mid   

      Category Color  SalePrice  Quantity ManufacturerName  Subtotal  
2316  sneakers   Red      21.77         2           Shmack     43.54  
2400  sneakers   Red      20.23         1           Shmack     20.23  
4455  sneakers   Red      21.99         1           Shmack     21.99  
Manufacturer: Steve Madden, Sum of subtotals: $1205.85.
       RowNO    SaleDate  CustomerID   FirstName     LastName  OrderID  \
80        81    1/5/2014        6102       Jared         Mack   191260   
898      899   2/27/2014       12306         Tor    Guimaraes   191526   
1358    1359   3/30/2014        7194      Luther       Lovett   191694   
2116    2117    5/8/2014       16418        John          Doe   191947   
4872    4873   10/9/2014        9906        Neil       Foshay   192879   
5346    5347   11/2/2014        5257   Salvatore         Berg   193043   
5369    5370   11/3/2014        7739      Lester   Singletary   193048   
5414    5415   11/5/2014       15262      Rainer      Berbner   193071   
6156    6157   12/5/2014        8438   Demetrius       Ritter   193338   
6609    6610  12/21/2014       15749      Robert         Weir   193486   
7492    7493    2/1/2015        3085     William         Wang   193790   
7821    7822   2/18/2015        8146        Paul       Tallon   193897   
7900    7901   2/23/2015        1714    Harriett     Matthews   193924   
8014    8015    3/2/2015        4304      Marlon        Dumas   193969   
8234    8235   3/16/2015        8011      Godwin       Tetteh   194046   
8477    8478    4/1/2015       13273         Max     Bessonov   194141   
8898    8899   4/25/2015       14463        Qian         Peng   194295   
8958    8959   4/30/2015       15956    Jia-Lang         Seng   194319   
9494    9495   5/28/2015       10194        Paul     Hendriks   194496   
10068  10069    7/5/2015        1394      Ronnie         Park   194707   
10199  10200   7/12/2015        9299       James     Courtney   194761   
10292  10293   7/16/2015       11474      Thelma         Frye   194794   
10890  10891   8/11/2015         755  Shuangyuan          Shi   194987   
10946  10947   8/14/2015        8782        Mike     Chiasson   195005   
11115  11116   8/22/2015        4338       Grace     Castillo   195061   
11805  11806   9/30/2015       13425        Kyle        Weber   195267   
12227  12228  10/20/2015       16635         Ola  Henfridsson   195399   

                    ProductName  Category  Color  SalePrice  Quantity  \
80                  gewelz boot     boots  Black      54.99         1   
898    tandumm sandal w/crystal   sandals   Pink      39.12         1   
1358    bookie platform sneaker  sneakers   Gold      43.64         1   
2116    bookie platform sneaker  sneakers   Gold      42.74         2   
4872                      getta     heels  Multi      16.91         1   
5346    bookie platform sneaker  sneakers   Gold      43.64         1   
5369   tandumm sandal w/crystal   sandals   Pink      39.12         1   
5414                    snappie     boots    Tan      25.37         1   
6156                      zappa     boots  Black      26.38         1   
6609                      zappa     boots  Black      28.99         1   
7492    bookie platform sneaker  sneakers   Gold      42.29         1   
7821    bookie platform sneaker  sneakers   Gold      41.84         1   
7900    bookie platform sneaker  sneakers   Gold      42.74         1   
8014    bookie platform sneaker  sneakers   Gold      40.49         2   
8234   tandumm sandal w/crystal   sandals   Pink      40.41         1   
8477                      getta     heels  Multi      17.81         1   
8898                      getta     heels  Multi      17.09         1   
8958    bookie platform sneaker  sneakers   Gold      44.99         1   
9494                      zappa     boots  Black      28.70         1   
10068               gewelz boot     boots  Black      52.24         2   
10199               gewelz boot     boots  Black      49.49         1   
10292   bookie platform sneaker  sneakers   Gold      43.19         2   
10890                   snappie     boots    Tan      25.37         1   
10946                     zappa     boots  Black      26.96         2   
11115                     zappa     boots  Black      27.54         1   
11805               gewelz boot     boots  Black      54.99         1   
12227   bookie platform sneaker  sneakers   Gold      43.19         1   

      ManufacturerName  Subtotal  
80        Steve Madden     54.99  
898       Steve Madden     39.12  
1358      Steve Madden     43.64  
2116      Steve Madden     85.48  
4872      Steve Madden     16.91  
5346      Steve Madden     43.64  
5369      Steve Madden     39.12  
5414      Steve Madden     25.37  
6156      Steve Madden     26.38  
6609      Steve Madden     28.99  
7492      Steve Madden     42.29  
7821      Steve Madden     41.84  
7900      Steve Madden     42.74  
8014      Steve Madden     80.98  
8234      Steve Madden     40.41  
8477      Steve Madden     17.81  
8898      Steve Madden     17.09  
8958      Steve Madden     44.99  
9494      Steve Madden     28.70  
10068     Steve Madden    104.48  
10199     Steve Madden     49.49  
10292     Steve Madden     86.38  
10890     Steve Madden     25.37  
10946     Steve Madden     53.92  
11115     Steve Madden     27.54  
11805     Steve Madden     54.99  
12227     Steve Madden     43.19  
Manufacturer: Supra, Sum of subtotals: $38836.91.
       RowNO   SaleDate  CustomerID FirstName  LastName  OrderID  \
11        12   1/2/2014       10767   Anthony    Hooper   191235   
32        33   1/2/2014        3724    Jarrod     Moran   191241   
52        53   1/4/2014       13696       May   Vaughan   191249   
72        73   1/4/2014       10402     Lewis   Leeburg   191255   
83        84   1/5/2014        6102     Jared      Mack   191260   
...      ...        ...         ...       ...       ...      ...   
12437  12438  11/3/2015       14625    Israel   Aguilar   195469   
12438  12439  11/3/2015       14625    Israel   Aguilar   195469   
12470  12471  11/4/2015       11740     Josip    Brumec   195477   
12544  12545  11/7/2015       10779    Ismael  Mcintyre   195499   
12550  12551  11/7/2015        3341    Tanvir    Goraya   195501   

                                             ProductName  Category  \
11                   assault tan leather/canvas sneakers  sneakers   
32                                       skytop sneakers  sneakers   
52                                       stacks sneakers  sneakers   
72                                         owen sneakers  sneakers   
83           owen mid red microfiber/black mesh sneakers  sneakers   
...                                                  ...       ...   
12437                   skytop white raptor tuf sneakers  sneakers   
12438                                    vaider sneakers  sneakers   
12470               vaider lite special edition sneakers  sneakers   
12544  mariner charcoal vintage canvas slip-on deck s...  sneakers   
12550                                      owen sneakers  sneakers   

                  Color  SalePrice  Quantity ManufacturerName  Subtotal  
11           Orange,Tan      54.71         1            Supra     54.71  
32     Black,Light Blue      75.59         1            Supra     75.59  
52                Black      45.53         1            Supra     45.53  
72           Black,Grey      44.99         1            Supra     44.99  
83                  Red      89.10         1            Supra     89.10  
...                 ...        ...       ...              ...       ...  
12437             white      88.34         1            Supra     88.34  
12438        Black,Gold      73.31         1            Supra     73.31  
12470             Black     105.00         1            Supra    105.00  
12544          Charcoal      65.00         2            Supra    130.00  
12550        Black,Grey      41.84         2            Supra     83.68  

[539 rows x 13 columns]
Manufacturer: The Skate Shop, Sum of subtotals: $68.39.
      RowNO  SaleDate  CustomerID FirstName LastName  OrderID  \
2031   2032  5/4/2014       13137    Reuben    Boyer   191923   

                         ProductName  Category Color  SalePrice  Quantity  \
2031  vaider red perf suede sneakers  sneakers   Red      68.39         1   

     ManufacturerName  Subtotal  
2031   The Skate Shop     68.39  
Manufacturer: Timberland, Sum of subtotals: $28030.98.
       RowNO    SaleDate  CustomerID FirstName     LastName  OrderID  \
3          4  12/31/2013        1134   Xiafeng         Wang   191228   
43        44    1/3/2014        6238    Gerard       Cannoo   191246   
95        96    1/6/2014       17811      Lois  Fitz-Gerald   191265   
183      184   1/12/2014        9106    Arnold      English   191299   
208      209   1/14/2014        7928   Roxanne       Whalen   191307   
...      ...         ...         ...       ...          ...      ...   
12501  12502   11/5/2015        2400      Ross        Oneal   195485   
12548  12549   11/7/2015        7888    Marcus       Garcia   195500   
12559  12560   11/7/2015       11921   Tabitha        James   195502   
12563  12564   11/7/2015        9345    Lorene      Charles   195505   
12566  12567   11/7/2015        9345    Lorene      Charles   195505   

                                             ProductName      Category  Color  \
3                       timberland icon 6" premium boots         boots  Black   
43         earthkeepers casco bay canvas oxford sneakers      sneakers  Black   
95                     earthkeepers hookset oxford shoes  casual shoes   Blue   
183          earthkeepers hookset fabric chukka sneakers      sneakers   Blue   
208          timberland mens oakwell 7 eye moc toe boots         boots   Grey   
...                                                  ...           ...    ...   
12501  earthkeepers hookset handcrafted fabric oxford...      sneakers  Brown   
12548  earthkeepers hookset handcrafted fabric oxford...      sneakers  Brown   
12559                   timberland icon 6" premium boots         boots  Black   
12563  earthkeepers hookset handcrafted fabric oxford...      sneakers  Brown   
12566                              nm camp leather boots         boots  Black   

       SalePrice  Quantity ManufacturerName  Subtotal  
3         116.99         1       Timberland    116.99  
43         65.00         1       Timberland     65.00  
95         71.25         1       Timberland     71.25  
183        81.60         1       Timberland     81.60  
208        77.07         1       Timberland     77.07  
...          ...       ...              ...       ...  
12501      68.25         1       Timberland     68.25  
12548      72.00         1       Timberland     72.00  
12559     105.29         1       Timberland    105.29  
12563      75.00         2       Timberland    150.00  
12566      74.68         1       Timberland     74.68  

[296 rows x 13 columns]
Manufacturer: Two Lip Shoes, Sum of subtotals: $2060.39.
       RowNO    SaleDate  CustomerID FirstName       LastName  OrderID  \
213      214   1/15/2014       11359    Bessie        Pickett   191309   
530      531   1/31/2014        6078   Antonia           Ryan   191400   
1591    1592    4/9/2014        3247   Bradley        Lundell   191770   
1765    1766   4/19/2014       11553    Michel        Chokron   191827   
2216    2217   5/12/2014       11405      Theo        Renkema   191976   
2231    2232   5/14/2014        5894      Jodi           Rowe   191984   
2727    2728    6/8/2014        8984    Janice             Ng   192139   
3169    3170    7/3/2014       18123    Carmen          Lewis   192308   
3332    3333   7/12/2014       16105    Lionel         Robert   192360   
3550    3551   7/23/2014       15420    Miguel          Nolan   192427   
3555    3556   7/24/2014       16895      Irma        Burgess   192429   
3941    3942   8/12/2014        8474     Bryon           Wolf   192549   
4284    4285    9/7/2014       11454    Genaro        Navarro   192678   
4395    4396   9/14/2014       16672       Gad          Ariav   192715   
4750    4751   10/3/2014        4989   Rolando     Mccullough   192839   
4949    4950  10/12/2014       15114      Paul  Beynon-Davies   192905   
5101    5102  10/22/2014       15780    Huimin           Xiao   192963   
5457    5458   11/8/2014       10487      Rose          Stone   193089   
6226    6227   12/8/2014       11252     Brett         Landry   193359   
6267    6268   12/9/2014        9982    Bettie       Robinson   193366   
6355    6356  12/12/2014        3624    Carlos        Coronel   193403   
6403    6404  12/13/2014       15342     Sharm        Manwani   193418   
6772    6773  12/27/2014         260       Ava           Khan   193543   
7037    7038    1/6/2015        3809    Thomas    Blankenship   193619   
7409    7410   1/29/2015        1278     Pablo         Golden   193765   
7422    7423   1/30/2015       11206   Charlie         Hanson   193770   
7782    7783   2/16/2015       16319     Nikos    Koutsoupias   193885   
7893    7894   2/22/2015       13649    Dolphy        Abraham   193922   
8307    8308   3/22/2015        9762   Norbert            Ray   194074   
8506    8507    4/3/2015        9453     Layne        Wallace   194152   
8773    8774   4/16/2015        5135    Magnus         Ramage   194247   
9187    9188   5/12/2015       17939   Christy       Cummings   194399   
9574    9575    6/4/2015        7694        Mu            Xia   194544   
9591    9592    6/5/2015        5314    Manuel          Odell   194549   
10303  10304   7/17/2015       17032     Bryan          Huber   194798   
10490  10491   7/22/2015       10950    Brooke          Nance   194845   
10691  10692   7/31/2015        7556      Dion          Miner   194917   
10703  10704    8/1/2015       17732     Sally          Heard   194922   
11424  11425    9/9/2015       15203   Hilario           Lang   195157   
11835  11836   9/30/2015       10388      Dave       McDonald   195275   
12088  12089  10/11/2015       18182   Yanjuan           Yang   195348   
12120  12121  10/14/2015       11814    Debora           Rosa   195359   

                                ProductName Category               Color  \
213                    grommet wedge sandal  sandals               Brown   
530               spiked patent strap wedge  sandals               Black   
1591   comfort strap stud trim wedge sandal  sandals                Blue   
1765                    woven zip gladiator  sandals              Orange   
2216              spiked patent strap wedge  sandals               Black   
2231              spiked patent strap wedge  sandals               Black   
2727   comfort strap stud trim wedge sandal  sandals                Blue   
3169            sexy gladiator wedge sandal  sandals               Black   
3332          striped peeptoe platform shoe  sandals               Black   
3550          striped peeptoe platform shoe  sandals               Black   
3555              spiked patent strap wedge  sandals               Black   
3941            sexy gladiator wedge sandal  sandals               Black   
4284          striped peeptoe platform shoe  sandals               Black   
4395            sexy gladiator wedge sandal  sandals               Black   
4750             knee high buckle trim boot    boots               Brown   
4949            sexy gladiator wedge sandal  sandals               Black   
5101                   grommet wedge sandal  sandals               Brown   
5457     leopard trim microsuede wedge boot    boots  Animal Print,Black   
6226     leopard trim microsuede wedge boot    boots  Animal Print,Black   
6267              spiked patent strap wedge  sandals               Black   
6355                   grommet wedge sandal  sandals               Brown   
6403          striped peeptoe platform shoe  sandals               Black   
6772                   grommet wedge sandal  sandals               Brown   
7037              spiked patent strap wedge  sandals               Black   
7409          feather trimmed braided wedge  sandals              Bronze   
7422    3 buckle trim microsuede wedge boot    boots               Black   
7782                   grommet wedge sandal  sandals               Brown   
7893    3 buckle trim microsuede wedge boot    boots               Black   
8307          striped peeptoe platform shoe  sandals               Black   
8506     fancy cut-out design platform heel    heels              Orange   
8773    3 buckle trim microsuede wedge boot    boots               Black   
9187                   grommet wedge sandal  sandals               Brown   
9574          feather trimmed braided wedge  sandals              Bronze   
9591   comfort strap stud trim wedge sandal  sandals                Blue   
10303         striped peeptoe platform shoe  sandals               Black   
10490                   woven zip gladiator  sandals              Orange   
10691             spiked patent strap wedge  sandals               Black   
10703   knee high elasticized platform boot    boots               Black   
11424    fancy cut-out design platform heel    heels              Orange   
11835                   woven zip gladiator  sandals              Orange   
12088           sexy gladiator wedge sandal  sandals               Black   
12120                   woven zip gladiator  sandals              Orange   

       SalePrice  Quantity ManufacturerName  Subtotal  
213        44.54         2    Two Lip Shoes     89.08  
530        54.14         1    Two Lip Shoes     54.14  
1591       49.97         1    Two Lip Shoes     49.97  
1765       52.80         1    Two Lip Shoes     52.80  
2216       56.42         1    Two Lip Shoes     56.42  
2231       53.00         1    Two Lip Shoes     53.00  
2727       50.99         1    Two Lip Shoes     50.99  
3169       42.99         1    Two Lip Shoes     42.99  
3332       19.59         1    Two Lip Shoes     19.59  
3550       19.59         1    Two Lip Shoes     19.59  
3555       53.00         1    Two Lip Shoes     53.00  
3941       42.99         1    Two Lip Shoes     42.99  
4284       18.59         1    Two Lip Shoes     18.59  
4395       41.70         1    Two Lip Shoes     41.70  
4750       51.29         2    Two Lip Shoes    102.58  
4949       42.99         2    Two Lip Shoes     85.98  
5101       44.09         2    Two Lip Shoes     88.18  
5457       30.07         1    Two Lip Shoes     30.07  
6226       31.03         2    Two Lip Shoes     62.06  
6267       52.43         1    Two Lip Shoes     52.43  
6355       42.29         1    Two Lip Shoes     42.29  
6403       18.39         1    Two Lip Shoes     18.39  
6772       42.74         1    Two Lip Shoes     42.74  
7037       51.29         1    Two Lip Shoes     51.29  
7409       39.99         1    Two Lip Shoes     39.99  
7422       22.53         1    Two Lip Shoes     22.53  
7782       40.94         1    Two Lip Shoes     40.94  
7893       22.99         1    Two Lip Shoes     22.99  
8307       19.39         1    Two Lip Shoes     19.39  
8506       56.99         1    Two Lip Shoes     56.99  
8773       22.99         1    Two Lip Shoes     22.99  
9187       44.09         1    Two Lip Shoes     44.09  
9574       36.79         1    Two Lip Shoes     36.79  
9591       48.95         2    Two Lip Shoes     97.90  
10303      18.79         2    Two Lip Shoes     37.58  
10490      51.15         1    Two Lip Shoes     51.15  
10691      56.42         1    Two Lip Shoes     56.42  
10703      43.23         2    Two Lip Shoes     86.46  
11424      51.86         1    Two Lip Shoes     51.86  
11835      53.90         1    Two Lip Shoes     53.90  
12088      42.56         1    Two Lip Shoes     42.56  
12120      55.00         1    Two Lip Shoes     55.00  
Manufacturer: Unstitched Utilities, Sum of subtotals: $131.21.
       RowNO    SaleDate  CustomerID    FirstName LastName  OrderID  \
60        61    1/4/2014        7881  Christopher    Jones   191251   
6244    6245   12/8/2014       11382    Katherine   Castle   193362   
6428    6429  12/14/2014       13674         John  Lindsay   193429   
11268  11269   8/31/2015        5654      Christa     Chen   195107   

                                ProductName      Category  Color  SalePrice  \
60     sergeant major low ultra woven shoes  casual shoes  Black      31.49   
6244   sergeant major low ultra woven shoes  casual shoes  Black      34.29   
6428   sergeant major low ultra woven shoes  casual shoes  Black      31.84   
11268  sergeant major low ultra woven shoes  casual shoes  Black      33.59   

       Quantity      ManufacturerName  Subtotal  
60            1  Unstitched Utilities     31.49  
6244          1  Unstitched Utilities     34.29  
6428          1  Unstitched Utilities     31.84  
11268         1  Unstitched Utilities     33.59  
Manufacturer: XOXO, Sum of subtotals: $86.44.
      RowNO   SaleDate  CustomerID FirstName LastName  OrderID    ProductName  \
1320   1321  3/26/2014       14209   Hartmut   Hoehle   191680  jane on wedge   
1386   1387  3/30/2014        8435  Weiqiang       Wu   191701  jane on wedge   
8102   8103  3/10/2015       14437      Jane   Klobas   194004  jane on wedge   

     Category  Color  SalePrice  Quantity ManufacturerName  Subtotal  
1320    heels  Black      20.69         1             XOXO     20.69  
1386    heels  Black      22.99         1             XOXO     22.99  
8102    heels  Black      21.38         2             XOXO     42.76  
Manufacturer: Y.R.U., Sum of subtotals: $4053.27.
       RowNO    SaleDate  CustomerID FirstName  LastName  OrderID  \
197      198   1/14/2014        6523    Rodger  Jamieson   191304   
251      252   1/16/2014       13914      Lisa    Murphy   191319   
400      401   1/22/2014        3442    Alvaro  Hamilton   191360   
423      424   1/23/2014       13877     Shaun     Chang   191367   
435      436   1/24/2014       14464     Terry  Gonzalez   191371   
...      ...         ...         ...       ...       ...      ...   
12126  12127  10/14/2015       14901     Penny     Boyce   195360   
12148  12149  10/16/2015        7831   Heather   McClain   195368   
12156  12157  10/16/2015        1790   Jocelyn   Freeman   195370   
12164  12165  10/17/2015       15006     Ronda     Brown   195373   
12364  12365  10/29/2015        8334   Maritza    Dotson   195442   

                    ProductName      Category       Color  SalePrice  \
197    pia slip on smoking shoe         flats       Black      24.24   
251    rae hidden wedge sneaker      sneakers  Black,Gold      50.04   
400            moustache loafer  casual shoes       Black      52.37   
423              pumped sneaker      sneakers       Black      44.00   
435    pia slip on smoking shoe         flats       Black      22.74   
...                         ...           ...         ...        ...   
12126          moustache loafer  casual shoes       Black      48.59   
12148         camo print loafer  casual shoes        Camo      51.99   
12156        prime slim sneaker      sneakers       Black      22.07   
12164        hella cute sneaker      sneakers  Black,Pink      23.03   
12364          moustache loafer  casual shoes       Black      50.75   

       Quantity ManufacturerName  Subtotal  
197           2           Y.R.U.     48.48  
251           1           Y.R.U.     50.04  
400           1           Y.R.U.     52.37  
423           1           Y.R.U.     44.00  
435           1           Y.R.U.     22.74  
...         ...              ...       ...  
12126         1           Y.R.U.     48.59  
12148         1           Y.R.U.     51.99  
12156         1           Y.R.U.     22.07  
12164         1           Y.R.U.     23.03  
12364         2           Y.R.U.    101.50  

[90 rows x 13 columns]
```

**Q11.6**
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>RowNO</th>
      <th>SaleDate</th>
      <th>CustomerID</th>
      <th>FirstName</th>
      <th>LastName</th>
      <th>OrderID</th>
      <th>ProductName</th>
      <th>Category</th>
      <th>Color</th>
      <th>SalePrice</th>
      <th>Quantity</th>
      <th>ManufacturerName</th>
      <th>Subtotal</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>2814</th>
      <td>2815</td>
      <td>6/13/2014</td>
      <td>11409</td>
      <td>Vives</td>
      <td>Josep</td>
      <td>192168</td>
      <td>wmns solarsoft thong ii sandals</td>
      <td>sandals</td>
      <td>Green</td>
      <td>15.29</td>
      <td>1</td>
      <td>Nike</td>
      <td>15.29</td>
    </tr>
    <tr>
      <th>1038</th>
      <td>1039</td>
      <td>3/5/2014</td>
      <td>4378</td>
      <td>Cheri</td>
      <td>Duffy</td>
      <td>191574</td>
      <td>wmns solarsoft thong ii sandals</td>
      <td>sandals</td>
      <td>Green</td>
      <td>15.46</td>
      <td>1</td>
      <td>Nike</td>
      <td>15.46</td>
    </tr>
    <tr>
      <th>11145</th>
      <td>11146</td>
      <td>8/24/2015</td>
      <td>6085</td>
      <td>Tami</td>
      <td>Estrada</td>
      <td>195071</td>
      <td>wmns solarsoft thong ii sandals</td>
      <td>sandals</td>
      <td>Green</td>
      <td>15.97</td>
      <td>1</td>
      <td>Nike</td>
      <td>15.97</td>
    </tr>
    <tr>
      <th>10147</th>
      <td>10148</td>
      <td>7/9/2015</td>
      <td>4294</td>
      <td>Rosetta</td>
      <td>Nash</td>
      <td>194740</td>
      <td>wmns solarsoft thong ii sandals</td>
      <td>sandals</td>
      <td>Green</td>
      <td>15.97</td>
      <td>1</td>
      <td>Nike</td>
      <td>15.97</td>
    </tr>
    <tr>
      <th>10791</th>
      <td>10792</td>
      <td>8/5/2015</td>
      <td>12785</td>
      <td>Betty</td>
      <td>Fernandez</td>
      <td>194947</td>
      <td>wmns solarsoft thong ii sandals</td>
      <td>sandals</td>
      <td>Green</td>
      <td>16.48</td>
      <td>1</td>
      <td>Nike</td>
      <td>16.48</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>8981</th>
      <td>8982</td>
      <td>5/1/2015</td>
      <td>10735</td>
      <td>Lora</td>
      <td>Snider</td>
      <td>194331</td>
      <td>nike air max tr 180 sneakers</td>
      <td>sneakers</td>
      <td>Grey</td>
      <td>119.99</td>
      <td>2</td>
      <td>Nike</td>
      <td>239.98</td>
    </tr>
    <tr>
      <th>4257</th>
      <td>4258</td>
      <td>9/4/2014</td>
      <td>6591</td>
      <td>Elizabeth</td>
      <td>Kolster</td>
      <td>192666</td>
      <td>nike air griffey max 360 sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>158.10</td>
      <td>2</td>
      <td>Nike</td>
      <td>316.20</td>
    </tr>
    <tr>
      <th>9601</th>
      <td>9602</td>
      <td>6/5/2015</td>
      <td>16433</td>
      <td>Freddie</td>
      <td>Shafer</td>
      <td>194550</td>
      <td>wmns air max 2013 + sneakers</td>
      <td>sneakers</td>
      <td>Blue</td>
      <td>169.20</td>
      <td>2</td>
      <td>Nike</td>
      <td>338.40</td>
    </tr>
    <tr>
      <th>4237</th>
      <td>4238</td>
      <td>9/3/2014</td>
      <td>7825</td>
      <td>Eberhard</td>
      <td>Hilf</td>
      <td>192657</td>
      <td>nike air griffey max 360 sneakers</td>
      <td>sneakers</td>
      <td>White</td>
      <td>170.00</td>
      <td>2</td>
      <td>Nike</td>
      <td>340.00</td>
    </tr>
    <tr>
      <th>7147</th>
      <td>7148</td>
      <td>1/13/2015</td>
      <td>8458</td>
      <td>Eula</td>
      <td>Mills</td>
      <td>193661</td>
      <td>wmns air max 2013 + sneakers</td>
      <td>sneakers</td>
      <td>Blue</td>
      <td>180.00</td>
      <td>2</td>
      <td>Nike</td>
      <td>360.00</td>
    </tr>
  </tbody>
</table>
<p>1314 rows × 13 columns</p>
</div>