**Please enter your name and student ID here.**

**Homework - Pandas**

**Use Pandas to solve questions 1-5.**

In [ ]:
# Mount your drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Change current directory
%cd "path of the new directory"

In [ ]:
 # Verify the current directory
%pwd

'/content/drive/MyDrive/Colab Notebooks/ANLY/ANLY6500/PRE/M2'

In [ ]:
 # Verify the current directory
%ls

 EmissionsData.csv  'HW 4 - Pandas.ipynb'   Matplotlib_Notes.ipynb

## Q1. (0.5 points)
Import the Pandas package and load the data from **EmissionsData.csv** into a dataframe called **em_df**.

In [ ]:
# Provide your answer here.

## Q2. (1 point)

Sort the dataframe using the `sort_values()` function by the column '**Emission**' in descending order. Display the top 5 records.

<div style="overflow-x:auto;">
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Year</th>
      <th>Country</th>
      <th>Continent</th>
      <th>Emission</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>592</th>
      <td>2008</td>
      <td>Qatar</td>
      <td>Asia</td>
      <td>48.601620</td>
    </tr>
    <tr>
      <th>593</th>
      <td>2009</td>
      <td>Qatar</td>
      <td>Asia</td>
      <td>44.836401</td>
    </tr>
    <tr>
      <th>595</th>
      <td>2011</td>
      <td>Qatar</td>
      <td>Asia</td>
      <td>44.018926</td>
    </tr>
    <tr>
      <th>594</th>
      <td>2010</td>
      <td>Qatar</td>
      <td>Asia</td>
      <td>42.639076</td>
    </tr>
    <tr>
      <th>710</th>
      <td>2010</td>
      <td>Trinidad And Tobago</td>
      <td>North America</td>
      <td>38.337841</td>
    </tr>
  </tbody>
</table>
</div>

In [ ]:
# Provide your answer here.

## Q3.

### Q3.1 (1 point)

Use the `groupby()` function to group **em_df** by the '**Year**' column..

In [ ]:
# Provide your answer here.

### Q3.2 (1.5 points)

Retrieve the group '**2011**' using the `get_group()` function, and sort the 2011 group dataframe by '**Emission**' in ascending order. Display the first 5 rows.

In [ ]:
# Provide your answer here.

### Q3.3 (1 point)

Use the `mean()` function to calculate the average emission of all countries in the year **2011**.

<div style="overflow-x:auto;">
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Year</th>
      <th>Country</th>
      <th>Continent</th>
      <th>Emission</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>51</th>
      <td>2011</td>
      <td>Burundi</td>
      <td>Africa</td>
      <td>0.021350</td>
    </tr>
    <tr>
      <th>683</th>
      <td>2011</td>
      <td>Chad</td>
      <td>Africa</td>
      <td>0.043830</td>
    </tr>
    <tr>
      <th>779</th>
      <td>2011</td>
      <td>Dem Rep Of Congo</td>
      <td>Africa</td>
      <td>0.050303</td>
    </tr>
    <tr>
      <th>639</th>
      <td>2011</td>
      <td>Somalia</td>
      <td>Africa</td>
      <td>0.058707</td>
    </tr>
    <tr>
      <th>607</th>
      <td>2011</td>
      <td>Rwanda</td>
      <td>Africa</td>
      <td>0.062874</td>
    </tr>
  </tbody>
</table>
</div>

```text
Average: 4.904900274527919
```

In [ ]:
# Provide your answer here.

## Q4.

### Q4.1 (2.0 points)

Find the rows in `em_df` that meet the following conditions: **Year is 2010, Continent is Europe, and Emission is greater than 2**. Sort the resulting dataframe by '**Emission**' in descending order, and display the first 5 rows.

In [ ]:
# Provide your answer here.

### Q4.2 (1 point)

Calculate the average emission of **the resulting dataframe from the previous conditions**.

<div style="overflow-x:auto;">
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Year</th>
      <th>Country</th>
      <th>Continent</th>
      <th>Emission</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>434</th>
      <td>2010</td>
      <td>Luxembourg</td>
      <td>Europe</td>
      <td>21.635136</td>
    </tr>
    <tr>
      <th>226</th>
      <td>2010</td>
      <td>Estonia</td>
      <td>Europe</td>
      <td>13.773197</td>
    </tr>
    <tr>
      <th>246</th>
      <td>2010</td>
      <td>Faroe Islands</td>
      <td>Europe</td>
      <td>12.986678</td>
    </tr>
    <tr>
      <th>534</th>
      <td>2010</td>
      <td>Norway</td>
      <td>Europe</td>
      <td>11.616193</td>
    </tr>
    <tr>
      <th>234</th>
      <td>2010</td>
      <td>Finland</td>
      <td>Europe</td>
      <td>11.530840</td>
    </tr>
  </tbody>
</table>
</div>

```text
Average: 7.4887038956
```

In [ ]:
# Provide your answer here.

## Q5.

### Q5.1 (1 point)

In **em_df**, create a new column called '**Emission10PMore**'. The value in this column should be 10% more than the corresponding value in the original '**Emission**' column.

In [ ]:
# Provide your answer here.

### Q5.2 (1 point)

Sort the resulting dataframe by '**Emission10PMore**' in ascending order and display the first 5 rows.

<div style="overflow-x:auto;">
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Year</th>
      <th>Country</th>
      <th>Continent</th>
      <th>Emission</th>
      <th>Emission10PMore</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>50</th>
      <td>2010</td>
      <td>Burundi</td>
      <td>Africa</td>
      <td>0.020542</td>
      <td>0.022596</td>
    </tr>
    <tr>
      <th>49</th>
      <td>2009</td>
      <td>Burundi</td>
      <td>Africa</td>
      <td>0.020868</td>
      <td>0.022954</td>
    </tr>
    <tr>
      <th>51</th>
      <td>2011</td>
      <td>Burundi</td>
      <td>Africa</td>
      <td>0.021350</td>
      <td>0.023485</td>
    </tr>
    <tr>
      <th>48</th>
      <td>2008</td>
      <td>Burundi</td>
      <td>Africa</td>
      <td>0.021615</td>
      <td>0.023777</td>
    </tr>
    <tr>
      <th>681</th>
      <td>2009</td>
      <td>Chad</td>
      <td>Africa</td>
      <td>0.042689</td>
      <td>0.046958</td>
    </tr>
  </tbody>
</table>
</div>

In [ ]:
# Provide your answer here.